def T(name, desc, props, req=()):
    return {"name": name, "description": desc,
            "parameters": {"type": "object", "properties": props, "required": list(req)}}
S = {"type": "string"}; N = {"type": "number"}; I = {"type": "integer"}; B = {"type": "boolean"}
def E(*v): return {"type": "string", "enum": list(v)}

TOOLS = [
 T("calc_creatinine_clearance", "Cockcroft-Gault creatinine clearance (CrCl) for renal dosing",
   {"age_years": N, "weight_kg": N, "serum_creatinine_mg_dl": N, "sex": E("male", "female")},
   ["age_years", "weight_kg", "serum_creatinine_mg_dl", "sex"]),
 T("calc_egfr", "CKD-EPI 2021 eGFR from creatinine",
   {"age_years": N, "serum_creatinine_mg_dl": N, "sex": E("male", "female")}, ["age_years", "serum_creatinine_mg_dl", "sex"]),
 T("calc_curb65", "CURB-65 pneumonia severity score",
   {"confusion": B, "urea_mmol_l": N, "respiratory_rate": N, "systolic_bp": N, "diastolic_bp": N, "age_years": N}, ["age_years"]),
 T("calc_qsofa", "qSOFA sepsis screen",
   {"respiratory_rate": N, "systolic_bp": N, "altered_mentation": B}),
 T("calc_gcs", "Glasgow Coma Scale total from eye, verbal, motor",
   {"eye": I, "verbal": I, "motor": I}, ["eye", "verbal", "motor"]),
 T("calc_bmi", "Body mass index", {"weight_kg": N, "height_cm": N}, ["weight_kg", "height_cm"]),
 T("calc_corrected_calcium", "Albumin corrected calcium", {"calcium_mg_dl": N, "albumin_g_dl": N}, ["calcium_mg_dl", "albumin_g_dl"]),
 T("calc_anion_gap", "Serum anion gap", {"sodium": N, "chloride": N, "bicarbonate": N}, ["sodium", "chloride", "bicarbonate"]),
 T("calc_wells_pe", "Wells score for pulmonary embolism", {"dvt_signs": B, "pe_most_likely": B, "heart_rate": N, "immobilization": B, "prior_vte": B, "hemoptysis": B, "malignancy": B}),
 T("calc_chads_vasc", "CHA2DS2-VASc stroke risk in atrial fibrillation", {"age_years": N, "sex": E("male","female"), "chf": B, "hypertension": B, "stroke_tia": B, "vascular": B, "diabetes": B}, ["age_years"]),
 T("drug_dose_lookup", "Look up the standard dose of a drug for an indication, optionally adjusted for renal function or paediatric weight",
   {"drug": S, "indication": S, "weight_kg": N, "crcl_ml_min": N, "age_years": N}, ["drug"]),
 T("check_drug_interactions", "Check drug-drug interactions between two or more drugs",
   {"drugs": {"type": "array", "items": S, "minItems": 2}}, ["drugs"]),
 T("recommend_empiric_antibiotic", "Antibiotic stewardship: empiric antibiotic for an infection syndrome using the local antibiogram",
   {"syndrome": E("community_acquired_pneumonia","hospital_acquired_pneumonia","urinary_tract_infection","pyelonephritis","cellulitis","intra_abdominal","meningitis","sepsis_unknown_source","febrile_neutropenia"),
    "setting": E("opd","ward","icu"), "penicillin_allergy": B, "crcl_ml_min": N, "mdr_risk": B}, ["syndrome"]),
 T("antibiogram_lookup", "Local antibiogram susceptibility of an organism to antibiotics",
   {"organism": S, "antibiotic": S, "specimen": E("blood","urine","sputum","pus","csf")}, ["organism"]),
 T("insulin_sliding_scale", "Insulin correction dose for a blood glucose value",
   {"glucose_mg_dl": N, "regimen": E("basal_bolus","sliding_scale","infusion"), "weight_kg": N}, ["glucose_mg_dl"]),
 T("electrolyte_correction", "Plan correction for sodium or potassium derangement",
   {"electrolyte": E("sodium","potassium","magnesium","calcium"), "value": N, "weight_kg": N, "age_years": N, "sex": E("male","female")}, ["electrolyte","value"]),
 T("icd10_search", "Find ICD-10 code for a diagnosis", {"diagnosis": S}, ["diagnosis"]),
 T("open_module", "Open an app screen",
   {"module": E("antibiogram","icu","opd_queue","scribe","drug_index","calculators","oncology","neonatal","insulin","wardsynq","protocols","ecg","xray")}, ["module"]),
 T("add_prescription_line", "Add a medicine to the current prescription",
   {"drug": S, "strength": S, "form": E("tablet","capsule","syrup","injection","inhaler","drops","ointment"), "frequency": E("OD","BD","TDS","QID","HS","SOS","STAT","Q6H","Q8H"), "duration_days": I, "route": E("oral","iv","im","sc","topical","inhaled"), "instructions": S}, ["drug"]),
 T("record_vitals", "Record vitals for the current patient",
   {"systolic_bp": N, "diastolic_bp": N, "heart_rate": N, "respiratory_rate": N, "spo2": N, "temperature_f": N, "glucose_mg_dl": N, "weight_kg": N}),
 T("next_patient", "Call the next patient in the OPD queue", {}),
 T("schedule_followup", "Schedule a follow-up visit", {"in_days": I, "date": {"type": "string", "format": "date"}, "reason": S}),
 T("ask_maik", "Hand a free-text clinical question to the large MaiK assistant when no calculator or lookup answers it", {"question": S}, ["question"]),
 T("search_protocol", "Search hospital clinical protocols and guidelines", {"query": S}, ["query"]),
 T("oncology_dose", "Chemotherapy dose by body surface area for a regimen", {"regimen": S, "weight_kg": N, "height_cm": N}, ["regimen"]),
 T("neonatal_bilirubin", "Neonatal jaundice phototherapy threshold", {"age_hours": N, "gestation_weeks": N, "bilirubin_mg_dl": N}, ["age_hours","bilirubin_mg_dl"]),
]
