// swift-tools-version: 5.9
import PackageDescription

// StewardmdCapacitorLlama — on-device LLM inference plugin (llama.cpp b10502).
//
// The C/C++ inference engine is linked as a PREBUILT XCFramework release asset from llama.cpp
// (Metal accelerated on-device, CPU fallback). Importable Swift module: `llama`.
//
// DEPLOYMENT TARGET: verified with `vtool -show-build` against the b10502 device slice —
//   platform IOS, minos 16.4, sdk 16.4
// which is EXACTLY the app's existing IPHONEOS_DEPLOYMENT_TARGET (16.4, set in
// ios/App/App.xcodeproj and already pinned there by the whisper.cpp XCFramework). So this plugin
// needs NO deployment-target change and no custom XCFramework build. We declare .iOS(.v15) to match
// the CLI-managed ios/App/CapApp-SPM/Package.swift, exactly as capacitor-whisper does — SPM refuses
// a dependency whose platform floor exceeds the consumer's, and CapApp-SPM is regenerated by
// `npx cap sync`. The real 16.4 floor is enforced by the app build setting + the framework's own
// min-OS at link time.
//
// SLICES: the b10502 xcframework ships ios-arm64 (device) and macos-arm64_x86_64 ONLY. There is NO
// iOS SIMULATOR slice, so a build for the simulator will fail to link. Test on a real device (which
// is the documented practice for this repo's native work anyway).
//
// The url + checksum are PINNED. checksum == `swift package compute-checksum <zip>` == the SHA-256
// of the release zip (computed 2026-08-20 against
// github.com/ggml-org/llama.cpp/releases/download/b10502/llama-b10502-xcframework.zip, 78,745,806 bytes).
// The Android side vendors the SAME tag as a submodule, so both platforms run identical inference code.
let package = Package(
    name: "StewardmdCapacitorLlama",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "StewardmdCapacitorLlama",
            targets: ["LlamaPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        .binaryTarget(
            name: "LlamaFramework",
            url: "https://github.com/ggml-org/llama.cpp/releases/download/b10502/llama-b10502-xcframework.zip",
            checksum: "f81c3c17f5e97fd2a004937d3dc56268fe009e1b1952f77f8e7a0b6032493803"
        ),
        .target(
            name: "LlamaPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                "LlamaFramework"
            ],
            path: "ios/Sources/LlamaPlugin")
    ]
)
