// swift-tools-version: 5.9
import PackageDescription

// StewardmdCapacitorLlama — on-device LLM inference plugin (llama.cpp b10502).
//
// The C/C++ inference engine is linked as a PREBUILT XCFramework release asset from llama.cpp
// (Metal accelerated on-device, CPU fallback). Importable Swift module: `llama`.
//
// DEPLOYMENT TARGET: verified with `vtool -show-build` against the b10502 device slice —
//   platform IOS, minos 16.4, sdk 16.4
// which is EXACTLY the app's existing IPHONEOS_DEPLOYMENT_TARGET (16.4, set in
// ios/App/App.xcodeproj and already pinned there by the whisper.cpp XCFramework). So this plugin
// needs NO deployment-target change and no custom XCFramework build. We declare .iOS(.v15) to match
// the CLI-managed ios/App/CapApp-SPM/Package.swift, exactly as capacitor-whisper does — SPM refuses
// a dependency whose platform floor exceeds the consumer's, and CapApp-SPM is regenerated by
// `npx cap sync`. The real 16.4 floor is enforced by the app build setting + the framework's own
// min-OS at link time.
//
// SLICES: the PrismML prism-b10685 xcframework ships ios-arm64 (device), ios simulator, macos, tvOS
// and visionOS. (The mainline b10502 zip it replaced had NO simulator slice.) Real-device testing is
// still the documented practice for this repo's native work.
//
// The url + checksum are PINNED. checksum == `swift package compute-checksum <zip>` == the SHA-256
// of the release zip (computed 2026-09-19 against the PrismML release below, 322,127,363 bytes; the
// mainline b10502 zip before it was 78,745,806 bytes, checksum f81c3c17...).
// The Android side vendors the SAME fork tag as a submodule, so both platforms run identical inference code.
let package = Package(
    name: "StewardmdCapacitorLlama",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "StewardmdCapacitorLlama",
            targets: ["LlamaPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        // 2026-09-19 (owner): moved from mainline b10502 to PrismML's fork, release
        // prism-b10685-7dffb15 (mainline b10685 base + the ternary PTQ1_0/PQ2_0 types and the Hadamard
        // activation runtime that Ternary Bonsai 2 needs; every earlier pack is a plain GGUF and loads
        // unchanged). Same zip layout as mainline (build-apple/llama.xcframework/) with ios-arm64,
        // macos, PLUS ios simulator, tvOS and visionOS slices. 322,127,363 bytes; checksum is the
        // SHA-256 of the release zip. Android vendors the SAME fork tag as its submodule.
        .binaryTarget(
            name: "LlamaFramework",
            url: "https://github.com/PrismML-Eng/llama.cpp/releases/download/prism-b10685-7dffb15/llama-prism-b10685-7dffb15-xcframework.zip",
            checksum: "c9c83d407299ebeb2c0c349cedd932e927f8d00340e9903f4d8d1d63829e652c"
        ),
        .target(
            name: "LlamaPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                "LlamaFramework"
            ],
            path: "ios/Sources/LlamaPlugin")
    ]
)
