/* test/maik-kb-relevance.test.mjs - which Knowledge Base notes does a standalone MaiK question get?
 *
 * The KB relevance benchmark (flag smd_kb_gate). StewardRAG.buildPackage() routes a knowledge question
 * with no case context to ONE KB entry, and the model reads that entry's notes. A wrong entry costs
 * 1-5k chars of off-topic notes, puts the wrong disease on the "Read more" chip, and anchors the
 * on-device engine's book search on it: "RA factor" -> Factor X deficiency, "panic attack" -> acute
 * coronary syndrome, "capital of France" -> slipped capital femoral epiphysis (all real, pre-fix).
 *
 * A case is [question, the right entries as an "id|name" regex (N: no entry is right), 1 if no notes
 * is also fine]. Each gate is scored: correct / abstain (no notes, fine) / miss (no notes, an entry
 * was right) / mis-route (notes from an entry the question did not ask about) / off-topic KB chars.
 * The name gate (default) must mis-route nothing, miss nothing and send no off-topic text; the legacy
 * coverage gate (smd_kb_gate=0) is scored alongside for comparison. Real buildPackage() over the real
 * KB on the lexical path (the name gate never calls the vector arm).
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createStewardAI, rrf } from "../kb/ai/interface.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const N = null;
const CASES = [
  // Set A (204): written while the name gate was built.
  ["dengue treatment", /dengue/i],
  ["management of scrub typhus", /scrub/i],
  ["malaria treatment", /malaria/i],
  ["first line treatment of enteric fever", /enteric|typhoid/i],
  ["typhoid fever antibiotics", /enteric|typhoid/i],
  ["leptospirosis treatment", /leptospir/i],
  ["community acquired pneumonia antibiotics", /^(CAP|SEVERE_CAP)\|/],
  ["how to treat pulmonary tuberculosis", /^PULMONARY_TB\|/],
  ["tuberculous meningitis treatment", /^(CNS_TB|tuberculous_meningitis)\|/],
  ["bacterial meningitis empiric antibiotics", /^MENINGITIS\|/],
  ["infective endocarditis duke criteria", /endocarditis/i],
  ["cellulitis antibiotics", /cellulitis/i],
  ["diabetic foot infection management", /diabetic foot/i],
  ["acute pyelonephritis treatment", /pyelonephritis/i],
  ["uncomplicated cystitis in women", /cystitis/i],
  ["c difficile treatment", /difficile/i],
  ["sepsis bundle", /^SEPSIS\|/],
  ["septic shock vasopressor", /septic shock/i],
  ["febrile neutropenia empiric therapy", /neutropeni/i],
  ["acute cholangitis management", /^CHOLANGITIS\|/],
  ["acute cholecystitis antibiotics", /cholecystitis/i],
  ["liver abscess treatment", /liver abscess/i],
  ["brain abscess management", /brain abscess/i],
  ["necrotizing fasciitis management", /necroti[sz]ing fasciitis/i],
  ["spontaneous bacterial peritonitis prophylaxis", /^SBP\||spontaneous bacterial peritonitis/i],
  ["herpes zoster treatment", /zoster/i],
  ["chikungunya management", /chikungunya/i],
  ["acute pancreatitis management", /pancreatitis/i],
  ["diabetic ketoacidosis management", /ketoacidosis/i],
  ["hyperkalemia treatment", /hyperkal/i],
  ["hyponatremia correction rate", /hyponat/i],
  ["hypoglycemia management", /hypoglyc/i],
  ["acute coronary syndrome management", /coronary syndrome/i],
  ["atrial fibrillation rate control", /atrial fib/i],
  ["acute heart failure treatment", /heart failure/i],
  ["pulmonary embolism treatment", /pulmonary embol/i],
  ["deep vein thrombosis anticoagulation", /deep vein/i],
  ["aortic dissection blood pressure target", /aortic dissection/i],
  ["hypertensive emergency management", /hypertensive emergency/i],
  ["ischemic stroke thrombolysis criteria", /ischemic stroke/i],
  ["status epilepticus management", /status epilepticus/i],
  ["guillain barre syndrome treatment", /guillain/i],
  ["myasthenic crisis management", /myasthen/i],
  ["asthma exacerbation management", /asthma/i],
  ["copd exacerbation antibiotics", /copd/i],
  ["anaphylaxis adrenaline dose", /anaphyla/i],
  ["organophosphate poisoning management", /organophosph/i],
  ["paracetamol overdose management", /paracetamol/i],
  ["snake bite anti snake venom dose", /^(snake_envenomation|snakebite_envenomation|disorders_caused_by_venomous)/],
  ["acute kidney injury management", /kidney injury/i],
  ["thyroid storm treatment", /thyroid storm/i],
  ["adrenal crisis management", /adrenal/i],
  ["upper gi bleed management", /peptic ulcer|upper gi/i],
  ["variceal bleeding management", /variceal/i],
  ["hepatic encephalopathy treatment", /hepatic enceph/i],
  ["gout flare treatment", /gout/i],
  ["rheumatoid arthritis treatment", /rheumatoid/i],
  ["lupus nephritis treatment", /lupus nephritis/i],
  ["giant cell arteritis treatment", /arteritis/i],
  ["pheochromocytoma preoperative management", /pheo/i],
  ["hemophilia A treatment", /^hemophilia_a\|/],
  ["sickle cell crisis management", /sickle/i],
  ["iron deficiency anemia treatment", /iron deficiency/i],
  ["vitamin b12 deficiency treatment", /b12|pernicious/i],
  ["hypothyroidism treatment", /hypothyroid/i],
  ["cushing syndrome diagnosis", /cushing/i],
  ["rabies post exposure prophylaxis", /rabies/i],
  ["tetanus management", /tetanus/i],
  ["hiv antiretroviral therapy", /hiv/i],
  ["nephrotic syndrome management", /nephrotic/i],
  ["kawasaki disease treatment", /kawasaki/i],
  ["preeclampsia magnesium sulphate", /eclampsia/i],
  ["neuroleptic malignant syndrome treatment", /neuroleptic/i],
  ["serotonin syndrome treatment", /serotonin/i],
  ["heat stroke management", /heat.?stroke/i],
  ["tension pneumothorax management", /pneumothorax/i],
  ["bell's palsy treatment", /bell/i],
  ["cluster headache treatment", /cluster headache/i],
  ["migraine prophylaxis", /^migraine\|/],
  ["pneumocystis pneumonia treatment", /pneumocystis/i],
  ["cryptococcal meningitis treatment", /cryptococc/i, 1],
  ["melioidosis treatment", /melioid/i],
  ["brucellosis treatment", /brucell/i],
  ["visceral leishmaniasis treatment", /leishmaniasis|kala/i],
  ["stable angina treatment", /stable angina|ischemic heart/i],
  ["hypovolemic shock management", /hypovol/i],
  ["yellow fever vaccine", /yellow fever/i],
  ["diabetes treatment", /diabetes mellitus/i],
  ["type 2 diabetes management", /diabetes mellitus/i],
  ["diabetes insipidus treatment", /diabetes insipidus/i],
  ["gestational diabetes screening", /gestational diabetes/i],
  ["renal colic analgesia", /renal.*colic/i],
  ["drug induced lupus", /drug_induced_lupus/i],
  ["hypertension management", /essential hypertension/i, 1],
  ["therapies for rheumatoid arthritis", /rheumatoid/i],
  ["angina pectoris management", /angina|ischemic heart/i],
  ["how to treat MI", /^acs\|/],
  ["AF treatment", /atrial fib/i],
  ["DKA fluids", /ketoacidosis/i],
  ["HHS management", /hyperosmolar/i],
  ["COPD exacerbation", /copd/i],
  ["CAP antibiotics", /^CAP\|/],
  ["UTI antibiotics", /urinary tract|cystitis/i],
  ["TB treatment regimen", /tuberculosis/i],
  ["SLE treatment", /lupus|sle/i],
  ["RA treatment", /rheumatoid/i],
  ["GBS treatment", /guillain/i],
  ["DIC management", /intravascular coagulation/i],
  ["ARDS ventilation", /respiratory distress/i],
  ["AKI management", /kidney injury/i],
  ["CKD management", /chronic kidney/i],
  ["PE treatment", /pulmonary embol/i],
  ["DVT treatment", /deep vein/i],
  ["UGIB management", /peptic ulcer|upper gi/i],
  ["SAH management", /subarachnoid/i],
  ["TIA workup", /transient isch/i],
  ["ITP treatment", /immune thrombocytopenia/i],
  ["TTP treatment", /thrombotic thrombocytopenic/i],
  ["NMS treatment", /neuroleptic/i],
  ["SJS management", /stevens/i],
  ["ACS management", /^acs\|/],
  ["CHF management", /heart failure/i],
  ["HCC treatment", /hepatocellular carcinoma/i, 1],
  ["heart attack treatment", /^acs\|/],
  ["loose motions treatment", /diarrh/i],
  ["fits in adults", /seizure|epilep/i, 1],
  ["piles treatment", /haemorrhoids\|/i],
  ["kidney stones treatment", /^nephrolithiasis\|/],
  ["high bp treatment", /essential hypertension/i, 1],
  ["black stools workup", /peptic ulcer|upper gi/i],
  ["blood in urine causes", N],
  ["haemophilia A treatment", /^hemophilia_a\|/],
  ["iron deficiency anaemia", /iron deficiency/i],
  ["oesophageal varices management", /variceal/i],
  ["acute myeloid leukaemia treatment", /myeloid/i],
  ["ischaemic stroke management", /ischemic stroke/i],
  ["haemorrhagic stroke management", /intracerebral|hemorrhagic stroke/i, 1],
  ["septicaemia treatment", /^SEPSIS\|/],
  ["coeliac disease diagnosis", /c(o)?eliac/i],
  ["hypokalaemia treatment", /^hypokal(a)?emia\|/i, 1],
  ["hyponatraemia correction", /hyponat/i],
  ["haemolytic uraemic syndrome", /uraemic|uremic/i],
  ["diarrhoea treatment", /diarrh/i],
  ["acute pulmonary oedema treatment", /heart failure|pulmonary edema/i],
  ["what is RA factor", /^rheumatoid\|/, 1],
  ["RA factor significance", /^rheumatoid\|/, 1],
  ["what does a positive rheumatoid factor mean", /^rheumatoid\|/, 1],
  ["factor 8 deficiency", /^hemophilia_a\|/, 1],
  ["factor 9 deficiency", /^hemophilia_b\|/, 1],
  ["factor V leiden", /^factor_v_leiden\|/],
  ["von willebrand disease treatment", /^von_willebrand_disease\|/],
  ["intrinsic factor antibodies", /pernicious|b12/i, 1],
  ["risk factors for DVT", /deep vein/i],
  ["risk factors for stroke", /stroke/i],
  ["complete heart block management", /heart block|atrioventricular block|bradyarrhythm/i],
  ["panic attack treatment", /panic/i],
  ["liver failure management", /liver failure/i],
  ["respiratory failure management", /respiratory failure/i],
  ["renal failure management", /kidney/i, 1],
  ["cardiogenic shock management", /cardiogenic/i],
  ["anaphylactic shock management", /anaphyla/i],
  ["gall stones management", /cholelith|biliary colic|gallstone/i],
  ["tension headache treatment", /tension/i],
  ["anti ccp antibody", /^rheumatoid\|/, 1],
  ["d dimer interpretation", /embol|deep vein/i, 1],
  ["troponin interpretation", /^acs\|/, 1],
  ["procalcitonin in sepsis", /^SEPSIS\|/],
  ["high lactate causes", N],
  ["yellow sclera causes", N],
  ["paracetamol dose in children", N],
  ["post op fever causes", N],
  ["ascending cholangitis management", /cholangitis/i],
  ["temporal lobe epilepsy", /epilep|seizure/i, 1],
  ["photophobia in migraine", /migraine/i, 1],
  ["potassium supplementation in hypokalemia", /hypokal/i, 1],
  ["ramipril dose", N],
  ["hepatitis b treatment", /hepatitis b/i, 1],
  ["how to write a prescription", N],
  ["explain the frank starling law", N],
  ["what is the henderson hasselbalch equation", N],
  ["difference between sensitivity and specificity", N],
  ["what is a p value", N],
  ["how to insert a central line", N],
  ["what is informed consent", N],
  ["tell me about hand hygiene", N],
  ["normal saline composition", N],
  ["how many calories in rice", N],
  ["what is the glasgow coma scale", N],
  ["how to calculate creatinine clearance", N],
  ["mechanism of action of metformin", N],
  ["what is the capital of france", N],
  ["what is the anion gap", N],
  ["how to interpret an abg", N],
  ["what is a normal heart rate", N],
  ["half life of digoxin", /digoxin/i, 1],
  ["how to do cpr", /cardiac arrest/i, 1],
  ["explain the coagulation cascade", /coagulation/i, 1],
  ["dengeu treatment", /dengue/i, 1],
  ["malria treatment", /malaria/i],
  ["pnemonia antibiotics", /pneumonia/i],
  ["menigitis treatment", /mening/i],
  ["diabetic ketoacidosis managment", /ketoacidosis/i],
  ["leptospirossis", /leptospir/i],
  ["hypokalemia treatmnet", /hypokal/i, 1],
  // Set B (110): labelled from the KB entry list before either gate ran on it. Its first run led to
  // the qualifier, "virus" and slash rules and a few KB_NAMES synonyms.
  ["what is the treatment of typhoid", /enteric|typhoid/i],
  ["empiric antibiotics for bacterial meningitis in adults", /^MENINGITIS\|/],
  ["how do you manage severe falciparum malaria", /malaria/i],
  ["dose of ceftriaxone in meningitis", /mening/i],
  ["steroids in septic shock", /septic shock/i],
  ["when to intubate in guillain barre", /guillain/i],
  ["insulin infusion rate in dka", /ketoacidosis/i],
  ["red flags in headache", /headache/i, 1],
  ["workup of pyrexia of unknown origin", /unknown origin/i],
  ["management of acute asthma in children", /asthma/i],
  ["treatment of hyperthyroidism", /hyperthyroid|thyrotox/i],
  ["thyrotoxicosis management", /thyrotox|hyperthyroid/i],
  ["acute gout treatment", /gout|crystal/i],
  ["cellulitis vs erysipelas", /cellulitis|erysipelas/i],
  ["treatment of scabies", /scabies/i],
  ["management of acute appendicitis", /appendicitis/i],
  ["diverticulitis antibiotics", /diverticul/i, 1],
  ["acute otitis media treatment", /^acute_otitis_media\|/],
  ["strep throat antibiotics", /pharyngitis/i, 1],
  ["influenza oseltamivir dose", /influenza/i],
  ["covid 19 treatment", /covid/i],
  ["chickenpox in adults", /varicella/i],
  ["measles vitamin a", /measles/i],
  ["mumps orchitis", /mumps/i],
  ["whooping cough treatment", /pertussis/i],
  ["rheumatic fever prophylaxis", /rheumatic fever/i],
  ["infective endocarditis prophylaxis before dental extraction", /endocarditis/i],
  ["pericarditis treatment colchicine", /pericarditis/i],
  ["cardiac tamponade signs", /tamponade/i],
  ["spontaneous pneumothorax management", /pneumothorax/i],
  ["pleural effusion causes", /pleural effusion/i],
  ["pulmonary tuberculosis diagnosis", /^PULMONARY_TB\|/],
  ["latent tb treatment", /latent tuberculosis/i, 1],
  ["mdr tb regimen", /multidrug/i, 1],
  ["hepatitis c treatment", /hepatitis c/i, 1],
  ["alcoholic hepatitis steroids", /alcoholic hepatitis/i, 1],
  ["cirrhosis ascites management", /cirrhosis/i],
  ["acute liver failure causes", /liver failure/i],
  ["wilson disease treatment", /^wilsons_disease\|/],
  ["hemochromatosis", /h(a)?emochromatosis/i],
  ["pancreatitis fluids", /pancreatitis/i],
  ["ulcerative colitis flare", /ulcerative colitis/i, 1],
  ["crohn disease treatment", /crohn/i, 1],
  ["irritable bowel syndrome", /irritable bowel|^ibs\|/i],
  ["gerd treatment", /reflux|^gerd_chest\|/i],
  ["h pylori eradication", /pylori/i],
  ["iron overload chelation", /iron overload|chromatosis/i, 1],
  ["thalassemia transfusion", /thalass/i, 1],
  ["aplastic anemia", /aplastic/i],
  ["multiple myeloma treatment", /myeloma/i],
  ["hodgkin lymphoma", /^hodgkin_lymphoma\|/],
  ["tumor lysis syndrome", /lysis/i, 1],
  ["hypercalcemia of malignancy", /hypercalc/i],
  ["addison disease", /adrenal|addison/i],
  ["cushing disease", /cushing/i],
  ["prolactinoma treatment", /prolactinoma/i],
  ["osteoporosis treatment", /osteoporosis/i],
  ["vitamin d deficiency", /vitamin d/i, 1],
  ["hyperparathyroidism", /hyperparathyroid/i, 1],
  ["myxedema coma treatment", /myx/i],
  ["parkinson disease treatment", /^parkinsons_disease\|/],
  ["multiple sclerosis relapse", /multiple sclerosis/i],
  ["bells palsy steroids", /bell/i],
  ["trigeminal neuralgia carbamazepine", /trigeminal/i],
  ["febrile seizure management", /febrile seizure/i],
  ["delirium management", /delirium/i],
  ["alcohol withdrawal management", /alcohol withdrawal/i],
  ["depression treatment", /depress/i, 1],
  ["schizophrenia antipsychotic", /schizophrenia/i],
  ["lithium toxicity", /^lithium_toxicity\|/],
  ["tricyclic overdose", /tricyclic/i],
  ["digoxin toxicity treatment", /digoxin/i],
  ["methanol poisoning", /methanol/i],
  ["dog bite rabies vaccine", /rabies/i],
  ["scorpion sting management", /scorpion/i],
  ["burns fluid resuscitation", /burn/i, 1],
  ["hypothermia management", /hypothermia/i],
  ["drowning management", /drowning/i],
  ["what is the normal range of hemoglobin", N],
  ["difference between type 1 and type 2 respiratory failure", /respiratory failure/i, 1],
  ["how to calculate qsofa", /sepsis/i, 1],
  ["what is a lumbar puncture", N],
  ["side effects of amiodarone", /amiodarone/i, 1],
  ["warfarin reversal", N],
  ["heparin induced thrombocytopenia", /heparin.induced/i],
  ["blood transfusion reaction", /transfusion/i, 1],
  ["oxygen therapy targets in copd", /copd/i],
  ["chest x ray interpretation", N],
  ["ecg changes in hyperkalemia", /hyperkal/i],
  ["what is heart failure with preserved ejection fraction", /heart failure/i, 1],
  ["stroke risk in atrial fibrillation", /atrial fib|stroke/i],
  ["cough for 3 weeks causes", N],
  ["sore throat", /pharyngitis/i, 1],
  ["back pain red flags", /back pain/i, 1],
  ["chest pain differential", N],
  ["fever with rash", N],
  ["jaundice workup", /jaundice/i, 1],
  ["anemia workup", /an(a)?emia/i, 1],
  ["high potassium treatment", /hyperkal/i, 1],
  ["low sodium", /hyponat/i, 1],
  ["sugar control in icu", /diabet|hypoglyc|hyperglyc/i, 1],
  ["insulin dose calculation", N],
  ["tell me about ebola", /ebola/i],
  ["what is kyasanur forest disease", /kyasanur/i],
  ["nipah virus", /nipah/i],
  ["japanese encephalitis vaccine", /japanese/i],
  ["leprosy treatment", /leprosy/i],
  ["filariasis treatment", /filariasis/i],
  ["hookworm infection", /hookworm/i],
  ["amoebic dysentery", /amoeb|amebi|dysentery/i, 1],
  // Set C (90): labelled blind after that. Its first run found one mis-route (brucella -> rubella),
  // fixed by the hasTerm() check.
  ["treatment of plasmodium vivax", /malaria/i, 1],
  ["artesunate dose in severe malaria", /malaria/i],
  ["leptospirosis doxycycline prophylaxis", /leptospir/i],
  ["scrub typhus doxycycline", /scrub/i],
  ["dengue warning signs", /dengue/i],
  ["dengue platelet transfusion", /dengue/i],
  ["typhoid carrier", /enteric|typhoid/i],
  ["brucella treatment", /brucell/i, 1],
  ["anthrax", /anthrax/i],
  ["tetanus immunoglobulin dose", /tetanus/i],
  ["diphtheria antitoxin", /diphtheria/i],
  ["cholera rehydration", /cholera/i],
  ["shigella dysentery", /shigell|dysentery/i, 1],
  ["giardiasis treatment", /giardia/i],
  ["neurocysticercosis albendazole", /cysticercosis/i],
  ["hydatid cyst", /hydatid|echinococc/i, 1],
  ["kala azar treatment", /kala|leishmaniasis/i],
  ["syphilis penicillin", /syphilis/i],
  ["gonorrhea ceftriaxone", /gonorrh/i],
  ["pelvic inflammatory disease", /pelvic inflammatory/i, 1],
  ["bacterial vaginosis", /vaginosis/i, 1],
  ["urinary retention causes", /retention/i, 1],
  ["acute prostatitis antibiotics", /prostatitis/i],
  ["epididymitis treatment", /epididym/i, 1],
  ["necrotising pancreatitis antibiotics", /pancreatitis/i, 1],
  ["acute mesenteric ischemia", /mesenteric/i, 1],
  ["small bowel obstruction management", /bowel obstruction/i, 1],
  ["perforated peptic ulcer", /peptic ulcer|perforat/i, 1],
  ["hepatorenal syndrome", /hepatorenal/i, 1],
  ["portal vein thrombosis", /portal vein/i, 1],
  ["budd chiari syndrome", /budd/i, 1],
  ["gilbert syndrome", /gilbert/i, 1],
  ["autoimmune hepatitis treatment", /autoimmune hepatitis/i],
  ["primary biliary cholangitis", /primary biliary/i],
  ["acute on chronic liver failure", /liver failure/i, 1],
  ["status asthmaticus", /asthma/i, 1],
  ["pulmonary hypertension treatment", /pulmonary (arterial )?hypertension/i, 1],
  ["sarcoidosis steroids", /sarcoid/i],
  ["interstitial lung disease", /interstitial lung|^ild\|/i, 1],
  ["idiopathic pulmonary fibrosis", /pulmonary fibrosis|^ipf\|/i],
  ["lung abscess antibiotics", /lung abscess/i, 1],
  ["empyema management", /empyema/i, 1],
  ["hemoptysis management", /h(a)?emoptysis/i, 1],
  ["obstructive sleep apnea", /sleep apn/i, 1],
  ["anaphylaxis in children adrenaline", /anaphyla/i],
  ["urticaria antihistamine", /urticaria/i, 1],
  ["angioedema ace inhibitor", /angioedema/i],
  ["stevens johnson syndrome causes", /stevens/i],
  ["psoriasis methotrexate", /psoriasis/i],
  ["herpes simplex encephalitis acyclovir", /herpes simplex|encephalitis/i, 1],
  ["brain death criteria", N],
  ["raised intracranial pressure management", /intracranial/i, 1],
  ["subdural hematoma", /subdural/i],
  ["myasthenia gravis treatment", /myasthen/i, 1],
  ["motor neuron disease", /motor neuron/i, 1],
  ["migraine acute treatment", /^migraine\|/],
  ["vertigo causes", /vertigo/i, 1],
  ["syncope workup", /syncope/i, 1],
  ["ventricular tachycardia management", /ventricular tachy/i, 1],
  ["svt adenosine dose", /supraventricular|svt/i, 1],
  ["bradycardia atropine", /brady/i, 1],
  ["hypertrophic cardiomyopathy", /hypertrophic cardiomyopathy/i, 1],
  ["mitral stenosis", /mitral stenosis/i, 1],
  ["aortic stenosis tavr", /aortic stenosis/i, 1],
  ["infective endocarditis antibiotics", /endocarditis/i],
  ["dvt in pregnancy", /deep vein/i],
  ["postpartum hemorrhage management", /postpartum h/i, 1],
  ["eclampsia magnesium", /eclampsia/i],
  ["ectopic pregnancy methotrexate", /ectopic/i, 1],
  ["hyperemesis gravidarum", /hyperemesis/i, 1],
  ["neonatal sepsis antibiotics", /sepsis/i, 1],
  ["bronchiolitis in infants", /bronchiolitis/i],
  ["croup dexamethasone", /croup/i],
  ["intussusception", /intussusception/i],
  ["rickets vitamin d", /rickets/i, 1],
  ["kwashiorkor management", /kwashiorkor/i],
  ["sam malnutrition", /malnutrition|kwashiorkor|marasmus/i, 1],
  ["paracetamol poisoning nac", /paracetamol/i],
  ["snake bite neurotoxic", /^(snake_envenomation|snakebite_envenomation|disorders_caused_by_venomous)/],
  ["aluminium phosphide poisoning", /phosphide/i, 1],
  ["kerosene poisoning", /kerosene|hydrocarbon/i, 1],
  ["carbon monoxide poisoning", /carbon monoxide/i, 1],
  ["benzodiazepine overdose flumazenil", /benzodiazepine/i, 1],
  ["iron poisoning", /iron/i, 1],
  ["what is a normal ferritin level", N],
  ["how to prescribe insulin glargine", N],
  ["mechanism of action of aspirin", N],
  ["difference between gram positive and negative", N],
  ["how to read a chest ct", N],
  ["what are the stages of sleep", N],
  // Set D (2026-09-26, MaiK answer-quality set): a qualifier and a plain-English name, plus look-alikes.
  ["simple febrile seizure what to tell parents", /febrile seizure/i],
  ["when to worry about jaundice in a newborn", /neonatal jaundice/i],
  ["newborn jaundice phototherapy threshold", /neonatal jaundice/i],
  ["jaundice in an adult with fever", N, 1],
  ["simple renal cyst follow up", N, 1],
];

const LS = { smd_hybrid: "0" };
global.window = global;
global.document = { querySelector: () => null, head: { appendChild() {} }, createElement: () => ({ setAttribute() {} }) };
global.localStorage = { getItem: (k) => (k in LS ? LS[k] : null), setItem: (k, v) => { LS[k] = String(v); }, removeItem: (k) => { delete LS[k]; } };
// Both gates read the same lexical retrieval, so it runs once per question.
const memo = new Map();
global.__loadIface = () => Promise.resolve({ rrf, createStewardAI: (s, o) => {
  const ai = createStewardAI(s, o), retrieve = ai.retrieve;
  ai.retrieve = (q, k) => { const key = q + "\u0000" + k; if (!memo.has(key)) memo.set(key, retrieve(q, k)); return memo.get(key); };
  return ai;
} });
const load = (f) => vm.runInThisContext(fs.readFileSync(join(ROOT, f), "utf8"), { filename: f });
["kb/dist/kb.core.js", "kb/dist/kb.enrichment.js", "kb/dist/kb.enrichment.2.js", "kb/dist/kb.rag.js", "dxmgmt.js"].forEach(load);
const src = fs.readFileSync(join(ROOT, "kb/ai/steward-ai.browser.js"), "utf8");
const patched = src.replace(/import\("\/kb\/ai\/interface\.mjs[^"]*"\)/, "globalThis.__loadIface()");
if (patched === src) throw new Error("could not patch the interface.mjs import");
vm.runInThisContext(patched, { filename: "steward-ai.browser.js" });
assert.ok(await window.StewardRAG.ready(), "StewardRAG.ready() with the real KB");

const nameOf = (id) => { const e = (window.KB_ENRICHMENT.byId || {})[id], m = (window.DX_MGMT || {})[id]; return (e && e.name) || (m && m.name) || String(id).replace(/_/g, " "); };
const empty = { infectious: [], nonInfectious: [], gate: null, dominantSystem: null };
async function score(gate) {
  if (gate == null) delete LS.smd_kb_gate; else LS.smd_kb_gate = gate;
  const t = { correct: 0, abstain: 0, miss: 0, misroute: 0, off: 0, bad: [] };
  for (const [q, accept, noneOk] of CASES) {
    const p = await window.StewardRAG.buildPackage(empty, { question: q, hospitalId: "GIMSR", caseData: {} });
    const ok = (id, name) => !!accept && accept.test(id + "|" + (name || nameOf(id)));
    const g = (p.grounding || [])[0];
    const cls = !g ? (accept === N || noneOk ? "abstain" : "miss") : (ok(g.diseaseId, g.name) ? "correct" : "misroute");
    t[cls]++;
    (p.grounding || []).forEach((x) => { if (!ok(x.diseaseId, x.name)) (x.knowledge || []).forEach((c) => { t.off += String(c.text || "").length; }); });
    (p.retrieved || []).forEach((c) => { if (!ok(c.diseaseId)) t.off += String(c.text || "").length; });
    if (cls === "miss" || cls === "misroute") t.bad.push(cls + ": " + q + " -> " + (g ? g.diseaseId + " (" + g.name + ")" : "no notes"));
  }
  delete LS.smd_kb_gate;
  return t;
}
const nameGate = await score(null);
const legacy = await score("0");
const row = (label, t) => label.padEnd(24) + [t.correct, t.abstain, t.miss, t.misroute].map((n) => String(n).padStart(9)).join("") + String(t.off).padStart(17);
console.log("\nKB relevance benchmark: " + CASES.length + " standalone questions\n" + "gate".padEnd(24) + "  correct  abstain     miss misroute  off-topic chars");
console.log(row("name (default)", nameGate));
console.log(row("legacy (smd_kb_gate=0)", legacy));
nameGate.bad.forEach((b) => console.log("  name gate " + b));

test("name gate: every question gets the notes it asked for, or none", () => {
  assert.deepEqual(nameGate.bad, []);
  assert.equal(nameGate.off, 0, "off-topic KB text sent");
});

test("smd_kb_gate=0 restores the legacy gate, which still mis-routes", async () => {
  assert.ok(legacy.misroute > 0 && legacy.off > 0, "the benchmark still tells the two gates apart");
  LS.smd_kb_gate = "0";
  const p = await window.StewardRAG.buildPackage(empty, { question: "what is RA factor" });
  delete LS.smd_kb_gate;
  assert.ok(p.grounding.length && !/rheumatoid/.test(p.grounding[0].diseaseId), "legacy: 'RA factor' still names a factor deficiency");
});
