// openmed-ner.js (OpenMed PharmaDetect / DiseaseDetect TinyMed-65M) and its two consumers:
// claim grounding (kb/ai/maik-grounding.js opts.drugs) and ICD suggestions (scribe-icdsug.js opts.extract).
// The real checkpoints are not in the repo (licence not yet verified, see openmed-ner.js); the fixture
// model under test/fixtures/openmed-ner is a lookup-table ONNX with the same I/O contract, generated by
// scripts/openmed/make-ner-fixture.py. The real-runtime check is test/run-openmed-ner-ui.mjs.
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const N = require("../openmed-ner.js");
const G = require("../kb/ai/maik-grounding.js");
const ICD = require("../scribe-icdsug.js");
const FIX = (kind, f) => readFileSync(new URL(`./fixtures/openmed-ner/${kind}/${f}`, import.meta.url));

// A pack pointing at the fixture, gate satisfied for the test only.
function fixturePack(kind) {
  const base = N.PACKS[kind];
  const files = {};
  for (const k of Object.keys(base.files)) files[k] = { name: base.files[k].name, sha256: "0".repeat(64), bytes: null };
  return { ...base, files, licence: { declared: "fixture", verified: true } };
}
const loadBytes = (kind) => (pack, f) => Promise.resolve(new Uint8Array(FIX(kind, f.name)).buffer);

// Fake onnxruntime: reproduces the fixture graph (vocab id -> one-hot label row) in JS, so the
// tokenizer -> tensors -> logits -> decode path runs without a native runtime.
function fakeOrt(kind, tagOf) {
  const tok = JSON.parse(FIX(kind, "tokenizer.json"));
  const labels = Object.values(JSON.parse(FIX(kind, "id2label.json")));
  const rev = {}; for (const [t, i] of Object.entries(tok.model.vocab)) rev[i] = t;
  return {
    Tensor: function (type, data, dims) { this.type = type; this.data = data; this.dims = dims; },
    InferenceSession: { create: async () => ({
      inputNames: ["input_ids", "attention_mask"], outputNames: ["logits"],
      run: async (feeds) => {
        const ids = feeds.input_ids.data, n = ids.length, L = labels.length, out = new Float32Array(n * L).fill(-4);
        for (let i = 0; i < n; i++) out[i * L + labels.indexOf(tagOf[rev[Number(ids[i])]] || "O")] = 4;
        return { logits: { data: out, dims: [1, n, L] } };
      } }) }
  };
}
const PHARMA_TAGS = { warfarin: "B-CHEM", aspirin: "B-CHEM", digoxin: "B-CHEM", para: "B-CHEM", "##ceta": "I-CHEM", "##mol": "I-CHEM",
  line: "B-CHEM", "##zol": "I-CHEM", "##id": "I-CHEM", insulin: "B-CHEM", glargine: "I-CHEM" };
const DISEASE_TAGS = { community: "B-DISEASE", acquired: "I-DISEASE", pneumonia: "I-DISEASE", type: "B-DISEASE", "2": "I-DISEASE",
  diabetes: "I-DISEASE", mellitus: "I-DISEASE", chronic: "B-DISEASE", kidney: "I-DISEASE", disease: "I-DISEASE", stage: "I-DISEASE",
  "3": "I-DISEASE", hypertension: "B-DISEASE" };
const opts = (kind, tags) => ({ pack: fixturePack(kind), loadBytes: loadBytes(kind), ort: fakeOrt(kind, tags) });

test("both packs point at the exact OpenMed checkpoints and FAIL CLOSED (no licence, no sha256)", () => {
  assert.equal(N.PACKS.pharma.repo, "OpenMed/OpenMed-NER-PharmaDetect-TinyMed-65M-v1-onnx-android");
  assert.equal(N.PACKS.disease.repo, "OpenMed/OpenMed-NER-DiseaseDetect-TinyMed-65M-v1-onnx-android");
  for (const k of ["pharma", "disease"]) {
    assert.equal(N.PACKS[k].licence.verified, false, "flip only after the HF licence page is checked");
    assert.equal(N.verified(N.PACKS[k]), false);
    assert.deepEqual(N.status(k), { ok: false, reason: "flag-off" });
  }
});

test("unverified pack never downloads: extract resolves [] without touching loadBytes", async () => {
  let called = 0;
  const r = await N.extract("pharma", "Start warfarin 5 mg", { loadBytes: () => { called++; return Promise.reject(new Error("x")); } });
  assert.deepEqual(r, []);
  assert.equal(called, 0);
  const unverifiedPack = { ...fixturePack("pharma"), licence: { verified: false } };
  assert.deepEqual(await N.extract("pharma", "Start warfarin", { pack: unverifiedPack, loadBytes: () => { called++; } }), []);
  assert.equal(called, 0);
});

test("WordPiece tokenizer: lowercases, splits sub-words, keeps offsets into the original text", () => {
  const T = N._makeTokenizer(JSON.parse(FIX("pharma", "tokenizer.json")));
  const s = "Give Paracetamol, 500 mg";
  const e = T.encode(s);
  const pieces = e.offsets.map(([a, b]) => s.slice(a, b));
  assert.deepEqual(pieces, ["Give", "Para", "ceta", "mol", ",", "500", "mg"]);
  assert.equal(new Set(e.word).size, 5, "five words: Give / Paracetamol / , / 500 / mg");
  assert.throws(() => N._makeTokenizer({ model: { type: "BPE", vocab: {} } }), /WordPiece/);
});

test("pharma: drugs found, including sub-word drugs; dose words are not drugs", async () => {
  const text = "Give paracetamol 500 mg and warfarin 5 mg od; start linezolid 600 mg bd with insulin glargine.";
  const ents = await N.extract("pharma", text, opts("pharma", PHARMA_TAGS));
  assert.deepEqual(ents.map((e) => e.text), ["paracetamol", "warfarin", "linezolid", "insulin glargine"]);
  for (const e of ents) assert.equal(text.slice(e.start, e.end), e.text);
  assert.deepEqual(await N.drugNames(text, opts("pharma", PHARMA_TAGS)), ["paracetamol", "warfarin", "linezolid", "insulin glargine"]);
});

test("disease: a combined diagnosis splits into its conditions", async () => {
  const dx = "Community acquired pneumonia with type 2 diabetes mellitus and chronic kidney disease stage 3";
  assert.deepEqual(await N.diseases(dx, opts("disease", DISEASE_TAGS)),
    ["Community acquired pneumonia", "type 2 diabetes mellitus", "chronic kidney disease stage 3"]);
});

test("score threshold and a broken runtime both resolve to [] (never reject)", async () => {
  const hi = { ...fixturePack("pharma"), minScore: 0.9999 };
  assert.deepEqual(await N.extract("pharma", "warfarin", { ...opts("pharma", PHARMA_TAGS), pack: hi }), []);
  const broken = { Tensor: function () {}, InferenceSession: { create: async () => { throw new Error("wasm failed"); } } };
  assert.deepEqual(await N.extract("pharma", "warfarin", { ...opts("pharma", PHARMA_TAGS), ort: broken }), []);
});

test("long text is windowed at 510 tokens and every window is tagged", async () => {
  const text = Array(600).fill("give").join(" ") + " warfarin";
  const ents = await N.extract("pharma", text, opts("pharma", PHARMA_TAGS));
  assert.deepEqual(ents.map((e) => e.text), ["warfarin"]);
});

// ── Consumer 1: claim grounding ──────────────────────────────────────────────────────────────────
test("grounding: a swapped drug the suffix rule cannot see passes today, is removed with tagger names", () => {
  const P = [{ text: "Fever in adults: give paracetamol 500 mg every 6 hours as needed." }];
  const a = "For fever in adults give aspirin 500 mg every 6 hours as needed.";
  assert.equal(G.groundAnswer(a, P, "fever?", {}).stats.supported, 1, "the gap: aspirin is invisible to DRUG_SUFFIX");
  const g = G.groundAnswer(a, P, "fever?", { drugs: ["aspirin", "paracetamol"] });
  assert.equal(g.stats.unsupported, 1);
  assert.match(g.removed[0].why.join(" "), /aspirin not in the reference/);
});

test("grounding: correct answer still supported; wrong dose becomes a contradiction; no list = unchanged", () => {
  const P = [{ text: "Fever in adults: give paracetamol 500 mg every 6 hours as needed." }];
  const ok = "For fever in adults give paracetamol 500 mg every 6 hours as needed.";
  assert.equal(G.groundAnswer(ok, P, "q", { drugs: ["paracetamol"] }).stats.supported, 1);
  const wrong = "For fever in adults give paracetamol 1 g every 6 hours.";
  assert.equal(G.groundAnswer(wrong, P, "q", { drugs: ["paracetamol"] }).stats.contradicted, 1);
  const base = G.groundAnswer(wrong, P, "q", {});
  assert.deepEqual(G.groundAnswer(wrong, P, "q", { drugs: [] }), base, "empty list is byte-identical to none");
  assert.deepEqual(G.groundAnswer(wrong, P, "q", {}), base, "no leakage of the previous call's list");
});

// ── Consumer 2: ICD suggestions ──────────────────────────────────────────────────────────────────
const IDX = {
  "community acquired pneumonia": [{ code: "J18.9", title: "Pneumonia, unspecified organism" }],
  "type 2 diabetes mellitus": [{ code: "E11.9", title: "Type 2 diabetes mellitus without complications" }],
  "chronic kidney disease stage 3": [{ code: "N18.3", title: "Chronic kidney disease, stage 3" }],
};
const search = (q) => Promise.resolve(IDX[q.toLowerCase()] || [{ code: "R69", title: "Illness, unspecified" }]);
const DX = "Community acquired pneumonia with type 2 diabetes mellitus and chronic kidney disease stage 3";

test("ICD: with the disease tagger every condition gets its own code offered", async () => {
  const rows = await ICD.suggest(DX, { search, extract: (t) => N.diseases(t, opts("disease", DISEASE_TAGS)) });
  assert.deepEqual(rows.map((r) => r.code), ["J18.9", "E11.9", "N18.3"]);
  assert.deepEqual(rows.map((r) => r.span), ["Community acquired pneumonia", "type 2 diabetes mellitus", "chronic kidney disease stage 3"]);
});

test("ICD: no extractor, one condition, or a failing extractor = the single-query behaviour exactly", async () => {
  const single = await ICD.suggest(DX, { search });
  assert.deepEqual(await ICD.suggest(DX, { search, extract: () => Promise.resolve(["pneumonia"]) }), single);
  assert.deepEqual(await ICD.suggest(DX, { search, extract: () => Promise.reject(new Error("x")) }), single);
  assert.deepEqual(await ICD.suggest(DX, { search, extract: () => { throw new Error("x"); } }), single);
  assert.deepEqual(await ICD.suggest(DX, { search, extract: () => Promise.resolve([]) }), single);
});

// ── maik-local.js wiring ─────────────────────────────────────────────────────────────────────────
const LOCAL = readFileSync(new URL("../maik-local.js", import.meta.url), "utf8");
function loadWithNer(win) {
  const a = LOCAL.indexOf("  var NER_TIMEOUT_MS"), b = LOCAL.indexOf("  function noThinkPack(");
  return new Function("window", "setTimeout", "clearTimeout", LOCAL.slice(a, b) + "; return withNerDrugs;")(win, setTimeout, clearTimeout);
}
test("maik-local: withNerDrugs is in the answer chain and passes drugs to groundAnswer", () => {
  assert.match(LOCAL, /\.then\(function \(r\) \{\n\s+return withNerDrugs\(r, grounding\);/);
  // The claim-check options are built once by groundOpts() (shared with the live stream view, T56).
  assert.match(LOCAL, /G\.groundAnswer\(text, grounding\.passages, pkg && pkg\.question, groundOpts\(r && r\._nerDrugs\)\)/);
  assert.match(LOCAL, /drugs: nerDrugs,/);
});
test("maik-local: withNerDrugs leaves r untouched when off / errored / ungrounded, attaches names when ready", async () => {
  const off = loadWithNer({ SMD_OPENMED_NER: { status: () => ({ ok: false }), drugNames: () => { throw new Error("must not run"); } } });
  const r0 = { text: "x" };
  assert.equal(await off(r0, { passages: [] }), r0);
  assert.equal(r0._nerDrugs, undefined);
  const on = loadWithNer({ SMD_OPENMED_NER: { status: () => ({ ok: true }), drugNames: async (s) => (/warfarin/.test(s) ? ["warfarin"] : []) } });
  const r1 = await on({ text: "warfarin 5 mg" }, { passages: [{ text: "..." }] });
  assert.deepEqual(r1._nerDrugs, ["warfarin"]);
  assert.equal((await on({ text: "warfarin" }, null))._nerDrugs, undefined, "no grounding, no tagging");
  const err = { error: "x" }; assert.equal(await on(err, { passages: [] }), err);
  const failing = loadWithNer({ SMD_OPENMED_NER: { status: () => ({ ok: true }), drugNames: () => Promise.reject(new Error("x")) } });
  const r2 = { text: "y" }; assert.equal(await failing(r2, { passages: [] }), r2);
});
