/* test/tenant-provision.test.mjs — platform-owner tenant provisioning.
 *
 * OWNER 2026-08-27: "for each medical college there will be an admin where I can assign username
 * pwd (autogenerated) and can be linked to google account".
 *
 * Every piece already existed (createOrg, setMembership, setMemberPassword, and an email+password
 * login that mints a staff session); nothing joined them up. This covers the one part that is pure
 * and therefore testable without Firestore — the generated credential — plus the route contract.
 *
 * node --test test/tenant-provision.test.mjs
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { genPassword, ALPHABET } from "../functions/api/tenants/[[path]].js";

const SRC = readFileSync(new URL("../functions/api/tenants/[[path]].js", import.meta.url), "utf8");

test("the alphabet has no glyph that can be misread off a screen", () => {
  // This password is read aloud or typed from a screenshot onto a phone. O/0 and I/1/l are the
  // pairs that turn into a support ticket.
  for (const bad of ["O", "0", "I", "l", "1"]) {
    assert.ok(ALPHABET.indexOf(bad) < 0, `ambiguous character in the alphabet: ${bad}`);
  }
  assert.ok(ALPHABET.length >= 50, "still a wide alphabet after the removals");
});

test("the generated password has the shape a human can retype", () => {
  const p = genPassword();
  assert.match(p, /^[A-Za-z2-9]{4}-[A-Za-z2-9]{4}-[A-Za-z2-9]{4}$/, `unexpected shape: ${p}`);
  const p2 = genPassword(4, 5);
  assert.equal(p2.split("-").length, 4);
  assert.equal(p2.split("-")[0].length, 5);
});

test("every character actually comes from the alphabet", () => {
  for (let i = 0; i < 200; i++) {
    for (const ch of genPassword().replace(/-/g, "")) {
      assert.ok(ALPHABET.indexOf(ch) > -1, `character outside the alphabet: ${ch}`);
    }
  }
});

test("passwords do not repeat", () => {
  // A generator seeded wrongly (or a Math.random one reset per isolate) shows up here first.
  const seen = new Set();
  for (let i = 0; i < 500; i++) seen.add(genPassword());
  assert.equal(seen.size, 500, "generated the same password twice in 500 draws");
});

test("it uses a CSPRNG, not Math.random", () => {
  assert.match(SRC, /crypto\.getRandomValues/);
  assert.ok(!/Math\.random/.test(SRC), "Math.random is not acceptable for a credential");
});

test("the route is platform-owner gated, and the gate runs BEFORE any work", () => {
  assert.match(SRC, /ownerOK\(request, env\)/);
  const guard = SRC.indexOf("ownerOK(request, env)");
  // Match CALL sites, not the header comment that also names these functions.
  for (const later of ["listAllOrgs(env,", "createOrg(env,", "setMemberPassword(env,", "lookupUidByEmail(env,"]) {
    const at = SRC.indexOf(later);
    assert.ok(at > -1, `expected a call to ${later}`);
    assert.ok(at > guard, `${later} must not be reachable before the owner check`);
  }
});

test("the password is never persisted in the clear, and is returned exactly once", () => {
  // setMemberPassword salts+hashes; the plaintext exists only in the response body.
  assert.match(SRC, /setMemberPassword\(env, org\.id, identity, email, password, identity\)/);
  // No path stores `password` onto the org or membership document.
  assert.ok(!/password:\s*password[,\s]*\}\s*\)/.test(SRC.replace(/return json\([\s\S]*?\);/g, "")),
    "plaintext password must not reach a write");
});

test("a college cannot be created without a name or an admin email", () => {
  assert.match(SRC, /error: "name_required"/);
  assert.match(SRC, /error: "admin_email_required"/);
  // And an admin who has never signed in is named, not silently skipped.
  assert.match(SRC, /error: "no_such_account", email/);
});

test("the admin OWNS their college — the reason support cannot read tenant data", () => {
  // createOrg's third argument is the ownerUid. Passing the admin's identity is what makes the
  // college theirs; passing the platform's would leave StewardMD able to read their records.
  assert.match(SRC, /createOrg\(env, \{ name, mode: "native", kind: "institution" \}, identity\)/);
  assert.match(SRC, /setMembership\(env, org\.id, identity, \{ role: "admin" \}/);
});

test("the two-logins limitation is written down where the next reader will hit it", () => {
  // The generated password mints a staff session, which the eLOGBook API does not accept. If that
  // ever stops being true this comment should change with it.
  assert.match(SRC, /verifyFirebaseToken\(\) only/);
  assert.match(SRC, /STAFF SESSION/);
});

/* ── institutions are SOLD, not self-served ────────────────────────────────────────────────────
 * Before this, POST /api/queue/org would mint anything for any signed-in account, so any user
 * could appoint themselves the Academic Cell of a "recognised" PG programme. */
test("only the platform owner may mint kind:institution through the queue route", () => {
  const q = readFileSync(new URL("../functions/api/queue/[[path]].js", import.meta.url), "utf8");
  assert.match(q, /institution_provisioning_required/,
    "the queue org-create route must refuse a self-served institution");
  assert.match(q, /String\(body && body\.kind\) === "institution" && !\(await ownerOK\(request, env\)\)/,
    "the refusal must be gated on ownerOK, not on a client-supplied claim");
  assert.match(q, /import \{ ownerEmails, ownerOK \}/, "ownerOK must actually be imported");
});

test("the eLOGBook console offers no self-serve create button", () => {
  const scr = readFileSync(new URL("../pglog-screens.js", import.meta.url), "utf8");
  assert.doesNotMatch(scr, /data-pgl="create-inst"/,
    "a create button that can only 403 is worse than none");
  assert.match(scr, /Institutions are set up by StewardMD/, "it explains who provisions one");
});
