/* Dump the app's live drug universe for the interaction pipeline.
 *
 * Loads the StewardMD PWA in headless Chrome and reads the three in-page drug
 * sources — window.MEDDRUGS._list (non-antibiotic formulary), window.ASP_DRUGS
 * (antibiotic stewardship formulary), and window.INTERACTION_RULES.drugClasses
 * (generics the current ruleset already understands) — then writes their union,
 * with formulary brand aliases, to curated/drug_universe.json.
 *
 * This is a build-time BOOTSTRAP helper. The emitted JSON is committed and read
 * by the Python pipeline (fetch_rxnorm.py), so the pipeline itself needs no
 * browser. Re-run when the app's formularies change.
 *
 * USAGE: CHROME=/path/to/chrome node scripts/interactions/dump_universe.mjs
 */
import { spawn } from "node:child_process";
import { setTimeout as sleep } from "node:timers/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { writeFileSync } from "node:fs";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const BASE = (process.env.BASE || "http://localhost:8973/").replace(/\/?$/, "/");
const PORT = 9391, userDir = (process.env.CLAUDE_JOB_DIR || "/tmp") + "/universe-chrome";
const CHROME = process.env.CHROME || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const OUT = join(HERE, "curated", "drug_universe.json");

let serveProc = null;
async function ensureServer() {
  try { await fetch(BASE); return; } catch {}
  const port = (BASE.match(/:(\d+)/) || [, "8973"])[1];
  serveProc = spawn("node", [join(HERE, "..", "..", "test", "serve.mjs"), ROOT, port], { stdio: "ignore" });
  for (let i = 0; i < 30; i++) { try { await fetch(BASE); return; } catch { await sleep(200); } }
}
await ensureServer();

const chrome = spawn(CHROME, [...(process.env.CHROME_FLAGS || "").split(" ").filter(Boolean),
  "--headless=new", `--remote-debugging-port=${PORT}`, `--user-data-dir=${userDir}`,
  "--no-first-run", "--disable-gpu", "--mute-audio"], { stdio: "ignore" });

let msgId = 1; const pending = new Map(); let ws, sessionId;
const call = (m, p) => { const i = msgId++; return new Promise(r => { pending.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: p || {}, sessionId })); }); };
const ev = async (e) => {
  const r = await call("Runtime.evaluate", { expression: `(async function(){try{${e}}catch(x){return JSON.stringify({__err:String(x&&x.message||x)})}})()`, returnByValue: true, awaitPromise: true });
  return r.result && r.result.result ? r.result.result.value : null;
};

try {
  let ver, t = 0; while (t++ < 60) { try { ver = await (await fetch(`http://localhost:${PORT}/json/version`)).json(); break; } catch { await sleep(200); } }
  ws = new WebSocket(ver.webSocketDebuggerUrl); await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
  ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { pending.get(m.id)(m); pending.delete(m.id); } };
  const { result: { targetId } } = await call("Target.createTarget", { url: "about:blank" });
  const { result: { sessionId: sid } } = await call("Target.attachToTarget", { targetId, flatten: true }); sessionId = sid;
  await call("Runtime.enable", {}); await call("Page.navigate", { url: BASE });

  let ready = false;
  for (let i = 0; i < 80; i++) { await sleep(400); if (await ev(`return !!(window.MEDDRUGS && window.INTERACTION_RULES)`) === true) { ready = true; break; } }
  if (!ready) throw new Error("app globals not loaded");

  const dump = JSON.parse(await ev(`
    var meddrugs = (window.MEDDRUGS && window.MEDDRUGS._list) || [];
    var ir = (window.INTERACTION_RULES && window.INTERACTION_RULES.drugClasses) || {};
    var asp = window.ASP_DRUGS || {};
    // generic -> { sources:[], brands:[] }
    var map = {};
    function add(name, src, brands){
      if(!name) return;
      var g = String(name).trim().toLowerCase();
      if(!g) return;
      if(!map[g]) map[g] = { generic:g, sources:[], brands:[] };
      if(map[g].sources.indexOf(src)===-1) map[g].sources.push(src);
      (brands||[]).forEach(function(b){ b=String(b).trim().toLowerCase(); if(b && map[g].brands.indexOf(b)===-1) map[g].brands.push(b); });
    }
    meddrugs.forEach(function(d){ add(d.generic, "meddrugs", d.brands||[]); });
    Object.keys(ir).forEach(function(g){ add(g, "interaction_rules", []); });
    Object.keys(asp).forEach(function(g){ add(g, "asp", []); });
    return JSON.stringify(Object.keys(map).sort().map(function(k){ return map[k]; }));
  `));

  const payload = {
    _comment: "Auto-generated by dump_universe.mjs — union of MEDDRUGS._list, ASP_DRUGS, and INTERACTION_RULES.drugClasses. Committed; read by fetch_rxnorm.py. Re-run when app formularies change.",
    count: dump.length,
    drugs: dump
  };
  writeFileSync(OUT, JSON.stringify(payload, null, 2) + "\n");
  console.log(`Wrote ${dump.length} drugs -> ${OUT}`);
  const bySrc = {}; dump.forEach(d => d.sources.forEach(s => bySrc[s] = (bySrc[s] || 0) + 1));
  console.log("By source:", JSON.stringify(bySrc));
} catch (e) {
  console.error("FAILED:", e && e.message || e); process.exitCode = 1;
} finally {
  try { ws && ws.close(); } catch {}
  try { chrome.kill(); } catch {}
  try { serveProc && serveProc.kill(); } catch {}
}
