"""Stage 8 — render the runtime asset.

Assembles the final payload (preserving the window.INTERACTION_RULES contract:
version, generated, sources, drugClasses, rules — PLUS generics, brands) and
writes two committed artifacts:
  * ../../interaction-rules.js         — IIFE assigning window.INTERACTION_RULES
                                          (auto-shipped to www/ by build-www.sh;
                                          bump the ?v= in index.html after emit)
  * ../../data/interaction-rules.json  — reviewable twin of the same data
Strips every internal _underscore field (e.g. _origin) so it never ships.
"""
import datetime
import os
import _lib as L

VERSION = "1.0.0"
RXCLASS_SOURCE = {
    "id": "rxnorm-rxclass",
    "title": "RxNorm / RxClass drug classification",
    "org": "U.S. National Library of Medicine",
    "version": "RxNav REST (ATC / DailyMed EPC / MED-RT MoA & PE)",
    "license": "U.S. Government work — public domain",
}

HEADER = """/* ============================================================================
   StewardMD — Drug–Drug Interaction Ruleset (GENERATED — do not edit by hand)
   ----------------------------------------------------------------------------
   ⚠️  CLINICAL DECISION SUPPORT ONLY — REQUIRES CLINICIAN SIGN-OFF.
   Generated by scripts/interactions/build_all.py from OPEN, commercially-safe
   sources (RxNorm/RxClass, ONC/NLM High-Priority DDI, openFDA labeling,
   CredibleMeds QT). Drug classes are auto-derived; interaction rules are
   class/mechanism-based. This is a broad SCREEN, NOT an exhaustive commercial
   compendium: absence of a finding does NOT mean a combination is safe.
   To change data, edit scripts/interactions/curated/* and re-run the pipeline.
   Exposes window.INTERACTION_RULES. Load BEFORE medlist.js.
   ========================================================================== */
"""


def _strip_private(obj):
    if isinstance(obj, dict):
        return {k: _strip_private(v) for k, v in obj.items() if not k.startswith("_")}
    if isinstance(obj, list):
        return [_strip_private(x) for x in obj]
    return obj


def build_payload(classmap, rules, generated=None):
    sources = list(L.curated("sources.json")["sources"])
    if not any(s.get("id") == RXCLASS_SOURCE["id"] for s in sources):
        sources.append(RXCLASS_SOURCE)
    return {
        "version": VERSION,
        "generated": generated or datetime.date.today().isoformat(),
        "sources": sources,
        "drugClasses": classmap["drugClasses"],
        "generics": classmap["generics"],
        "brands": classmap["brands"],
        "rules": _strip_private(rules),
    }


def emit(payload):
    import json
    clean = _strip_private(payload)
    json_path = os.path.join(L.ROOT, "data", "interaction-rules.json")
    L.save_json(json_path, clean)

    js_path = os.path.join(L.ROOT, "interaction-rules.js")
    body = json.dumps(clean, ensure_ascii=False, indent=2)
    js = (HEADER +
          '(function () {\n  "use strict";\n' +
          "  window.INTERACTION_RULES = " + body + ";\n" +
          "})();\n")
    with open(js_path, "w", encoding="utf-8") as fh:
        fh.write(js)

    kb = os.path.getsize(js_path) / 1024.0
    print(f"emit: interaction-rules.js ({kb:.1f} KB), data/interaction-rules.json")
    print(f"  version {clean['version']} generated {clean['generated']}: "
          f"{len(clean['drugClasses'])} classified drugs, {len(clean['rules'])} rules, "
          f"{len(clean['generics'])} generics, {len(clean['brands'])} brand aliases")
    return js_path, json_path


if __name__ == "__main__":
    import build_classmap
    import build_rules
    emit(build_payload(build_classmap.build(), build_rules.build()))
