/* StewardMD — Regional antibiogram data (study records + best-of regional composites).
 * ===========================================================================
 * GENERATED by scripts/build-antibiogram-data.mjs from data/antibiogram-raw.json —
 * do not hand-edit; re-run the generator. Provenance: 20 Indian antibiogram
 * studies (downloaded PDFs), each extracted from the actual susceptibility tables and
 * then adversarially re-verified cell-by-cell against the source (0 corrections).
 *
 * Every value is % SUSCEPTIBLE (0–100); %R sources were converted s = 100 − R at
 * extraction. Missing cells are simply absent (the UI renders "—"). No values invented.
 *
 * CREDIBILITY RANKING (lower = more authoritative; drives composite selection):
 *   1  state/national AMR surveillance networks (TARS-Net 2024, ICMR-AMRSN)
 *   2  large recent (≥2022) multicentre or high-n full-panel single-centre studies
 *   3  narrow single-organism / single-syndrome / pre-2021 (fallback only)
 * Tie-break: more recent 'year' wins.
 *
 * Load order: AFTER app.js (for window.ASP_ABG.national fallback), BEFORE policy.js.
 * Exposes: window.ABG_STUDIES, window.buildComposite(region), window.REGION_ABG,
 *          window.ABG_DATA = { studies, buildComposite, region, getStudy }.
 * ======================================================================== */
(function () {
  "use strict";

  var ABG_STUDIES = [
 {
  "id": "RML_ICU",
  "label": "RML Lucknow ICU blood cultures (2022–23)",
  "region": "north",
  "city": "Lucknow",
  "year": 2023,
  "credibility": 2,
  "source": "RML Institute of Medical Sciences, Lucknow — ICU blood cultures · Cureus 2024 (10.7759/cureus.57356)",
  "org": {
   "Staphylococcus aureus": {
    "n": 20,
    "specimen": "ICU blood culture",
    "d": {
     "cefoxitin": {
      "s": 22.4
     },
     "erythromycin": {
      "s": 40
     },
     "clindamycin": {
      "s": 35
     },
     "tetracycline": {
      "s": 40
     },
     "ciprofloxacin": {
      "s": 15
     },
     "chloramphenicol": {
      "s": 60
     },
     "vancomycin": {
      "s": 100
     },
     "linezolid": {
      "s": 100
     },
     "gentamicin": {
      "s": 26.1
     },
     "teicoplanin": {
      "s": 67.4
     }
    }
   },
   "Enterococcus": {
    "n": 9,
    "specimen": "ICU blood culture",
    "d": {
     "erythromycin": {
      "s": 12.8
     },
     "tetracycline": {
      "s": 33.3
     },
     "ciprofloxacin": {
      "s": 16
     },
     "chloramphenicol": {
      "s": 77.8
     },
     "vancomycin": {
      "s": 84.1
     },
     "linezolid": {
      "s": 100
     },
     "gentamicin": {
      "s": 22.2
     },
     "teicoplanin": {
      "s": 62.4
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 41,
    "specimen": "ICU blood culture",
    "d": {
     "ampsulbactam": {
      "s": 0
     },
     "ceftazidime": {
      "s": 2.4
     },
     "imipenem": {
      "s": 19.5
     },
     "tetracycline": {
      "s": 39
     },
     "piptazo": {
      "s": 9.8
     },
     "ciprofloxacin": {
      "s": 2.5
     },
     "gentamicin": {
      "s": 3.2
     },
     "amikacin": {
      "s": 14.6
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 38,
    "specimen": "ICU blood culture",
    "d": {
     "ampsulbactam": {
      "s": 7.9
     },
     "ceftazidime": {
      "s": 23.7
     },
     "imipenem": {
      "s": 18.4
     },
     "tetracycline": {
      "s": 23.7
     },
     "piptazo": {
      "s": 26.3
     },
     "ciprofloxacin": {
      "s": 10.5
     },
     "gentamicin": {
      "s": 11
     },
     "amikacin": {
      "s": 26.3
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 19,
    "specimen": "ICU blood culture",
    "d": {
     "ampsulbactam": {
      "s": 10.5
     },
     "ceftazidime": {
      "s": 26.3
     },
     "imipenem": {
      "s": 26.1
     },
     "tetracycline": {
      "s": 57.9
     },
     "piptazo": {
      "s": 5.3
     },
     "ciprofloxacin": {
      "s": 15.8
     },
     "gentamicin": {
      "s": 10.5
     },
     "amikacin": {
      "s": 11.1
     }
    }
   }
  }
 },
 {
  "id": "DOON_CSOM",
  "label": "Govt Doon Dehradun CSOM ear discharge (2022–24)",
  "region": "north",
  "city": "Dehradun",
  "year": 2024,
  "credibility": 3,
  "source": "Govt Doon Medical College, Dehradun — CSOM ear discharge · Cureus 2024 (PMC11483178)",
  "org": {
   "Pseudomonas aeruginosa": {
    "n": 46,
    "specimen": "ear discharge (CSOM)",
    "d": {
     "piptazo": {
      "s": 84.2
     },
     "ceftazidime": {
      "s": 68.9
     },
     "cefoperazone": {
      "s": 61.4
     },
     "cefepime": {
      "s": 72.1
     },
     "imipenem": {
      "s": 72.7
     },
     "meropenem": {
      "s": 72.1
     },
     "ciprofloxacin": {
      "s": 37
     },
     "levofloxacin": {
      "s": 34.9
     },
     "amikacin": {
      "s": 57.8
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 23,
    "specimen": "ear discharge (CSOM)",
    "d": {
     "gentamicin": {
      "s": 86.4
     },
     "ciprofloxacin": {
      "s": 4.5
     },
     "levofloxacin": {
      "s": 9.1
     },
     "cotrimoxazole": {
      "s": 50
     },
     "erythromycin": {
      "s": 36.4
     },
     "clindamycin": {
      "s": 77.3
     },
     "linezolid": {
      "s": 100
     },
     "daptomycin": {
      "s": 100
     },
     "vancomycin": {
      "s": 90.9
     },
     "tetracycline": {
      "s": 90.9
     }
    }
   }
  }
 },
 {
  "id": "SGRD_KLEB",
  "label": "SGRD Amritsar Klebsiella VAP (2018 & 2022)",
  "region": "north",
  "city": "Amritsar",
  "year": 2022,
  "credibility": 3,
  "source": "SGRD Institute of Medical Sciences, Amritsar — Klebsiella VAP · Cureus 2023 (PMC10106535)",
  "org": {
   "Klebsiella pneumoniae": {
    "n": 40,
    "specimen": "endotracheal aspirate, ICU mechanically ventilated (VAP)",
    "d": {
     "tigecycline": {
      "s": 100
     },
     "colistin": {
      "s": 92
     },
     "cotrimoxazole": {
      "s": 38
     },
     "minocycline": {
      "s": 67
     },
     "amoxicillin": {
      "s": 10
     },
     "ceftriaxone": {
      "s": 7.5
     },
     "piptazo": {
      "s": 7.5
     },
     "cefoperazonesulbactam": {
      "s": 5
     },
     "cefuroxime": {
      "s": 0
     },
     "imipenem": {
      "s": 15
     },
     "meropenem": {
      "s": 15
     },
     "amikacin": {
      "s": 17.5
     },
     "gentamicin": {
      "s": 12.5
     },
     "nalidixicacid": {
      "s": 7.5
     },
     "ciprofloxacin": {
      "s": 7.5
     }
    }
   }
  }
 },
 {
  "id": "HAYES_URO",
  "label": "Hayes Prayagraj uropathogens (2018–19)",
  "region": "north",
  "city": "Prayagraj",
  "year": 2019,
  "credibility": 3,
  "source": "Hayes Memorial Mission Hospital, Prayagraj — uropathogens · Front. Microbiol. 2022 (10.3389/fmicb.2022.965053)",
  "org": {
   "Escherichia coli": {
    "n": 183,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 77
     },
     "gentamicin": {
      "s": 49.7
     },
     "ampicillin": {
      "s": 1.1
     },
     "amoxiclav": {
      "s": 12.6
     },
     "piptazo": {
      "s": 37.7
     },
     "ceftazidime": {
      "s": 12
     },
     "cefepime": {
      "s": 6.6
     },
     "ceftriaxone": {
      "s": 16.9
     },
     "cotrimoxazole": {
      "s": 39.8
     },
     "ceftazidime-clav": {
      "s": 45.9
     },
     "imipenem": {
      "s": 57.4
     },
     "meropenem": {
      "s": 37.2
     },
     "nitrofurantoin": {
      "s": 49.7
     },
     "norfloxacin": {
      "s": 4.4
     },
     "ciprofloxacin": {
      "s": 3.8
     }
    }
   },
   "Proteus mirabilis": {
    "n": 23,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 73.9
     },
     "gentamicin": {
      "s": 56.5
     },
     "ampicillin": {
      "s": 8.7
     },
     "amoxiclav": {
      "s": 0
     },
     "piptazo": {
      "s": 52.2
     },
     "ceftazidime": {
      "s": 26.1
     },
     "cefepime": {
      "s": 8.7
     },
     "ceftriaxone": {
      "s": 26.1
     },
     "cotrimoxazole": {
      "s": 34.7
     },
     "imipenem": {
      "s": 13
     },
     "meropenem": {
      "s": 13
     },
     "nitrofurantoin": {
      "s": 21.7
     },
     "norfloxacin": {
      "s": 13
     },
     "ciprofloxacin": {
      "s": 21.7
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 22,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 81.8
     },
     "gentamicin": {
      "s": 86.4
     },
     "ampicillin": {
      "s": 0
     },
     "amoxiclav": {
      "s": 18.2
     },
     "piptazo": {
      "s": 45.5
     },
     "ceftazidime": {
      "s": 54.5
     },
     "cefepime": {
      "s": 22.7
     },
     "ceftriaxone": {
      "s": 40.9
     },
     "cotrimoxazole": {
      "s": 86.4
     },
     "ceftazidime-clav": {
      "s": 0
     },
     "imipenem": {
      "s": 72.7
     },
     "meropenem": {
      "s": 40.9
     },
     "nitrofurantoin": {
      "s": 13.6
     },
     "norfloxacin": {
      "s": 13.6
     },
     "ciprofloxacin": {
      "s": 22.7
     }
    }
   },
   "Enterobacter cloacae": {
    "n": 17,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 52.9
     },
     "gentamicin": {
      "s": 52.9
     },
     "ampicillin": {
      "s": 0
     },
     "amoxiclav": {
      "s": 5.9
     },
     "piptazo": {
      "s": 23.5
     },
     "ceftazidime": {
      "s": 17.6
     },
     "cefepime": {
      "s": 23.5
     },
     "ceftriaxone": {
      "s": 35.3
     },
     "cotrimoxazole": {
      "s": 35.3
     },
     "imipenem": {
      "s": 29.4
     },
     "meropenem": {
      "s": 29.4
     },
     "nitrofurantoin": {
      "s": 17.6
     },
     "norfloxacin": {
      "s": 0
     },
     "ciprofloxacin": {
      "s": 5.9
     }
    }
   },
   "Citrobacter": {
    "n": 21,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 90.5
     },
     "gentamicin": {
      "s": 81
     },
     "ampicillin": {
      "s": 23.8
     },
     "amoxiclav": {
      "s": 4.8
     },
     "piptazo": {
      "s": 71.4
     },
     "ceftazidime": {
      "s": 33.3
     },
     "cefepime": {
      "s": 9.5
     },
     "ceftriaxone": {
      "s": 42.9
     },
     "cotrimoxazole": {
      "s": 52.4
     },
     "imipenem": {
      "s": 57.1
     },
     "meropenem": {
      "s": 52.4
     },
     "nitrofurantoin": {
      "s": 61.9
     },
     "norfloxacin": {
      "s": 23.8
     },
     "ciprofloxacin": {
      "s": 28.6
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 21,
    "specimen": "urine",
    "d": {
     "amikacin": {
      "s": 76.2
     },
     "gentamicin": {
      "s": 81
     },
     "tobramycin": {
      "s": 71.4
     },
     "piperacillin": {
      "s": 23.8
     },
     "piptazo": {
      "s": 71.4
     },
     "ceftazidime": {
      "s": 23.8
     },
     "cefepime": {
      "s": 38.1
     },
     "imipenem": {
      "s": 90.5
     },
     "meropenem": {
      "s": 23.8
     },
     "nitrofurantoin": {
      "s": 0
     },
     "norfloxacin": {
      "s": 66.7
     },
     "ciprofloxacin": {
      "s": 71.4
     }
    }
   },
   "Enterococcus": {
    "n": 18,
    "specimen": "urine",
    "d": {
     "ampicillin": {
      "s": 66.7
     },
     "penicillin": {
      "s": 33.3
     },
     "nitrofurantoin": {
      "s": 94.4
     },
     "norfloxacin": {
      "s": 33.3
     },
     "ciprofloxacin": {
      "s": 44.4
     },
     "erythromycin": {
      "s": 11.1
     },
     "h-gentamicin": {
      "s": 66.7
     },
     "tetracycline": {
      "s": 38.9
     },
     "teicoplanin": {
      "s": 83.3
     },
     "vancomycin": {
      "s": 72.2
     },
     "linezolid": {
      "s": 88.9
     },
     "chloramphenicol": {
      "s": 83.3
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 20,
    "specimen": "urine",
    "d": {
     "cotrimoxazole": {
      "s": 20
     },
     "nitrofurantoin": {
      "s": 70
     },
     "penicillin": {
      "s": 0
     },
     "cefoxitin": {
      "s": 15
     },
     "norfloxacin": {
      "s": 10
     },
     "ciprofloxacin": {
      "s": 10
     },
     "clindamycin": {
      "s": 55
     },
     "erythromycin": {
      "s": 5
     },
     "netilmicin": {
      "s": 25
     },
     "novobiocin": {
      "s": 70
     },
     "doxycycline": {
      "s": 40
     },
     "vancomycin": {
      "s": 100
     },
     "chloramphenicol": {
      "s": 75
     }
    }
   }
  }
 },
 {
  "id": "JPNATC_ACINETO",
  "label": "JPNATC AIIMS Delhi Acinetobacter (2012–16)",
  "region": "north",
  "city": "New Delhi",
  "year": 2016,
  "credibility": 3,
  "source": "JPN Apex Trauma Centre, AIIMS Delhi — Acinetobacter surveillance · J. Lab. Physicians 2019 (10.4103/JLP.JLP_72_18)",
  "org": {
   "Acinetobacter baumannii": {
    "n": 3744,
    "specimen": "all clinical (trauma centre; 98.5% A. baumannii)",
    "d": {
     "amikacin": {
      "s": 8
     },
     "cefepime": {
      "s": 5
     },
     "ceftazidime": {
      "s": 5
     },
     "ciprofloxacin": {
      "s": 4
     },
     "gentamicin": {
      "s": 8
     },
     "imipenem": {
      "s": 10
     },
     "levofloxacin": {
      "s": 20
     },
     "meropenem": {
      "s": 10
     },
     "piperacillin": {
      "s": 5
     },
     "piptazo": {
      "s": 7
     },
     "cotrimoxazole": {
      "s": 20
     },
     "tigecycline": {
      "s": 92
     },
     "colistin": {
      "s": 98.2
     }
    }
   }
  }
 },
 {
  "id": "MGJAIPUR_BSI",
  "label": "MG Jaipur bloodstream infections (2022–23)",
  "region": "north",
  "city": "Jaipur",
  "year": 2023,
  "credibility": 2,
  "source": "Mahatma Gandhi Medical College, Jaipur — bloodstream infections · J. Lab. Physicians 2024 (10.25259/JLP_94_2024)",
  "org": {
   "Klebsiella pneumoniae": {
    "n": 309,
    "specimen": "blood",
    "d": {
     "cefepime": {
      "s": 10.4
     },
     "meropenem": {
      "s": 12.3
     },
     "imipenem": {
      "s": 25.2
     },
     "piptazo": {
      "s": 20.1
     },
     "cefoperazonesulbactam": {
      "s": 21
     },
     "gentamicin": {
      "s": 27.5
     },
     "amikacin": {
      "s": 28.2
     },
     "ciprofloxacin": {
      "s": 14.2
     },
     "colistin": {
      "s": 100
     },
     "cotrimoxazole": {
      "s": 23.3
     },
     "cefuroxime": {
      "s": 23.9
     },
     "ceftriaxone": {
      "s": 34.6
     },
     "ertapenem": {
      "s": 28.5
     },
     "amoxiclav": {
      "s": 26.9
     }
    }
   },
   "Escherichia coli": {
    "n": 191,
    "specimen": "blood",
    "d": {
     "cefepime": {
      "s": 37.7
     },
     "meropenem": {
      "s": 57.6
     },
     "imipenem": {
      "s": 59.7
     },
     "piptazo": {
      "s": 39.8
     },
     "cefoperazonesulbactam": {
      "s": 52.9
     },
     "gentamicin": {
      "s": 62.8
     },
     "amikacin": {
      "s": 78.5
     },
     "ciprofloxacin": {
      "s": 3.7
     },
     "colistin": {
      "s": 100
     },
     "cotrimoxazole": {
      "s": 38.2
     },
     "cefuroxime": {
      "s": 13.6
     },
     "ceftriaxone": {
      "s": 29.8
     },
     "ertapenem": {
      "s": 55.5
     },
     "amoxiclav": {
      "s": 24.6
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 138,
    "specimen": "blood",
    "d": {
     "ceftazidime": {
      "s": 6.5
     },
     "cefepime": {
      "s": 5.1
     },
     "aztreonam": {
      "s": 5.1
     },
     "meropenem": {
      "s": 8
     },
     "imipenem": {
      "s": 5.1
     },
     "piptazo": {
      "s": 7.2
     },
     "cefoperazonesulbactam": {
      "s": 15.2
     },
     "gentamicin": {
      "s": 8
     },
     "amikacin": {
      "s": 7.2
     },
     "ciprofloxacin": {
      "s": 6.5
     },
     "levofloxacin": {
      "s": 6.5
     },
     "minocycline": {
      "s": 42
     },
     "colistin": {
      "s": 100
     },
     "cotrimoxazole": {
      "s": 26.1
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 50,
    "specimen": "blood",
    "d": {
     "ceftazidime": {
      "s": 44
     },
     "cefepime": {
      "s": 42
     },
     "aztreonam": {
      "s": 0
     },
     "meropenem": {
      "s": 36
     },
     "imipenem": {
      "s": 40
     },
     "piptazo": {
      "s": 28
     },
     "cefoperazonesulbactam": {
      "s": 40
     },
     "ciprofloxacin": {
      "s": 32
     },
     "levofloxacin": {
      "s": 28
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 46,
    "specimen": "blood",
    "d": {
     "penicillin": {
      "s": 15.2
     },
     "oxacillin": {
      "s": 43.5
     },
     "gentamicin": {
      "s": 82.6
     },
     "ciprofloxacin": {
      "s": 8.7
     },
     "levofloxacin": {
      "s": 15.2
     },
     "tetracycline": {
      "s": 89.1
     },
     "cotrimoxazole": {
      "s": 80.4
     },
     "erythromycin": {
      "s": 34.8
     },
     "clindamycin": {
      "s": 67.4
     },
     "vancomycin": {
      "s": 100
     },
     "teicoplanin": {
      "s": 95.7
     },
     "linezolid": {
      "s": 100
     },
     "daptomycin": {
      "s": 100
     }
    }
   },
   "Enterococcus": {
    "n": 125,
    "specimen": "blood",
    "d": {
     "penicillin": {
      "s": 12
     },
     "hlgentamicin": {
      "s": 18.4
     },
     "ciprofloxacin": {
      "s": 4.8
     },
     "levofloxacin": {
      "s": 6.4
     },
     "tetracycline": {
      "s": 11.2
     },
     "erythromycin": {
      "s": 2.4
     },
     "vancomycin": {
      "s": 92.8
     },
     "teicoplanin": {
      "s": 93.6
     },
     "linezolid": {
      "s": 96.8
     },
     "daptomycin": {
      "s": 100
     }
    }
   }
  }
 },
 {
  "id": "AIIMS_MEDWARDS",
  "label": "AIIMS Delhi medicine wards & ICU (2017–19)",
  "region": "north",
  "city": "New Delhi",
  "year": 2019,
  "credibility": 3,
  "source": "AIIMS New Delhi (medicine wards & ICU) · J. Lab. Physicians 2020 (10.1055/s-0040-1721161)",
  "org": {
   "Acinetobacter baumannii": {
    "n": 92,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "ciprofloxacin": {
      "s": 1.1
     },
     "amikacin": {
      "s": 1.1
     },
     "netilmicin": {
      "s": 10.6
     },
     "cefotaxime": {
      "s": 0
     },
     "ceftazidime": {
      "s": 0
     },
     "cefoperazonesulbactam": {
      "s": 65.3
     },
     "imipenem": {
      "s": 9.9
     },
     "meropenem": {
      "s": 22.8
     },
     "amoxiclav": {
      "s": 0
     },
     "piptazo": {
      "s": 1.2
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 86,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "ciprofloxacin": {
      "s": 3.5
     },
     "amikacin": {
      "s": 15.2
     },
     "netilmicin": {
      "s": 17
     },
     "cefotaxime": {
      "s": 2.4
     },
     "ceftazidime": {
      "s": 3.6
     },
     "cefoperazonesulbactam": {
      "s": 27.1
     },
     "imipenem": {
      "s": 57
     },
     "meropenem": {
      "s": 16.3
     },
     "amoxiclav": {
      "s": 0
     },
     "piptazo": {
      "s": 14.3
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Escherichia coli": {
    "n": 75,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "ciprofloxacin": {
      "s": 6.4
     },
     "amikacin": {
      "s": 59.5
     },
     "netilmicin": {
      "s": 64
     },
     "cefotaxime": {
      "s": 9.9
     },
     "ceftazidime": {
      "s": 12
     },
     "cefoperazonesulbactam": {
      "s": 60.6
     },
     "imipenem": {
      "s": 75.7
     },
     "meropenem": {
      "s": 19.5
     },
     "amoxiclav": {
      "s": 9.4
     },
     "piptazo": {
      "s": 13.5
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 22,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "ciprofloxacin": {
      "s": 33.4
     },
     "amikacin": {
      "s": 31.8
     },
     "netilmicin": {
      "s": 30.8
     },
     "cefotaxime": {
      "s": 14.3
     },
     "ceftazidime": {
      "s": 22.7
     },
     "cefoperazonesulbactam": {
      "s": 36.4
     },
     "imipenem": {
      "s": 50
     },
     "meropenem": {
      "s": 36.4
     },
     "piptazo": {
      "s": 36.4
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Enterococcus faecium": {
    "n": 15,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "penicillin": {
      "s": 23.1
     },
     "ciprofloxacin": {
      "s": 0
     },
     "erythromycin": {
      "s": 0
     },
     "gentamicin": {
      "s": 0
     },
     "linezolid": {
      "s": 93.3
     },
     "teicoplanin": {
      "s": 66.7
     },
     "vancomycin": {
      "s": 65.9
     },
     "tetracycline": {
      "s": 66.7
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 10,
    "specimen": "all clinical (medicine wards & ICU)",
    "d": {
     "penicillin": {
      "s": 22.3
     },
     "amoxiclav": {
      "s": 33.3
     },
     "ciprofloxacin": {
      "s": 30
     },
     "erythromycin": {
      "s": 33.3
     },
     "gentamicin": {
      "s": 50
     },
     "amikacin": {
      "s": 77.8
     },
     "linezolid": {
      "s": 100
     },
     "teicoplanin": {
      "s": 100
     },
     "vancomycin": {
      "s": 100
     },
     "cotrimoxazole": {
      "s": 40
     }
    }
   }
  }
 },
 {
  "id": "SRM_CARBA",
  "label": "SRM Chennai carbapenem resistance (2022–24)",
  "region": "south",
  "city": "Chennai",
  "year": 2024,
  "credibility": 2,
  "source": "SRM Medical College, Kattankulathur — carbapenem resistance in GNB · Front. Med. 2025 (10.3389/fmed.2025.1571231)",
  "org": {
   "Escherichia coli": {
    "n": 433,
    "specimen": "carbapenem-resistant subset, all clinical",
    "d": {
     "ceftazidime": {
      "s": 0
     },
     "piptazo": {
      "s": 0
     },
     "ciprofloxacin": {
      "s": 1.7
     },
     "cefepime": {
      "s": 1.7
     },
     "colistin": {
      "s": 93.2
     },
     "gentamicin": {
      "s": 50.9
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 733,
    "specimen": "carbapenem-resistant subset, all clinical",
    "d": {
     "ceftazidime": {
      "s": 4
     },
     "ciprofloxacin": {
      "s": 5.6
     },
     "cefepime": {
      "s": 4.8
     },
     "levofloxacin": {
      "s": 7.1
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 290,
    "specimen": "carbapenem-resistant subset, all clinical",
    "d": {
     "ciprofloxacin": {
      "s": 6
     },
     "piptazo": {
      "s": 12
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 388,
    "specimen": "carbapenem-resistant subset, all clinical",
    "d": {
     "ceftazidime": {
      "s": 3.8
     },
     "piptazo": {
      "s": 3.8
     },
     "ciprofloxacin": {
      "s": 5.1
     },
     "colistin": {
      "s": 92.5
     }
    }
   }
  }
 },
 {
  "id": "JSS_KLEB",
  "label": "JSS Mysuru Klebsiella 10-yr (2014–23)",
  "region": "south",
  "city": "Mysuru",
  "year": 2023,
  "credibility": 2,
  "source": "JSS Medical College, Mysuru — 10-yr Klebsiella · Front. Microbiol. 2025 (PMC12209295)",
  "org": {
   "Klebsiella pneumoniae": {
    "n": 83,
    "specimen": "urine",
    "d": {
     "imipenem": {
      "s": 61.5
     },
     "meropenem": {
      "s": 61.5
     },
     "ertapenem": {
      "s": 61.5
     },
     "ciprofloxacin": {
      "s": 59
     },
     "aminoglycosides": {
      "s": 30.1
     },
     "amoxiclav": {
      "s": 13.3
     },
     "piptazo": {
      "s": 13.3
     },
     "cefoperazone-sulbactam": {
      "s": 37.4
     },
     "cotrimoxazole": {
      "s": 24.1
     },
     "cefepime": {
      "s": 14.5
     },
     "ceftriaxone": {
      "s": 10.8
     },
     "cefuroxime": {
      "s": 14.5
     },
     "cefuroxime-axetil": {
      "s": 8.4
     }
    }
   }
  }
 },
 {
  "id": "EASTPOINT",
  "label": "East Point Bengaluru full antibiogram (2022)",
  "region": "south",
  "city": "Bengaluru",
  "year": 2022,
  "credibility": 2,
  "source": "East Point Hospital & Research Center, Bengaluru — full antibiogram · Cureus 2024 (10.7759/cureus.60542)",
  "org": {
   "Escherichia coli": {
    "n": 131,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 25
     },
     "piptazo": {
      "s": 88
     },
     "aztreonam": {
      "s": 100
     },
     "imipenem": {
      "s": 95
     },
     "meropenem": {
      "s": 94
     },
     "gentamicin": {
      "s": 88
     },
     "amikacin": {
      "s": 93
     },
     "ciprofloxacin": {
      "s": 41
     },
     "ceftriaxone": {
      "s": 39
     },
     "cefuroxime": {
      "s": 34
     },
     "cotrimoxazole": {
      "s": 55
     },
     "levofloxacin": {
      "s": 26
     },
     "nitrofurantoin": {
      "s": 98
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 62,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 7
     },
     "piptazo": {
      "s": 83
     },
     "aztreonam": {
      "s": 100
     },
     "imipenem": {
      "s": 88
     },
     "meropenem": {
      "s": 89
     },
     "gentamicin": {
      "s": 83
     },
     "amikacin": {
      "s": 84
     },
     "ciprofloxacin": {
      "s": 54
     },
     "ceftriaxone": {
      "s": 63
     },
     "cefuroxime": {
      "s": 56
     },
     "cotrimoxazole": {
      "s": 67
     },
     "levofloxacin": {
      "s": 53
     },
     "nitrofurantoin": {
      "s": 76
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 36,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 12
     },
     "piptazo": {
      "s": 85
     },
     "aztreonam": {
      "s": 72
     },
     "imipenem": {
      "s": 82
     },
     "meropenem": {
      "s": 93
     },
     "gentamicin": {
      "s": 74
     },
     "amikacin": {
      "s": 81
     },
     "ciprofloxacin": {
      "s": 60
     },
     "ceftriaxone": {
      "s": 0
     },
     "cefuroxime": {
      "s": 0
     },
     "cotrimoxazole": {
      "s": 67
     },
     "levofloxacin": {
      "s": 80
     },
     "nitrofurantoin": {
      "s": 100
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 3,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 0
     },
     "piptazo": {
      "s": 0
     },
     "imipenem": {
      "s": 0
     },
     "meropenem": {
      "s": 0
     },
     "gentamicin": {
      "s": 0
     },
     "amikacin": {
      "s": 0
     },
     "ciprofloxacin": {
      "s": 0
     },
     "ceftriaxone": {
      "s": 0
     },
     "cefuroxime": {
      "s": 0
     },
     "cotrimoxazole": {
      "s": 0
     },
     "levofloxacin": {
      "s": 0
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 51,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 100
     },
     "amoxiclav": {
      "s": 100
     },
     "cefazolin": {
      "s": 100
     },
     "gentamicin": {
      "s": 83
     },
     "tetracycline": {
      "s": 90
     },
     "ciprofloxacin": {
      "s": 38
     },
     "cefotaxime": {
      "s": 100
     },
     "erythromycin": {
      "s": 43
     },
     "clindamycin": {
      "s": 74
     },
     "cefoxitin": {
      "s": 41
     },
     "cotrimoxazole": {
      "s": 6
     },
     "chloramphenicol": {
      "s": 96
     },
     "levofloxacin": {
      "s": 31
     },
     "nitrofurantoin": {
      "s": 100
     },
     "teicoplanin": {
      "s": 100
     }
    }
   },
   "Enterococcus": {
    "n": 26,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 81
     },
     "gentamicin": {
      "s": 33
     },
     "tetracycline": {
      "s": 40
     },
     "ciprofloxacin": {
      "s": 40
     },
     "erythromycin": {
      "s": 50
     },
     "chloramphenicol": {
      "s": 100
     },
     "levofloxacin": {
      "s": 0
     },
     "nitrofurantoin": {
      "s": 75
     },
     "vancomycin": {
      "s": 82
     },
     "teicoplanin": {
      "s": 40
     }
    }
   },
   "Proteus mirabilis": {
    "n": 11,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 33
     },
     "piptazo": {
      "s": 100
     },
     "imipenem": {
      "s": 91
     },
     "meropenem": {
      "s": 100
     },
     "gentamicin": {
      "s": 54
     },
     "amikacin": {
      "s": 82
     },
     "ciprofloxacin": {
      "s": 29
     },
     "ceftriaxone": {
      "s": 63
     },
     "cefuroxime": {
      "s": 54
     },
     "cotrimoxazole": {
      "s": 50
     },
     "levofloxacin": {
      "s": 100
     },
     "nitrofurantoin": {
      "s": 0
     }
    }
   },
   "Citrobacter": {
    "n": 8,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 25
     },
     "piptazo": {
      "s": 87
     },
     "imipenem": {
      "s": 100
     },
     "meropenem": {
      "s": 83
     },
     "gentamicin": {
      "s": 86
     },
     "amikacin": {
      "s": 100
     },
     "ciprofloxacin": {
      "s": 60
     },
     "ceftriaxone": {
      "s": 100
     },
     "cefuroxime": {
      "s": 57
     },
     "cotrimoxazole": {
      "s": 71
     },
     "levofloxacin": {
      "s": 50
     },
     "nitrofurantoin": {
      "s": 100
     }
    }
   },
   "Salmonella Typhi": {
    "n": 1,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 0
     },
     "piptazo": {
      "s": 100
     },
     "meropenem": {
      "s": 0
     },
     "gentamicin": {
      "s": 100
     },
     "amikacin": {
      "s": 0
     },
     "ciprofloxacin": {
      "s": 100
     },
     "ceftriaxone": {
      "s": 0
     },
     "cefuroxime": {
      "s": 0
     },
     "cotrimoxazole": {
      "s": 100
     }
    }
   }
  }
 },
 {
  "id": "SAVEETHA_URO",
  "label": "Saveetha Chennai E. coli UTI (2023–24)",
  "region": "south",
  "city": "Chennai",
  "year": 2024,
  "credibility": 3,
  "source": "Saveetha Medical College, Chennai — E. coli UTI · Cureus 2024 (10.7759/cureus.56632)",
  "org": {
   "Escherichia coli": {
    "n": 18,
    "specimen": "urine (female UTI, 35-50 yr)",
    "d": {
     "cefepime": {
      "q": "susceptible"
     },
     "ciprofloxacin": {
      "q": "variable"
     },
     "gentamicin": {
      "q": "variable"
     },
     "cotrimoxazole": {
      "q": "resistant"
     },
     "ceftriaxone": {
      "q": "resistant"
     },
     "meropenem": {
      "q": "resistant"
     },
     "amikacin": {
      "q": "resistant"
     },
     "ampicillin": {
      "q": "resistant"
     },
     "nitrofurantoin": {
      "q": "resistant"
     }
    }
   }
  }
 },
 {
  "id": "ANDHRA_UTI",
  "label": "Andhra MC Vizag UTI GNB (2022–23)",
  "region": "south",
  "city": "Visakhapatnam",
  "year": 2023,
  "credibility": 3,
  "source": "Andhra Medical College, Visakhapatnam — UTI GNB · Int. J. Curr. Pharm. Sci. 2024",
  "org": {}
 },
 {
  "id": "KONASEEMA_GNB",
  "label": "Konaseema Amalapuram GNB (2023–24)",
  "region": "south",
  "city": "Amalapuram",
  "year": 2024,
  "credibility": 2,
  "source": "Konaseema Institute of Medical Sciences, Amalapuram — GNB · Bioinformation 2025",
  "org": {
   "Escherichia coli": {
    "n": 244,
    "specimen": "urine (Table 3 titled 'urinary isolates'); ICU",
    "d": {
     "meropenem": {
      "s": 70,
      "approx": true
     },
     "minocycline": {
      "s": 70,
      "approx": true
     },
     "amoxiclav": {
      "q": "<60% (poorly sensitive)"
     },
     "ampsulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftriaxone": {
      "q": "<60% (poorly sensitive)"
     },
     "levofloxacin": {
      "q": "<60% (poorly sensitive)"
     },
     "gentamicin": {
      "q": "<60% (poorly sensitive)"
     },
     "cotrimoxazole": {
      "q": "<60% (poorly sensitive)"
     },
     "piptazo": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime-avibactam": {
      "q": "<60% (poorly sensitive)"
     },
     "cefoperazone-sulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "nitrofurantoin": {
      "q": "effective (listed effective urinary drug)"
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 277,
    "specimen": "urine (Table 3 titled 'urinary isolates'); ICU",
    "d": {
     "gentamicin": {
      "s": 70,
      "approx": true
     },
     "cefoperazone-sulbactam": {
      "s": 70,
      "approx": true
     },
     "meropenem": {
      "s": 70,
      "approx": true
     },
     "minocycline": {
      "s": 70,
      "approx": true
     },
     "amoxiclav": {
      "q": "<60% (poorly sensitive)"
     },
     "ampsulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftriaxone": {
      "q": "<60% (poorly sensitive)"
     },
     "levofloxacin": {
      "q": "<60% (poorly sensitive)"
     },
     "cotrimoxazole": {
      "q": "<60% (poorly sensitive)"
     },
     "piptazo": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime-avibactam": {
      "q": "<60% (poorly sensitive)"
     },
     "nitrofurantoin": {
      "q": "effective (listed effective urinary drug)"
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 148,
    "specimen": "urine (Table 3 titled 'urinary isolates'); ICU",
    "d": {
     "meropenem": {
      "s": 80,
      "approx": true
     },
     "gentamicin": {
      "s": 70,
      "approx": true
     },
     "piptazo": {
      "s": 70,
      "approx": true
     },
     "tobramycin": {
      "s": 70,
      "approx": true
     },
     "amoxiclav": {
      "q": "<60% (poorly sensitive)"
     },
     "ampsulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftriaxone": {
      "q": "<60% (poorly sensitive)"
     },
     "levofloxacin": {
      "q": "<60% (poorly sensitive)"
     },
     "cotrimoxazole": {
      "q": "<60% (poorly sensitive)"
     },
     "tetracycline": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime-avibactam": {
      "q": "<60% (poorly sensitive)"
     },
     "cefoperazone-sulbactam": {
      "q": "<60% (poorly sensitive)"
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 93,
    "specimen": "urine (Table 3 titled 'urinary isolates'); ICU",
    "d": {
     "tobramycin": {
      "s": 96
     },
     "gentamicin": {
      "s": 70,
      "approx": true
     },
     "minocycline": {
      "s": 70,
      "approx": true
     },
     "meropenem": {
      "q": "<60% (poorly sensitive)"
     },
     "amoxiclav": {
      "q": "<60% (poorly sensitive)"
     },
     "ampsulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftriaxone": {
      "q": "<60% (poorly sensitive)"
     },
     "levofloxacin": {
      "q": "<60% (poorly sensitive)"
     },
     "cotrimoxazole": {
      "q": "<60% (poorly sensitive)"
     },
     "tetracycline": {
      "q": "<60% (poorly sensitive)"
     },
     "piptazo": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime-avibactam": {
      "q": "<60% (poorly sensitive)"
     },
     "cefoperazone-sulbactam": {
      "q": "<60% (poorly sensitive)"
     }
    }
   },
   "Proteus mirabilis": {
    "n": 13,
    "specimen": "urine (Table 3 titled 'urinary isolates'); ICU",
    "d": {
     "piptazo": {
      "s": 70,
      "approx": true
     },
     "ceftazidime-avibactam": {
      "s": 70,
      "approx": true
     },
     "cefoperazone-sulbactam": {
      "s": 70,
      "approx": true
     },
     "meropenem": {
      "s": 70,
      "approx": true
     },
     "amoxiclav": {
      "q": "<60% (poorly sensitive)"
     },
     "ampsulbactam": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftazidime": {
      "q": "<60% (poorly sensitive)"
     },
     "ceftriaxone": {
      "q": "<60% (poorly sensitive)"
     },
     "levofloxacin": {
      "q": "<60% (poorly sensitive)"
     },
     "gentamicin": {
      "q": "<60% (poorly sensitive)"
     },
     "cotrimoxazole": {
      "q": "<60% (poorly sensitive)"
     },
     "minocycline": {
      "q": "<60% (poorly sensitive)"
     },
     "nitrofurantoin": {
      "q": "<60% / ineffective"
     },
     "norfloxacin": {
      "q": "<60% / ineffective"
     }
    }
   }
  }
 },
 {
  "id": "TARSNET",
  "label": "TARS-Net Telangana Annual Report 2024",
  "region": "south",
  "city": "Telangana",
  "year": 2024,
  "credibility": 1,
  "source": "TARS-Net Telangana Annual Report 2024 (Osmania MC / NCDC) — 13 sites, 16,274 isolates",
  "org": {
   "Staphylococcus aureus": {
    "n": 227,
    "specimen": "blood",
    "d": {
     "cefoxitin": {
      "s": 47
     },
     "gentamicin": {
      "s": 87
     },
     "ciprofloxacin": {
      "s": 44
     },
     "cotrimoxazole": {
      "s": 72
     },
     "clindamycin": {
      "s": 78
     },
     "erythromycin": {
      "s": 44
     },
     "linezolid": {
      "s": 100
     },
     "teicoplanin": {
      "s": 98
     },
     "doxycycline": {
      "s": 93
     }
    }
   },
   "Enterococcus": {
    "n": 290,
    "specimen": "blood",
    "d": {
     "ampicillin": {
      "s": 9
     },
     "gentamicin": {
      "s": 87
     },
     "erythromycin": {
      "s": 27
     },
     "linezolid": {
      "s": 100
     },
     "vancomycin": {
      "s": 97
     },
     "teicoplanin": {
      "s": 87
     },
     "doxycycline": {
      "s": 91
     },
     "nitrofurantoin": {
      "s": 74
     },
     "tetracycline": {
      "s": 33
     }
    }
   },
   "Escherichia coli": {
    "n": 295,
    "specimen": "blood",
    "d": {
     "ampicillin": {
      "s": 9
     },
     "amoxicillin": {
      "s": 29
     },
     "piptazo": {
      "s": 69
     },
     "cefuroxime": {
      "s": 19
     },
     "ceftriaxone": {
      "s": 23
     },
     "cefotaxime": {
      "s": 15
     },
     "cefepime": {
      "s": 42
     },
     "ertapenem": {
      "s": 89
     },
     "imipenem": {
      "s": 93
     },
     "meropenem": {
      "s": 89
     },
     "amikacin": {
      "s": 79
     },
     "gentamicin": {
      "s": 74
     },
     "ciprofloxacin": {
      "s": 30
     },
     "cotrimoxazole": {
      "s": 56
     },
     "colistin": {
      "s": 100
     },
     "fosfomycin": {
      "s": 78
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 890,
    "specimen": "blood",
    "d": {
     "ampicillin": {
      "s": 14
     },
     "piptazo": {
      "s": 52
     },
     "cefuroxime": {
      "s": 16
     },
     "ceftriaxone": {
      "s": 12
     },
     "cefotaxime": {
      "s": 9
     },
     "cefepime": {
      "s": 35
     },
     "ertapenem": {
      "s": 53
     },
     "imipenem": {
      "s": 79
     },
     "meropenem": {
      "s": 51
     },
     "amikacin": {
      "s": 52
     },
     "gentamicin": {
      "s": 63
     },
     "ciprofloxacin": {
      "s": 49
     },
     "cotrimoxazole": {
      "s": 50
     },
     "colistin": {
      "s": 100
     },
     "doxycycline": {
      "s": 86
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 288,
    "specimen": "blood",
    "d": {
     "piptazo": {
      "s": 70
     },
     "ceftazidime": {
      "s": 45
     },
     "aztreonam": {
      "s": 15
     },
     "imipenem": {
      "s": 86
     },
     "meropenem": {
      "s": 79
     },
     "amikacin": {
      "s": 86
     },
     "gentamicin": {
      "s": 82
     },
     "ciprofloxacin": {
      "s": 78
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 495,
    "specimen": "blood",
    "d": {
     "ampsulbactam": {
      "s": 17
     },
     "piptazo": {
      "s": 44
     },
     "ceftazidime": {
      "s": 12
     },
     "imipenem": {
      "s": 74
     },
     "meropenem": {
      "s": 51
     },
     "amikacin": {
      "s": 57
     },
     "gentamicin": {
      "s": 59
     },
     "ciprofloxacin": {
      "s": 50
     },
     "cotrimoxazole": {
      "s": 55
     },
     "colistin": {
      "s": 100
     },
     "minocycline": {
      "s": 50
     }
    }
   }
  }
 },
 {
  "id": "KIMS_KLEB",
  "label": "KIMS Bhubaneswar Klebsiella (2022–24)",
  "region": "east",
  "city": "Bhubaneswar",
  "year": 2024,
  "credibility": 2,
  "source": "KIMS Bhubaneswar — Klebsiella (7,942 isolates) · Cureus 2025 (10.7759/cureus.94006)",
  "org": {
   "Klebsiella pneumoniae": {
    "n": 7942,
    "specimen": "all clinical (blood, urine, ETT, body fluid, sputum, pus, wound, skin swabs)",
    "d": {
     "amoxiclav": {
      "s": 27.4
     },
     "piptazo": {
      "s": 32.4
     },
     "cefuroxime": {
      "s": 16.9
     },
     "ceftriaxone": {
      "s": 19.9
     },
     "cefoperazonesulbactam": {
      "s": 26.4
     },
     "cefepime": {
      "s": 20.4
     },
     "imipenem": {
      "s": 30.8
     },
     "meropenem": {
      "s": 34.3
     },
     "amikacin": {
      "s": 25.4
     },
     "gentamicin": {
      "s": 39.5
     },
     "ciprofloxacin": {
      "s": 19.1
     },
     "tigecycline": {
      "s": 74.8
     },
     "cotrimoxazole": {
      "s": 25.5
     }
    }
   }
  }
 },
 {
  "id": "KIMS_STERILE",
  "label": "KIMS Bhubaneswar sterile body fluids (2021–22)",
  "region": "east",
  "city": "Bhubaneswar",
  "year": 2022,
  "credibility": 2,
  "source": "KIMS Bhubaneswar — sterile body fluids · Cureus 2026 (10.7759/cureus.104772)",
  "org": {
   "Staphylococcus aureus": {
    "n": 92,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "cloxacillin": {
      "s": 51.1
     },
     "linezolid": {
      "s": 95.7
     },
     "daptomycin": {
      "s": 95
     },
     "tigecycline": {
      "s": 92
     },
     "vancomycin": {
      "s": 90.2
     },
     "teicoplanin": {
      "s": 90.2
     },
     "gentamicin": {
      "s": 68,
      "approx": true
     },
     "cotrimoxazole": {
      "s": 70,
      "approx": true
     },
     "clindamycin": {
      "s": 43,
      "approx": true
     },
     "ciprofloxacin": {
      "s": 35,
      "approx": true
     },
     "erythromycin": {
      "s": 15,
      "approx": true
     },
     "penicillin": {
      "s": 14,
      "approx": true
     }
    }
   },
   "Enterococcus": {
    "n": 15,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "tigecycline": {
      "s": 100
     },
     "daptomycin": {
      "s": 93
     },
     "linezolid": {
      "s": 93
     },
     "vancomycin": {
      "s": 86
     },
     "teicoplanin": {
      "s": 86
     },
     "gentamicin": {
      "s": 86
     },
     "ciprofloxacin": {
      "s": 46,
      "approx": true
     },
     "penicillin": {
      "s": 26,
      "approx": true
     },
     "erythromycin": {
      "s": 6,
      "approx": true
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 40,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "amikacin": {
      "s": 59.9,
      "approx": true
     },
     "amoxiclav": {
      "s": 54.8,
      "approx": true
     },
     "cotrimoxazole": {
      "s": 54.8,
      "approx": true
     },
     "ceftriaxone": {
      "s": 51.8,
      "approx": true
     },
     "ceftazidime": {
      "s": 46.8,
      "approx": true
     },
     "cefepime": {
      "s": 44.9,
      "approx": true
     },
     "ampicillin": {
      "s": 41.9,
      "approx": true
     },
     "meropenem": {
      "s": 39.9,
      "approx": true
     },
     "imipenem": {
      "s": 39.9,
      "approx": true
     },
     "piptazo": {
      "s": 36.9,
      "approx": true
     },
     "ciprofloxacin": {
      "s": 29.9,
      "approx": true
     },
     "gentamicin": {
      "s": 26.9,
      "approx": true
     }
    }
   },
   "Escherichia coli": {
    "n": 27,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "amikacin": {
      "s": 61.9,
      "approx": true
     },
     "gentamicin": {
      "s": 58.9,
      "approx": true
     },
     "imipenem": {
      "s": 58.9,
      "approx": true
     },
     "meropenem": {
      "s": 47.9,
      "approx": true
     },
     "ceftazidime": {
      "s": 43.8,
      "approx": true
     },
     "ampicillin": {
      "s": 43.8,
      "approx": true
     },
     "ceftriaxone": {
      "s": 40.9,
      "approx": true
     },
     "amoxiclav": {
      "s": 39.9,
      "approx": true
     },
     "cotrimoxazole": {
      "s": 32.8,
      "approx": true
     },
     "piptazo": {
      "s": 29.9,
      "approx": true
     },
     "cefepime": {
      "s": 28.9,
      "approx": true
     },
     "ciprofloxacin": {
      "s": 10.8,
      "approx": true
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 19,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "meropenem": {
      "s": 25.9,
      "approx": true
     },
     "cefepime": {
      "s": 25.9,
      "approx": true
     },
     "amikacin": {
      "s": 20.9,
      "approx": true
     },
     "gentamicin": {
      "s": 20.9,
      "approx": true
     },
     "ceftazidime": {
      "s": 20.9,
      "approx": true
     },
     "piptazo": {
      "s": 20.9,
      "approx": true
     },
     "cotrimoxazole": {
      "s": 15.9,
      "approx": true
     },
     "ciprofloxacin": {
      "s": 9.9,
      "approx": true
     },
     "ceftriaxone": {
      "s": 4.9,
      "approx": true
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 24,
    "specimen": "sterile body fluids (CSF/pleural/ascitic/synovial)",
    "d": {
     "imipenem": {
      "s": 41.9,
      "approx": true
     },
     "gentamicin": {
      "s": 41.5,
      "approx": true
     },
     "amikacin": {
      "s": 37.9,
      "approx": true
     },
     "ciprofloxacin": {
      "s": 36.8,
      "approx": true
     },
     "cotrimoxazole": {
      "s": 36.8,
      "approx": true
     },
     "piptazo": {
      "s": 32.8,
      "approx": true
     },
     "meropenem": {
      "s": 28.9,
      "approx": true
     },
     "cefepime": {
      "s": 28.9,
      "approx": true
     },
     "ceftazidime": {
      "s": 28.9,
      "approx": true
     }
    }
   }
  }
 },
 {
  "id": "ASSAM",
  "label": "Assam MC Dibrugarh institution-wide (2018–21)",
  "region": "east",
  "city": "Dibrugarh",
  "year": 2021,
  "credibility": 3,
  "source": "Assam Medical College, Dibrugarh — institution-wide · J. Pure Appl. Microbiol. 2023",
  "org": {
   "Escherichia coli": {
    "n": 2237,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 55.4
     },
     "cefotaxime": {
      "s": 20.2
     },
     "ceftazidime": {
      "s": 14.9
     },
     "cefazolin": {
      "s": 26.3
     },
     "ciprofloxacin": {
      "s": 30
     },
     "levofloxacin": {
      "s": 37.1
     },
     "ertapenem": {
      "s": 49.8
     },
     "imipenem": {
      "s": 47.8
     },
     "meropenem": {
      "s": 62.5
     },
     "piptazo": {
      "s": 48.4
     },
     "nitrofurantoin": {
      "s": 84.7
     },
     "cotrimoxazole": {
      "s": 40.7
     },
     "fosfomycin": {
      "s": 97.8
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 2673,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 57.9
     },
     "cefotaxime": {
      "s": 16.2
     },
     "ceftazidime": {
      "s": 28.4
     },
     "cefazolin": {
      "s": 28.1
     },
     "ciprofloxacin": {
      "s": 50.1
     },
     "levofloxacin": {
      "s": 61.4
     },
     "ertapenem": {
      "s": 50.6
     },
     "imipenem": {
      "s": 46.9
     },
     "meropenem": {
      "s": 55.9
     },
     "piptazo": {
      "s": 43.9
     },
     "nitrofurantoin": {
      "s": 52
     },
     "cotrimoxazole": {
      "s": 46.7
     },
     "fosfomycin": {
      "s": 90
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 646,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 67.5
     },
     "ceftazidime": {
      "s": 53.6
     },
     "cefepime": {
      "s": 55.6
     },
     "ciprofloxacin": {
      "s": 68.9
     },
     "levofloxacin": {
      "s": 66.5
     },
     "imipenem": {
      "s": 62.2
     },
     "meropenem": {
      "s": 76.8
     },
     "piptazo": {
      "s": 67
     },
     "tobramycin": {
      "s": 68.8
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 687,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 33.5
     },
     "ceftazidime": {
      "s": 13.3
     },
     "cefepime": {
      "s": 16.8
     },
     "levofloxacin": {
      "s": 42.6
     },
     "imipenem": {
      "s": 25.8
     },
     "meropenem": {
      "s": 35.1
     },
     "minocycline": {
      "s": 84.2
     },
     "piptazo": {
      "s": 22.4
     }
    }
   },
   "Citrobacter": {
    "n": 551,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 52.3
     },
     "cefotaxime": {
      "s": 8.9
     },
     "ceftazidime": {
      "s": 14.3
     },
     "ciprofloxacin": {
      "s": 46
     },
     "levofloxacin": {
      "s": 58.8
     },
     "ertapenem": {
      "s": 51
     },
     "imipenem": {
      "s": 41.9
     },
     "meropenem": {
      "s": 52.6
     },
     "piptazo": {
      "s": 46
     },
     "nitrofurantoin": {
      "s": 51.6
     },
     "cotrimoxazole": {
      "s": 47
     },
     "fosfomycin": {
      "s": 74
     }
    }
   },
   "Proteus mirabilis": {
    "n": 125,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 53
     },
     "cefotaxime": {
      "s": 29.4
     },
     "ceftazidime": {
      "s": 46
     },
     "cefazolin": {
      "s": 37.9
     },
     "ciprofloxacin": {
      "s": 67.3
     },
     "levofloxacin": {
      "s": 68
     },
     "ertapenem": {
      "s": 71.4
     },
     "imipenem": {
      "s": 47
     },
     "meropenem": {
      "s": 73
     },
     "piptazo": {
      "s": 67.3
     },
     "nitrofurantoin": {
      "s": 31
     },
     "cotrimoxazole": {
      "s": 37.9
     },
     "fosfomycin": {
      "s": 93
     }
    }
   },
   "Enterobacter cloacae": {
    "n": 177,
    "specimen": "all clinical",
    "d": {
     "amikacin": {
      "s": 52.9
     },
     "cefotaxime": {
      "s": 7.7
     },
     "ceftazidime": {
      "s": 15
     },
     "ciprofloxacin": {
      "s": 57
     },
     "levofloxacin": {
      "s": 73
     },
     "ertapenem": {
      "s": 57.6
     },
     "imipenem": {
      "s": 32
     },
     "meropenem": {
      "s": 55.1
     },
     "piptazo": {
      "s": 34.6
     },
     "nitrofurantoin": {
      "s": 61.9
     },
     "cotrimoxazole": {
      "s": 57.1
     },
     "fosfomycin": {
      "s": 81
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 1786,
    "specimen": "all clinical",
    "d": {
     "cefoxitin": {
      "s": 55.3
     },
     "ciprofloxacin": {
      "s": 36.2
     },
     "clindamycin": {
      "s": 66.6
     },
     "erythromycin": {
      "s": 27.2
     },
     "linezolid": {
      "s": 99.6
     },
     "mupirocin": {
      "s": 82.9
     },
     "penicillin": {
      "s": 8.4
     },
     "tetracycline": {
      "s": 89.2
     },
     "cotrimoxazole": {
      "s": 69.4
     },
     "vancomycin": {
      "s": 100
     }
    }
   },
   "Enterococcus faecalis": {
    "n": 200,
    "specimen": "all clinical",
    "d": {
     "ciprofloxacin": {
      "s": 32.6
     },
     "linezolid": {
      "s": 99.5
     },
     "nitrofurantoin": {
      "s": 87.1
     },
     "ampicillin": {
      "s": 75.5
     },
     "fosfomycin": {
      "s": 91.7
     },
     "gentamicin": {
      "s": 61.5
     },
     "teicoplanin": {
      "s": 99.5
     }
    }
   },
   "Enterococcus faecium": {
    "n": 617,
    "specimen": "all clinical",
    "d": {
     "ciprofloxacin": {
      "s": 12.8
     },
     "linezolid": {
      "s": 98.4
     },
     "nitrofurantoin": {
      "s": 57.5
     },
     "ampicillin": {
      "s": 31
     },
     "gentamicin": {
      "s": 37.3
     },
     "teicoplanin": {
      "s": 99.2
     }
    }
   }
  }
 },
 {
  "id": "IGGMC",
  "label": "IGGMC Nagpur full antibiogram (2024–25)",
  "region": "west",
  "city": "Nagpur",
  "year": 2025,
  "credibility": 2,
  "source": "Indira Gandhi Govt Medical College, Nagpur — full antibiogram · Cureus 2026 (10.7759/cureus.100797)",
  "org": {
   "Escherichia coli": {
    "n": 1321,
    "specimen": "all clinical",
    "d": {
     "ampicillin": {
      "s": 2
     },
     "cefazolin": {
      "s": 12
     },
     "cefuroxime": {
      "s": 14
     },
     "ceftriaxone": {
      "s": 24
     },
     "cefotaxime": {
      "s": 27
     },
     "cefixime": {
      "s": 23
     },
     "ceftazidime": {
      "s": 28
     },
     "cefepime": {
      "s": 44
     },
     "imipenem": {
      "s": 48
     },
     "meropenem": {
      "s": 56
     },
     "aztreonam": {
      "s": 82
     },
     "amoxiclav": {
      "s": 12
     },
     "piptazo": {
      "s": 47
     },
     "ampsulbactam": {
      "s": 42
     },
     "gentamicin": {
      "s": 68
     },
     "amikacin": {
      "s": 65
     },
     "tetracycline": {
      "s": 67
     },
     "ciprofloxacin": {
      "s": 52
     },
     "levofloxacin": {
      "s": 46
     },
     "cotrimoxazole": {
      "s": 57
     },
     "nitrofurantoin": {
      "s": 84
     },
     "fosfomycin": {
      "s": 90
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 1051,
    "specimen": "all clinical",
    "d": {
     "cefazolin": {
      "s": 11
     },
     "cefuroxime": {
      "s": 12
     },
     "ceftriaxone": {
      "s": 22
     },
     "cefotaxime": {
      "s": 24
     },
     "cefixime": {
      "s": 23
     },
     "ceftazidime": {
      "s": 27
     },
     "cefepime": {
      "s": 45
     },
     "imipenem": {
      "s": 49
     },
     "meropenem": {
      "s": 49
     },
     "aztreonam": {
      "s": 35
     },
     "amoxiclav": {
      "s": 11
     },
     "piptazo": {
      "s": 48
     },
     "ampsulbactam": {
      "s": 44
     },
     "gentamicin": {
      "s": 64
     },
     "amikacin": {
      "s": 67
     },
     "tetracycline": {
      "s": 66
     },
     "ciprofloxacin": {
      "s": 56
     },
     "levofloxacin": {
      "s": 49
     },
     "cotrimoxazole": {
      "s": 59
     },
     "nitrofurantoin": {
      "s": 76
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 785,
    "specimen": "all clinical",
    "d": {
     "ceftazidime": {
      "s": 21
     },
     "cefepime": {
      "s": 72
     },
     "imipenem": {
      "s": 55
     },
     "meropenem": {
      "s": 59
     },
     "aztreonam": {
      "s": 44
     },
     "piptazo": {
      "s": 66
     },
     "ciprofloxacin": {
      "s": 75
     },
     "levofloxacin": {
      "s": 80
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 479,
    "specimen": "all clinical",
    "d": {
     "ceftriaxone": {
      "s": 22
     },
     "cefotaxime": {
      "s": 24
     },
     "ceftazidime": {
      "s": 32
     },
     "cefepime": {
      "s": 48
     },
     "imipenem": {
      "s": 34
     },
     "meropenem": {
      "s": 45
     },
     "piptazo": {
      "s": 57
     },
     "ampsulbactam": {
      "s": 28
     },
     "gentamicin": {
      "s": 74
     },
     "amikacin": {
      "s": 76
     },
     "ciprofloxacin": {
      "s": 58
     },
     "levofloxacin": {
      "s": 62
     },
     "cotrimoxazole": {
      "s": 72
     },
     "colistin": {
      "s": 100
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 664,
    "specimen": "all clinical",
    "d": {
     "penicillin": {
      "s": 4
     },
     "cefoxitin": {
      "s": 52
     },
     "clindamycin": {
      "s": 78
     },
     "erythromycin": {
      "s": 66
     },
     "doxycycline": {
      "s": 75
     },
     "tetracycline": {
      "s": 73
     },
     "ciprofloxacin": {
      "s": 79
     },
     "levofloxacin": {
      "s": 77
     },
     "gentamicin": {
      "s": 88
     },
     "cotrimoxazole": {
      "s": 81
     },
     "chloramphenicol": {
      "s": 25
     },
     "vancomycin": {
      "s": 100
     },
     "linezolid": {
      "s": 92
     },
     "azithromycin": {
      "s": 12
     },
     "nitrofurantoin": {
      "s": 82
     },
     "fosfomycin": {
      "s": 88
     }
    }
   },
   "Enterococcus faecalis": {
    "n": 98,
    "specimen": "all clinical",
    "d": {
     "penicillin": {
      "s": 2
     },
     "ampicillin": {
      "s": 10
     },
     "erythromycin": {
      "s": 54
     },
     "doxycycline": {
      "s": 58
     },
     "tetracycline": {
      "s": 53
     },
     "ciprofloxacin": {
      "s": 68
     },
     "levofloxacin": {
      "s": 75
     },
     "hlg": {
      "s": 68
     },
     "chloramphenicol": {
      "s": 35
     },
     "vancomycin": {
      "s": 97
     },
     "teicoplanin": {
      "s": 64
     },
     "linezolid": {
      "s": 92
     },
     "nitrofurantoin": {
      "s": 78
     },
     "fosfomycin": {
      "s": 84
     }
    }
   },
   "Enterococcus faecium": {
    "n": 54,
    "specimen": "all clinical",
    "d": {
     "penicillin": {
      "s": 2
     },
     "ampicillin": {
      "s": 8
     },
     "erythromycin": {
      "s": 59
     },
     "doxycycline": {
      "s": 64
     },
     "tetracycline": {
      "s": 58
     },
     "ciprofloxacin": {
      "s": 65
     },
     "levofloxacin": {
      "s": 68
     },
     "hlg": {
      "s": 74
     },
     "chloramphenicol": {
      "s": 39
     },
     "vancomycin": {
      "s": 95
     },
     "teicoplanin": {
      "s": 70
     },
     "linezolid": {
      "s": 88
     },
     "nitrofurantoin": {
      "s": 76
     }
    }
   },
   "Salmonella Typhi": {
    "n": 11,
    "specimen": "intestinal and extra-intestinal",
    "d": {
     "ampicillin": {
      "s": 22
     },
     "cefotaxime": {
      "s": 51
     },
     "azithromycin": {
      "s": 36
     },
     "levofloxacin": {
      "s": 36
     },
     "cotrimoxazole": {
      "s": 54
     }
    }
   }
  }
 },
 {
  "id": "ICMR_AMRSN_2023",
  "label": "ICMR-AMRSN Annual Report 2023",
  "region": "national",
  "city": "All-India",
  "year": 2023,
  "credibility": 1,
  "source": "ICMR-AMRSN Annual Report 2023 — ~99,492 isolates, ~30 tertiary sites",
  "org": {
   "Escherichia coli": {
    "n": 3244,
    "specimen": "blood",
    "d": {
     "piptazo": {
      "s": 50
     },
     "ceftriaxone": {
      "s": 21.9
     },
     "imipenem": {
      "s": 68.6
     },
     "meropenem": {
      "s": 70.5
     },
     "ertapenem": {
      "s": 70.6
     },
     "amikacin": {
      "s": 69.1
     },
     "ciprofloxacin": {
      "s": 15.4
     },
     "levofloxacin": {
      "s": 18.7
     },
     "colistin": {
      "s": 99.7
     },
     "fosfomycin": {
      "s": 97.8
     },
     "minocycline": {
      "s": 84.6
     },
     "cotrimoxazole": {
      "s": 49.5
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 2909,
    "specimen": "blood",
    "d": {
     "piptazo": {
      "s": 23.8
     },
     "ceftriaxone": {
      "s": 16.8
     },
     "imipenem": {
      "s": 28.9
     },
     "meropenem": {
      "s": 30.3
     },
     "ertapenem": {
      "s": 32.8
     },
     "amikacin": {
      "s": 34.2
     },
     "ciprofloxacin": {
      "s": 16.7
     },
     "levofloxacin": {
      "s": 18.7
     },
     "colistin": {
      "s": 96.3
     },
     "fosfomycin": {
      "s": 60.5
     },
     "minocycline": {
      "s": 70
     },
     "cotrimoxazole": {
      "s": 39.1
     }
    }
   },
   "Acinetobacter baumannii": {
    "n": 2131,
    "specimen": "blood",
    "d": {
     "piptazo": {
      "s": 16.2
     },
     "ceftazidime": {
      "s": 12
     },
     "cefepime": {
      "s": 15.3
     },
     "imipenem": {
      "s": 12.4
     },
     "meropenem": {
      "s": 14.6
     },
     "amikacin": {
      "s": 23.5
     },
     "levofloxacin": {
      "s": 17.2
     },
     "colistin": {
      "s": 97.3
     },
     "minocycline": {
      "s": 74
     }
    }
   },
   "Pseudomonas aeruginosa": {
    "n": 1184,
    "specimen": "urine",
    "d": {
     "piptazo": {
      "s": 61.8
     },
     "ceftazidime": {
      "s": 42.9
     },
     "cefepime": {
      "s": 47.5
     },
     "imipenem": {
      "s": 46.4
     },
     "meropenem": {
      "s": 50.5
     },
     "amikacin": {
      "s": 53.4
     },
     "gentamicin": {
      "s": 48.3
     },
     "tobramycin": {
      "s": 42.1
     },
     "ciprofloxacin": {
      "s": 36.4
     },
     "levofloxacin": {
      "s": 28.2
     },
     "colistin": {
      "s": 96.9
     }
    }
   },
   "Staphylococcus aureus": {
    "n": 1919,
    "specimen": "pus/exudates",
    "d": {
     "cefoxitin": {
      "s": 47.8
     },
     "ciprofloxacin": {
      "s": 14.4
     },
     "clindamycin": {
      "s": 77.1
     },
     "erythromycin": {
      "s": 36.6
     },
     "cotrimoxazole": {
      "s": 76.2
     },
     "tetracycline": {
      "s": 79.5
     },
     "linezolid": {
      "s": 97.7
     },
     "vancomycin": {
      "s": 100
     },
     "teicoplanin": {
      "s": 100
     },
     "daptomycin": {
      "s": 93
     },
     "tigecycline": {
      "s": 100
     }
    }
   },
   "Enterococcus faecalis": {
    "n": 1595,
    "specimen": "urine",
    "d": {
     "ampicillin": {
      "s": 66
     },
     "penicillin": {
      "s": 40.2
     },
     "ciprofloxacin": {
      "s": 11.4
     },
     "gentamicin_hl": {
      "s": 44.2
     },
     "fosfomycin": {
      "s": 76.2
     },
     "nitrofurantoin": {
      "s": 79.7
     },
     "linezolid": {
      "s": 96.4
     },
     "teicoplanin": {
      "s": 92
     },
     "vancomycin": {
      "s": 94.7
     }
    }
   },
   "Enterococcus faecium": {
    "n": 942,
    "specimen": "urine",
    "d": {
     "ampicillin": {
      "s": 16.1
     },
     "penicillin": {
      "s": 11.9
     },
     "ciprofloxacin": {
      "s": 4.5
     },
     "gentamicin_hl": {
      "s": 40
     },
     "nitrofurantoin": {
      "s": 37.6
     },
     "linezolid": {
      "s": 92.1
     },
     "teicoplanin": {
      "s": 73.5
     },
     "vancomycin": {
      "s": 73
     }
    }
   },
   "Salmonella Typhi": {
    "n": 1061,
    "specimen": "blood",
    "d": {
     "ampicillin": {
      "s": 97.7
     },
     "ceftriaxone": {
      "s": 97
     },
     "cefotaxime": {
      "s": 95.5
     },
     "cefixime": {
      "s": 96.6
     },
     "azithromycin": {
      "s": 97.3
     },
     "chloramphenicol": {
      "s": 98.1
     },
     "cotrimoxazole": {
      "s": 97
     },
     "ciprofloxacin": {
      "s": 2.1
     },
     "levofloxacin": {
      "s": 19.2
     }
    }
   }
  }
 },
 {
  "id": "ICMR_ESBL",
  "label": "ICMR ESBL multicentric (2014–16)",
  "region": "national",
  "city": "All-India",
  "year": 2016,
  "credibility": 2,
  "source": "ICMR multicentric ESBL study · Indian J. Med. Res. 2019 (10.4103/ijmr.IJMR_172_18)",
  "org": {
   "Escherichia coli": {
    "n": 341,
    "specimen": "all clinical (blood, pus, sputum, body fluids)",
    "d": {
     "amikacin": {
      "s": 77.5
     },
     "cefotaxime": {
      "s": 39.8
     },
     "ceftazidime": {
      "s": 37.9
     },
     "cefepime": {
      "s": 40.1
     },
     "ciprofloxacin": {
      "s": 41
     },
     "cefpodoxime": {
      "s": 33.8
     },
     "chloramphenicol": {
      "s": 82.2
     },
     "cefoperazone-sulbactam": {
      "s": 68.8
     },
     "colistin": {
      "s": 99
     },
     "ertapenem": {
      "s": 56.7
     },
     "imipenem": {
      "s": 79.4
     },
     "meropenem": {
      "s": 78.3
     },
     "tetracycline": {
      "s": 42.4
     },
     "piptazo": {
      "s": 65.9
     }
    }
   },
   "Klebsiella pneumoniae": {
    "n": 304,
    "specimen": "all clinical (blood, pus, sputum, body fluids)",
    "d": {
     "amikacin": {
      "s": 50.9
     },
     "cefotaxime": {
      "s": 29.9
     },
     "ceftazidime": {
      "s": 29
     },
     "cefepime": {
      "s": 30.8
     },
     "ciprofloxacin": {
      "s": 48.7
     },
     "cefpodoxime": {
      "s": 31.2
     },
     "chloramphenicol": {
      "s": 82.1
     },
     "cefoperazone-sulbactam": {
      "s": 41.2
     },
     "colistin": {
      "s": 98
     },
     "ertapenem": {
      "s": 67.2
     },
     "imipenem": {
      "s": 54
     },
     "meropenem": {
      "s": 46.4
     },
     "tetracycline": {
      "s": 77.4
     },
     "piptazo": {
      "s": 42.4
     }
    }
   }
  }
 }
];

  // Build a region's best-of composite: studies ranked by credibility then recency; for each
  // organism/drug the first (most-credible) study that reports it wins, later studies fill gaps.
  // Every filled cell records its provenance in .src (the contributing study id).
  function buildComposite(region) {
    var studies = ABG_STUDIES.filter(function (s) { return s.region === region && s.org && Object.keys(s.org).length; })
      .slice().sort(function (a, b) { return (a.credibility - b.credibility) || ((b.year || 0) - (a.year || 0)); });
    var out = { region: region, composite: true, source: "", note: "Best-of regional composite — each organism/drug taken from the most-credible source in this region that reports it.", org: {} };
    var contrib = [];
    studies.forEach(function (st) {
      var used = false, orgs = st.org || {};
      Object.keys(orgs).forEach(function (name) {
        var so = orgs[name];
        var dst = out.org[name] || (out.org[name] = { n: null, specimen: null, d: {} });
        if (dst.n == null && so.n != null) { dst.n = so.n; dst.specimen = so.specimen || null; dst.nsrc = st.id; }
        var dd = so.d || {};
        Object.keys(dd).forEach(function (k) {
          if (dst.d[k]) return;                       // a higher-credibility study already filled this cell
          var cell = dd[k];
          if (cell.s == null && !cell.q) return;
          var nc = { src: st.id };
          if (cell.s != null) nc.s = cell.s;
          if (cell.approx) nc.approx = true;
          if (cell.q) nc.q = cell.q;
          dst.d[k] = nc; used = true;
        });
      });
      if (used) contrib.push(st.id);
    });
    out.sources = contrib;
    out.source = "Regional best-of composite · sources: " + contrib.join(", ");
    return out;
  }

  var REGION_ABG = { south: buildComposite("south"), north: buildComposite("north"), east: buildComposite("east"), west: buildComposite("west") };
  var STUDY_BY_ID = {}; ABG_STUDIES.forEach(function (s) { STUDY_BY_ID[s.id] = s; });

  window.ABG_STUDIES = ABG_STUDIES;
  window.buildComposite = buildComposite;
  window.REGION_ABG = REGION_ABG;
  window.ABG_DATA = { studies: ABG_STUDIES, buildComposite: buildComposite, region: REGION_ABG, getStudy: function (id) { return STUDY_BY_ID[id] || null; } };
})();
