/* edge-schemas.js — score version map (Edge-Master-Plan A1.7). GENERATED by scripts/edge/schemas.mjs from
 * calculators.js: do not edit by hand. Each family lists calculators a request can confuse ("meld" vs
 * "MELD-Na" vs "MELD 3.0"); "only_here" are the inputs that tell the versions apart. Read by
 * SMD_EDGE_SCHEMAS.familyOf(id) / .siblings(id). ES5, no network. */
(function (root) {
  "use strict";
  var FAMILIES = [
 {
  "family": "MELD",
  "kind": "versions",
  "members": [
   {
    "id": "meld",
    "title": "MELD & MELD-Na",
    "desc": "End-stage liver disease 90-day mortality.",
    "ref": "Kamath PS et al. Hepatology 2001;33(2):464–70; MELD-Na: Kim WR et al. NEJM 2008.",
    "inputs": [
     "Bilirubin (mg/dL)",
     "INR",
     "Creatinine (mg/dL)",
     "Sodium (for MELD-Na) (mEq/L)",
     "Dialysis ≥2× in past week"
    ],
    "only_here": [
     "Dialysis ≥2× in past week"
    ]
   },
   {
    "id": "meld_na",
    "title": "MELD-Na Score",
    "desc": "Liver disease severity incorporating sodium (transplant prioritisation).",
    "ref": "Kim WR, et al. N Engl J Med 2008;359(10):1018–26 (MELD-Na).",
    "inputs": [
     "Bilirubin (mg/dL)",
     "INR",
     "Creatinine (mg/dL)",
     "Dialysis ≥ twice in the past week",
     "Sodium (mmol/L)"
    ],
    "only_here": [
     "Dialysis ≥ twice in the past week"
    ]
   },
   {
    "id": "meld3",
    "title": "MELD 3.0",
    "desc": "90-day mortality in chronic liver disease & transplant priority (2021; replaces MELD-Na).",
    "ref": "",
    "inputs": [
     "Bilirubin (mg/dL)",
     "Creatinine (mg/dL)",
     "INR",
     "Sodium (mEq/L)",
     "Albumin (g/dL)",
     "Sex",
     "≥2 haemodialysis / 24 h CVVHD in the past week"
    ],
    "only_here": [
     "Albumin",
     "Sex",
     "≥2 haemodialysis / 24 h CVVHD in the past week"
    ]
   }
  ],
  "shared_inputs": [
   "bilirubin",
   "inr",
   "creatinine",
   "sodium"
  ]
 },
 {
  "family": "PHQ (depression)",
  "kind": "variants",
  "members": [
   {
    "id": "phq2",
    "title": "PHQ-2 (Depression Screen)",
    "desc": "Ultra-brief screen for depression over the past 2 weeks.",
    "ref": "Kroenke K, et al. Med Care 2003;41(11):1284–92 (PHQ-2).",
    "inputs": [
     "Little interest or pleasure in doing things",
     "Feeling down, depressed or hopeless"
    ],
    "only_here": []
   },
   {
    "id": "phq9",
    "title": "PHQ-9 (depression)",
    "desc": "Depression severity. Over the last 2 weeks, how often bothered by each problem?",
    "ref": "",
    "inputs": [
     "Little interest or pleasure in doing things",
     "Feeling down, depressed or hopeless",
     "Trouble falling/staying asleep, or sleeping too much",
     "Feeling tired or having little energy",
     "Poor appetite or overeating",
     "Feeling bad about yourself / a failure",
     "Trouble concentrating",
     "Moving/speaking slowly, or being restless/fidgety",
     "Thoughts of being better off dead or self-harm"
    ],
    "only_here": [
     "Trouble falling/staying asleep, or sleeping too much",
     "Feeling tired or having little energy",
     "Poor appetite or overeating",
     "Feeling bad about yourself / a failure",
     "Trouble concentrating",
     "Moving/speaking slowly, or being restless/fidgety",
     "Thoughts of being better off dead or self-harm"
    ]
   }
  ],
  "shared_inputs": [
   "little interest or pleasure in doing things",
   "feeling down depressed or hopeless"
  ]
 },
 {
  "family": "GAD (anxiety)",
  "kind": "variants",
  "members": [
   {
    "id": "gad2",
    "title": "GAD-2 (Anxiety Screen)",
    "desc": "Ultra-brief screen for generalised anxiety over the past 2 weeks.",
    "ref": "Kroenke K, et al. Ann Intern Med 2007;146(5):317–25 (GAD-2).",
    "inputs": [
     "Feeling nervous, anxious or on edge",
     "Not being able to stop or control worrying"
    ],
    "only_here": []
   },
   {
    "id": "gad7",
    "title": "GAD-7 (anxiety)",
    "desc": "Generalised anxiety severity. Over the last 2 weeks, how often bothered by each problem?",
    "ref": "",
    "inputs": [
     "Feeling nervous, anxious or on edge",
     "Not being able to stop or control worrying",
     "Worrying too much about different things",
     "Trouble relaxing",
     "Being so restless it is hard to sit still",
     "Becoming easily annoyed or irritable",
     "Feeling afraid as if something awful might happen"
    ],
    "only_here": [
     "Worrying too much about different things",
     "Trouble relaxing",
     "Being so restless it is hard to sit still",
     "Becoming easily annoyed or irritable",
     "Feeling afraid as if something awful might happen"
    ]
   }
  ],
  "shared_inputs": [
   "feeling nervous anxious or on edge",
   "not being able to stop or control worrying"
  ]
 },
 {
  "family": "AUDIT (alcohol)",
  "kind": "variants",
  "members": [
   {
    "id": "auditc",
    "title": "AUDIT-C (alcohol)",
    "desc": "Brief alcohol-use screen (3 items).",
    "ref": "",
    "inputs": [
     "How often do you drink?",
     "Drinks on a typical drinking day",
     "How often ≥6 drinks on one occasion?",
     "Sex"
    ],
    "only_here": [
     "How often do you drink?",
     "Sex"
    ]
   },
   {
    "id": "audit_full",
    "title": "AUDIT (Alcohol Use Disorders Identification Test)",
    "desc": "10-item screen for hazardous and harmful alcohol use.",
    "ref": "Saunders JB, et al. Addiction 1993;88(6):791–804 (WHO AUDIT).",
    "inputs": [
     "How often do you have a drink containing alcohol?",
     "Drinks on a typical drinking day",
     "How often ≥6 drinks on one occasion?",
     "Unable to stop drinking once started",
     "Failed to do what was expected because of drinking",
     "Needed a drink in the morning",
     "Guilt or remorse after drinking",
     "Unable to remember the night before",
     "You or someone injured due to your drinking",
     "Others concerned or suggested you cut down"
    ],
    "only_here": [
     "How often do you have a drink containing alcohol?",
     "Unable to stop drinking once started",
     "Failed to do what was expected because of drinking",
     "Needed a drink in the morning",
     "Guilt or remorse after drinking",
     "Unable to remember the night before",
     "You or someone injured due to your drinking",
     "Others concerned or suggested you cut down"
    ]
   }
  ],
  "shared_inputs": [
   "drinks on a typical drinking day",
   "how often 6 drinks on one occasion"
  ]
 },
 {
  "family": "GDS (geriatric depression)",
  "kind": "variants",
  "members": [
   {
    "id": "gds15",
    "title": "Geriatric Depression Scale (GDS-15)",
    "desc": "Depression screen in older adults. Tick each item that is TRUE for the patient.",
    "ref": "Sheikh JI, Yesavage JA. Clin Gerontol 1986 (GDS-15).",
    "inputs": [
     "NOT satisfied with your life",
     "Dropped many activities and interests",
     "Feel that your life is empty",
     "Often get bored",
     "NOT in good spirits most of the time",
     "Afraid something bad will happen to you",
     "NOT feeling happy most of the time",
     "Often feel helpless",
     "Prefer to stay in rather than go out",
     "More problems with memory than most",
     "NOT think it wonderful to be alive now",
     "Feel worthless the way you are now",
     "NOT feeling full of energy",
     "Feel your situation is hopeless",
     "Think most people are better off than you"
    ],
    "only_here": [
     "NOT satisfied with your life",
     "Dropped many activities and interests",
     "Feel that your life is empty",
     "Often get bored",
     "NOT in good spirits most of the time",
     "Afraid something bad will happen to you",
     "NOT feeling happy most of the time",
     "Often feel helpless",
     "Prefer to stay in rather than go out",
     "More problems with memory than most",
     "NOT think it wonderful to be alive now",
     "Feel worthless the way you are now",
     "NOT feeling full of energy",
     "Feel your situation is hopeless",
     "Think most people are better off than you"
    ]
   },
   {
    "id": "gds30",
    "title": "Geriatric Depression Scale (GDS-30) — interpreter",
    "desc": "Interprets a 30-item Geriatric Depression Scale total.",
    "ref": "Yesavage JA, et al. J Psychiatr Res 1982;17(1):37–49 (GDS).",
    "inputs": [
     "GDS-30 total (0–30)"
    ],
    "only_here": [
     "GDS-30 total (0–30)"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "ISS (myeloma staging)",
  "kind": "versions",
  "members": [
   {
    "id": "iss_myeloma",
    "title": "ISS (Multiple Myeloma Staging)",
    "desc": "International Staging System for multiple myeloma.",
    "ref": "Greipp PR, et al. J Clin Oncol 2005;23(15):3412–20 (ISS).",
    "inputs": [
     "Serum beta-2 microglobulin (mg/L)",
     "Serum albumin (g/L)"
    ],
    "only_here": [
     "Serum beta-2 microglobulin",
     "Serum albumin"
    ]
   },
   {
    "id": "r_iss",
    "title": "R-ISS (Revised ISS, Myeloma)",
    "desc": "Revised International Staging System for multiple myeloma.",
    "ref": "Palumbo A, et al. J Clin Oncol 2015;33(26):2863–9 (R-ISS).",
    "inputs": [
     "ISS stage",
     "Serum LDH",
     "High-risk cytogenetics — del(17p), t(4;14) or t(14;16)"
    ],
    "only_here": [
     "ISS stage",
     "Serum LDH",
     "High-risk cytogenetics — del(17p), t(4;14) or t(14;16)"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "IPI (lymphoma)",
  "kind": "versions",
  "members": [
   {
    "id": "ipi",
    "title": "IPI (Lymphoma Prognostic Index)",
    "desc": "International Prognostic Index for aggressive non-Hodgkin lymphoma.",
    "ref": "The International NHL Prognostic Factors Project. N Engl J Med 1993;329(14):987–94.",
    "inputs": [
     "Age >60 years",
     "LDH above normal",
     "ECOG performance status ≥2",
     "Ann Arbor stage III–IV",
     ">1 extranodal site"
    ],
    "only_here": [
     "LDH above normal",
     ">1 extranodal site"
    ]
   },
   {
    "id": "r_ipi",
    "title": "R-IPI (Revised IPI, DLBCL)",
    "desc": "Revised IPI in rituximab-treated diffuse large B-cell lymphoma.",
    "ref": "",
    "inputs": [
     "Age > 60 years",
     "LDH > upper limit normal",
     "ECOG performance status ≥ 2",
     "Ann Arbor stage III-IV",
     "Extranodal sites > 1"
    ],
    "only_here": [
     "LDH > upper limit normal",
     "Extranodal sites > 1"
    ]
   }
  ],
  "shared_inputs": [
   "age 60 years",
   "ecog performance status 2",
   "ann arbor stage iii iv"
  ]
 },
 {
  "family": "POSSUM (surgical risk)",
  "kind": "versions",
  "members": [
   {
    "id": "possum",
    "title": "POSSUM (morbidity and mortality)",
    "desc": "Physiological score (12 variables) and operative severity score (6 variables) with the POSSUM morbidity and mortality equations (Copeland 1991).",
    "ref": "Copeland GP, et al. Br J Surg 1991;78(3):355 (POSSUM).",
    "inputs": [
     "Age (yrs)",
     "Cardiac signs (clinical and chest X-ray)",
     "Respiratory history (and chest X-ray)",
     "Systolic BP (mmHg)",
     "Pulse (bpm)",
     "Glasgow Coma Scale",
     "Haemoglobin (g/dL)",
     "White cell count (×10⁹/L)",
     "Urea (unit below)",
     "Urea unit",
     "Sodium (mmol/L)",
     "Potassium (mmol/L)",
     "ECG",
     "Operative severity",
     "Number of procedures",
     "Total blood loss (mL)",
     "Peritoneal soiling",
     "Malignancy",
     "Mode of surgery"
    ],
    "only_here": []
   },
   {
    "id": "p_possum",
    "title": "P-POSSUM (Portsmouth POSSUM, in-hospital mortality)",
    "desc": "Portsmouth recalibration of POSSUM for predicted in-hospital mortality, using the same 18 POSSUM variables (Prytherch 1998).",
    "ref": "Prytherch DR, et al. Br J Surg 1998;85(9):1217 (P-POSSUM).",
    "inputs": [
     "Age (yrs)",
     "Cardiac signs (clinical and chest X-ray)",
     "Respiratory history (and chest X-ray)",
     "Systolic BP (mmHg)",
     "Pulse (bpm)",
     "Glasgow Coma Scale",
     "Haemoglobin (g/dL)",
     "White cell count (×10⁹/L)",
     "Urea (unit below)",
     "Urea unit",
     "Sodium (mmol/L)",
     "Potassium (mmol/L)",
     "ECG",
     "Operative severity",
     "Number of procedures",
     "Total blood loss (mL)",
     "Peritoneal soiling",
     "Malignancy",
     "Mode of surgery"
    ],
    "only_here": []
   }
  ],
  "shared_inputs": [
   "age",
   "cardiac signs",
   "respiratory history",
   "systolic bp",
   "pulse",
   "glasgow coma scale",
   "haemoglobin",
   "white cell count",
   "urea",
   "urea unit",
   "sodium",
   "potassium",
   "ecg",
   "operative severity",
   "number of procedures",
   "total blood loss",
   "peritoneal soiling",
   "malignancy",
   "mode of surgery"
  ]
 },
 {
  "family": "CHADS (AF stroke risk)",
  "kind": "versions",
  "members": [
   {
    "id": "chads2",
    "title": "CHADS₂ Score",
    "desc": "Stroke risk in non-valvular atrial fibrillation (predecessor of CHA₂DS₂-VASc).",
    "ref": "Gage BF, et al. JAMA 2001;285(22):2864–70.",
    "inputs": [
     "Congestive heart failure",
     "Hypertension",
     "Age ≥ 75 years",
     "Diabetes mellitus",
     "Prior stroke / TIA / thromboembolism (2 points)"
    ],
    "only_here": [
     "Congestive heart failure",
     "Age ≥ 75 years"
    ]
   },
   {
    "id": "chadsvasc",
    "title": "CHA₂DS₂-VASc",
    "desc": "Stroke risk in non-valvular atrial fibrillation.",
    "ref": "Lip GYH et al. Chest 2010;137(2):263–72.",
    "inputs": [
     "Congestive heart failure / LV dysfunction",
     "Hypertension",
     "Age (yrs)",
     "Diabetes mellitus",
     "Prior stroke / TIA / thromboembolism",
     "Vascular disease (MI, PAD, aortic plaque)",
     "Sex"
    ],
    "only_here": [
     "Congestive heart failure / LV dysfunction",
     "Age",
     "Vascular disease (MI, PAD, aortic plaque)",
     "Sex"
    ]
   }
  ],
  "shared_inputs": [
   "hypertension",
   "diabetes mellitus",
   "prior stroke tia thromboembolism"
  ]
 },
 {
  "family": "CURB (pneumonia)",
  "kind": "variants",
  "members": [
   {
    "id": "curb65",
    "title": "CURB-65 (pneumonia)",
    "desc": "Community-acquired pneumonia severity / disposition.",
    "ref": "Lim WS et al. Thorax 2003;58(5):377–82.",
    "inputs": [
     "Confusion (new disorientation)",
     "Urea >7 mmol/L (BUN >19 mg/dL)",
     "Respiratory rate ≥30",
     "SBP <90 or DBP ≤60 mmHg",
     "Age ≥65"
    ],
    "only_here": [
     "Confusion (new disorientation)",
     "Urea >7 mmol/L (BUN >19 mg/dL)",
     "Respiratory rate ≥30",
     "SBP <90 or DBP ≤60 mmHg",
     "Age ≥65"
    ]
   },
   {
    "id": "crb65",
    "title": "CRB-65 (CAP, no labs)",
    "desc": "Community-acquired pneumonia severity without urea — primary-care friendly.",
    "ref": "",
    "inputs": [
     "New confusion",
     "Respiratory rate (/min)",
     "Systolic BP (mmHg)",
     "Diastolic BP (mmHg)",
     "Age (yrs)"
    ],
    "only_here": [
     "New confusion",
     "Respiratory rate",
     "Systolic BP",
     "Diastolic BP",
     "Age"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "SOFA (sepsis)",
  "kind": "variants",
  "members": [
   {
    "id": "sofa",
    "title": "SOFA score",
    "desc": "Sequential Organ Failure Assessment (0–4 per system).",
    "ref": "Vincent JL et al. Intensive Care Med 1996;22(7):707–10.",
    "inputs": [
     "Respiration (PaO₂/FiO₂)",
     "Coagulation (platelets ×10³)",
     "Liver (bilirubin mg/dL)",
     "Cardiovascular (pressor µg/kg/min)",
     "CNS (GCS)",
     "Renal (creatinine mg/dL)"
    ],
    "only_here": [
     "Respiration (PaO₂/FiO₂)",
     "Coagulation (platelets ×10³)",
     "Liver (bilirubin mg/dL)",
     "Cardiovascular (pressor µg/kg/min)",
     "CNS (GCS)",
     "Renal (creatinine mg/dL)"
    ]
   },
   {
    "id": "qsofa",
    "title": "qSOFA",
    "desc": "Bedside screen for sepsis with poor outcome.",
    "ref": "Singer M et al. (Sepsis-3) JAMA 2016;315(8):801–10.",
    "inputs": [
     "Respiratory rate ≥22",
     "Altered mentation (GCS <15)",
     "Systolic BP ≤100 mmHg"
    ],
    "only_here": [
     "Respiratory rate ≥22",
     "Altered mentation (GCS <15)",
     "Systolic BP ≤100 mmHg"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "Fisher (SAH)",
  "kind": "versions",
  "members": [
   {
    "id": "fisher",
    "title": "Fisher Grade (SAH on CT)",
    "desc": "Amount/pattern of subarachnoid blood on CT; relates to vasospasm risk.",
    "ref": "",
    "inputs": [
     "CT appearance"
    ],
    "only_here": [
     "CT appearance"
    ]
   },
   {
    "id": "modified_fisher",
    "title": "Modified Fisher Scale (SAH)",
    "desc": "CT grading of subarachnoid haemorrhage to estimate vasospasm risk.",
    "ref": "Frontera JA, et al. Neurosurgery 2006;59(1):21–7 (modified Fisher scale).",
    "inputs": [
     "Subarachnoid blood",
     "Intraventricular haemorrhage present"
    ],
    "only_here": [
     "Subarachnoid blood",
     "Intraventricular haemorrhage present"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "Glasgow Outcome Scale",
  "kind": "versions",
  "members": [
   {
    "id": "gos",
    "title": "Glasgow Outcome Scale (GOS)",
    "desc": "Global outcome after brain injury.",
    "ref": "",
    "inputs": [
     "Outcome"
    ],
    "only_here": [
     "Outcome"
    ]
   },
   {
    "id": "gose",
    "title": "Glasgow Outcome Scale — Extended (GOS-E)",
    "desc": "Functional outcome after traumatic brain injury.",
    "ref": "Wilson JTL, et al. J Neurotrauma 1998;15(8):573–85 (GOS-E).",
    "inputs": [
     "Outcome category"
    ],
    "only_here": [
     "Outcome category"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "GCS",
  "kind": "variants",
  "members": [
   {
    "id": "gcs",
    "title": "Glasgow Coma Scale",
    "desc": "Level of consciousness (E+V+M).",
    "ref": "Teasdale G, Jennett B. Lancet 1974;2(7872):81–4.",
    "inputs": [
     "Eye opening",
     "Verbal response",
     "Motor response"
    ],
    "only_here": [
     "Eye opening",
     "Verbal response",
     "Motor response"
    ]
   },
   {
    "id": "gcs_p",
    "title": "GCS-Pupils Score (GCS-P)",
    "desc": "Glasgow Coma Scale combined with pupil reactivity.",
    "ref": "Brennan PM, Murray GD, Teasdale GM. J Neurosurg 2018;128(6):1612–20.",
    "inputs": [
     "GCS total (3–15)",
     "Unreactive pupils"
    ],
    "only_here": [
     "GCS total (3–15)",
     "Unreactive pupils"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "Braden (pressure injury)",
  "kind": "variants",
  "members": [
   {
    "id": "braden",
    "title": "Braden Scale (Pressure Ulcer Risk)",
    "desc": "Risk of pressure ulcer development in immobile or at-risk patients.",
    "ref": "Bergstrom N, et al. Nurs Res 1987;36(4):205–10.",
    "inputs": [
     "Sensory perception",
     "Moisture",
     "Activity",
     "Mobility",
     "Nutrition",
     "Friction and shear"
    ],
    "only_here": [
     "Friction and shear"
    ]
   },
   {
    "id": "braden_q",
    "title": "Braden Q Scale (Paediatric Pressure Injury)",
    "desc": "Pressure-injury risk in paediatric patients (lower total = higher risk).",
    "ref": "Curley MAQ, et al. Nurs Res 2003;52(1):22–33 (Braden Q).",
    "inputs": [
     "Mobility",
     "Activity",
     "Sensory perception",
     "Moisture",
     "Friction & shear",
     "Nutrition",
     "Tissue perfusion & oxygenation"
    ],
    "only_here": [
     "Friction & shear",
     "Tissue perfusion & oxygenation"
    ]
   }
  ],
  "shared_inputs": [
   "sensory perception",
   "moisture",
   "activity",
   "mobility",
   "nutrition"
  ]
 },
 {
  "family": "HOMA",
  "kind": "variants",
  "members": [
   {
    "id": "homa_ir",
    "title": "HOMA-IR (insulin resistance)",
    "desc": "Homeostatic model assessment of insulin resistance.",
    "ref": "",
    "inputs": [
     "Fasting glucose (mg/dL)",
     "Fasting insulin (µU/mL)"
    ],
    "only_here": []
   },
   {
    "id": "homa_b",
    "title": "HOMA-%B (Beta-Cell Function)",
    "desc": "Estimates pancreatic beta-cell function from fasting values.",
    "ref": "Matthews DR, et al. Diabetologia 1985;28(7):412–9 (HOMA model).",
    "inputs": [
     "Fasting insulin (µU/mL)",
     "Fasting glucose (mmol/L)"
    ],
    "only_here": []
   }
  ],
  "shared_inputs": [
   "fasting glucose",
   "fasting insulin"
  ]
 },
 {
  "family": "eGFR",
  "kind": "variants",
  "members": [
   {
    "id": "ckdepi",
    "title": "eGFR (CKD-EPI 2021)",
    "desc": "Race-free creatinine eGFR.",
    "ref": "Inker LA et al. (CKD-EPI 2021) N Engl J Med 2021;385:1737–49.",
    "inputs": [
     "Serum creatinine (mg/dL)",
     "Age (yrs)",
     "Sex"
    ],
    "only_here": [
     "Serum creatinine",
     "Age",
     "Sex"
    ]
   },
   {
    "id": "mdrd",
    "title": "eGFR (MDRD, race-free)",
    "desc": "4-variable MDRD eGFR.",
    "ref": "Levey AS et al. (MDRD) Ann Intern Med 1999;130(6):461–70.",
    "inputs": [
     "Serum creatinine (mg/dL)",
     "Age (yrs)",
     "Sex"
    ],
    "only_here": [
     "Serum creatinine",
     "Age",
     "Sex"
    ]
   },
   {
    "id": "egfr_cysc",
    "title": "eGFR (cystatin C, CKD-EPI)",
    "desc": "Race-free estimated GFR from serum cystatin C (CKD-EPI cystatin C) — useful when creatinine is confounded.",
    "ref": "",
    "inputs": [
     "Cystatin C (mg/L)",
     "Age (yrs)",
     "Sex"
    ],
    "only_here": [
     "Cystatin C",
     "Age",
     "Sex"
    ]
   },
   {
    "id": "schwartz",
    "title": "Bedside Schwartz eGFR (Paediatric)",
    "desc": "Estimated GFR in children from height and serum creatinine.",
    "ref": "Schwartz GJ, et al. J Am Soc Nephrol 2009;20(3):629–37.",
    "inputs": [
     "Height (cm)",
     "Serum creatinine (mg/dL)"
    ],
    "only_here": [
     "Height",
     "Serum creatinine"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "QTc",
  "kind": "variants",
  "members": [
   {
    "id": "qtc",
    "title": "Corrected QT (QTc)",
    "desc": "Rate-correct the QT interval (Bazett & Fridericia).",
    "ref": "Bazett HC. Heart 1920; Fridericia LS. Acta Med Scand 1920.",
    "inputs": [
     "QT interval (ms)",
     "Heart rate (bpm)",
     "Sex"
    ],
    "only_here": [
     "QT interval",
     "Sex"
    ]
   },
   {
    "id": "qtcf",
    "title": "Corrected QT — Fridericia (QTcF)",
    "desc": "Rate-corrected QT using the Fridericia (cube-root) formula.",
    "ref": "Fridericia LS. 1920 (cube-root QT correction).",
    "inputs": [
     "Measured QT interval (ms)",
     "Heart rate (bpm)"
    ],
    "only_here": [
     "Measured QT interval"
    ]
   },
   {
    "id": "qtc_fram",
    "title": "Corrected QT — Framingham (QTcFram)",
    "desc": "Linear heart-rate correction of the QT interval.",
    "ref": "Sagie A, et al. Am J Cardiol 1992;70(7):797–801 (Framingham).",
    "inputs": [
     "Measured QT interval (ms)",
     "Heart rate (bpm)"
    ],
    "only_here": [
     "Measured QT interval"
    ]
   },
   {
    "id": "qtc_hodges",
    "title": "Corrected QT — Hodges (QTcH)",
    "desc": "Heart-rate correction of the QT interval (Hodges).",
    "ref": "Hodges M, et al. 1983 (Hodges QT correction).",
    "inputs": [
     "Measured QT interval (ms)",
     "Heart rate (bpm)"
    ],
    "only_here": [
     "Measured QT interval"
    ]
   }
  ],
  "shared_inputs": [
   "heart rate"
  ]
 },
 {
  "family": "TIMI",
  "kind": "variants",
  "members": [
   {
    "id": "timi_nstemi",
    "title": "TIMI risk (UA/NSTEMI)",
    "desc": "14-day risk of death/MI/urgent revascularisation.",
    "ref": "Antman EM et al. JAMA 2000;284(7):835–42.",
    "inputs": [
     "Age ≥65",
     "≥3 CAD risk factors",
     "Known CAD (stenosis ≥50%)",
     "Aspirin use in prior 7 days",
     "≥2 anginal episodes in 24 h",
     "ST deviation ≥0.5 mm",
     "Positive cardiac marker"
    ],
    "only_here": [
     "Age ≥65",
     "≥3 CAD risk factors",
     "Known CAD (stenosis ≥50%)",
     "Aspirin use in prior 7 days",
     "≥2 anginal episodes in 24 h",
     "ST deviation ≥0.5 mm",
     "Positive cardiac marker"
    ]
   },
   {
    "id": "timistemi",
    "title": "TIMI risk (STEMI)",
    "desc": "30-day mortality risk in ST-elevation MI.",
    "ref": "",
    "inputs": [
     "Age (yrs)",
     "DM or HTN or angina history (+1)",
     "Systolic BP (mmHg)",
     "Heart rate (bpm)",
     "Killip II–IV (+2)",
     "Weight <67 kg (+1)",
     "Anterior STEMI or LBBB (+1)",
     "Time to treatment >4 h (+1)"
    ],
    "only_here": [
     "Age",
     "DM or HTN or angina history (+1)",
     "Systolic BP",
     "Heart rate",
     "Killip II–IV (+2)",
     "Weight <67 kg (+1)",
     "Anterior STEMI or LBBB (+1)",
     "Time to treatment >4 h (+1)"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "Wells",
  "kind": "same-name",
  "members": [
   {
    "id": "wells_dvt",
    "title": "Wells score — DVT",
    "desc": "Pre-test probability of deep vein thrombosis.",
    "ref": "Wells PS et al. Lancet 1997;350(9094):1795–8.",
    "inputs": [
     "Active cancer",
     "Paralysis/paresis or recent immobilisation of leg",
     "Bedridden >3 days or major surgery <12 weeks",
     "Localised tenderness along deep veins",
     "Entire leg swollen",
     "Calf swelling >3 cm vs other leg",
     "Pitting oedema (symptomatic leg)",
     "Collateral superficial veins (non-varicose)",
     "Previously documented DVT",
     "Alternative diagnosis at least as likely (−2)"
    ],
    "only_here": [
     "Active cancer",
     "Paralysis/paresis or recent immobilisation of leg",
     "Bedridden >3 days or major surgery <12 weeks",
     "Localised tenderness along deep veins",
     "Entire leg swollen",
     "Calf swelling >3 cm vs other leg",
     "Pitting oedema (symptomatic leg)",
     "Collateral superficial veins (non-varicose)",
     "Previously documented DVT",
     "Alternative diagnosis at least as likely (−2)"
    ]
   },
   {
    "id": "wells_pe",
    "title": "Wells score — PE",
    "desc": "Pre-test probability of pulmonary embolism.",
    "ref": "Wells PS et al. Thromb Haemost 2000;83(3):416–20.",
    "inputs": [
     "Clinical signs of DVT",
     "PE is the most likely diagnosis",
     "Heart rate >100",
     "Immobilisation/surgery in prior 4 weeks",
     "Previous DVT/PE",
     "Haemoptysis",
     "Active malignancy"
    ],
    "only_here": [
     "Clinical signs of DVT",
     "PE is the most likely diagnosis",
     "Heart rate >100",
     "Immobilisation/surgery in prior 4 weeks",
     "Previous DVT/PE",
     "Haemoptysis",
     "Active malignancy"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "NEXUS",
  "kind": "same-name",
  "members": [
   {
    "id": "nexus_cspine",
    "title": "NEXUS C-Spine Criteria",
    "desc": "Whether cervical-spine imaging can be safely avoided after blunt trauma.",
    "ref": "",
    "inputs": [
     "Posterior midline cervical tenderness",
     "Focal neurological deficit",
     "Altered level of alertness",
     "Evidence of intoxication",
     "Distracting painful injury"
    ],
    "only_here": [
     "Posterior midline cervical tenderness",
     "Focal neurological deficit",
     "Altered level of alertness",
     "Evidence of intoxication"
    ]
   },
   {
    "id": "nexus_chest",
    "title": "NEXUS Chest (Blunt Trauma Imaging)",
    "desc": "Identifies blunt-trauma patients at very low risk of thoracic injury.",
    "ref": "Rodriguez RM, et al. PLoS Med 2015;12(10):e1001883 (NEXUS Chest).",
    "inputs": [
     "Age >60",
     "Rapid deceleration (fall >6 m or MVC >64 km/h)",
     "Chest pain",
     "Intoxication",
     "Altered alertness / mental status",
     "Distracting painful injury",
     "Chest-wall tenderness"
    ],
    "only_here": [
     "Age >60",
     "Rapid deceleration (fall >6 m or MVC >64 km/h)",
     "Chest pain",
     "Intoxication",
     "Altered alertness / mental status",
     "Chest-wall tenderness"
    ]
   }
  ],
  "shared_inputs": [
   "distracting painful injury"
  ]
 },
 {
  "family": "Hamilton",
  "kind": "same-name",
  "members": [
   {
    "id": "hamd",
    "title": "HAM-D (Hamilton Depression) — interpreter",
    "desc": "Interprets a 17-item Hamilton Depression Rating Scale total.",
    "ref": "Hamilton M. J Neurol Neurosurg Psychiatry 1960;23:56–62 (HDRS).",
    "inputs": [
     "HAM-D 17-item total (0–52)"
    ],
    "only_here": [
     "HAM-D 17-item total (0–52)"
    ]
   },
   {
    "id": "hama",
    "title": "Hamilton Anxiety Rating Scale (HAM-A)",
    "desc": "Clinician-rated severity of anxiety (14 domains, each 0–4).",
    "ref": "Hamilton M. Br J Med Psychol 1959;32(1):50–5 (HAM-A).",
    "inputs": [
     "Anxious mood",
     "Tension",
     "Fears",
     "Insomnia",
     "Intellectual (cognitive)",
     "Depressed mood",
     "Somatic (muscular)",
     "Somatic (sensory)",
     "Cardiovascular symptoms",
     "Respiratory symptoms",
     "Gastrointestinal symptoms",
     "Genitourinary symptoms",
     "Autonomic symptoms",
     "Behaviour at interview"
    ],
    "only_here": [
     "Anxious mood",
     "Tension",
     "Fears",
     "Insomnia",
     "Intellectual (cognitive)",
     "Depressed mood",
     "Somatic (muscular)",
     "Somatic (sensory)",
     "Cardiovascular symptoms",
     "Respiratory symptoms",
     "Gastrointestinal symptoms",
     "Genitourinary symptoms",
     "Autonomic symptoms",
     "Behaviour at interview"
    ]
   }
  ],
  "shared_inputs": []
 },
 {
  "family": "Framingham",
  "kind": "same-name",
  "members": [
   {
    "id": "framingham",
    "title": "Framingham Risk (General CVD, 2008)",
    "desc": "10-year general cardiovascular disease risk (D'Agostino 2008).",
    "ref": "D'Agostino RB, et al. Circulation 2008;117(6):743–53 (General CVD risk).",
    "inputs": [
     "Sex",
     "Age (years (30–74))",
     "Total cholesterol (mg/dL)",
     "HDL cholesterol (mg/dL)",
     "Systolic blood pressure (mmHg)",
     "On blood-pressure treatment",
     "Current smoker",
     "Diabetes mellitus"
    ],
    "only_here": [
     "Sex",
     "Age",
     "Total cholesterol",
     "HDL cholesterol",
     "Systolic blood pressure",
     "On blood-pressure treatment",
     "Current smoker",
     "Diabetes mellitus"
    ]
   },
   {
    "id": "framingham_hf",
    "title": "Framingham Criteria (Heart Failure)",
    "desc": "Two major, or one major and two minor, make the clinical diagnosis.",
    "ref": "",
    "inputs": [
     "MAJOR criteria present",
     "MINOR criteria present"
    ],
    "only_here": [
     "MAJOR criteria present",
     "MINOR criteria present"
    ]
   }
  ],
  "shared_inputs": []
 }
];
  var BY_ID = {};
  FAMILIES.forEach(function (f) { f.members.forEach(function (m) { BY_ID[m.id] = f; }); });
  var API = {
    FAMILIES: FAMILIES,
    familyOf: function (id) { return BY_ID[id] || null; },
    siblings: function (id) { var f = BY_ID[id]; return f ? f.members.filter(function (m) { return m.id !== id; }) : []; },
    _version: "1"
  };
  if (root) root.SMD_EDGE_SCHEMAS = API;
  if (typeof module !== "undefined" && module.exports) module.exports = API;
})(typeof window !== "undefined" ? window : null);
