/* pglog-reports.js — NMC Logbook · report builders (PURE) + print/export.
 * ===========================================================================
 * Eleven reports, each returning a plain structure:
 *
 *   { id, title, subtitle, meta[], sections[ { heading, note, columns[], rows[][], provenance } ],
 *     verification{}, disclaimer }
 *
 * The builders are pure so every number in a document a University examiner may see is produced by
 * code that is unit-tested, and so the same report renders identically on screen, in print and in
 * an export. Rendering is a separate, dumb function at the bottom.
 *
 * THREE RULES THE BUILDERS ENFORCE
 * --------------------------------
 * 1. A REPORT CARRIES ITS VERIFICATION STATE. Every row shows whether it is verified, by whom and
 *    when, and every report carries the monthly-authentication ledger (PGMER-2023 5.2(vii)) and the
 *    revision count. A logbook printout that hides which rows are unverified is worse than none.
 * 2. PATIENT IDENTITY IS OPT-IN AND NEVER CROSS-RESIDENT. `includeCaseRef` defaults FALSE. It may
 *    only be true for the resident's OWN logbook and procedure report — the two documents that are
 *    their own record. Every department/institution report is built from counts.
 * 3. NO NUMBER WITHOUT A SOURCE. Progress tables print the provenance grade beside each target, so
 *    an institutional target can never be read as an NMC one.
 *
 * window.SMD_PGLOG_REPORTS + module.exports.
 */
(function () {
  "use strict";

  var G = (typeof window !== "undefined") ? window : null;
  function Q() { try { return (G && G.SMD_PGLOG_QR) || (typeof require === "function" ? require("./pglog-qr.js") : null); } catch (e) { return null; } }
  function M() { try { return (G && G.SMD_PGLOG_MODEL) || (typeof require === "function" ? require("./pglog-model.js") : null); } catch (e) { return null; } }
  function C() { try { return (G && G.SMD_PGLOG_CURRICULUM) || (typeof require === "function" ? require("./pglog-curriculum.js") : null); } catch (e) { return null; } }

  function arr(x) { return Array.isArray(x) ? x : []; }
  function s(v) { return v == null ? "" : String(v); }
  function esc(v) {
    return s(v).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; });
  }
  function fmtDate(v) { var m = M(); return m ? m.isoDate(v) : s(v); }
  function fmtTs(v) { return v ? fmtDate(v) : ""; }
  function person(id) {
    // Identities are namespaced uids ("fb:abc…"). A report shows the readable part; the full id
    // stays in the audit trail, which is where an auditor looks.
    var t = s(id).replace(/^(fb:|ghis:|cfa:)/, "");
    return t.length > 24 ? t.slice(0, 10) + "…" + t.slice(-6) : t;
  }
  function verifiedCell(e) {
    // A signature is only worth printing if it names the registration behind it. The uid is a
    // fallback for records signed before the registration gate existed.
    if (e.status === "verified") {
      var who = e.verifiedName || person(e.verifiedBy);
      var reg = e.verifiedReg ? " (" + e.verifiedReg + ")" : "";
      return "Verified " + fmtTs(e.verifiedAt) + " · " + who + reg + (e.verifyCode ? " · " + e.verifyCode : "");
    }
    if (e.status === "submitted") return "Awaiting verification";
    if (e.status === "returned") return "Returned for correction";
    return "Draft — not submitted";
  }
  function live(entries) { return arr(entries).filter(function (e) { return e && !e.deleted; }); }
  function byKind(entries, kind) { return live(entries).filter(function (e) { return e.kind === kind; }); }
  function sortByDate(rows) { return rows.slice().sort(function (a, b) { return s(a.occurredAt).localeCompare(s(b.occurredAt)); }); }

  var DISCLAIMER =
    "Generated by StewardMD from the resident's own logbook entries. Requirements shown are traced " +
    "to the NMC source named beside them. This document does not certify compliance and does not " +
    "determine examination eligibility — that is the University's and the institution's decision.";

  // The header block every report carries.
  function header(ctx, id, title, subtitle) {
    var m = M(), res = ctx.resident || {}, prog = ctx.programme || {};
    var meta = [
      ["Resident", res.name || person(res.uid)],
      ["StewardMD ID", res.smdId || ""],
      ["Programme", prog.name || (prog.degree + " " + (prog.specialtyId || ""))],
      ["Institution", ctx.orgName || res.orgId || ""],
      ["Department", ctx.departmentName || res.departmentId || ""],
      ["Unit", res.unit || ""],
      ["Training year", String(res.trainingYear || (m ? m.trainingYearOn(res, prog, ctx.today) : ""))],
      ["Training period", fmtDate(res.startDate) + (res.endDate ? " to " + fmtDate(res.endDate) : "")],
      ["Guide", person(res.guide)],
      ["Co-guides", arr(res.coGuides).map(person).join(", ")],
      ["Generated", fmtDate(ctx.today)]
    ].filter(function (r) { return s(r[1]).trim(); });
    return { id: id, title: title, subtitle: subtitle || "", meta: meta, sections: [], disclaimer: DISCLAIMER };
  }

  // The verification summary appended to every resident-level report. This is rule 1.
  function verificationBlock(ctx) {
    var m = M(), entries = live(ctx.entries);
    var months = arr(ctx.months);
    return {
      total: entries.length,
      verified: entries.filter(function (e) { return e.status === "verified"; }).length,
      submitted: entries.filter(function (e) { return e.status === "submitted"; }).length,
      returned: entries.filter(function (e) { return e.status === "returned"; }).length,
      draft: entries.filter(function (e) { return e.status === "draft"; }).length,
      amended: entries.filter(function (e) { return (e.revisionCount || (e.revisions || []).length) > 0; }).length,
      monthsAttested: months.filter(function (x) { return x.attested; }).length,
      monthsTotal: months.length,
      monthsOverdue: months.filter(function (x) { return x.overdue; }).map(function (x) { return x.period; }),
      weekly: ctx.weekly || (m ? m.weeklyCadence(entries, (ctx.resident || {}).startDate, ctx.today) : null),
      clause: "PGMER-2023 5.2(vi) weekly update; 5.2(vii) monthly authentication by the postgraduate guide",
      // Every signature on this document names a registered practitioner and carries a code the
      // reader can check independently. Reported so the reader knows to expect it.
      signedWithRegistration: entries.filter(function (e) { return e.status === "verified" && e.verifiedReg; }).length,
      withVerificationCode: entries.filter(function (e) { return e.verifyCode; }).length
    };
  }

  /* ── 1. Individual resident logbook ─────────────────────────────────────────
   * The whole record, in date order, exactly as the curricula describe it: postings/work in wards,
   * OPDs and casualty; procedures assisted and performed; teaching sessions attended. */
  function residentLogbook(ctx, opts) {
    opts = opts || {};
    var r = header(ctx, "resident_logbook", "Postgraduate Logbook", "Complete record of training");
    var withRef = opts.includeCaseRef === true;   // rule 2: opt-in, own record only
    var cols = ["Date", "Type", "Activity", "Role", "Supervisor"]
      .concat(withRef ? ["Case ref"] : [])
      .concat(["Requirement", "Verification"]);
    var rows = sortByDate(live(ctx.entries).filter(function (e) { return e.kind !== "attendance"; })).map(function (e) {
      var base = [
        fmtDate(e.occurredAt), kindLabel(e), activityLabel(e), roleLabel(e), person(e.supervisor)
      ];
      if (withRef) base.push(e.caseRef || "");
      base.push(arr(e.requirementIds).join(", "));
      base.push(verifiedCell(e));
      return base;
    });
    r.sections.push({
      heading: "All logged activity", columns: cols, rows: rows,
      note: "Entries are listed by the date the work was done. " +
        (withRef ? "Case references are hospital/MRN references only — no patient identity is stored." : "Case references are withheld from this copy.")
    });
    r.sections.push(monthlyAttestationSection(ctx));
    r.verification = verificationBlock(ctx);
    return r;
  }

  function monthlyAttestationSection(ctx) {
    return {
      heading: "Monthly authentication by the postgraduate guide",
      provenance: { source: "nmc_regulation", clause: "5.2(vii)" },
      columns: ["Month", "Entries", "Authenticated", "By", "Date"],
      rows: arr(ctx.months).map(function (x) {
        return [x.period, String(x.entries), x.attested ? "Yes" : (x.overdue ? "OVERDUE" : (x.closed ? "No" : "Month open")),
                person(x.attestedBy), fmtTs(x.attestedAt)];
      }),
      note: "PGMER-2023 5.2(vii): “The record (Log) books shall be checked, assessed and " +
        "authenticated monthly by the postgraduate guide imparting the training.”"
    };
  }

  /* ── 2. Procedure / operation report ────────────────────────────────────────
   * Columns are the NMC's own: MD Emergency Medicine 2024 prints "Total procedures (consolidated)"
   * as Date · Procedure · Number assisted · Number performed · Comments · Faculty signature with
   * date. We store one entry per event (which "real time" requires) and CONSOLIDATE here. */
  function procedureReport(ctx, opts) {
    opts = opts || {};
    var r = header(ctx, "procedure_report", "Procedures and Operations", "Consolidated procedure log");
    var procs = byKind(ctx.entries, "procedure");
    var byName = {};
    procs.forEach(function (e) {
      var key = e.procedureId || e.procedureText || "(unnamed)";
      var b = byName[key] || (byName[key] = { label: procLabel(ctx, e), observed: 0, assisted: 0, supervised: 0, independent: 0, verified: 0, total: 0, last: "", complications: 0 });
      b.total++;
      if (e.status === "verified") b.verified++;
      if (e.role === "observed") b.observed++;
      if (e.role === "assisted") b.assisted++;
      if (e.role === "performed_supervised") b.supervised++;
      if (e.role === "performed_independent") b.independent++;
      if (arr(e.complications).length) b.complications++;
      if (!b.last || s(e.occurredAt) > b.last) b.last = e.occurredAt;
    });
    r.sections.push({
      heading: "Consolidated",
      provenance: { source: "nmc_curriculum", clause: "MD Emergency Medicine 2024 — “Total procedures (consolidated)”" },
      columns: ["Procedure", "Observed", "Assisted", "Performed under supervision", "Independently", "Total", "Verified", "Complications", "Last performed"],
      rows: Object.keys(byName).sort().map(function (k) {
        var b = byName[k];
        return [b.label, String(b.observed), String(b.assisted), String(b.supervised), String(b.independent),
                String(b.total), String(b.verified), String(b.complications), fmtDate(b.last)];
      }),
      note: "PGMER-2023 5.2(vi) requires MS/M.Ch students to enter every surgical procedure assisted " +
        "or done independently. Only verified entries count toward a training requirement."
    });
    var withRef = opts.includeCaseRef === true;
    r.sections.push({
      heading: "Every procedure entry",
      columns: ["Date", "Procedure", "Role", "Setting"].concat(withRef ? ["Case ref"] : [])
        .concat(["Outcome", "Complications", "Supervisor", "Verification"]),
      rows: sortByDate(procs).map(function (e) {
        var row = [fmtDate(e.occurredAt), procLabel(ctx, e), roleLabel(e), s(e.setting)];
        if (withRef) row.push(e.caseRef || "");
        row.push(s(e.outcome), arr(e.complications).join("; "), person(e.supervisor), verifiedCell(e));
        return row;
      })
    });
    if (ctx.requirementProgress) r.sections.push(procedureTargetsSection(ctx));
    r.verification = verificationBlock(ctx);
    return r;
  }
  function procedureTargetsSection(ctx) {
    var rows = arr(ctx.requirementProgress).filter(function (p) { return p.kind === "procedure"; });
    return {
      heading: "Against the curriculum",
      columns: ["Requirement", "Verified", "Target", "Source", "Clause"],
      rows: rows.map(function (p) {
        return [p.label, String(p.done), p.target == null ? "no number stated" : String(p.target),
                sourceLabel(p.source), s(p.clause)];
      }),
      note: "A requirement whose NMC source states no number is COUNTED, not scored. An " +
        "institutional target is labelled as institutional policy."
    };
  }

  /* ── 3. Clinical activity report (OPD / IPD / Emergency) ──────────────────── */
  function clinicalReport(ctx, opts) {
    opts = opts || {};
    var r = header(ctx, "clinical_report", "Clinical Activity", "OPD, inpatient and emergency work");
    var rows = byKind(ctx.entries, "clinical");
    ["opd", "ipd", "emergency"].forEach(function (setting) {
      var sub = rows.filter(function (e) { return e.setting === setting; });
      if (!sub.length) return;
      var withRef = opts.includeCaseRef === true;
      r.sections.push({
        heading: { opd: "Outpatient (OPD)", ipd: "Inpatient (IPD)", emergency: "Emergency" }[setting],
        columns: ["Date", "Case / problem", "Category", "Diagnosis", "Role"].concat(withRef ? ["Case ref"] : [])
          .concat(["Outcome", "Supervisor", "Verification"]),
        rows: sortByDate(sub).map(function (e) {
          var row = [fmtDate(e.occurredAt), s(e.title), s(e.category), opts.includeCaseRef ? s(e.diagnosis) : "", roleLabel(e)];
          if (withRef) row.push(e.caseRef || "");
          row.push(s(e.outcome), person(e.supervisor), verifiedCell(e));
          return row;
        })
      });
    });
    r.sections.push({
      heading: "Summary by setting",
      columns: ["Setting", "Entries", "Verified", "Observed", "Assisted", "Supervised", "Independent"],
      rows: ["opd", "ipd", "emergency"].map(function (setting) {
        var sub = rows.filter(function (e) { return e.setting === setting; });
        return [setting.toUpperCase(), String(sub.length),
                String(sub.filter(function (e) { return e.status === "verified"; }).length),
                String(sub.filter(function (e) { return e.role === "observed"; }).length),
                String(sub.filter(function (e) { return e.role === "assisted"; }).length),
                String(sub.filter(function (e) { return e.role === "performed_supervised"; }).length),
                String(sub.filter(function (e) { return e.role === "performed_independent"; }).length)];
      }),
      note: "The role columns are the graded responsibility PGMER-2023 5.2(x) describes."
    });
    r.verification = verificationBlock(ctx);
    return r;
  }

  /* ── 4. Academic activity report ────────────────────────────────────────────
   * Columns from MD Emergency Medicine 2024's own "Academic activities (consolidated…)" table:
   * S.No · Date · Academic activity · Place · Comments · Faculty signature. */
  function academicReport(ctx) {
    var r = header(ctx, "academic_report", "Academic Activities", "Seminars, journal clubs, teaching and conferences");
    var rows = byKind(ctx.entries, "academic");
    var m = M();
    r.sections.push({
      heading: "Consolidated",
      provenance: { source: "nmc_curriculum", clause: "MD Emergency Medicine 2024 — “Academic activities (consolidated)”" },
      columns: ["S.No", "Date", "Academic activity", "Topic", "Role", "Scope", "Place", "Faculty", "Verification"],
      rows: sortByDate(rows).map(function (e, i) {
        return [String(i + 1), fmtDate(e.occurredAt),
                (m && m.ACADEMIC_LABEL[e.academicType]) || s(e.academicType), s(e.topic || e.title),
                s(e.role), scopeLabel(e.scope), s(e.place), person(e.supervisor), verifiedCell(e)];
      })
    });
    var counts = {};
    rows.forEach(function (e) { counts[e.academicType] = (counts[e.academicType] || 0) + 1; });
    r.sections.push({
      heading: "By activity type",
      columns: ["Activity", "Total", "Verified"],
      rows: Object.keys(counts).sort().map(function (k) {
        var sub = rows.filter(function (e) { return e.academicType === k; });
        return [(m && m.ACADEMIC_LABEL[k]) || k, String(sub.length),
                String(sub.filter(function (e) { return e.status === "verified"; }).length)];
      }),
      note: "PGMER-2023 5.2(x) names lectures, seminars, journal clubs, group discussions, " +
        "laboratory work, clinical meetings, grand rounds and clinico-pathological conferences; " +
        "5.2(viii) requires participation in the teaching of undergraduates and interns."
    });
    r.verification = verificationBlock(ctx);
    return r;
  }

  /* ── 5. Research / thesis report ────────────────────────────────────────── */
  function researchReport(ctx) {
    var r = header(ctx, "research_report", "Research and Thesis", "Thesis milestones, publications and presentations");
    var rows = byKind(ctx.entries, "research");
    var thesis = rows.filter(function (e) { return e.subtype === "thesis_milestone"; });
    var title = (thesis.filter(function (e) { return e.projectTitle; })[0] || {}).projectTitle || "";
    if (title) r.meta.push(["Thesis title", title]);
    r.sections.push({
      heading: "Thesis milestones",
      columns: ["Milestone", "Date", "Evidence", "Verification"],
      rows: sortByDate(thesis).map(function (e) {
        return [milestoneLabel(e.milestone), fmtDate(e.occurredAt),
                arr(e.attachments).length ? arr(e.attachments).length + " attached" : "", verifiedCell(e)];
      }),
      note: "PGMER-2023 makes thesis a curriculum component (2.2(iii)) and gives it 5% of the " +
        "practical marks (8.1). It prescribes no milestone chain; the milestones above are the " +
        "institution's, seeded from the specialty curriculum."
    });
    ["publication", "poster", "conference_paper", "additional_project", "presentation"].forEach(function (st) {
      var sub = rows.filter(function (e) { return e.subtype === st; });
      if (!sub.length) return;
      r.sections.push({
        heading: { publication: "Publications", poster: "Posters", conference_paper: "Conference papers",
                   additional_project: "Additional research projects", presentation: "Other presentations" }[st],
        columns: ["Date", "Title", "Journal / conference", "Level", "First author", "Indexed", "Identifier", "Verification"],
        rows: sortByDate(sub).map(function (e) {
          return [fmtDate(e.occurredAt), s(e.projectTitle || e.title), s(e.journal || e.conference),
                  s(e.conferenceLevel), e.firstAuthor ? "Yes" : "", e.indexed ? "Yes" : "",
                  s(e.identifier), verifiedCell(e)];
        })
      });
    });
    if (ctx.eligibility) {
      var diss = arr(ctx.eligibility.rows).filter(function (x) { return x.key === "dissemination"; });
      if (diss.length) {
        r.sections.push({
          heading: "Examination pre-requisite (dissemination)",
          provenance: { source: "nmc_regulation", clause: "5.2(x)" },
          columns: ["Requirement", "Met", "Satisfied by"],
          rows: [[diss[0].label, diss[0].met ? "Yes" : "No", s(diss[0].via)]],
          note: "PGMER-2023 5.2(x) states this as ONE requirement with three alternatives (poster OR " +
            "paper read OR first-author publication). A specialty curriculum may require more; where " +
            "it does, those appear separately in the progress report."
        });
      }
    }
    r.verification = verificationBlock(ctx);
    return r;
  }

  /* ── 6. Assessment report + 7. Faculty feedback report ───────────────────── */
  function assessmentReport(ctx) {
    var r = header(ctx, "assessment_report", "Formative Assessments", "Faculty assessment and feedback");
    r.sections.push({
      heading: "Assessments",
      columns: ["Date", "Template", "Period / activity", "Score", "Outcome", "Discussed with trainee", "Assessor", "Status"],
      note2: "A dash in Score means the NMC form for that assessment prints no total — the element ratings are the record.",
      rows: arr(ctx.assessments).slice().sort(function (a, b) { return (a.assessedAt || 0) - (b.assessedAt || 0); }).map(function (a) {
        // A template the NMC prints WITHOUT a total row must not acquire one here. The MD General
        // Medicine appraisal (Annexure 1) is a banded per-element rating; "105 / 135" is a mark that
        // form does not have, on a document an examiner may read. (R1, finding I5.)
        var noTotal = arr(ctx.templates).some(function (t) { return t.id === a.templateId && t.noTotal; });
        return [fmtTs(a.assessedAt || a.createdAt), s(a.templateId), s(a.period || a.entryId),
                (noTotal || !a.maxTotal) ? "—" : a.total + " / " + a.maxTotal,
                s(a.outcome), a.discussedWithTrainee === true ? "Yes" : (a.discussedWithTrainee === false ? "No" : ""),
                person(a.assessor), s(a.status)];
      }),
      note: "PGMER-2023 8.1: the medical college conducts the FORMATIVE assessment; the University " +
        "conducts the summative examination. This module records formative assessment only and holds " +
        "no examination marks."
    });
    var remediation = arr(ctx.assessments).filter(function (a) { return a.outcome === "remediation"; });
    if (remediation.length) {
      r.sections.push({
        heading: "Remediation and action plans",
        columns: ["Date", "Template", "Action plan", "Reassessment due", "Status"],
        rows: remediation.map(function (a) {
          return [fmtTs(a.assessedAt), s(a.templateId), s(a.actionPlan), fmtDate(a.reassessmentDue), s(a.status)];
        })
      });
    }
    r.verification = verificationBlock(ctx);
    return r;
  }
  function feedbackReport(ctx) {
    var r = header(ctx, "feedback_report", "Faculty Feedback", "Narrative feedback across the training period");
    r.sections.push({
      heading: "Feedback",
      columns: ["Date", "Assessor", "Strengths", "Areas for development", "Feedback"],
      rows: arr(ctx.assessments).filter(function (a) { return a.feedback || a.strengths || a.improvements; })
        .sort(function (a, b) { return (a.assessedAt || 0) - (b.assessedAt || 0); })
        .map(function (a) { return [fmtTs(a.assessedAt), person(a.assessor), s(a.strengths), s(a.improvements), s(a.feedback)]; })
    });
    var returns = live(ctx.entries).filter(function (e) {
      return arr(e.history).some(function (h) { return h.action === "return"; });
    });
    if (returns.length) {
      r.sections.push({
        heading: "Entries returned for correction",
        columns: ["Date", "Activity", "Returned by", "Reason", "Now"],
        rows: returns.map(function (e) {
          var h = arr(e.history).filter(function (x) { return x.action === "return"; }).slice(-1)[0] || {};
          return [fmtTs(h.at), activityLabel(e), person(h.by), s(h.reason), verifiedCell(e)];
        }),
        note: "A return always carries a reason — the model refuses one without it."
      });
    }
    return r;
  }

  /* ── 8. Rotation report ─────────────────────────────────────────────────── */
  function rotationReport(ctx) {
    var m = M();
    var r = header(ctx, "rotation_report", "Rotations and Postings", "Where the training was done");
    r.sections.push({
      heading: "Rotations",
      columns: ["Start", "End", "Rotation", "Type", "Unit / site", "Faculty", "Entries logged", "Verified", "Status"],
      rows: arr(ctx.rotations).map(function (rot) {
        var sub = live(ctx.entries).filter(function (e) { return e.rotationId === rot.id; });
        return [fmtDate(rot.startDate), fmtDate(rot.endDate), s(rot.name), s(rot.kind),
                s(rot.unit || rot.externalSite), person(rot.faculty), String(sub.length),
                String(sub.filter(function (e) { return e.status === "verified"; }).length), s(rot.status)];
      })
    });
    var drp = arr(ctx.rotations).filter(function (x) { return x.kind === "drp"; });
    r.sections.push({
      heading: "District Residency Programme",
      provenance: { source: "nmc_regulation", clause: "5.2(xv)V, VIII(c)" },
      columns: ["Start", "End", "District site", "Coordinator (DRPC)", "Months", "Status"],
      rows: drp.map(function (rot) {
        return [fmtDate(rot.startDate), fmtDate(rot.endDate), s(rot.externalSite || rot.name),
                person(rot.coordinator), (m ? (m.daysBetween(rot.startDate, rot.endDate) / 30.4375).toFixed(1) : ""), s(rot.status)];
      }),
      note: "PGMER-2023 5.2(xv)V requires a compulsory three-month rotation in a District Hospital " +
        "/ District Health System, in the 3rd, 4th or 5th semester; VIII(c) makes satisfactory " +
        "completion an essential condition before the final examination." +
        (m && drp.length ? " Recorded: " + m.drpMonths(drp).toFixed(1) + " months." : "")
    });
    return r;
  }

  /* ── 9. Training progress report ────────────────────────────────────────── */
  function progressReport(ctx) {
    var r = header(ctx, "progress_report", "Training Progress", "Against the applicable NMC requirements");
    var rows = arr(ctx.requirementProgress);
    r.sections.push({
      heading: "Requirements",
      columns: ["Requirement", "Verified", "Target", "Expected by now", "State", "Source", "Clause"],
      rows: rows.map(function (p) {
        return [p.label, String(p.done),
                p.target == null ? "no number stated" : (p.target + (p.per && p.per !== "course" ? " / " + p.per : "")),
                p.expected == null ? "" : String(p.expected),
                stateLabel(p.state), sourceLabel(p.source), s(p.clause)];
      }),
      note: "Only VERIFIED entries count. A cadence requirement (“once a fortnight”) is " +
        "measured against what is expected by today, not against the whole course."
    });
    if (ctx.weekly) {
      r.sections.push({
        heading: "Weekly logbook cadence",
        provenance: { source: "nmc_regulation", clause: "5.2(vi)" },
        columns: ["Weeks in training", "Weeks with an entry", "Weeks missed", "Current streak"],
        rows: [[String(ctx.weekly.weeks), String(ctx.weekly.logged), String(arr(ctx.weekly.missed).length), String(ctx.weekly.streak)]],
        note: "PGMER-2023 5.2(vi): the e-logbook “needs to be updated on weekly basis”."
      });
    }
    if (ctx.attendance) r.sections.push(attendanceSection(ctx));
    if (ctx.eligibility) {
      r.sections.push({
        heading: "Examination pre-requisite checklist",
        columns: ["Requirement", "Met", "Detail", "Source", "Clause"],
        rows: arr(ctx.eligibility.rows).map(function (x) {
          return [x.label, x.met === true ? "Yes" : (x.met === false ? "No" : "Unknown"),
                  s(x.detail || x.via), sourceLabel(x.source), s(x.clause)];
        }),
        note: ctx.eligibility.disclaimer
      });
    }
    var g = arr(ctx.gaps);
    if (g.length) {
      r.sections.push({
        heading: "Gaps to act on",
        columns: ["Requirement", "Severity", "Position", "Source"],
        rows: g.map(function (x) { return [x.label, x.severity, s(x.message), sourceLabel(x.source)]; })
      });
    }
    r.verification = verificationBlock(ctx);
    return r;
  }
  function attendanceSection(ctx) {
    var a = ctx.attendance;
    return {
      heading: "Attendance",
      provenance: { source: "nmc_faq", clause: "PGMER-2023 5.5 · PGMEB FAQ 10.04.2024 Q2" },
      // The FAQ's own framing: days attended, of WORKING days. The recorded-days reading is kept but
      // demoted — a resident who records only the days they attended scores 100% on it.
      columns: ["Days counted as attended", "Working days elapsed", "% of working days",
                "Required for the course", "Meets threshold", "% of days recorded (secondary)"],
      rows: [[String(a.attendedDays), String(a.workingDaysElapsed),
              a.pctOfWorkingDays == null ? "training not started" : a.pctOfWorkingDays + "%",
              a.requiredDays ? a.requiredDays + " of " + a.courseWorkingDays + " working days" : "",
              a.meetsPct == null ? "unknown" : (a.meetsPct ? "Yes" : "No"),
              a.pctOfRecorded == null ? "nothing recorded" : a.pctOfRecorded + "%"]],
      note: a.note +
        (a.exceedsWorkingDays ? " More attended days than working days have been recorded, which means attendance was logged on weekly offs." : "") +
        (a.termExtension && a.termExtension.totalDays
          ? " Training is extended by " + a.termExtension.totalDays + " days (" +
            a.termExtension.maternity + " maternity, " + a.termExtension.paternity + " paternity, " +
            a.termExtension.excessCasual + " excess casual) — these do not reduce the percentage."
          : "")
    };
  }

  /* ── 10. Department-level summary ────────────────────────────────────────────
   * Built from AGGREGATES only. No case reference, no diagnosis, no clinical detail reaches this
   * document — the server has already projected the rows through publicEntry(). */
  function departmentSummary(ctx) {
    var rows = arr(ctx.residents);
    var r = {
      id: "department_summary",
      title: "Department Training Summary",
      subtitle: (ctx.departmentName || "") + (ctx.orgName ? " · " + ctx.orgName : ""),
      meta: [["Generated", fmtDate(ctx.today)], ["Residents", String(rows.length)]],
      sections: [], disclaimer: DISCLAIMER
    };
    r.sections.push({
      heading: "Residents",
      columns: ["Resident", "Year", "Unit", "Guide", "Entries", "Verified", "Awaiting verification",
                "Weekly cadence", "Authentication overdue", "Verification overdue", "DRP months", "Last entry"],
      rows: rows.map(function (x) {
        var res = x.resident || {};
        return [res.name || person(res.id), String(res.trainingYear || ""), s(res.unit), person(res.guide),
                String((x.summary || {}).total || 0), String((x.summary || {}).verified || 0),
                String((x.summary || {}).submitted || 0),
                (x.weekly && x.weekly.pct != null) ? x.weekly.pct + "%" : "—",
                String(x.attestationOverdue || 0), String(x.overdueVerifications || 0),
                x.drpMonths ? Number(x.drpMonths).toFixed(1) : "0",
                fmtDate(x.lastEntryAt)];
      }),
      note: "Patient-identifiable information is deliberately absent from this document. It reports " +
        "training completeness, not clinical detail."
    });
    var attention = rows.filter(function (x) {
      return (x.weekly && x.weekly.pct != null && x.weekly.pct < 70) || (x.attestationOverdue || 0) > 0 || (x.overdueVerifications || 0) > 0;
    });
    r.sections.push({
      heading: "Residents requiring intervention",
      columns: ["Resident", "Why"],
      rows: attention.map(function (x) {
        var why = [];
        if (x.weekly && x.weekly.pct != null && x.weekly.pct < 70) why.push("weekly logbook cadence " + x.weekly.pct + "% (PGMER-2023 5.2(vi))");
        if (x.attestationOverdue) why.push(x.attestationOverdue + " month(s) without guide authentication (5.2(vii))");
        if (x.overdueVerifications) why.push(x.overdueVerifications + " entries awaiting verification beyond the institutional SLA");
        return [(x.resident || {}).name || person((x.resident || {}).id), why.join("; ")];
      }),
      note: "The purpose of this list is to identify gaps early, while they can still be closed."
    });
    return r;
  }

  /* ── 11. Final PG training portfolio ────────────────────────────────────────
   * Everything, in the order an examiner reads it. This is the artefact the curricula mean by
   * "produce completed log book in original at the time of final practical examination". */
  function finalPortfolio(ctx) {
    var r = header(ctx, "final_portfolio", "Postgraduate Training Portfolio", "Complete record for the final examination");
    var parts = [
      progressReport(ctx), rotationReport(ctx), clinicalReport(ctx, { includeCaseRef: false }),
      procedureReport(ctx, { includeCaseRef: false }), academicReport(ctx), researchReport(ctx),
      assessmentReport(ctx), feedbackReport(ctx)
    ];
    parts.forEach(function (p) {
      r.sections.push({ heading: "— " + p.title + " —", columns: [], rows: [], divider: true });
      p.sections.forEach(function (sec) { r.sections.push(sec); });
    });
    r.sections.push(monthlyAttestationSection(ctx));
    r.sections.push({
      heading: "Head of Department certification",
      provenance: { source: "nmc_curriculum", clause: "J. Log book" },
      columns: ["Certification", "Signed", "By", "Date"],
      rows: arr(ctx.attestations).filter(function (a) { return a.kind !== "monthly"; }).map(function (a) {
        return [a.kind === "hod_final" ? "Completed log book signed by the Head of Department"
                                       : "Proficiency certificate (clinical competence and skilful performance of procedures)",
                "Yes", person(a.attestedBy), fmtTs(a.attestedAt)];
      }),
      note: "The 2022-revised NMC curricula require the completed log book to be signed by the Head " +
        "of the Department, and a proficiency certificate from the HoD to be submitted at the " +
        "examination. Both are recorded above only when they have actually been signed in the app."
    });
    r.verification = verificationBlock(ctx);
    return r;
  }


  /* ═══════════════════════════════════════════════════════════════════════════════════════════════
   * THE CERTIFIED LOGBOOK — the document that leaves the app.
   * ═══════════════════════════════════════════════════════════════════════════════════════════════
   *
   * Everything else in this file is a working report a department reads on screen. This one is an
   * ARTEFACT: it is printed, signed, filed with a college, and possibly produced years later at an
   * examination. So it obeys three rules the others do not.
   *
   * 1. IT SAYS WHAT IT IS. An uncertified export is stamped, on every page, as a draft that carries
   *    no signature. There is no configuration in which this document is silently ambiguous about
   *    whether anyone signed it — that ambiguity is the only way it could ever mislead.
   * 2. IT CARRIES ITS OWN VERIFICATION. The signature page prints every signer with the medical
   *    registration number a reader can check on the Indian Medical Register, the content
   *    fingerprint, and a QR to the StewardMD verification page.
   * 3. IT DOES NOT OVERSTATE ITSELF. It is not a Digital Signature Certificate under the IT Act,
   *    2000, and it does not claim NMC endorsement. The limits are printed ON the document, not
   *    buried in a help page, because the person relying on it is the person who needs to read them.
   */
  function certifiedLogbook(ctx) {
    var cert = ctx.certificate || null;
    var official = !!(cert && cert.status === "issued" && cert.verifyCode);
    var r = header(ctx, "certified_logbook", "Postgraduate Training Logbook",
      official ? "Certified record for submission" : "UNCERTIFIED DRAFT — not for submission");
    r.official = official;
    r.certificate = cert;
    r.draftBanner = official ? "" :
      (cert && cert.status === "superseded"
        ? "SUPERSEDED — a record covered by this certificate was corrected after it was signed. Ask for a current certified copy."
        : cert && cert.status === "revoked"
        ? "REVOKED — this certification was withdrawn by the head of department."
        : cert && cert.status === "pending"
        ? "AWAITING SIGNATURES — this logbook has not yet been certified. It carries no signature and must not be submitted."
        : "NOT CERTIFIED — this is a working copy of a logbook. It carries no signature and must not be submitted.");

    // The whole record, then the certification page.
    var parts = [
      progressReport(ctx), rotationReport(ctx), clinicalReport(ctx, { includeCaseRef: false }),
      procedureReport(ctx, { includeCaseRef: false }), academicReport(ctx), researchReport(ctx),
      assessmentReport(ctx), feedbackReport(ctx)
    ];
    parts.forEach(function (p) {
      r.sections.push({ heading: "— " + p.title + " —", columns: [], rows: [], divider: true });
      p.sections.forEach(function (sec) { r.sections.push(sec); });
    });
    r.sections.push(monthlyAttestationSection(ctx));
    r.sections.push(certificationSection(ctx, cert));
    r.verification = verificationBlock(ctx);
    return r;
  }

  /* The signature page. Each row is a person a reader can look up on the register — that is the
   * entire reason this document is worth more than a printout. */
  function certificationSection(ctx, cert) {
    var m = M();
    var sigs = arr(cert && cert.signatures);
    var st = (m && cert) ? m.quorumState(cert, cert.quorum, ctx.resident) : null;
    var rows = sigs.map(function (sig) {
      return [
        sig.name || person(sig.by),
        sig.role === "hod" ? "Head of Department"
          : sig.role === "guide" ? "Postgraduate guide" : "Faculty",
        sig.reg || "—",
        sig.council || "—",
        fmtTs(sig.at)
      ];
    });
    var note;
    if (cert && cert.status === "issued") {
      note = "Each signatory above held a medical registration verified against the Indian Medical " +
        "Register at the moment of signing, and that number is recorded on this document so it can " +
        "be checked independently. " + quorumSentence(st, cert);
    } else if (cert) {
      note = "This logbook is NOT certified. " + (st && st.missing.length ? "Still required: " + st.missing.join("; ") + ". " : "") +
        quorumSentence(st, cert);
    } else {
      note = "No certification has been opened for this logbook.";
    }
    return {
      heading: "Certification",
      provenance: { source: "nmc_curriculum", clause: "J. Log book — signed by the Head of the Department" },
      columns: ["Signatory", "Capacity", "Medical registration", "Council", "Signed"],
      rows: rows,
      note: note
    };
  }

  // Whose rule is whose. The HoD signature comes from the NMC curricula; the number of faculty
  // signatures is the institution's own policy, and this document must never let one read as the
  // other — that is the single rule the whole module is built around.
  function quorumSentence(st, cert) {
    var q = (cert && cert.quorum) || (st || {});
    var need = [];
    if (q.faculty) need.push(q.faculty + " faculty signature" + (q.faculty > 1 ? "s" : ""));
    if (q.hod) need.push(q.hod + " Head of Department signature" + (q.hod > 1 ? "s" : ""));
    return "This institution requires " + (need.join(" and ") || "no signatures") +
      (q.hodCountsAsFaculty ? " (the Head of Department counts toward both)" : "") + ". " +
      "The Head of Department signature follows the NMC specialty curricula, which require the " +
      "completed log book to be signed by the Head of the Department. The NUMBER OF FACULTY " +
      "signatures is this institution's own rule and is not an NMC requirement.";
  }

  /* The standalone HTML document that becomes the PDF. Self-contained: inline CSS, a QR built out of
   * table cells (so it survives both the WKWebView renderer and the html2canvas fallback), and no
   * external request of any kind — this file has to render years from now, offline, from a folder. */
  function certifiedDocHtml(rep, opts) {
    opts = opts || {};
    var qr = Q();
    var cert = rep.certificate || null;
    var official = !!rep.official;
    var url = opts.verifyUrl || "";
    var code = (cert && cert.verifyCode) || "";
    var qrHtml = (official && qr && url) ? qr.toTableHtml(url, { scale: 3 }) : "";

    var h = ['<!doctype html><html lang="en"><head><meta charset="utf-8"><title>' + esc(rep.title) +
             // The QR geometry rules ship only with a QR. A draft that carried them would contain the
             // string "pgl-qrt" while showing no code, which is exactly the ambiguity this document
             // must not have.
             "</title><style>" + PRINT_CSS + CERT_CSS + (qrHtml && qr ? qr.tableCss(3) : "") + "</style></head><body>"];
    if (!official) h.push('<div class="pgl-draft-band">' + esc(rep.draftBanner) + "</div>");
    h.push(toHtml(rep));
    if (official) {
      h.push('<section class="pgl-cert-seal">');
      h.push("<h2>Verification</h2>");
      h.push('<div class="pgl-cert-seal-grid"><div>');
      h.push("<p><b>This document can be checked independently.</b> Scan the code, or open the link " +
             "below and enter the verification code. StewardMD will show who signed this logbook, " +
             "their medical registration numbers, and whether the record still stands unchanged.</p>");
      h.push('<dl class="pgl-rep-meta">');
      h.push("<dt>Verification code</dt><dd class=\"pgl-mono\">" + esc(code) + "</dd>");
      h.push("<dt>Verify at</dt><dd class=\"pgl-mono\">" + esc(url) + "</dd>");
      h.push("<dt>Content fingerprint</dt><dd class=\"pgl-mono\">" + esc(fingerprint(cert.contentDigest)) + "</dd>");
      h.push("<dt>Entries certified</dt><dd>" + esc(String(cert.entryCount)) + "</dd>");
      h.push("<dt>Issued</dt><dd>" + esc(fmtTs(cert.issuedAt)) + "</dd>");
      h.push("</dl>");
      h.push("</div><div class=\"pgl-cert-qr\">" + qrHtml + '<p class="pgl-mono">' + esc(code) + "</p></div></div>");
      h.push('<p class="pgl-cert-limits"><b>What this verification does and does not mean.</b> ' +
        "StewardMD attests to the content it recorded and to each signatory's medical registration as " +
        "verified against the Indian Medical Register at the time of signing. It does not certify the " +
        "clinical content of any entry, and it is not a determination by the National Medical " +
        "Commission or by any University. " +
        "<b>This is a tamper-evident verifiable document, not a digitally signed one under the " +
        "Information Technology Act, 2000</b> — no Digital Signature Certificate from a licensed " +
        "Certifying Authority is applied to this file. A printed or forwarded copy is only as good as " +
        "the check above: if the two do not agree, trust the StewardMD verification page, not the paper.</p>");
      h.push("</section>");
    }
    h.push("</body></html>");
    return h.join("");
  }

  function fingerprint(d) {
    var t = s(d).toUpperCase();
    if (t.length < 16) return "";
    return t.slice(0, 4) + "-" + t.slice(4, 8) + "-" + t.slice(8, 12) + "-" + t.slice(12, 16);
  }

  var CERT_CSS =
    ".pgl-draft-band{background:#8a1c1c;color:#fff;font:700 13px/1.3 -apple-system,BlinkMacSystemFont,sans-serif;" +
      "padding:10px 12px;border-radius:4px;margin:0 0 16px;letter-spacing:.02em;-webkit-print-color-adjust:exact;print-color-adjust:exact;}" +
    ".pgl-cert-seal{margin-top:26px;border:2px solid #0F766E;border-radius:6px;padding:12px 14px;page-break-inside:avoid;}" +
    ".pgl-cert-seal h2{margin-top:0;border:0;color:#0F766E;}" +
    ".pgl-cert-seal-grid{display:flex;gap:18px;align-items:flex-start;}" +
    ".pgl-cert-seal-grid>div:first-child{flex:1;}" +
    ".pgl-cert-qr{text-align:center;}" +
    ".pgl-cert-qr p{margin:4px 0 0;font-size:10px;}" +
    ".pgl-mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;letter-spacing:.04em;}" +
    ".pgl-cert-limits{font-size:10.5px;color:#444;margin:12px 0 0;line-height:1.5;}";

  /* Export it. Native → a REAL PDF through the existing WKWebView renderer and the share sheet;
   * web → the browser's own print dialog, which offers Save as PDF. One path, because a second PDF
   * engine for a document that is a table would be a dependency we do not need. */
  function exportCertifiedPdf(rep, opts) {
    opts = opts || {};
    var html = certifiedDocHtml(rep, opts);
    var res = ctxResident(opts);
    var name = ("StewardMD-Logbook-" + (res || "record") + (rep.official ? "-certified" : "-DRAFT"))
      .replace(/[^\w.-]+/g, "-");
    var title = rep.official ? "Certified postgraduate logbook" : "Postgraduate logbook (draft)";
    var N = G.SMD_NATIVE;
    if (G.SMD_IS_NATIVE && N && N.sharePdfFromHtml) return N.sharePdfFromHtml(html, name, title);
    if (G.SMD_PDF && G.SMD_PDF.fromHtml) {
      return G.SMD_PDF.fromHtml(html, name, title).catch(function () { return printHtml(html); });
    }
    return Promise.resolve(printHtml(html));
  }
  function ctxResident(opts) { return (opts && opts.residentName) || ""; }
  function printHtml(html) {
    try {
      var w = G.open("", "_blank");
      if (!w) return false;
      w.document.write(html);
      w.document.close();
      setTimeout(function () { try { w.print(); } catch (e) {} }, 350);
      return true;
    } catch (e) { return false; }
  }

  /* ── labels ──────────────────────────────────────────────────────────────── */
  var KIND_LABEL = { clinical: "Clinical", procedure: "Procedure", academic: "Academic",
    research: "Research", certification: "Certification", attendance: "Attendance", reflection: "Reflection" };
  function kindLabel(e) {
    if (e.kind === "clinical") return "Clinical · " + s(e.setting).toUpperCase();
    return KIND_LABEL[e.kind] || s(e.kind);
  }
  function activityLabel(e) {
    var m = M();
    if (e.kind === "procedure") return s(e.procedureText || e.procedureId);
    if (e.kind === "academic") return ((m && m.ACADEMIC_LABEL[e.academicType]) || s(e.academicType)) + (e.topic ? " — " + e.topic : "");
    if (e.kind === "research") return s(e.projectTitle || e.milestone || e.subtype);
    if (e.kind === "certification") return s(e.subtype);
    if (e.kind === "reflection") return s(e.subtype);
    return s(e.title);
  }
  function procLabel(ctx, e) {
    if (e.procedureText) return e.procedureText;
    var cat = arr(ctx.procedureCatalog).filter(function (p) { return p.id === e.procedureId; })[0];
    return cat ? cat.label : s(e.procedureId);
  }
  function roleLabel(e) { var m = M(); return (m && m.ROLE_LABEL[e.role]) || s(e.role); }
  function scopeLabel(x) {
    return { within_department: "Within department", peripheral_posting: "Peripheral posting",
             outside_department: "Outside department", outside_institution: "Outside institution" }[x] || s(x);
  }
  function milestoneLabel(x) {
    return { topic_selected: "Topic selected", guide_allotted: "Guide allotted", protocol_drafted: "Protocol drafted",
             protocol_approved: "Protocol approved", ethics_approval: "Ethics committee approval",
             data_collection: "Data collection", analysis: "Analysis", draft_written: "Draft written",
             submitted: "Thesis submitted", accepted: "Thesis accepted" }[x] || s(x);
  }
  function stateLabel(x) {
    return { met: "Met", on_track: "On track", slightly_behind: "Slightly behind", behind: "Behind",
             in_progress: "In progress", counted: "Counted (no NMC number)", not_started: "Not started" }[x] || s(x);
  }
  function sourceLabel(x) { var c = C(); return c ? c.sourceLabel(x) : s(x); }

  /* ── rendering ───────────────────────────────────────────────────────────────
   * Dumb on purpose: it turns the structure above into HTML and adds nothing. Anything a reader
   * sees was decided by a builder, which is tested. */
  function toHtml(rep, opts) {
    opts = opts || {};
    var h = ['<article class="pgl-report">'];
    h.push('<header class="pgl-rep-head"><h1>' + esc(rep.title) + "</h1>");
    if (rep.subtitle) h.push('<p class="pgl-rep-sub">' + esc(rep.subtitle) + "</p>");
    h.push('<dl class="pgl-rep-meta">');
    arr(rep.meta).forEach(function (m) { h.push("<dt>" + esc(m[0]) + "</dt><dd>" + esc(m[1]) + "</dd>"); });
    h.push("</dl></header>");
    if (rep.verification) {
      var v = rep.verification;
      h.push('<section class="pgl-rep-verif"><h2>Verification status</h2><p>' +
        esc(v.verified + " of " + v.total + " entries verified · " + v.submitted + " awaiting verification · " +
            v.returned + " returned · " + v.draft + " draft" + (v.amended ? " · " + v.amended + " amended (originals retained)" : "")) +
        "</p><p>" + esc(v.monthsAttested + " of " + v.monthsTotal + " months authenticated by the guide" +
          (v.monthsOverdue.length ? " · overdue: " + v.monthsOverdue.join(", ") : "")) + "</p>" +
        "<p>" + esc(v.signedWithRegistration + " of " + v.verified + " verified entries carry the signer's " +
          "medical registration number; " + v.withVerificationCode + " carry a scannable verification code.") + "</p>" +
        '<p class="pgl-rep-clause">' + esc(v.clause) + "</p></section>");
    }
    arr(rep.sections).forEach(function (sec) {
      if (sec.divider) { h.push('<h2 class="pgl-rep-divider">' + esc(sec.heading) + "</h2>"); return; }
      h.push('<section class="pgl-rep-sec"><h2>' + esc(sec.heading) + "</h2>");
      if (sec.provenance) {
        h.push('<p class="pgl-rep-prov">' + esc(sourceLabel(sec.provenance.source)) +
          (sec.provenance.clause ? " · " + esc(sec.provenance.clause) : "") + "</p>");
      }
      if (arr(sec.rows).length) {
        h.push('<div class="pgl-rep-scroll"><table><thead><tr>');
        arr(sec.columns).forEach(function (c) { h.push("<th>" + esc(c) + "</th>"); });
        h.push("</tr></thead><tbody>");
        arr(sec.rows).forEach(function (row) {
          h.push("<tr>");
          arr(row).forEach(function (cell) { h.push("<td>" + esc(cell) + "</td>"); });
          h.push("</tr>");
        });
        h.push("</tbody></table></div>");
      } else {
        h.push('<p class="pgl-rep-empty">Nothing recorded yet.</p>');
      }
      if (sec.note) h.push('<p class="pgl-rep-note">' + esc(sec.note) + "</p>");
      h.push("</section>");
    });
    h.push('<footer class="pgl-rep-foot"><p>' + esc(rep.disclaimer) + "</p></footer>");
    h.push("</article>");
    return h.join("");
  }

  // Print / share. Reuses the browser's own print pipeline (which is also how the native WebView
  // produces a PDF) rather than shipping a PDF library for a document that is a table.
  function print(rep) {
    try {
      var w = G.open("", "_blank");
      if (!w) return false;
      w.document.write("<!doctype html><html><head><meta charset=\"utf-8\"><title>" + esc(rep.title) +
        "</title><style>" + PRINT_CSS + "</style></head><body>" + toHtml(rep) + "</body></html>");
      w.document.close();
      setTimeout(function () { try { w.print(); } catch (e) {} }, 350);
      return true;
    } catch (e) { return false; }
  }
  var PRINT_CSS =
    "body{font:13px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#111;margin:24px;}" +
    "h1{font-size:20px;margin:0 0 2px;}h2{font-size:14px;margin:20px 0 6px;border-bottom:1px solid #ddd;padding-bottom:3px;}" +
    ".pgl-rep-sub{color:#555;margin:0 0 12px;}" +
    ".pgl-rep-meta{display:grid;grid-template-columns:max-content 1fr;gap:2px 14px;margin:0 0 14px;font-size:12px;}" +
    ".pgl-rep-meta dt{color:#666;}.pgl-rep-meta dd{margin:0;font-weight:600;}" +
    "table{border-collapse:collapse;width:100%;font-size:11.5px;}" +
    "th,td{border:1px solid #ccc;padding:4px 6px;text-align:left;vertical-align:top;}" +
    "th{background:#f4f4f4;font-weight:600;}" +
    ".pgl-rep-note,.pgl-rep-prov,.pgl-rep-clause{font-size:11px;color:#555;margin:6px 0 0;}" +
    ".pgl-rep-prov{color:#0F766E;font-weight:600;}" +
    ".pgl-rep-verif{background:#f6f8f8;border:1px solid #dde;padding:8px 10px;border-radius:6px;}" +
    ".pgl-rep-divider{margin-top:28px;font-size:16px;border:0;background:#eee;padding:6px 8px;}" +
    ".pgl-rep-foot{margin-top:24px;font-size:10.5px;color:#666;border-top:1px solid #ddd;padding-top:8px;}" +
    "@media print{body{margin:12mm;}h2{page-break-after:avoid;}tr{page-break-inside:avoid;}}";

  // CSV of one section — the format a department actually re-analyses in a spreadsheet.
  function toCsv(rep, sectionIndex) {
    var sec = arr(rep.sections)[sectionIndex || 0];
    if (!sec) return "";
    function cell(v) { var t = s(v); return /[",\n]/.test(t) ? '"' + t.replace(/"/g, '""') + '"' : t; }
    return [arr(sec.columns).map(cell).join(",")]
      .concat(arr(sec.rows).map(function (r) { return arr(r).map(cell).join(","); })).join("\n");
  }

  var API = {
    residentLogbook: residentLogbook, procedureReport: procedureReport, clinicalReport: clinicalReport,
    academicReport: academicReport, researchReport: researchReport, assessmentReport: assessmentReport,
    feedbackReport: feedbackReport, rotationReport: rotationReport, progressReport: progressReport,
    departmentSummary: departmentSummary, finalPortfolio: finalPortfolio,
    certifiedLogbook: certifiedLogbook, certifiedDocHtml: certifiedDocHtml,
    exportCertifiedPdf: exportCertifiedPdf, certificationSection: certificationSection,
    fingerprint: fingerprint,
    toHtml: toHtml, toCsv: toCsv, print: print,
    verificationBlock: verificationBlock, DISCLAIMER: DISCLAIMER,
    // exported for the screens' own labelling
    kindLabel: kindLabel, activityLabel: activityLabel, roleLabel: roleLabel,
    milestoneLabel: milestoneLabel, stateLabel: stateLabel, scopeLabel: scopeLabel, person: person,
    ALL: ["resident_logbook", "rotation_report", "procedure_report", "clinical_report",
          "academic_report", "assessment_report", "feedback_report", "research_report",
          "progress_report", "department_summary", "final_portfolio", "certified_logbook"]
  };

  if (typeof module !== "undefined" && module.exports) module.exports = API;
  if (typeof window !== "undefined") window.SMD_PGLOG_REPORTS = API;
})();
