/* PrepNucleus Cards: module flashcards (front/back, cloze, image occlusion) on the same FSRS memory as the questions.
   window.PREP_FLASH. ES5. Loaded by prep-loader.js after prep.js and drawn through PREP._host (the same overlay, back
   stack and store). prep.js forwards every data-act starting "k-" here, asks back() first on back and calls leave() on
   close. (prep-cards.js is the older Layer C deck reviewer; this file is the module Cards of Plan 2.)

   Data: prep/cards/v1/index.json { v, modules: { <module>: { n, gen } } } and prep/cards/v1/<module>.json
   { v: 1, module, cards: [card] }. A card is { id, kind, fr, bk, src: { item?, kb? }, gen } where kind is
   "basic" (fr is a question, bk the answer), "cloze" (fr is a statement with exactly one {{hidden term}}, bk adds a
   short why) or "occl" ({ img, boxes: [{ x, y, w, h, label }] } in fractions of the image; fr is the prompt).
   Generated by tools/prep-cards.mjs (gates there) or by hand (gen "hand").

   Memory: FSRS-6 through specialty-core.js in the PrepNucleus store, deck key "p:<module>:c", so a card's key is
   "p:<module>:c:<cardId>": recall() over "p:<module>" sees questions and cards together (readiness, weak areas),
   while prep.js progressByModule skips card keys so MCQ counts stay MCQ counts. Store: fc = { cap, day, n, more }
   (new cards a day, default 20; new cards started today; extra allowed today). Pure helpers load under node. */
(function (G) {
  "use strict";
  // Bound once per element and site; a later call swaps the handler (prep.js PREP_DOM.on: a patched repaint keeps nodes).
  function ON(el, site, type, fn, opts) { if (G.PREP_DOM && G.PREP_DOM.on) return G.PREP_DOM.on(el, site, type, fn, opts); el.addEventListener(type, fn, opts); }

  /* ================= pure ================= */
  var KINDS = ["basic", "cloze", "occl"];
  var LIM = { fr: 25, bk: 40, cards: 60, boxes: [1, 8] };
  var CAP_DEFAULT = 20, CAPS = [10, 20, 30, 50];
  var ID_RE = /^[a-z0-9][a-z0-9-]{0,39}$/;
  var IMG_RE = /^prep\/lessons\/media\/[a-z0-9-]+\.(?:svg|webp|png)$/;
  var CLOZE_RE = /\{\{([^{}]+)\}\}/g;
  var GRADES = [{ g: 1, k: "again", label: "Again" }, { g: 2, k: "hard", label: "Hard" }, { g: 3, k: "good", label: "Good" }, { g: 4, k: "easy", label: "Easy" }];

  function str(s) { return s == null ? "" : String(s); }
  function words(s) { var t = str(s).trim(); return t ? t.split(/\s+/).length : 0; }
  function nonEmpty(s) { return typeof s === "string" && s.trim().length > 0; }
  function clozeCount(fr) { var m = str(fr).match(CLOZE_RE); return m ? m.length : 0; }
  /* clozeParts("A {{b}} c") -> { pre: "A ", term: "b", post: " c" } (first blank). */
  function clozeParts(fr) {
    var s = str(fr), m = /\{\{([^{}]+)\}\}/.exec(s);
    return m ? { pre: s.slice(0, m.index), term: m[1], post: s.slice(m.index + m[0].length) } : { pre: s, term: "", post: "" };
  }
  function plainFront(c) { return c && c.kind === "cloze" ? str(c.fr).replace(CLOZE_RE, "$1") : str(c && c.fr); }
  function deckKey(mid) { return "p:" + mid + ":c"; }
  /* cardKeyModule("p:sur-x:c:c01") -> "sur-x"; null for any other key. */
  function cardKeyModule(k) { var p = str(k).split(":"); return p.length === 4 && p[0] === "p" && p[2] === "c" ? p[1] : null; }
  function normText(s) { return str(s).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); }
  /* frontSim(a, b) -> token Jaccard of the two fronts after normalising (cloze braces dropped). */
  function frontSim(a, b) {
    var A = {}, B = {}, na = 0, nb = 0, inter = 0, k;
    normText(str(a).replace(CLOZE_RE, "$1")).split(" ").forEach(function (w) { if (w && !A[w]) { A[w] = 1; na++; } });
    normText(str(b).replace(CLOZE_RE, "$1")).split(" ").forEach(function (w) { if (w && !B[w]) { B[w] = 1; nb++; } });
    if (!na && !nb) return 1;
    for (k in A) if (B[k]) inter++;
    return inter / (na + nb - inter);
  }
  /* checkCard(card) -> [problems]; [] = drawable. */
  function checkCard(c) {
    var p = [];
    if (!c || typeof c !== "object") return ["not a card"];
    if (!ID_RE.test(str(c.id))) p.push("id must be 1 to 40 lower-case letters, digits or -");
    if (KINDS.indexOf(c.kind) < 0) return p.concat(["kind must be basic, cloze or occl"]);
    if (!nonEmpty(c.fr)) p.push("no front");
    else if (words(plainFront(c)) > LIM.fr) p.push("front is " + words(plainFront(c)) + " words (25 at most)");
    if (c.kind !== "occl" && !nonEmpty(c.bk)) p.push("no back");
    if (c.bk != null && words(c.bk) > LIM.bk) p.push("back is " + words(c.bk) + " words (40 at most)");
    if (c.kind === "basic" && !/\?\s*$/.test(str(c.fr))) p.push("a basic front must be a question");
    if (c.kind === "basic" && clozeCount(c.fr)) p.push("a basic front has no {{blank}}");
    if (c.kind === "cloze" && clozeCount(c.fr) !== 1) p.push("a cloze front needs exactly one {{blank}}");
    if (c.kind !== "cloze" && /\{\{|\}\}/.test(str(c.fr))) p.push("stray braces");
    if (c.kind === "occl") {
      if (!IMG_RE.test(str(c.img))) p.push("occlusion image must be cleared in-app media (prep/lessons/media)");
      var b = c.boxes;
      if (!Array.isArray(b) || b.length < LIM.boxes[0] || b.length > LIM.boxes[1]) p.push("occlusion needs 1 to 8 boxes");
      else b.forEach(function (x, i) {
        var ok = x && [x.x, x.y, x.w, x.h].every(function (v) { return typeof v === "number" && v >= 0 && v <= 1; }) && x.w > 0 && x.h > 0 && x.x + x.w <= 1.0001 && x.y + x.h <= 1.0001;
        if (!ok) p.push("box " + (i + 1) + " must sit inside the image (fractions 0 to 1)");
        if (!x || !nonEmpty(x.label)) p.push("box " + (i + 1) + " needs a label");
      });
    }
    var s = c.src;
    if (!s || typeof s !== "object" || !(nonEmpty(s.item) || nonEmpty(s.kb))) p.push("src needs a bank item id or a KB doc id");
    if (c.gen !== "AI" && c.gen !== "hand") p.push('gen must be "AI" or "hand"');
    return p;
  }
  /* checkDeck(deck) -> [problems]; [] = drawable. */
  function checkDeck(d) {
    var p = [];
    if (!d || d.v !== 1) return ["not a v1 deck"];
    if (!nonEmpty(d.module)) p.push("module is required");
    if (!Array.isArray(d.cards) || !d.cards.length || d.cards.length > LIM.cards) return p.concat(["a deck has 1 to 60 cards"]);
    var seen = {};
    d.cards.forEach(function (c, i) {
      checkCard(c).forEach(function (x) { p.push("card " + (i + 1) + ": " + x); });
      if (c && seen[c.id]) p.push("card " + (i + 1) + ": duplicate id " + c.id);
      if (c) seen[c.id] = 1;
    });
    return p;
  }

  /* ---- scheduling (C = specialty-core.js) ---- */
  function newToday(store, today) { var f = store.fc || {}; return f.day === today ? f.n || 0 : 0; }
  function capOf(store) { var f = store.fc || {}; return CAPS.indexOf(f.cap) >= 0 ? f.cap : CAP_DEFAULT; }
  function newLeft(store, today) { var f = store.fc || {}; return Math.max(0, capOf(store) + (f.day === today ? f.more || 0 : 0) - newToday(store, today)); }
  /* deckCounts(cards, mid, store, today, C) -> { total, seen, due, fresh } for one module deck. */
  function deckCounts(cards, mid, store, today, C) { return C.counts({ id: deckKey(mid), items: cards || [] }, store, today); }
  /* session(cards, mid, store, today, C, rnd) -> cards: due first (least remembered first), then new ones up to what
     today's new-card allowance leaves. Every due card comes, however many. */
  function session(cards, mid, store, today, C, rnd) {
    var n = deckCounts(cards, mid, store, today, C), left = newLeft(store, today);
    var size = n.due + Math.min(left, n.fresh);
    if (!size) return [];
    // New cards keep the deck's order (the generator writes them in teaching order).
    var due = C.buildSession({ id: deckKey(mid), items: cards }, store, today, { size: n.due || 1, newCap: 0, rnd: rnd }).slice(0, n.due);
    var fresh = cards.filter(function (c) { return !store.cards[C.key(deckKey(mid), c.id)]; }).slice(0, Math.min(left, n.fresh));
    return due.concat(fresh);
  }
  /* dueByModule(store, today) -> { <module>: n } for every card key due today or before. */
  function dueByModule(store, today) {
    var out = {};
    for (var k in store.cards) { var m = cardKeyModule(k); if (m && store.cards[k][3] <= today) out[m] = (out[m] || 0) + 1; }
    return out;
  }
  function hasCards(store) { for (var k in store.cards) if (cardKeyModule(k)) return true; return false; }
  /* intervalFor(store, mid, id, g, today, C) -> days until the card would be due after grade g (what review() writes). */
  function intervalFor(store, mid, id, g, today, C) {
    var c = store.cards[C.key(deckKey(mid), id)], mem = c ? { d: c[0], s: c[1] } : null;
    if (g === C.AGAIN) return 1;
    return C.intervalDays(C.nextState(mem, c ? Math.max(0, today - c[2]) : 0, g).s);
  }
  function fmtIvl(d) {
    if (d < 30) return d + "d";
    if (d < 365) { var m = d / 30; return (m < 10 ? Math.round(m * 10) / 10 : Math.round(m)) + "mo"; }
    return Math.round(d / 36.5) / 10 + "y";
  }
  function ivlWords(d) { return d === 1 ? "1 day" : d < 30 ? d + " days" : d < 365 ? "about " + Math.round(d / 30) + " months" : "about " + Math.round(d / 36.5) / 10 + " years"; }
  /* grade(store, mid, id, g, today, C) -> the card row; counts a first-ever review toward today's new cards. */
  function grade(store, mid, id, g, today, C) {
    var fresh = !store.cards[C.key(deckKey(mid), id)];
    var row = C.review(store, deckKey(mid), id, g, today);
    if (fresh) {
      var f = store.fc || (store.fc = { cap: CAP_DEFAULT, day: today, n: 0, more: 0 });
      if (f.day !== today) { f.day = today; f.n = 0; f.more = 0; }
      f.n++;
    }
    return row;
  }
  /* nextDue(store, mids, today) -> { day, n } for the earliest card due after today across these modules; null if none. */
  function nextDue(store, mids, today) {
    var want = {}, best = null, n = 0;
    (mids || []).forEach(function (m) { want[m] = 1; });
    for (var k in store.cards) {
      var m = cardKeyModule(k), d = store.cards[k][3];
      if (!m || !want[m] || d <= today) continue;
      if (best == null || d < best) { best = d; n = 1; } else if (d === best) n++;
    }
    return best == null ? null : { day: best, n: n };
  }
  /* swipeGrade(dx, dy, ms) -> 1 (Again, left), 3 (Good, right), 4 (Easy, up) or 0: past 96 px, or a flick over
     0.11 px/ms and 24 px, and clearly along one axis. Down is never a grade. */
  function swipeGrade(dx, dy, ms) {
    var ax = Math.abs(dx), up = -dy, d, g;
    if (up > 0 && up >= 1.4 * ax) { d = up; g = 4; }
    else if (ax >= 1.4 * Math.abs(dy)) { d = ax; g = dx < 0 ? 1 : 3; }
    else return 0;
    if (d < 24 || (d < 96 && !(ms > 0 && d / ms > 0.11))) return 0;
    return g;
  }

  /* Bundled index (pilot files in the app) + bank index (generated, from R2 through /api/prep/bank): the bank copy
     wins, except a hand-written bundled file ("gen":"hand") always wins for its module. Each entry says where its
     file lives ("from": "app" or "bank"). */
  function mergeIx(app, bank) {
    var out = {}, a = (app && app.modules) || {}, b = (bank && bank.modules) || {}, m, k, e;
    for (m in b) { e = { from: "bank" }; for (k in b[m]) e[k] = b[m][k]; out[m] = e; }
    for (m in a) if (!out[m] || a[m].gen === "hand") { e = { from: "app" }; for (k in a[m]) e[k] = a[m][k]; out[m] = e; }
    return { v: 1, modules: out };
  }
  var PURE = { mergeIx: mergeIx, KINDS: KINDS, LIM: LIM, CAPS: CAPS, CAP_DEFAULT: CAP_DEFAULT, ID_RE: ID_RE, IMG_RE: IMG_RE, GRADES: GRADES, words: words, clozeCount: clozeCount,
    clozeParts: clozeParts, plainFront: plainFront, deckKey: deckKey, cardKeyModule: cardKeyModule, frontSim: frontSim, checkCard: checkCard, checkDeck: checkDeck,
    newToday: newToday, newLeft: newLeft, capOf: capOf, deckCounts: deckCounts, session: session, dueByModule: dueByModule, hasCards: hasCards,
    intervalFor: intervalFor, fmtIvl: fmtIvl, ivlWords: ivlWords, grade: grade, nextDue: nextDue, swipeGrade: swipeGrade };
  if (typeof module !== "undefined" && module.exports && !(G && G.document)) { module.exports = PURE; return; }

  /* ================= app ================= */
  var BASE = G.SMD_PREP_CARDS_BASE || (G.SMD_PREP_BASE || "/prep/") + "cards/";
  var VER = "v1";
  var K = { ix: null, ixP: null, mem: {}, run: null, view: null, keys: false };
  var host = null;

  function escH(s) { return str(s).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function getJSON(url) { return G.fetch(url, { cache: "no-cache" }).then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); }); }
  // Generated cards live in R2: /api/prep/bank/v1/cards/... (the same API base as the bank, so tests can point it at fixtures).
  function api() { return ((host && host.bankApi) || G.SMD_PREP_BANK_API || "/api/prep/bank/") + VER + "/cards/"; }
  // The network copy, else the IndexedDB copy (offline); null when neither.
  function fresh(url, key) {
    return getJSON(url).then(function (x) { if (host && host.cachePut) host.cachePut(key, x); return x; }, function () {
      return host && host.cacheGet ? host.cacheGet(key).then(null, function () { return null; }) : null;
    });
  }
  function index() {
    if (K.ix) return Promise.resolve(K.ix);
    if (K.ixP) return K.ixP;
    K.ixP = Promise.all([fresh(BASE + VER + "/index.json", "cards/" + VER + "/index.json"), fresh(api() + "index.json", VER + "/cards/index.json")])
      .then(function (r) { K.ix = mergeIx(r[0], r[1]); K.ixP = null; return K.ix; });
    return K.ixP;
  }
  // Bundled file: memory, then the shipped file (refreshing the IndexedDB copy), then IndexedDB when offline.
  function appFile(mid) {
    var key = "cards/" + VER + "/" + mid + ".json";
    return getJSON(BASE + VER + "/" + encodeURIComponent(mid) + ".json").then(function (f) { if (host.cachePut) host.cachePut(key, f); return f; }, function (e) {
      return (host.cacheGet ? host.cacheGet(key) : Promise.resolve(null)).then(function (hit) { if (!hit) throw e; return hit; });
    });
  }
  // Bank file: immutable once uploaded, so IndexedDB first (like the bank's module files), then the API; the bundled
  // file when the bank one cannot be had (offline before first open, or a 404).
  function bankFile(mid) {
    var key = VER + "/cards/" + mid + ".json";
    return (host.cacheGet ? host.cacheGet(key).then(null, function () { return null; }) : Promise.resolve(null)).then(function (hit) {
      return hit || getJSON(api() + encodeURIComponent(mid) + ".json").then(function (f) { if (host.cachePut) host.cachePut(key, f); return f; });
    }).then(null, function () { return appFile(mid); });
  }
  function deckFile(mid) {
    if (K.mem[mid]) return Promise.resolve(K.mem[mid]);
    return index().then(function (ix) { var m = ix.modules[mid]; return m && m.from === "bank" ? bankFile(mid) : appFile(mid); }).then(function (f) {
      // A bad card is dropped, not the deck.
      var cards = (f && Array.isArray(f.cards) ? f.cards : []).filter(function (c) { return !checkCard(c).length; });
      if (!cards.length) throw new Error("empty deck");
      return (K.mem[mid] = { module: f.module, cards: cards });
    });
  }
  function store() { var s = host.store(); if (!s.fc) s.fc = { cap: CAP_DEFAULT, day: 0, n: 0, more: 0 }; return s; }
  function C() { return host.core(); }
  function haptic() { try { if (G.SMD_HAPTICS && G.SMD_HAPTICS.selection) G.SMD_HAPTICS.selection(); } catch (e) {} }
  function reduced() { try { return G.matchMedia && G.matchMedia("(prefers-reduced-motion: reduce)").matches; } catch (e) { return false; } }
  function rootEl() { return host && host.root && host.root(); }
  function q(sel) { var r = rootEl(); return r ? r.querySelector(sel) : null; }

  var ICO = {
    cards: '<rect x="3" y="7" width="14" height="13" rx="2"/><path d="M7 4h12a2 2 0 0 1 2 2v11"/>',
    eye: '<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>'
  };
  function ic(n) { return ICO[n] ? '<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">' + ICO[n] + "</svg>" : host.ico(n); }

  /* ---------- drawing ---------- */
  function curCard() { var r = K.run; return r && r.list[r.i]; }
  // Cloze: the hidden term keeps its width (no reflow on reveal) but is invisible and silent until shown.
  function frontHtml(c, shown) {
    if (c.kind === "cloze") {
      var p = clozeParts(c.fr);
      return '<p class="pk-fr">' + escH(p.pre) + '<span class="pk-gap"><span class="pk-gap-t"' + (shown ? "" : ' aria-hidden="true"') + ">" + escH(p.term) + "</span>" + (shown ? "" : '<span class="pn-sr">blank</span>') + "</span>" + escH(p.post) + "</p>";
    }
    return '<p class="pk-fr">' + escH(c.fr) + "</p>";
  }
  function occlHtml(c, r) {
    return '<div class="pk-occ"><img src="/' + escH(c.img) + '" alt="Diagram with ' + c.boxes.length + ' hidden labels" decoding="async">' +
      c.boxes.map(function (b, i) {
        var on = !!r.rev[i];
        return '<button type="button" class="pk-box' + (on ? " on" : "") + '" data-act="k-box" data-i="' + i + '" aria-pressed="' + on + '" aria-label="' + (on ? "Label " + (i + 1) + ": " + escH(b.label) : "Hidden label " + (i + 1) + ", reveal") + '" style="left:' + (b.x * 100).toFixed(2) + "%;top:" + (b.y * 100).toFixed(2) + "%;width:" + (b.w * 100).toFixed(2) + "%;height:" + (b.h * 100).toFixed(2) + '%"></button>';
      }).join("") + "</div>";
  }
  // The next cards peek from under the current one (blank backs: nothing of the next card is given away).
  function stackHtml(r) {
    var left = r.list.length - r.i - 1;
    return '<div class="pk-stack" id="pkStack">' + (left > 1 ? '<div class="pk-peek p2" aria-hidden="true"></div>' : "") + (left > 0 ? '<div class="pk-peek p1" aria-hidden="true"></div>' : "") + cardHtml(r) + "</div>";
  }
  function cardHtml(r) {
    var c = curCard(), shown = r.shown, enter = r.enter ? " in" : "";
    r.enter = false;
    if (c.kind === "occl") {
      return '<section class="pk-card pk-plain' + enter + '" id="pkCard" aria-label="Card ' + (r.i + 1) + '">' +
        '<p class="pk-fr pk-fr-s">' + escH(c.fr) + "</p>" + occlHtml(c, r) +
        '<div class="pk-bk-w' + (shown ? " on" : "") + '" id="pkBack" tabindex="-1">' + (c.bk ? '<p class="pk-bk">' + escH(c.bk) + "</p>" : "") + "</div></section>";
    }
    if (c.kind === "cloze") {
      return '<section class="pk-card pk-plain pk-cloze' + (shown ? " on" : "") + enter + '" id="pkCard" aria-label="Card ' + (r.i + 1) + '"' + (shown ? "" : ' data-act="k-flip"') + ">" +
        frontHtml(c, shown) + '<div class="pk-bk-w' + (shown ? " on" : "") + '" id="pkBack" tabindex="-1"><p class="pk-bk">' + escH(c.bk) + "</p></div></section>";
    }
    return '<section class="pk-card pk-flip' + (shown ? " on" : "") + enter + '" id="pkCard" aria-label="Card ' + (r.i + 1) + '"' + (shown ? "" : ' data-act="k-flip"') + ">" +
      '<div class="pk-face pk-front"' + (shown ? ' aria-hidden="true"' : "") + ">" + frontHtml(c) + '<p class="pk-tap">Tap to turn over</p></div>' +
      '<div class="pk-face pk-back" id="pkBack" tabindex="-1"' + (shown ? "" : ' aria-hidden="true"') + '><p class="pk-q">' + escH(c.fr) + '</p><p class="pk-bk">' + escH(c.bk) + "</p></div></section>";
  }
  function barHtml(r) {
    var c = curCard();
    if (!r.shown) {
      var occ = c.kind === "occl";
      return '<div class="pk-bar" id="pkBar"><button type="button" class="pn-btn pri pk-show" data-act="k-flip">' + (occ ? ic("eye") + " Reveal all" : "Show answer") + '<kbd class="pk-kbd" aria-hidden="true">Space</kbd></button></div>';
    }
    var s = store(), today = host.today();
    // Ask MaiK (prep-ask.js) about the turned card: on this phone or online, from the card's own two sides.
    var ask = G.PREP_ASK && c.kind !== "occl" ? '<button type="button" class="pn-link pk-ask" data-act="k-ask">' + (function () { var M = G.SMD_MAIK_MARK, m = M ? M.html("tile", { size: 28 }) : ""; return '<span class="pt-av' + (m ? " mk" : "") + '" aria-hidden="true">' + m + "</span>"; })() + (G.SMD_MAIK_MARK ? G.SMD_MAIK_MARK.label("Ask MaiK about this card") : "Ask MaiK about this card") + '</button>' : "";
    return '<div class="pk-bar" id="pkBar">' + ask + '<div class="pk-grades" role="group" aria-label="How well did you remember it?">' + GRADES.map(function (x) {
      var d = intervalFor(s, c._m, c.id, x.g, today, C());
      return '<button type="button" class="pk-g pk-' + x.k + '" data-act="k-grade" data-g="' + x.g + '" aria-label="' + x.label + ", next in " + ivlWords(d) + '"><b>' + x.label + "</b><small>" + fmtIvl(d) + '</small><kbd class="pk-kbd" aria-hidden="true">' + x.g + "</kbd></button>";
    }).join("") + "</div></div>";
  }
  // Session progress: a ring in the bar, the cards left in its centre.
  function progHtml(r) {
    var pct = Math.round(r.i * 100 / r.list.length);
    return '<span class="pk-ring" role="progressbar" aria-label="Cards done" aria-valuemin="0" aria-valuemax="' + r.list.length + '" aria-valuenow="' + r.i + '"><svg viewBox="0 0 40 40" aria-hidden="true"><circle class="rt" cx="20" cy="20" r="16" pathLength="100"/>' +
      '<circle class="rv" cx="20" cy="20" r="16" pathLength="100" stroke-dasharray="' + pct + ' 100"' + (pct ? "" : ' style="opacity:0"') + '/></svg><b aria-hidden="true">' + (r.list.length - r.i) + "</b></span>";
  }
  function runHtml() {
    var r = K.run, c = curCard();
    return host.bar(escH(r.title), "Card " + (r.i + 1) + " of " + r.list.length + (r.relearn[c._m + ":" + c.id] ? " · again" : ""), "back", progHtml(r)) +
      '<div class="pn-body pk-body" id="pkBody">' + stackHtml(r) +
      (r.i === 0 && c.kind !== "occl" ? '<p class="pn-note pk-note">Swipe the answer right for Good, left for Again, up for Easy.</p>' : "") + "</div>" + barHtml(r);
  }
  function endHtml() {
    var r = K.run, s = store(), today = host.today(), mids = r.mids, nd = nextDue(s, mids, today), left = newLeft(s, today), more = r.moreNew;
    var cap = capOf(s), total = r.n[1] + r.n[2] + r.n[3] + r.n[4];
    var when = nd ? (nd.day - today === 1 ? "tomorrow" : "in " + (nd.day - today) + " days") : "";
    return host.bar(escH(r.title), "Session finished", "back") + '<div class="pn-body"><section class="pn-panel pk-end" role="status" tabindex="-1" id="pkEnd">' +
      '<p class="pk-end-n"><b>' + total + "</b> " + (total === 1 ? "card" : "cards") + " reviewed</p>" +
      '<dl class="pk-tally">' + GRADES.map(function (x) { return '<div class="pk-' + x.k + '"><dt>' + x.label + "</dt><dd>" + r.n[x.g] + "</dd></div>"; }).join("") + "</dl>" +
      '<p class="pn-mut">' + (nd ? "Next cards are due " + when + ": " + nd.n + " " + (nd.n === 1 ? "card" : "cards") + "." : "No cards are scheduled yet.") +
      (r.n[1] ? " Cards you marked Again come back tomorrow." : "") + "</p>" +
      (more > 0 ? '<button type="button" class="pn-btn pri" data-act="k-more">Learn ' + Math.min(10, more) + " more new cards</button>" : "") +
      '<button type="button" class="pn-btn' + (more > 0 ? "" : " pri") + '" data-act="back">Done</button></section>' +
      '<section class="pk-cap"><h2 class="pn-h">New cards a day</h2><div class="pn-wrap" role="group" aria-label="New cards a day">' + CAPS.map(function (n) {
        return '<button type="button" class="pn-chip' + (n === cap ? " on" : "") + '" aria-pressed="' + (n === cap) + '" data-act="k-cap" data-v="' + n + '">' + n + "</button>";
      }).join("") + '</div><p class="pn-mut pn-small">' + (left ? left + " new " + (left === 1 ? "card" : "cards") + " left for today. " : "Today's new cards are done. ") + "Due cards always come, whatever this is set to.</p></section></div>";
  }
  function emptyHtml() {
    var r = K.run, s = store(), today = host.today(), nd = nextDue(s, r.mids, today), more = r.moreNew;
    return host.bar(escH(r.title), "Cards", "back") + '<div class="pn-body"><section class="pn-panel pk-end" tabindex="-1" id="pkEnd">' +
      '<p class="pk-end-n"><b>Nothing due</b></p><p class="pn-mut">' + (nd ? "Next cards are due " + (nd.day - today === 1 ? "tomorrow" : "in " + (nd.day - today) + " days") + "." : "") +
      (more > 0 ? " Today's " + capOf(s) + " new cards are done." : "") + "</p>" +
      (more > 0 ? '<button type="button" class="pn-btn pri" data-act="k-more">Learn ' + Math.min(10, more) + " more new cards</button>" : "") +
      '<button type="button" class="pn-btn' + (more > 0 ? "" : " pri") + '" data-act="back">Done</button></section></div>';
  }
  function draw(focus) {
    if (!K.run || !rootEl()) return;
    var r = K.run, done = r.i >= r.list.length;
    if (!r.list.length) return host.paint(emptyHtml(), "#pkEnd");
    host.paint(done ? endHtml() : runHtml(), focus || (done ? "#pkEnd" : null));
    if (!done) { bindSwipe(); ringFrom(r); }
  }

  // The ring moves from the last value it showed (the screen is repainted per card, so a CSS transition cannot).
  function ringFrom(r) {
    var rv = q(".pk-ring .rv"), to = Math.round(r.i * 100 / r.list.length), from = K.ringAt == null ? to : K.ringAt;
    K.ringAt = to;
    if (!rv || from === to || reduced() || !rv.animate) return;
    try { rv.style.opacity = ""; rv.animate([{ strokeDasharray: from + " 100" }, { strokeDasharray: to + " 100" }], { duration: 260, easing: "cubic-bezier(.23, 1, .32, 1)" }); } catch (e) {}
  }

  /* ---------- reveal, grade ---------- */
  function reveal(kb) {
    var r = K.run, c = curCard();
    if (!c || r.shown) return;
    r.shown = true;
    if (c.kind === "occl") c.boxes.forEach(function (b, i) { r.rev[i] = 1; });
    var card = q("#pkCard"), back = q("#pkBack"), bar = q("#pkBar");
    if (!card || !bar) return draw();
    if (kb) card.classList.add("kb");
    card.classList.add("on"); card.removeAttribute("data-act");
    if (c.kind === "occl") Array.prototype.forEach.call(card.querySelectorAll(".pk-box"), function (b, i) { b.classList.add("on"); b.setAttribute("aria-pressed", "true"); b.setAttribute("aria-label", "Label " + (i + 1) + ": " + c.boxes[i].label); });
    var gt = card.querySelector(".pk-gap-t"), gs = card.querySelector(".pk-gap .pn-sr");
    if (gt) gt.removeAttribute("aria-hidden");
    if (gs) gs.parentNode.removeChild(gs);
    var front = card.querySelector(".pk-front");
    if (front) front.setAttribute("aria-hidden", "true");
    if (back) { back.removeAttribute("aria-hidden"); back.classList.add("on"); }
    bar.outerHTML = barHtml(r);
    try { if (back) back.focus({ preventScroll: true }); } catch (e) {}
  }
  function boxTap(i) {
    var r = K.run, c = curCard();
    if (!c || c.kind !== "occl" || r.rev[i]) return;
    r.rev[i] = 1;
    var b = q('.pk-box[data-i="' + i + '"]');
    if (b) { b.classList.add("on"); b.setAttribute("aria-pressed", "true"); b.setAttribute("aria-label", "Label " + (i + 1) + ": " + c.boxes[i].label); }
    if (c.boxes.every(function (x, k) { return r.rev[k]; })) reveal(false);
  }
  function doGrade(g, how, at) {
    var r = K.run, c = curCard();
    if (!c || !r.shown || r.busy) return;
    var s = store(), today = host.today(), key = c._m + ":" + c.id;
    grade(s, c._m, c.id, g, today, C());
    if (G.PrepPro) G.PrepPro.use("cards", { module: c._m });   // PrepNucleus Pro: counts only; the gate is at the batch start
    host.save(); haptic();
    if (!r.relearn[key]) r.n[g]++;
    // An Again comes back once at the end of this session (FSRS same-day step), and tomorrow.
    if (g === 1 && !r.relearn[key]) { r.relearn[key] = 1; r.list.push(c); }
    var card = q("#pkCard"), next = function () { r.busy = false; r.i++; r.shown = false; r.rev = {}; r.enter = how !== "key"; draw(r.i >= r.list.length ? "#pkEnd" : how === "key" ? "#pkCard" : null); };
    if (how === "key" || reduced() || !card) return next();
    // Leave the screen the way the grade points: left for Again, up for Easy, right otherwise. A thrown card carries on
    // from where the finger let go; the card under it is already rising into place.
    r.busy = true;
    var peek = q(".pk-peek.p1"); if (peek) peek.classList.add("up");
    if (at) {
      var w = (rootEl() && rootEl().clientWidth) || 400, h = (rootEl() && rootEl().clientHeight) || 800;
      var tx = g === 4 ? at.x : g === 1 ? -w * 1.15 : w * 1.15, ty = g === 4 ? -h * 0.9 : at.y;
      card.style.transition = "transform 200ms cubic-bezier(.32, .72, 0, 1), opacity 200ms ease-out";
      card.style.transform = "translateX(" + Math.round(tx) + "px) translateY(" + Math.round(ty) + "px) rotate(" + (g === 4 ? 0 : g === 1 ? -10 : 10) + "deg)";
      card.style.opacity = "0";
      card.classList.add(g === 1 ? "out-l" : g === 4 ? "out-u" : "out-r");
    } else card.classList.add(g === 1 ? "out-l" : g === 4 ? "out-u" : "out-r");
    G.setTimeout(next, 190);
  }

  /* ---------- swipe (the answer side only; the left screen edge stays with the system back gesture) ----------
     The card follows the finger in both axes (down is damped: it is not a grade), tilts with the throw, and takes a tint
     and a stamp for the grade a release would give: Again to the left, Good to the right, Easy up. The next card under it
     rises as the throw grows. Crossing the commit line gives one light haptic. A short throw settles back on a spring. */
  var TINT = { 1: ["l", "Again"], 3: ["r", "Good"], 4: ["u", "Easy"] };
  function bindSwipe() {
    var el = q("#pkCard"), r = K.run;
    if (!el || curCard().kind === "occl") return;
    var x0 = 0, y0 = 0, t0 = 0, on = false, moved = false, id = null, dx = 0, dy = 0, armed = 0;
    var peek = q(".pk-peek.p1");
    var layer = function (cls) {
      var n = el.querySelector("." + cls);
      if (!n) { n = G.document.createElement("span"); n.className = cls; n.setAttribute("aria-hidden", "true"); el.appendChild(n); }
      return n;
    };
    var paintDrag = function () {
      var ax = Math.abs(dx), up = -dy, g = up > 0 && up >= 1.4 * ax ? 4 : ax >= 1.4 * Math.abs(dy) ? (dx < 0 ? 1 : 3) : 0;
      var dist = g === 4 ? up : ax, p = Math.min(1, dist / 96), t = TINT[g];
      el.style.transform = "translateX(" + Math.round(dx) + "px) translateY(" + Math.round(dy) + "px) rotate(" + Math.max(-8, Math.min(8, dx * 0.03)).toFixed(2) + "deg)";
      var lab = layer("pk-stamp"), tint = layer("pk-tint");
      if (t) { lab.textContent = t[1]; lab.className = "pk-stamp " + t[0]; tint.className = "pk-tint " + t[0]; }
      lab.style.opacity = t ? String(p) : "0"; tint.style.opacity = t ? String((p * 0.9).toFixed(3)) : "0";
      if (peek) peek.style.transform = "translateY(" + (14 - 14 * p).toFixed(1) + "px) scale(" + (0.94 + 0.06 * p).toFixed(3) + ")";
      var now = t && dist >= 96 ? g : 0;
      if (now && now !== armed) haptic();
      armed = now;
    };
    ON(el, "pk", "pointerdown", function (e) {
      if (!r.shown || r.busy || on || e.pointerType === "mouse" || e.clientX < 28) return;
      on = true; moved = false; id = e.pointerId; x0 = e.clientX; y0 = e.clientY; t0 = Date.now(); dx = dy = 0; armed = 0;
    });
    ON(el, "pk", "pointermove", function (e) {
      if (!on || e.pointerId !== id) return;
      var mx = e.clientX - x0, my = e.clientY - y0;
      if (!moved) {
        if (Math.max(Math.abs(mx), -my) < 8) { if (my > 12 && my > Math.abs(mx)) on = false; return; }
        moved = true; try { el.setPointerCapture(id); } catch (x) {} el.classList.add("drag"); if (peek) peek.classList.add("drag");
      }
      dx = mx; dy = my > 0 ? my * 0.2 : my;
      paintDrag();
    });
    var end = function (e) {
      if (!on || e.pointerId !== id) return;
      on = false;
      if (!moved) return;
      var g = e.type === "pointerup" ? swipeGrade(e.clientX - x0, e.clientY - y0, Date.now() - t0) : 0;
      el.classList.remove("drag"); if (peek) peek.classList.remove("drag");
      if (g) return doGrade(g, "swipe", { x: dx, y: dy });
      var from = el.style.transform;
      if (peek) peek.style.transform = "";
      var lab = el.querySelector(".pk-stamp"), tint = el.querySelector(".pk-tint");
      if (lab) lab.style.opacity = "0"; if (tint) tint.style.opacity = "0";
      if (!(G.PREP_MOTION && G.PREP_MOTION.settle && G.PREP_MOTION.settle(el, from, "translateX(0px) translateY(0px) rotate(0deg)"))) el.style.transform = "";
      else G.setTimeout(function () { if (el.isConnected && !el.classList.contains("drag")) el.style.transform = ""; }, 700);
    };
    ON(el, "pk", "pointerup", end);
    ON(el, "pk", "pointercancel", end);
  }

  /* ---------- keys: Space or Enter shows the answer, 1 to 4 grade. No animation for keys. ---------- */
  function onKey(e) {
    if (!K.run || !host || host.stackTop() !== K.view || K.run.i >= K.run.list.length || e.ctrlKey || e.metaKey || e.altKey) return;
    var t = e.target, tag = t && t.tagName, rt = rootEl();
    if (tag === "INPUT" || tag === "TEXTAREA" || (rt && rt.querySelector(".pn-sheet-wrap"))) return;
    if (!K.run.shown && (e.key === " " || (e.key === "Enter" && !(t && t.closest && t.closest("button"))))) { e.preventDefault(); return reveal(true); }
    if (K.run.shown && /^[1-4]$/.test(e.key)) { e.preventDefault(); return doGrade(Number(e.key), "key"); }
  }
  function keysOn() { var r = rootEl(); if (r && !r.__pkKeys) { r.__pkKeys = 1; r.addEventListener("keydown", onKey); } }

  /* ---------- sessions ---------- */
  function startRun(title, mids, list, moreNew) {
    K.ringAt = null;
    K.run = { title: title, mids: mids, list: list, i: 0, shown: false, rev: {}, n: { 1: 0, 2: 0, 3: 0, 4: 0 }, relearn: {}, enter: true, moreNew: moreNew };
  }
  function newRemaining(decks) {
    var s = store(), n = 0;
    decks.forEach(function (d) { n += deckCounts(d.cards, d.module, s, host.today(), C()).fresh; });
    return n;
  }
  function tag(d) { return d.cards.map(function (c) { var x = {}; for (var k in c) x[k] = c[k]; x._m = d.module; return x; }); }
  // One module deck: due first, then new up to today's allowance.
  function openModule(sid, mid, title, h) {
    host = h; keysOn();
    var loading = function () { host.paint(host.bar("Cards", "", "back") + '<div class="pn-body"><p class="pn-load" role="status">Loading the cards…</p></div>'); };
    var view = function () { draw(); };
    K.view = view; K.loading = loading;
    host.push(loading);
    deckFile(mid).then(function (d) {
      if (host.stackTop() !== loading) return;
      var s = store(), list = session(tag(d), mid, s, host.today(), C());
      startRun(title, [mid], list, Math.max(0, newRemaining([d]) - list.filter(function (c) { return !s.cards[C().key(deckKey(mid), c.id)]; }).length));
      K.run.decks = [d];
      var stk = host.stack(); stk[stk.length - 1] = view;
      draw();
    }, function () {
      if (host.stackTop() !== loading) return;
      host.paint(host.bar("Cards", "", "back") + '<div class="pn-body"><p class="pn-err" role="alert">The cards did not load. Check the connection and try again. A deck opened once works offline.</p><button type="button" class="pn-btn" data-act="k-open" data-s="' + escH(sid) + '" data-m="' + escH(mid) + '">Try again</button></div>');
    });
  }
  // Home "Cards due": every due card across modules, no new ones.
  function openDue(h) {
    host = h; keysOn();
    var s = store(), today = host.today(), by = dueByModule(s, today), mids = Object.keys(by);
    var loading = function () { host.paint(host.bar("Cards due", "", "back") + '<div class="pn-body"><p class="pn-load" role="status">Loading the cards…</p></div>'); };
    var view = function () { draw(); };
    K.view = view; K.loading = loading;
    host.push(loading);
    Promise.all(mids.map(function (m) { return deckFile(m).then(function (d) { return d; }, function () { return null; }); })).then(function (decks) {
      if (host.stackTop() !== loading) return;
      var list = [];
      decks.filter(Boolean).forEach(function (d) {
        list = list.concat(C().buildSession({ id: deckKey(d.module), items: tag(d) }, s, today, { size: by[d.module], newCap: 0 }));
      });
      startRun("Cards due", mids, list, 0);
      var stk = host.stack(); stk[stk.length - 1] = view;
      draw();
    });
  }
  function learnMore() {
    var r = K.run, s = store(), today = host.today(), f = s.fc;
    if (f.day !== today) { f.day = today; f.n = 0; f.more = 0; }
    f.more = (f.more || 0) + 10; host.save();
    var list = [];
    (r.decks || []).forEach(function (d) { list = list.concat(session(tag(d), d.module, s, today, C())); });
    var n = list.length;
    startRun(r.title, r.mids, list, Math.max(0, newRemaining(r.decks || []) - n));
    K.run.decks = r.decks;
    draw();
  }

  /* ---------- public ---------- */
  function entryHtml(sid, mid, title, meta, s) {
    var n = meta.n, today = host.today(), c = s.cards, dk = deckKey(mid), seen = 0, due = 0;
    for (var k in c) if (k.indexOf(dk + ":") === 0) { seen++; if (c[k][3] <= today) due++; }
    var fresh = Math.max(0, n - seen), sub = due ? due + " due" + (fresh ? " · " + fresh + " new" : "") : seen ? (fresh ? fresh + " new · " : "") + "nothing due today" : "Flip, recall, grade yourself";
    return '<div class="pn-group pk-entry"><button type="button" class="pn-row" data-act="k-open" data-s="' + escH(sid) + '" data-m="' + escH(mid) + '" data-t="' + escH(title) + '"><span class="pn-ri" aria-hidden="true">' + ic("cards") +
      "</span><span class=\"pn-rb\"><b>Cards · " + n + "</b><small>" + escH(sub) + "</small></span>" + host.ico("chev") + "</button></div>";
  }
  /* mount(slotEl, sid, mid, h): fills the module screen's cards slot once the index is known (empty when none). */
  function mount(slot, sid, mid, h) {
    host = h;
    if (!slot) return;
    index().then(function (ix) {
      var meta = ix.modules[mid];
      if (!meta || !meta.n || !slot.isConnected) return;
      var t = slot.closest && slot.closest(".pn-root"), h1 = t && t.querySelector(".pn-bar h1");
      slot.innerHTML = entryHtml(sid, mid, h1 ? h1.textContent : "Cards", meta, store());
    });
  }
  /* homeRow(h): "Cards due" in the home's Practise list once the student has studied any card. */
  function homeRow(h) {
    host = h;
    var s = store();
    if (!hasCards(s)) return "";
    var by = dueByModule(s, host.today()), n = 0;
    for (var m in by) n += by[m];
    return host.row("k-due", ic("cards"), "Cards due", n ? n + " due today across " + Object.keys(by).length + (Object.keys(by).length === 1 ? " module" : " modules") : "Nothing due today", n ? "" : ' aria-disabled="true"');
  }
  function act(a, b, h) {
    host = h;
    if (a === "k-open") { if (K.loading && host.stackTop() === K.loading) host.stack().pop(); return openModule(b.getAttribute("data-s"), b.getAttribute("data-m"), b.getAttribute("data-t") || "Cards", h); }
    if (a === "k-due") return openDue(h);
    if (!K.run) return;
    if (a === "k-flip") return reveal(false);
    if (a === "k-ask") { var kc = curCard(); if (kc && G.PREP_ASK) G.PREP_ASK.open({ kind: "card", fr: kc.fr, bk: kc.bk, title: K.run.title }, h); return; }
    if (a === "k-box") return boxTap(Number(b.getAttribute("data-i")));
    if (a === "k-grade") return doGrade(Number(b.getAttribute("data-g")), "tap");
    if (a === "k-more") return learnMore();
    if (a === "k-cap") { var s = store(); s.fc.cap = Number(b.getAttribute("data-v")); host.save(); return draw('[data-act=k-cap][data-v="' + s.fc.cap + '"]'); }
  }
  function back() { return false; }
  function leave() { K.run = null; }

  G.PREP_FLASH = { mount: mount, homeRow: homeRow, act: act, back: back, leave: leave, index: index, _pure: PURE, _k: K };
})(typeof window !== "undefined" ? window : this);
