#!/usr/bin/env python3
"""StewardMD — Government Health Schemes: Telangana Aarogyasri "Surgery/Therapy List
(Consolidated)" adapter. Reads the JSON produced by parse_telangana_rtf.py, emits SQL
matching functions/db/govschemes_schema.sql + migrate_govschemes_hbp_fields.sql, same
shape/chunking convention as ingest_hbp_workbook.py.

Field mapping (no field is invented — anything the source doesn't state is left blank):
  speciality_code/name  <- top-level heading (e.g. "S1"/"GENERAL SURGERY")
  treatment_code/name   <- surgery code + procedure name
  icd_code              <- ICD code column when present (native "-" placeholder kept as "-")
  pre_investigation     <- PREAUTH EVIDENCE column (what's needed before treatment)
  post_investigation    <- CLAIM EVIDENCE column (what's needed to settle the claim)
  eligibility           <- "Reserved for Government hospitals: Yes/No" (this source's own
                            RESERVED FOR GOVERNMENT column - not a rate tier, not preauth_required;
                            no dedicated schema column for it, so it's recorded as an eligibility note)
  rate_tier             <- '' (this source publishes ONE price per procedure, no NABH/tier split
                            unlike the HBP-family workbooks - left blank rather than invented)
  package_code/name, treatment_type, los_days, implant_criteria, stratification_criteria
                         <- not present in this source; left blank/0

Natural key: (speciality_code, treatment_code) - same as every other importer. The source has
2 genuine duplicate codes (S8.3.1, M19.1, each with a different name/amount under the same code) -
first occurrence kept, the rest dropped and reported to stderr AND logged in crawl_logs.detail,
never silently merged/averaged.

Usage: ingest_telangana.py <parsed.json> --source-file <original.txt> > out.sql
"""
import sys, json, time, random, hashlib, argparse, pathlib


def sql_str(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"


def new_id(prefix):
    return f"{prefix}{int(time.time()*1000):x}{''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=6))}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("parsed_json")
    ap.add_argument("--source-file", required=True)
    ap.add_argument("--jurisdiction", default="telangana")
    ap.add_argument("--scheme-id", default="telangana-aarogyasri")
    ap.add_argument("--scheme-name", default="Rajiv Aarogyasri Health Care Trust")
    ap.add_argument("--authority", default="Telangana State Government / Rajiv Aarogyasri Health Care Trust")
    ap.add_argument("--version-label", default="Surgery/Therapy List (Consolidated)")
    a = ap.parse_args()

    d = json.load(open(a.parsed_json, encoding="utf-8"))
    if d["errors"]:
        print(f"NOTE: {len(d['errors'])} source rows dropped (unparseable) — see errors[] "
              f"in {a.parsed_json}, not silently guessed.", file=sys.stderr)

    seen, dupes, recs = set(), [], []
    for r in d["records"]:
        key = (r["speciality_code"], r["treatment_code"])
        if key in seen:
            dupes.append(r)
            continue
        seen.add(key)
        recs.append(r)
    if not recs:
        sys.exit("no rows parsed")

    for r, dropped in [(r, r) for r in dupes]:
        print(f"DUPLICATE dropped: {dropped['treatment_code']} — {dropped['treatment_name']!r} "
              f"(kept the first occurrence of this code)", file=sys.stderr)

    canon = "\n".join("|".join([r["speciality_code"], r["treatment_code"], r["treatment_name"],
                                str(r["package_amount"])]) for r in recs)
    content_hash = hashlib.sha256(canon.encode()).hexdigest()
    now = int(time.time() * 1000)
    src, svid = new_id("gssrc"), new_id("sv")
    p = pathlib.Path(a.source_file)

    o = ["-- Generated by scripts/govschemes/ingest_telangana.py -- DO NOT HAND-EDIT.",
         f"-- Source: {p.name} (RTF supplied by owner; portal has no reachable package master, "
         f"see functions/db/govschemes_verified_sources_batch1.md)",
         f"-- {len(recs)} procedures ({len(dupes)} duplicate codes dropped, "
         f"{len(d['errors'])} unparseable rows dropped), content_hash={content_hash}", ""]
    o.append(f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
             f"({sql_str(a.scheme_id)}, {sql_str(a.jurisdiction)}, {sql_str(a.scheme_name)}, {sql_str(a.authority)}, 'active');")
    o.append(f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
             f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
             f"({sql_str(src)}, {sql_str(a.jurisdiction)}, {sql_str(a.authority)}, '', "
             f"'https://rajivaarogyasri.telangana.gov.in/', 'rtf', '', {now}, 'unverified', 1, {now});")
    o.append(f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
             f"content_hash, status, published_ts, created_ts) VALUES ({sql_str(svid)}, {sql_str(a.scheme_id)}, "
             f"{sql_str(a.version_label)}, {sql_str(src)}, '', {sql_str(content_hash)}, 'draft', 0, {now});")
    o.append("")

    cols = ("id, scheme_version_id, speciality_code, speciality_name, treatment_code, treatment_name, "
            "package_amount, pre_investigation, post_investigation, eligibility, icd_code, rate_tier")
    vals = []
    for r in recs:
        elig = f"Reserved for Government hospitals: {r['reserved_for_government']}"
        vals.append(
            f"({sql_str(new_id('pkg'))}, {sql_str(svid)}, {sql_str(r['speciality_code'])}, "
            f"{sql_str(r['speciality_name'])}, {sql_str(r['treatment_code'])}, {sql_str(r['treatment_name'])}, "
            f"{r['package_amount']}, {sql_str(r['preauth_evidence'])}, {sql_str(r['claim_evidence'])}, "
            f"{sql_str(elig)}, {sql_str(r['icd_code'])}, '')"
        )
    CHUNK = 50
    for i in range(0, len(vals), CHUNK):
        o.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(vals[i:i + CHUNK]) + ";")
    o.append("")
    detail = (f"ingest_telangana.py {p.name}; {len(dupes)} dup codes dropped "
              f"({', '.join(x['treatment_code'] for x in dupes) or 'none'}); "
              f"{len(d['errors'])} unparseable rows dropped")
    o.append(f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
             f"({sql_str(new_id('cl'))}, {now}, {sql_str(src)}, 'new', {sql_str(detail)}, "
             f"{len(recs) + len(dupes) + len(d['errors'])}, {len(recs)});")
    print("\n".join(o))
    print(f"-- telangana: {len(recs)} procedures, {len(dupes)} dupes dropped, "
          f"{len(d['errors'])} unparseable dropped", file=sys.stderr)


if __name__ == "__main__":
    main()
