#!/usr/bin/env python3
"""StewardMD — Government Health Schemes: Uttarakhand SHA "GetSpecDetails" JSON API adapter.

Source: `POST https://sha.uk.gov.in/CMS/GetSpecDetails` body `SPEC_CODE=<code>` for each of the
24 speciality codes listed in functions/db/govschemes_verified_sources_batch2.md (the portal's
own "List Of Package and Rates" modal calls this same endpoint). Returns clean JSON per row
(PKG_CODE, PKG_NAME, PROC_CODE, PROC_NAME, PROC_AMT, SPEC_NAME + a long tail of unrelated
CMS/document-upload fields from a shared response DTO, ignored). This is the safest source shape
this project has ingested so far - PROC_AMT is a plain numeric JSON string, no free-text/layout
position guessing needed at all.

Fetch first (not done by this script - keep the network step separate and inspectable):
  for code in BM MC SV ER MG SG IN MO MM MN SN SO SE SM SB SL MP SS SP ST MR SC SU US; do
    curl -sL -A "Mozilla/5.0" -X POST https://sha.uk.gov.in/CMS/GetSpecDetails \
      -d "SPEC_CODE=$code" -o uk_specs/$code.json; sleep 1; done

Then: ingest_uttarakhand_json.py uk_specs/*.json > out.sql
"""
import sys, re, json, time, random, hashlib, argparse, glob

AMT_RE = re.compile(r"^[0-9,]+(\.[0-9]+)?$")


def money(v):
    s = str(v or "").strip()
    if not s:
        return 0, True
    if not AMT_RE.match(s):
        return 0, False
    return int(round(float(s.replace(",", "")))), True


def sql_str(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"


def new_id(prefix):
    return f"{prefix}{int(time.time()*1000):x}{''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=6))}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json_files", nargs="+")
    ap.add_argument("--jurisdiction", default="uttarakhand")
    ap.add_argument("--scheme-id", default="uttarakhand-sha")
    ap.add_argument("--scheme-name", default="State Health Authority Uttarakhand (Atal Ayushman Uttarakhand)")
    ap.add_argument("--authority", default="State Health Authority Uttarakhand")
    ap.add_argument("--version-label", default="SHA Uttarakhand Package and Rates")
    ap.add_argument("--source-url", default="https://sha.uk.gov.in/CMS/GetDiseaseCovered")
    a = ap.parse_args()

    files = []
    for pat in a.json_files:
        files.extend(sorted(glob.glob(pat)))
    if not files:
        sys.exit("no JSON files matched")

    recs, seen, skipped = [], set(), 0
    for fp in files:
        rows = json.load(open(fp, encoding="utf-8"))
        for r in rows:
            code = str(r.get("PROC_CODE") or "").strip()
            if not code:
                skipped += 1
                continue
            pkg = str(r.get("PKG_CODE") or "").strip()
            key = (pkg, code)
            if key in seen:
                skipped += 1
                continue
            amount, ok = money(r.get("PROC_AMT"))
            if not ok:
                print(f"DROPPED (non-numeric PROC_AMT): {code} = {r.get('PROC_AMT')!r}", file=sys.stderr)
                skipped += 1
                continue
            seen.add(key)
            recs.append({
                "speciality_name": str(r.get("SPEC_NAME") or ""),
                "package_code": pkg,
                "package_name": str(r.get("PKG_NAME") or ""),
                "treatment_code": code,
                "treatment_name": str(r.get("PROC_NAME") or ""),
                "package_amount": amount,
            })
    if not recs:
        sys.exit("no rows parsed")

    canon = "\n".join("|".join([r["package_code"], r["treatment_code"], r["treatment_name"],
                                str(r["package_amount"])]) for r in recs)
    content_hash = hashlib.sha256(canon.encode()).hexdigest()
    now = int(time.time() * 1000)
    src, svid = new_id("gssrc"), new_id("sv")

    o = ["-- Generated by scripts/govschemes/ingest_uttarakhand_json.py -- DO NOT HAND-EDIT.",
         f"-- Source: {a.source_url} (POST /CMS/GetSpecDetails per speciality code, JSON, curl-exact)",
         f"-- {len(recs)} procedures ({skipped} rows skipped), content_hash={content_hash}", ""]
    o.append(f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
             f"({sql_str(a.scheme_id)}, {sql_str(a.jurisdiction)}, {sql_str(a.scheme_name)}, {sql_str(a.authority)}, 'active');")
    o.append(f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
             f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
             f"({sql_str(src)}, {sql_str(a.jurisdiction)}, {sql_str(a.authority)}, {sql_str(a.source_url)}, "
             f"{sql_str(a.source_url)}, 'json', '', {now}, 'unverified', 1, {now});")
    o.append(f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
             f"content_hash, status, published_ts, created_ts) VALUES ({sql_str(svid)}, {sql_str(a.scheme_id)}, "
             f"{sql_str(a.version_label)}, {sql_str(src)}, '', {sql_str(content_hash)}, 'draft', 0, {now});")
    o.append("")

    cols = ("id, scheme_version_id, speciality_name, package_code, package_name, "
            "treatment_code, treatment_name, package_amount, rate_tier")
    vals = [f"({sql_str(new_id('pkg'))}, {sql_str(svid)}, {sql_str(r['speciality_name'])}, "
            f"{sql_str(r['package_code'])}, {sql_str(r['package_name'])}, "
            f"{sql_str(r['treatment_code'])}, {sql_str(r['treatment_name'])}, {r['package_amount']}, '')"
            for r in recs]
    CHUNK = 50
    for i in range(0, len(vals), CHUNK):
        o.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(vals[i:i + CHUNK]) + ";")
    o.append("")
    o.append(f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
             f"({sql_str(new_id('cl'))}, {now}, {sql_str(src)}, 'new', "
             f"{sql_str('ingest_uttarakhand_json.py ' + str(len(files)) + ' speciality files')}, "
             f"{len(recs) + skipped}, {len(recs)});")
    print("\n".join(o))
    print(f"-- uttarakhand: {len(recs)} procedures ({skipped} skipped) from {len(files)} files", file=sys.stderr)


if __name__ == "__main__":
    main()
