#!/usr/bin/env python3
"""StewardMD — Government Health Schemes: Dr. NTR Vaidya Seva Trust (Andhra Pradesh) ingestion.

Parses the source XLSX into normalized SQL matching functions/db/govschemes_schema.sql, as one
new scheme_version. Never mutates any prior version - re-running produces a fresh scheme_version
row with a fresh id every time, per the "government package master = one scheme_version, never
overwritten" rule (see vault/decisions/Decisions.md, 2026-09-02).

GOTCHA: openpyxl.load_workbook() throws TypeError: Fill() takes no arguments on this file (a
malformed stylesheet, not a code bug). Parses the raw XLSX XML instead (zipfile + xml.etree),
handling both shared-string (t="s") and inline-string (t="inlineStr") cells - this file uses
inline strings exclusively. See vault/modules/Government Health Schemes.md.

Usage: python3 scripts/govschemes/ingest_ntr_vaidya_seva.py <path-to-xlsx> > out.sql
"""
import sys
import re
import hashlib
import time
import random
from xml.etree import ElementTree as ET
import zipfile

NS = {"s": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
JURISDICTION_ID = "andhra-pradesh"
SCHEME_ID = "ap-ntr-vaidya-seva"
SCHEME_NAME = "Dr. NTR Vaidya Seva"
AUTHORITY = "Dr. NTR Vaidya Seva Trust"


def col_index(ref):
    letters = re.match(r"([A-Z]+)", ref).group(1)
    n = 0
    for c in letters:
        n = n * 26 + (ord(c) - ord("A") + 1)
    return n - 1


def cellval(c, shared):
    t = c.get("t")
    if t == "inlineStr":
        isnode = c.find("s:is", NS)
        texts = isnode.findall(".//s:t", NS) if isnode is not None else []
        return "".join((t2.text or "") for t2 in texts)
    v = c.find("s:v", NS)
    val = v.text if v is not None else None
    if t == "s" and val is not None:
        return shared[int(val)]
    return val


def parse_rows(path):
    z = zipfile.ZipFile(path)
    shared = []
    if "xl/sharedStrings.xml" in z.namelist():
        root = ET.fromstring(z.read("xl/sharedStrings.xml"))
        for si in root.findall("s:si", NS):
            texts = si.findall(".//s:t", NS)
            shared.append("".join((t.text or "") for t in texts))
    root = ET.fromstring(z.read("xl/worksheets/sheet1.xml"))
    rows = root.findall(".//s:sheetData/s:row", NS)
    out = []
    for r in rows[1:]:  # skip header
        cells = {}
        for c in r.findall("s:c", NS):
            cells[col_index(c.get("r"))] = cellval(c, shared)
        if not cells:
            continue
        out.append({
            "speciality_code": cells.get(0) or "",
            "speciality_name": cells.get(1) or "",
            "treatment_code": cells.get(2) or "",
            "treatment_name": cells.get(3) or "",
            "treatment_type": cells.get(4) or "",
            "package_amount": int(cells.get(5) or 0),
            "rider_amount": int(cells.get(6) or 0),
            "pre_investigation": cells.get(7) or "",
            "post_investigation": cells.get(8) or "",
        })
    return out


def sql_str(s):
    return "'" + str(s).replace("'", "''") + "'"


def new_id(prefix):
    ts = int(time.time() * 1000)
    rand = "".join(random.choices("abcdefghijklmnopqrstuvwxyz0123456789", k=6))
    return f"{prefix}{ts:x}{rand}"


def main():
    if len(sys.argv) < 2:
        print("usage: ingest_ntr_vaidya_seva.py <path-to-xlsx>", file=sys.stderr)
        sys.exit(1)
    path = sys.argv[1]
    rows = parse_rows(path)

    # Content hash over the normalized rows, for change detection on re-import.
    canon = "\n".join(
        "|".join([r["speciality_code"], r["treatment_code"], r["treatment_name"],
                   r["treatment_type"], str(r["package_amount"]), str(r["rider_amount"])])
        for r in rows
    )
    content_hash = hashlib.sha256(canon.encode("utf-8")).hexdigest()

    now_ms = int(time.time() * 1000)
    source_id = new_id("gssrc")
    scheme_version_id = new_id("sv")

    out = []
    out.append("-- Generated by scripts/govschemes/ingest_ntr_vaidya_seva.py -- DO NOT HAND-EDIT.")
    out.append(f"-- Source file: {path}")
    out.append(f"-- {len(rows)} package rows, content_hash={content_hash}")
    out.append("")
    out.append(
        f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
        f"({sql_str(SCHEME_ID)}, {sql_str(JURISDICTION_ID)}, {sql_str(SCHEME_NAME)}, "
        f"{sql_str(AUTHORITY)}, 'active');"
    )
    out.append(
        f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
        f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
        f"({sql_str(source_id)}, {sql_str(JURISDICTION_ID)}, {sql_str(AUTHORITY)}, '', '', "
        f"'xlsx', '', {now_ms}, 'unverified', 1, {now_ms});"
    )
    out.append(
        f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
        f"content_hash, status, published_ts, created_ts) VALUES "
        f"({sql_str(scheme_version_id)}, {sql_str(SCHEME_ID)}, '2026-import-1', {sql_str(source_id)}, "
        f"'', {sql_str(content_hash)}, 'draft', 0, {now_ms});"
    )
    out.append("")

    cols = ("id, scheme_version_id, speciality_code, speciality_name, treatment_code, "
            "treatment_name, treatment_type, package_amount, rider_amount, pre_investigation, "
            "post_investigation")
    batch = []
    for r in rows:
        pid = new_id("pkg")
        vals = (
            f"({sql_str(pid)}, {sql_str(scheme_version_id)}, {sql_str(r['speciality_code'])}, "
            f"{sql_str(r['speciality_name'])}, {sql_str(r['treatment_code'])}, "
            f"{sql_str(r['treatment_name'])}, {sql_str(r['treatment_type'])}, "
            f"{r['package_amount']}, {r['rider_amount']}, {sql_str(r['pre_investigation'])}, "
            f"{sql_str(r['post_investigation'])})"
        )
        batch.append(vals)

    # D1 rejects an over-long single statement (SQLITE_TOOBIG) - 500 rows/statement hit that
    # limit in practice; 50 is comfortably under it.
    CHUNK = 50
    for i in range(0, len(batch), CHUNK):
        chunk = batch[i:i + CHUNK]
        out.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(chunk) + ";")

    out.append("")
    out.append(
        f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
        f"({sql_str(new_id('cl'))}, {now_ms}, {sql_str(source_id)}, 'new', "
        f"'Initial ingestion via ingest_ntr_vaidya_seva.py', {len(rows)}, {len(rows)});"
    )

    print("\n".join(out))
    print(f"-- {len(rows)} rows, {len(batch)} package inserts", file=sys.stderr)


if __name__ == "__main__":
    main()
