#!/usr/bin/env python3
"""StewardMD — Government Health Schemes: Arunachal Pradesh CMAAY package list adapter.

Source: `cmaay.arunachal.gov.in/packageratelist.aspx` (ASP.NET WebForms - POST with
__VIEWSTATE/__EVENTVALIDATION per postback, one postback per category dropdown selection +
one per GridView page). **The source publishes NO amount column at all** - confirmed in
functions/db/govschemes_verified_sources_batch3.md ("codes + names only, NO amounts on the
public page") and by inspecting every row this adapter fetched. This is not a parsing gap to
fix; the owner explicitly accepted codes+disease-names-only for this jurisdiction.

package_amount is set to 0 for every row - NOT because the price is zero, but because none is
published. The public UI's `inr()` formatter already treats amount<=0 as "no amount, render
nothing" (govschemes.js), so this doesn't display as a false "₹0/free" - but rate_tier is set to
an explicit "Amount not published by source" label on every row anyway, so the reason is visible
wherever rate_tier is shown, not just wherever amount is silently blank.

Fetch first (kept separate, not baked into this script - see fetch_arunachal_full.py-equivalent
logic, run once and its JSON output handed to this script): reads JSON list of
[category, package_code, package_name, procedure_code, procedure_name] 5-tuples.

Usage: ingest_arunachal_json.py <rows.json> --source-url <url> > out.sql
"""
import sys, re, json, time, random, hashlib, argparse

CODE_RE = re.compile(r'^[A-Z]{2}[0-9]{3}[A-Z]$')


def sql_str(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"


def new_id(prefix):
    return f"{prefix}{int(time.time()*1000):x}{''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=6))}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("rows_json")
    ap.add_argument("--jurisdiction", default="arunachal-pradesh")
    ap.add_argument("--scheme-id", default="arunachal-cmaay")
    ap.add_argument("--scheme-name", default="Chief Minister's Arogya Arunachal Yojana (CMAAY)")
    ap.add_argument("--authority", default="Directorate of Health Services, Government of Arunachal Pradesh")
    ap.add_argument("--version-label", default="CMAAY Package Rate List (codes/names only)")
    ap.add_argument("--source-url", default="https://cmaay.arunachal.gov.in/packageratelist.aspx")
    a = ap.parse_args()

    rows = json.load(open(a.rows_json, encoding="utf-8"))
    recs, seen, skipped = [], set(), 0
    for r in rows:
        if len(r) != 5:
            skipped += 1
            continue
        speciality_name, package_code, package_name, treatment_code, treatment_name = r
        code = treatment_code.strip()
        if not code:
            skipped += 1
            continue
        if code in seen:
            skipped += 1
            continue
        seen.add(code)
        recs.append({
            "speciality_name": speciality_name.strip(),
            "package_code": package_code.strip(),
            "package_name": package_name.strip(),
            "treatment_code": code,
            "treatment_name": treatment_name.strip(),
        })
    if not recs:
        sys.exit("no rows parsed")

    canon = "\n".join("|".join([r["package_code"], r["treatment_code"], r["treatment_name"]])
                      for r in recs)
    content_hash = hashlib.sha256(canon.encode()).hexdigest()
    now = int(time.time() * 1000)
    src, svid = new_id("gssrc"), new_id("sv")

    o = ["-- Generated by scripts/govschemes/ingest_arunachal_json.py -- DO NOT HAND-EDIT.",
         f"-- Source: {a.source_url} (codes+names only - no amount column exists in this source, "
         f"confirmed in govschemes_verified_sources_batch3.md; owner explicitly accepted this)",
         f"-- {len(recs)} procedures ({skipped} rows skipped: blank/duplicate code), "
         f"content_hash={content_hash}", ""]
    o.append(f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
             f"({sql_str(a.scheme_id)}, {sql_str(a.jurisdiction)}, {sql_str(a.scheme_name)}, {sql_str(a.authority)}, 'active');")
    o.append(f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
             f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
             f"({sql_str(src)}, {sql_str(a.jurisdiction)}, {sql_str(a.authority)}, {sql_str(a.source_url)}, "
             f"{sql_str(a.source_url)}, 'html', '', {now}, 'unverified', 1, {now});")
    o.append(f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
             f"content_hash, status, published_ts, created_ts) VALUES ({sql_str(svid)}, {sql_str(a.scheme_id)}, "
             f"{sql_str(a.version_label)}, {sql_str(src)}, '', {sql_str(content_hash)}, 'draft', 0, {now});")
    o.append("")

    cols = ("id, scheme_version_id, speciality_name, package_code, package_name, "
            "treatment_code, treatment_name, package_amount, rate_tier")
    vals = [f"({sql_str(new_id('pkg'))}, {sql_str(svid)}, {sql_str(r['speciality_name'])}, "
            f"{sql_str(r['package_code'])}, {sql_str(r['package_name'])}, "
            f"{sql_str(r['treatment_code'])}, {sql_str(r['treatment_name'])}, 0, "
            f"{sql_str('Amount not published by source')})" for r in recs]
    CHUNK = 50
    for i in range(0, len(vals), CHUNK):
        o.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(vals[i:i + CHUNK]) + ";")
    o.append("")
    o.append(f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
             f"({sql_str(new_id('cl'))}, {now}, {sql_str(src)}, 'new', "
             f"{sql_str('ingest_arunachal_json.py ' + a.source_url + ' (no amount column in source)')}, "
             f"{len(rows)}, {len(recs)});")
    print("\n".join(o))
    print(f"-- arunachal-pradesh: {len(recs)} procedures ({skipped} skipped), NO amounts (source "
          f"publishes none)", file=sys.stderr)


if __name__ == "__main__":
    main()
