#!/usr/bin/env python3
"""StewardMD — Government Health Schemes: Meghalaya MHIS package master adapter.

Source: mhis.org.in/package-rates/ - three wpDataTables (WordPress plugin), export buttons are
client-side (need the viewer's own browser session/nonce - see govschemes_verified_sources_
batch3.md). The owner exported these directly from their own browser and supplied the files, so
this reads clean, well-formed .xlsx exports (openpyxl works fine - unlike the raw-XML workaround
elsewhere in this project for malformed GOVERNMENT-AUTHORED xlsx; these are wpDataTables' own
Excel export, well-formed).

Two files, two different completeness levels - documented, not glossed over:
  - Package_Rates_OPD.xlsx: 130 rows, SL.No 1-130 - COMPLETE (matches the 130-entry count
    recorded in govschemes_verified_sources_batch3.md).
  - Package_Master_MHIS_VI__IPD.xlsx: 101 rows, SL.No starts at 372 (not 1) - a PARTIAL export,
    one page of the server-side-paginated IPD table (100 rows/page), not the whole table. Loaded
    as-is because partial real data beats none, but `scheme_versions.version_label` and this
    script's stderr both say so plainly - never claim this is the full IPD master.

Usage: ingest_meghalaya_xlsx.py <opd.xlsx> <ipd.xlsx> --source-url <url> > out.sql
"""
import sys, re, time, random, hashlib, argparse
import openpyxl

CODE_RE = re.compile(r'^[A-Z]{2,3}[0-9]{2,4}[A-Z]{1,3}$')


def sql_str(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"


def new_id(prefix):
    return f"{prefix}{int(time.time()*1000):x}{''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=6))}"


def money(v):
    s = re.sub(r"[^\d.]", "", str(v or ""))
    if not s:
        return 0, True
    try:
        return int(round(float(s))), True
    except ValueError:
        return 0, False


def read_sheet(path):
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb[wb.sheetnames[0]]
    header = [str(c.value or "").strip() for c in ws[1]]
    rows = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        if all(v is None for v in r):
            continue
        rows.append(dict(zip(header, r)))
    return rows


def extract(rows, table_label):
    recs, skipped = [], 0
    for r in rows:
        code = str(r.get("Procedure Code") or "").strip()
        if not code:
            skipped += 1
            continue
        amount, ok = money(r.get("Procedure Price"))
        if not ok:
            skipped += 1
            continue
        recs.append({
            "speciality_name": str(r.get("Specialty") or "").strip(),
            "treatment_type": str(r.get("Medical or Surgical") or "").strip(),
            "package_name": str(r.get("Package Name") or "").strip(),
            "treatment_code": code,
            "treatment_name": str(r.get("Procedure Name") or "").strip(),
            "package_amount": amount,
            "los_days": money(r.get("ALoS"))[0],
            "implant_criteria": str(r.get("Implants") or r.get("Implants/Diagnostics") or "").strip(),
            "stratification_criteria": str(r.get("Stratification Options") or "").strip(),
            "pre_investigation": str(r.get("Minimum Documents Required - Pre Authorization") or "").strip(),
            "post_investigation": str(r.get("Minimum Documents Required - Claim Processing") or "").strip(),
            "table": table_label,
        })
    return recs, skipped


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("opd_xlsx")
    ap.add_argument("ipd_xlsx")
    ap.add_argument("--jurisdiction", default="meghalaya")
    ap.add_argument("--scheme-id", default="meghalaya-mhis")
    ap.add_argument("--scheme-name", default="Megha Health Insurance Scheme (MHIS)")
    ap.add_argument("--authority", default="State Health Agency Meghalaya")
    ap.add_argument("--source-url", default="https://mhis.org.in/package-rates/")
    a = ap.parse_args()

    opd_rows = read_sheet(a.opd_xlsx)
    ipd_rows = read_sheet(a.ipd_xlsx)
    opd_recs, opd_skip = extract(opd_rows, "OPD")
    ipd_recs, ipd_skip = extract(ipd_rows, "IPD (PARTIAL - 1 page of a paginated table)")

    seen, recs = set(), []
    for r in opd_recs + ipd_recs:
        if r["treatment_code"] in seen:
            continue
        seen.add(r["treatment_code"])
        recs.append(r)
    if not recs:
        sys.exit("no rows parsed")

    canon = "\n".join("|".join([r["treatment_code"], r["treatment_name"], str(r["package_amount"])])
                      for r in recs)
    content_hash = hashlib.sha256(canon.encode()).hexdigest()
    now = int(time.time() * 1000)
    src, svid = new_id("gssrc"), new_id("sv")

    o = ["-- Generated by scripts/govschemes/ingest_meghalaya_xlsx.py -- DO NOT HAND-EDIT.",
         f"-- Source: {a.source_url} (owner-exported client-side wpDataTables xlsx)",
         f"-- OPD: {len(opd_recs)} procedures ({opd_skip} skipped) - COMPLETE (130-row table)",
         f"-- IPD: {len(ipd_recs)} procedures ({ipd_skip} skipped) - PARTIAL, one page of a "
         f"paginated table (SL.No starts at 372, not 1) - NOT the full IPD master",
         f"-- {len(recs)} total after dedup, content_hash={content_hash}", ""]
    o.append(f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
             f"({sql_str(a.scheme_id)}, {sql_str(a.jurisdiction)}, {sql_str(a.scheme_name)}, {sql_str(a.authority)}, 'active');")
    o.append(f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
             f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
             f"({sql_str(src)}, {sql_str(a.jurisdiction)}, {sql_str(a.authority)}, {sql_str(a.source_url)}, "
             f"{sql_str(a.source_url)}, 'xlsx', '', {now}, 'unverified', 1, {now});")
    o.append(f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
             f"content_hash, status, published_ts, created_ts) VALUES ({sql_str(svid)}, {sql_str(a.scheme_id)}, "
             f"{sql_str('Package Rates OPD (complete) + IPD (partial, 1 page)')}, {sql_str(src)}, '', "
             f"{sql_str(content_hash)}, 'draft', 0, {now});")
    o.append("")

    cols = ("id, scheme_version_id, speciality_name, treatment_type, package_name, treatment_code, "
            "treatment_name, package_amount, los_days, implant_criteria, stratification_criteria, "
            "pre_investigation, post_investigation, rate_tier")
    vals = [f"({sql_str(new_id('pkg'))}, {sql_str(svid)}, {sql_str(r['speciality_name'])}, "
            f"{sql_str(r['treatment_type'])}, {sql_str(r['package_name'])}, {sql_str(r['treatment_code'])}, "
            f"{sql_str(r['treatment_name'])}, {r['package_amount']}, {r['los_days']}, "
            f"{sql_str(r['implant_criteria'])}, {sql_str(r['stratification_criteria'])}, "
            f"{sql_str(r['pre_investigation'])}, {sql_str(r['post_investigation'])}, {sql_str(r['table'])})"
            for r in recs]
    CHUNK = 50
    for i in range(0, len(vals), CHUNK):
        o.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(vals[i:i + CHUNK]) + ";")
    o.append("")
    o.append(f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
             f"({sql_str(new_id('cl'))}, {now}, {sql_str(src)}, 'new', "
             f"{sql_str('ingest_meghalaya_xlsx.py OPD+IPD(partial), owner-supplied exports')}, "
             f"{len(opd_rows) + len(ipd_rows)}, {len(recs)});")
    print("\n".join(o))
    print(f"-- meghalaya: {len(recs)} procedures (OPD {len(opd_recs)} complete + IPD {len(ipd_recs)} "
          f"PARTIAL)", file=sys.stderr)


if __name__ == "__main__":
    main()
