#!/usr/bin/env python3
"""StewardMD — Ingest Tamil Nadu CMCHIS API packages into GovSchemes SQL."""
import urllib.request
import json
import re
import sys
import time
import hashlib
import random
import pathlib

BASE_URL = "https://chtn.cmchistn.com/api/v1/package-rate-master-new/?page={page}&page_size=100"
TOTAL_ITEMS = 4302
PAGE_SIZE = 100
MAX_PAGES = (TOTAL_ITEMS + PAGE_SIZE - 1) // PAGE_SIZE

def new_id(prefix):
    return f"{prefix}{int(time.time()*1000):x}{''.join(random.choices('abcdefghijklmnopqrstuvwxyz0123456789', k=6))}"

def sql_str(s):
    return "'" + str(s if s is not None else "").replace("'", "''") + "'"

def money(v):
    s = re.sub(r"[^\d.]", "", str(v or ""))
    if not s:
        return 0
    try:
        return int(round(float(s)))
    except ValueError:
        return 0

def fetch_all():
    raw_path = pathlib.Path("data/govschemes/raw/tamilnadu_cmchis_package_rates_full.json")
    if raw_path.exists():
        try:
            data = json.loads(raw_path.read_text())
            if len(data) >= TOTAL_ITEMS:
                print(f"Loaded {len(data)} items from cache {raw_path}", file=sys.stderr)
                return data
        except Exception:
            pass

    all_results = []
    headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"}

    for page in range(1, MAX_PAGES + 1):
        url = BASE_URL.format(page=page)
        print(f"Fetching page {page}/{MAX_PAGES}...", file=sys.stderr)
        req = urllib.request.Request(url, headers=headers)
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            results = data.get("results", [])
            all_results.extend(results)
            if not data.get("next"):
                break
        time.sleep(0.05)

    raw_path.write_text(json.dumps(all_results, indent=2))
    print(f"Fetched {len(all_results)} items, saved to {raw_path}", file=sys.stderr)
    return all_results

def main():
    items = fetch_all()
    
    # Process rows
    recs = []
    seen = set()
    for item in items:
        raw_pkg = item.get("package") or ""
        # split on first colon: "CODE : NAME"
        parts = re.split(r"\s*:\s*", raw_pkg, maxsplit=1)
        if len(parts) == 2:
            code, name = parts[0].strip(), parts[1].strip()
        else:
            code = raw_pkg.strip()
            name = raw_pkg.strip()
        
        if not code:
            continue
            
        category = (item.get("category") or "").strip()
        
        # Rate: a1 is standard / lowest tier
        amt = money(item.get("a1"))
        
        # Dedupe key: (speciality_code or '', treatment_code) -> TN has no speciality_code, so ('', code)
        if ("", code) in seen:
            continue
        seen.add(("", code))
        
        recs.append({
            "speciality_code": "",
            "speciality_name": category,
            "package_code": "",
            "package_name": "",
            "treatment_code": code,
            "treatment_name": name,
            "package_amount": amt,
            "rate_tier": "A1",
            "los_days": 0,
            "implant_criteria": "",
            "stratification_criteria": "",
            "icd_code": "",
        })

    canon = "\n".join("|".join([r["speciality_code"], r["treatment_code"], r["treatment_name"],
                                str(r["package_amount"])]) for r in recs)
    content_hash = hashlib.sha256(canon.encode()).hexdigest()
    now = int(time.time() * 1000)
    src, svid = new_id("gssrc"), new_id("sv")
    
    jurisdiction = "tamil-nadu"
    scheme_id = "tamil-nadu-cmchis"
    scheme_name = "Chief Minister's Comprehensive Health Insurance Scheme (CMCHIS)"
    authority = "United India Insurance / Govt of Tamil Nadu"
    version_label = "2022"
    rate_tier = "A1"
    source_url = "https://chtn.cmchistn.com/api/v1/package-rate-master-new/"

    o = [
        f"-- Generated by scripts/govschemes/ingest_tamilnadu.py -- DO NOT HAND-EDIT.",
        f"-- Source: CMCHIS API | rate_tier={rate_tier!r}",
        f"-- {len(recs)} procedures, content_hash={content_hash}",
        ""
    ]
    o.append(f"INSERT OR IGNORE INTO schemes (id, jurisdiction_id, name, authority, status) VALUES "
             f"({sql_str(scheme_id)}, {sql_str(jurisdiction)}, {sql_str(scheme_name)}, {sql_str(authority)}, 'active');")
    o.append(f"INSERT INTO sources (id, jurisdiction_id, authority, url, homepage, document_type, "
             f"document_date, retrieved_ts, verification_status, enabled, created_ts) VALUES "
             f"({sql_str(src)}, {sql_str(jurisdiction)}, {sql_str(authority)}, {sql_str(source_url)}, 'https://www.cmchistn.com/', "
             f"'json', '', {now}, 'verified', 1, {now});")
    o.append(f"INSERT INTO scheme_versions (id, scheme_id, version_label, source_id, effective_date, "
             f"content_hash, status, published_ts, created_ts) VALUES ({sql_str(svid)}, {sql_str(scheme_id)}, "
             f"{sql_str(version_label)}, {sql_str(src)}, '', {sql_str(content_hash)}, 'draft', 0, {now});")
    o.append("")

    cols = ("id, scheme_version_id, speciality_code, speciality_name, package_code, package_name, "
            "treatment_code, treatment_name, package_amount, rate_tier, los_days, implant_criteria, "
            "stratification_criteria, icd_code")
    vals = [f"({sql_str(new_id('pkg'))}, {sql_str(svid)}, {sql_str(r['speciality_code'])}, "
            f"{sql_str(r['speciality_name'])}, {sql_str(r['package_code'])}, {sql_str(r['package_name'])}, "
            f"{sql_str(r['treatment_code'])}, {sql_str(r['treatment_name'])}, {r['package_amount']}, "
            f"{sql_str(rate_tier)}, {r['los_days']}, {sql_str(r['implant_criteria'])}, "
            f"{sql_str(r['stratification_criteria'])}, {sql_str(r['icd_code'])})" for r in recs]
    CHUNK = 50
    for i in range(0, len(vals), CHUNK):
        o.append(f"INSERT INTO packages ({cols}) VALUES\n" + ",\n".join(vals[i:i + CHUNK]) + ";")
    o.append("")
    o.append(f"INSERT INTO crawl_logs (id, ts, source_id, status, detail, rows_in, rows_out) VALUES "
             f"({sql_str(new_id('cl'))}, {now}, {sql_str(src)}, 'new', "
             f"{sql_str('ingest_tamilnadu.py tier=' + rate_tier)}, {len(items)}, {len(recs)});")
             
    out_file = pathlib.Path("data/govschemes/sql/tamilnadu.sql")
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text("\n".join(o) + "\n")
    print(f"Generated {out_file}: {len(recs)} packages", file=sys.stderr)

if __name__ == "__main__":
    main()
