#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — FollowCare AI voice fallback: one-time provisioning.
# ──────────────────────────────────────────────────────────────────────────

HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$HERE/.env"
POD_ID=""

TOTAL_STAGES=8

banner "FollowCare AI voice — one-time setup"

# ── Stage 1: tools + fixed defaults ───────────────────────────────────────
stage "Getting ready"
say "This sets up the AI follow-up CALL feature. You'll paste 4 things from the web"
say "(RunPod, GitHub, Plivo, Gemini); I generate the rest and start the server for you."
note "Nothing is charged until Stage 7 (the GPU), and I ask before that."
if ! command -v jq >/dev/null 2>&1; then
  warn "The tool 'jq' is missing (needed to talk to RunPod)."
  if command -v brew >/dev/null 2>&1 && confirm "Install it now with Homebrew?"; then
    brew install jq
  else
    say "Install jq, then re-run this. (macOS: brew install jq)"; exit 1
  fi
fi
command -v curl >/dev/null 2>&1 || { warn "curl is required"; exit 1; }
# Fixed defaults (no need to ask).
write_env FOLLOWCARE_BASE "https://stewardmd.in/api/followcare"
write_env STT_MODEL "ai4bharat/indic-conformer-600m-multilingual"
write_env TTS_MODEL "ai4bharat/indic-parler-tts"
write_env VOICE_MAX_CONCURRENT "5"
write_env VOICE_AUDIO_FORMAT "mulaw"
write_env VOICE_PUBLIC_BASE ""    # the server derives its own URL from its RunPod id
pause "Got it — continue?"

# ── Stage 2: RunPod API key ───────────────────────────────────────────────
stage "RunPod — API key"
say "RunPod runs the voice AI on a GPU (only while calls are happening)."
open_url "https://www.runpod.io/console/user/settings"
step "Sign in. Scroll to 'API Keys' → '+ Create API Key' → give it Read/Write → Create."
step "Copy the key it shows (starts with a long string)."
ask_secret RUNPOD_API_KEY "Paste your RunPod API key:"
write_env RUNPOD_API_KEY "$RUNPOD_API_KEY"

# ── Stage 3: GitHub token (lets the server download the code) ──────────────
stage "GitHub — access token"
say "The server needs a read-only token to download the StewardMD code."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: 'followcare-voice'. Expiration: 90 days is fine."
step "Resource owner: drmanojkurmana.  Repository access: 'Only select repositories' → StewardMD."
step "Permissions → Repository permissions → Contents → Read-only.  Then 'Generate token'."
step "Copy the token (starts with github_pat_)."
ask_secret GITHUB_TOKEN "Paste the GitHub token:"
write_env GITHUB_TOKEN "$GITHUB_TOKEN"

# ── Stage 4: Plivo credentials ────────────────────────────────────────────
stage "Plivo — phone credentials"
say "Plivo places the actual phone call. Finish buying your number first if you haven't."
open_url "https://console.plivo.com/dashboard/"
step "On the dashboard, find 'Auth ID' and 'Auth Token' (top area). Copy each."
ask PLIVO_AUTH_ID "Paste your Plivo Auth ID:"
ask_secret PLIVO_AUTH_TOKEN "Paste your Plivo Auth Token:"
say "Your Plivo phone number, digits only with country code (e.g. 918031906669):"
ask PLIVO_FROM "Plivo number [Enter for 918031906669]:"
[[ -z "$PLIVO_FROM" ]] && PLIVO_FROM="918031906669"
write_env PLIVO_AUTH_ID "$PLIVO_AUTH_ID"
write_env PLIVO_AUTH_TOKEN "$PLIVO_AUTH_TOKEN"
write_env PLIVO_FROM "$PLIVO_FROM"

# ── Stage 5: Gemini key (understands what the patient says) ───────────────
stage "Gemini — backup API key"
say "Understanding the patient's reply uses your existing Vertex AI first; this key is just a backup."
say "(It makes NO medical decision — it only turns speech into a clear answer.)"
open_url "https://aistudio.google.com/apikey"
step "Click 'Create API key' → copy it."
ask_secret GEMINI_API_KEY "Paste your Gemini API key (backup):"
write_env GEMINI_API_KEY "$GEMINI_API_KEY"

# ── Stage 6: generate the shared service token (no input) ─────────────────
stage "Security token"
say "Generating a secret that lets the voice server talk to StewardMD securely."
if [[ -n "$(_existing FOLLOWCARE_VOICE_SERVICE_TOKEN || true)" ]] && ! confirm "A token already exists — generate a NEW one?"; then
  note "Keeping the existing token."
else
  TOKEN="$( (openssl rand -hex 32 2>/dev/null) || (head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n') )"
  write_env FOLLOWCARE_VOICE_SERVICE_TOKEN "$TOKEN"
  note "Generated — you don't need to remember it."
fi
pause "Continue?"

# ── Stage 7: create the GPU pod (COSTS MONEY) ─────────────────────────────
stage "Start the voice server on RunPod"
warn "This starts a paid GPU (roughly \$0.20–0.40/hour while running). It self-stops when idle."
if confirm "Start it now?"; then
  say "Creating the pod and loading the models (this can take a few minutes on first boot)…"
  if OUT=$(RUNPOD_API_KEY="$RUNPOD_API_KEY" GITHUB_TOKEN="$GITHUB_TOKEN" ENV_FILE="$ENV_FILE" bash "$HERE/runpod.sh" up); then
    printf '%s\n' "$OUT" | grep -E '^(POD_ID|Public URL)' || true
    POD_ID=$(printf '%s\n' "$OUT" | awk '/^POD_ID:/{print $2}')
    if [[ -n "$POD_ID" ]]; then
      write_env RUNPOD_POD_ID "$POD_ID"
      note "Health check (ready in a few min): https://${POD_ID}-8080.proxy.runpod.net/healthz"
    else
      warn "Pod created but I couldn't read its id — check the output above."
      SKIPPED+=("Set RUNPOD_POD_ID in $ENV_FILE and re-run cloudflare step")
    fi
  else
    warn "RunPod deploy failed (see message above). You can re-run this wizard to retry."
    SKIPPED+=("Create the RunPod pod (deploy/runpod.sh up)")
  fi
else
  note "Skipped — re-run this wizard when you're ready to start the GPU."
  SKIPPED+=("Start the RunPod pod (deploy/runpod.sh up)")
fi

# ── Stage 8: wire Cloudflare ──────────────────────────────────────────────
stage "Connect StewardMD (Cloudflare)"
say "Last step: give StewardMD the 3 shared secrets so it can wake the pod at call time."
if [[ -n "$POD_ID" ]] || [[ -n "$(_existing RUNPOD_POD_ID || true)" ]]; then
  warn "A browser window may open to log in to Cloudflare — approve it."
  if confirm "Set the Cloudflare secrets now?"; then
    if RUNPOD_API_KEY="$RUNPOD_API_KEY" ENV_FILE="$ENV_FILE" bash "$HERE/cloudflare.sh"; then
      WRITTEN_SECRET+=("FOLLOWCARE_VOICE_SERVICE_TOKEN" "RUNPOD_API_KEY" "RUNPOD_POD_ID" "GEMINI_API_KEY")
    else
      warn "Cloudflare step failed (login/permissions?). Re-run: bash deploy/cloudflare.sh"
      SKIPPED+=("Set Cloudflare secrets (deploy/cloudflare.sh)")
    fi
  else
    SKIPPED+=("Set Cloudflare secrets (deploy/cloudflare.sh)")
  fi
else
  note "No pod id yet — start the pod (Stage 7) first, then re-run for this step."
  SKIPPED+=("Set Cloudflare secrets (deploy/cloudflare.sh)")
fi

finish
say "What's left (in the StewardMD app):"
step "FollowCare → Voice & ambulance settings → turn ON + set the ambulance number."
step "Do a TEST call to your own phone. (Plivo free trial only calls verified numbers.)"
printf '\n'
