"""Build drug-lexicon.js (window.SMD_DRUG_LEXICON) from data/interaction-rules.json.

Source: the `generics` and `brands` tables of data/interaction-rules.json (openFDA structured product
labelling and the ONC/NLM high-priority DDI list, both U.S. Government works, public domain).
Output is names only: what drug-link.js needs to find and highlight a drug in text.

Rules:
  - plain names only (letters, spaces, hyphens; at most 4 words); chemicals with digits/commas dropped
  - allergen extracts, antivenins and vaccines-of-pollen style entries dropped (not prescribable drugs)
  - salt / form words stripped to add the BASE name too ("amoxicillin anhydrous" -> "amoxicillin",
    "alfentanil hydrochloride" -> "alfentanil"), because the catalogue often only lists the salt
  - bare electrolytes, elements and body substances dropped ("sodium", "potassium", "glucose", "iron"):
    they are lab values far more often than prescriptions, and highlighting "potassium 3.2" is wrong
Usage: python3 scripts/druglink/build-drug-lexicon.py
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..", "..")
src = json.load(open(os.path.join(ROOT, "data", "interaction-rules.json"), encoding="utf-8"))

SALT = ("anhydrous hydrochloride hcl hydrobromide sodium potassium calcium magnesium sulfate sulphate "
        "acetate maleate dimaleate mesylate mesilate besylate besilate tartrate bitartrate citrate "
        "phosphate succinate fumarate hemifumarate dihydrate monohydrate trihydrate hydrate bromide "
        "chloride nitrate lactate gluconate propionate dipropionate valerate butyrate furoate xinafoate "
        "tosylate hyclate pamoate embonate disodium trometamol tromethamine meglumine hydrobromide "
        "monosodium decanoate enanthate cypionate undecanoate palmitate").split()
DROP_PHRASE = re.compile(r"(pollen|allergenic|allergen|extract|antivenin|antivenom|venom|dander|mite|"
                         r"mold|mould|feather|hair|epithelia|smut|weed|grass|tree|dust|insect|food)")
NOT_A_DRUG = set("""sodium potassium calcium magnesium chloride phosphate bicarbonate glucose dextrose
oxygen nitrogen water alcohol ethanol urea iron zinc copper lead gold silver sulfur sulphur iodine
fluoride selenium chromium manganese molybdenum histamine cholesterol protein albumin collagen
starch sucrose lactose fructose glycerin glycerol honey caffeine menthol camphor talc kaolin
petrolatum paraffin lanolin gelatin nickel cobalt rosin""".split())
# Real, commonly prescribed names the catalogue lists only in compound form.
EXTRA = ["insulin", "clavulanate"]

def plain(x):
    return re.fullmatch(r"[a-z][a-z \-]{2,48}", x) and len(x.split()) <= 4

names = set()
for g in src["generics"]:
    g = g.strip().lower()
    if not plain(g) or DROP_PHRASE.search(g):
        continue
    words = g.split()
    base = [w for w in words if w not in SALT]
    for cand in (g, " ".join(base)):
        cand = cand.strip()
        if len(cand) >= 4 and cand not in NOT_A_DRUG and plain(cand):
            names.add(cand)

brands = {}
for b, gen in src["brands"].items():
    b = b.strip().lower(); gen = str(gen).strip().lower()
    # brand keys that are really class shorthands ("acei", "acid reducer", "ppi") are not drug names
    if len(b) < 5 or " " in b or not re.fullmatch(r"[a-z][a-z\-]+", b) or b in NOT_A_DRUG:
        continue
    if gen in names or plain(gen):
        brands[b] = gen
        names.add(gen) if plain(gen) and gen not in NOT_A_DRUG and len(gen) >= 4 else None

names.update(EXTRA)
out = sorted(names)
js = ("/* drug-lexicon.js - window.SMD_DRUG_LEXICON. GENERATED by scripts/druglink/build-drug-lexicon.py\n"
      " * from data/interaction-rules.json (openFDA SPL + ONC/NLM HP-DDI; U.S. Government works, public domain).\n"
      " * Names only, for drug-link.js highlighting. Do not edit by hand; re-run the script. */\n"
      "(function (root) {\n  var L = { version: \"1\", generics: " + json.dumps(out, separators=(",", ":")) +
      ",\n    brands: " + json.dumps(dict(sorted(brands.items())), separators=(",", ":")) + " };\n"
      "  if (typeof module !== \"undefined\" && module.exports) module.exports = L;\n"
      "  if (root) root.SMD_DRUG_LEXICON = L;\n"
      "})(typeof window !== \"undefined\" ? window : null);\n")
open(os.path.join(ROOT, "drug-lexicon.js"), "w", encoding="utf-8").write(js)
print(len(out), "generics,", len(brands), "brands,", len(js), "bytes")
