// scripts/edge/schemas.mjs — calculator schema export + score version map (Edge-Master-Plan A1.7, A1.8).
//
//   node scripts/edge/schemas.mjs           writes edge-schemas.js and vault/plans/edge-data/schemas/calculators.json
//   node scripts/edge/schemas.mjs --check   exits 1 if edge-schemas.js is out of date (test/edge-schemas.test.mjs)
//
// Everything is GENERATED from MEDCALC (calculators.js): titles, descriptions, inputs, units, option
// values and references. The only hand-written part is FAMILIES, the list of calculators a clinician can
// confuse with each other (versions of one score, or one name for two scores). "What differs" is
// computed from the input lists, never authored, so this file makes no clinical claim of its own.
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { ROOT } from "./lib.mjs";

// [family, kind, ids]. kind "versions": the same score revised; "variants": short and long forms or
// population variants; "same-name": different scores that share a name.
export const FAMILIES = [
  ["MELD", "versions", ["meld", "meld_na", "meld3"]],
  ["PHQ (depression)", "variants", ["phq2", "phq9"]],
  ["GAD (anxiety)", "variants", ["gad2", "gad7"]],
  ["AUDIT (alcohol)", "variants", ["auditc", "audit_full"]],
  ["GDS (geriatric depression)", "variants", ["gds15", "gds30"]],
  ["ISS (myeloma staging)", "versions", ["iss_myeloma", "r_iss"]],
  ["IPI (lymphoma)", "versions", ["ipi", "r_ipi"]],
  ["POSSUM (surgical risk)", "versions", ["possum", "p_possum"]],
  ["CHADS (AF stroke risk)", "versions", ["chads2", "chadsvasc"]],
  ["CURB (pneumonia)", "variants", ["curb65", "crb65"]],
  ["SOFA (sepsis)", "variants", ["sofa", "qsofa"]],
  ["Fisher (SAH)", "versions", ["fisher", "modified_fisher"]],
  ["Glasgow Outcome Scale", "versions", ["gos", "gose"]],
  ["GCS", "variants", ["gcs", "gcs_p"]],
  ["Braden (pressure injury)", "variants", ["braden", "braden_q"]],
  ["HOMA", "variants", ["homa_ir", "homa_b"]],
  ["eGFR", "variants", ["ckdepi", "mdrd", "egfr_cysc", "schwartz"]],
  ["QTc", "variants", ["qtc", "qtcf", "qtc_fram", "qtc_hodges"]],
  ["TIMI", "variants", ["timi_nstemi", "timistemi"]],
  ["Wells", "same-name", ["wells_dvt", "wells_pe"]],
  ["NEXUS", "same-name", ["nexus_cspine", "nexus_chest"]],
  ["Hamilton", "same-name", ["hamd", "hama"]],
  ["Framingham", "same-name", ["framingham", "framingham_hf"]]
];

function loadCalcs() {
  const g = { document: { createElement: () => ({ style: {}, setAttribute() {}, appendChild() {} }), addEventListener() {}, head: { appendChild() {} }, body: { classList: { add() {}, remove() {} } } },
    localStorage: { getItem: () => null, setItem() {} }, location: { search: "" }, navigator: {} };
  g.window = g; vm.createContext(g);
  vm.runInContext(fs.readFileSync(path.join(ROOT, "calculators.js"), "utf8"), g, { filename: "calculators.js" });
  return g.MEDCALC;
}

const inputOf = (x) => {
  const o = { id: x.id, label: x.label, type: x.type || "number" };
  if (x.unit) o.unit = x.unit;
  if (x.opts && x.opts.length) o.opts = x.opts.map((p) => ({ v: p.v, t: p.t }));
  return o;
};

export function build() {
  const M = loadCalcs();
  const calculators = M._calcs.map((c) => ({
    id: c.id, title: c.title, cat: c.cat || "", desc: c.desc || "", ref: c.ref || "",
    inputs: (c.inputs || []).map(inputOf)
  }));
  const byId = Object.fromEntries(calculators.map((c) => [c.id, c]));
  const families = FAMILIES.map(([name, kind, ids]) => {
    ids.forEach((id) => { if (!byId[id]) throw new Error(`family ${name}: no calculator "${id}" in calculators.js`); });
    // Compare labels without units or notes in brackets ("Sodium (for MELD-Na)" is "sodium").
    const key = (l) => String(l).toLowerCase().replace(/\(.*?\)/g, " ").replace(/[^a-z0-9]+/g, " ").trim();
    const sets = ids.map((id) => new Set(byId[id].inputs.map((x) => key(x.label))));
    const shared = [...sets[0]].filter((l) => sets.every((s) => s.has(l)));
    return {
      family: name, kind,
      members: ids.map((id, i) => ({
        id, title: byId[id].title, desc: byId[id].desc, ref: byId[id].ref,
        inputs: byId[id].inputs.map((x) => (x.unit ? `${x.label} (${x.unit})` : x.label)),
        only_here: byId[id].inputs.map((x) => x.label).filter((l) => !shared.includes(key(l)))
      })),
      shared_inputs: shared
    };
  });
  const js = `/* edge-schemas.js — score version map (Edge-Master-Plan A1.7). GENERATED by scripts/edge/schemas.mjs from
 * calculators.js: do not edit by hand. Each family lists calculators a request can confuse ("meld" vs
 * "MELD-Na" vs "MELD 3.0"); "only_here" are the inputs that tell the versions apart. Read by
 * SMD_EDGE_SCHEMAS.familyOf(id) / .siblings(id). ES5, no network. */
(function (root) {
  "use strict";
  var FAMILIES = ${JSON.stringify(families, null, 1)};
  var BY_ID = {};
  FAMILIES.forEach(function (f) { f.members.forEach(function (m) { BY_ID[m.id] = f; }); });
  var API = {
    FAMILIES: FAMILIES,
    familyOf: function (id) { return BY_ID[id] || null; },
    siblings: function (id) { var f = BY_ID[id]; return f ? f.members.filter(function (m) { return m.id !== id; }) : []; },
    _version: "1"
  };
  if (root) root.SMD_EDGE_SCHEMAS = API;
  if (typeof module !== "undefined" && module.exports) module.exports = API;
})(typeof window !== "undefined" ? window : null);
`;
  const json = JSON.stringify({ generated_from: "calculators.js", count: calculators.length, calculators }, null, 1) + "\n";
  return { js, json, families, calculators };
}

export const OUT_JS = path.join(ROOT, "edge-schemas.js");
export const OUT_JSON = path.join(ROOT, "vault", "plans", "edge-data", "schemas", "calculators.json");

if (import.meta.url === "file://" + process.argv[1]) {
  const { js, json, families, calculators } = build();
  if (process.argv.includes("--check")) {
    // Only the shipped file is checked: the JSON export is gitignored and rebuilt on demand.
    const stale = [[OUT_JS, js]].filter(([f, s]) => !fs.existsSync(f) || fs.readFileSync(f, "utf8") !== s).map(([f]) => path.relative(ROOT, f));
    if (stale.length) { console.error("out of date: " + stale.join(", ") + " (run node scripts/edge/schemas.mjs)"); process.exit(1); }
    console.log("schemas up to date");
  } else {
    fs.mkdirSync(path.dirname(OUT_JSON), { recursive: true });
    fs.writeFileSync(OUT_JS, js);
    fs.writeFileSync(OUT_JSON, json);
    console.log(`${calculators.length} calculators, ${families.length} families -> edge-schemas.js, ${path.relative(ROOT, OUT_JSON)}`);
  }
}
