/* Generated by capture/capture-screens.mjs: element rectangles (app CSS px: x, y, w, h). */
FILM.RECTS = {
 "home": {
  "dxTile": [
   109,
   171,
   82,
   84
  ]
 },
 "dx4": {
  "confirm": [
   33,
   502,
   157,
   38
  ]
 },
 "dx5": {
  "review": [
   199,
   59,
   182,
   40
  ],
  "chips": [
   15,
   642,
   360,
   112
  ]
 },
 "dxr": {
  "changed": [
   15,
   692,
   360,
   59
  ],
  "stewBtn": [
   30,
   626,
   329,
   42
  ],
  "top1": [
   15,
   856,
   360,
   134
  ]
 },
 "stew": {
  "quick": [
   17,
   117,
   336,
   279
  ]
 },
 "icu": {
  "vitals": [
   13,
   63,
   363,
   43
  ],
  "status": [
   11,
   1343,
   367,
   147
  ],
  "qsofa": [
   27,
   1858,
   264,
   68
  ]
 }
};
