/* StewardMD KB P3 — compile the authored KB into the shipped runtime artifact.
 *
 * Emits kb/dist/kb.core.js  (window.KB_CORE = {version, diseases:{id:{...}}}) —
 * a single, offline-cacheable <script> the reasoning engine consumes at runtime.
 * The runtime stays buildless; only this artifact is compiled (mirrors the
 * drug pipeline's build_structured.py).
 *
 * Each infective entry carries the EXACT assocKeys the legacy engine derived
 * (regex over match+baseScore+reasoning source ∩ valid finding vocabulary), so
 * the IDF soft-score and "missing/would help" lists stay byte-identical.
 *
 * USAGE: node kb/tools/build-kb-core.mjs <engine-dump.json> <engine-assoc.json> <kbVersion>
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const dumpPath = process.argv[2] || join(process.env.CLAUDE_JOB_DIR || "/tmp", "engine-dump.json");
const assocPath = process.argv[3] || join(process.env.CLAUDE_JOB_DIR || "/tmp", "engine-assoc.json");
const kbVersion = process.argv[4] || "1";

const dump = JSON.parse(readFileSync(dumpPath, "utf8"));
const assocDump = JSON.parse(readFileSync(assocPath, "utf8"));

// VALID finding vocabulary = EXTRA_GROUPS keys (parsed from reasoning.js source) ∪ FIELD_GROUPS keys (runtime)
const rjs = readFileSync(join(ROOT, "reasoning.js"), "utf8");
const eg = rjs.indexOf("var EXTRA_GROUPS"); const egEnd = rjs.indexOf("var GROUP_TAG", eg);
const extraKeys = [...rjs.slice(eg, egEnd > 0 ? egEnd : eg + 8000).matchAll(/key:\s*"([a-zA-Z0-9_]+)"/g)].map((m) => m[1]);
const VALID = new Set([...extraKeys, ...assocDump.fieldGroupKeys]);

// reproduce the engine's assocKeys(): unique VALID keys appearing as `.key` in match+baseScore+reasoning source
function engineAssoc(id) {
  const src = (dump.syndromes[id].matchSrc || "") + " " + (dump.syndromes[id].baseSrc || "") + " " + (assocDump.reasoningSrc[id] || "");
  const keys = {}; let m; const re = /\.([a-zA-Z][a-zA-Z0-9_]*)/g;
  while ((m = re.exec(src))) if (VALID.has(m[1])) keys[m[1]] = true;
  return Object.keys(keys);
}

const diseases = {};
for (const f of readdirSync(join(ROOT, "kb", "diseases"))) {
  if (!f.endsWith(".json")) continue;
  const d = JSON.parse(readFileSync(join(ROOT, "kb", "diseases", f), "utf8"));
  if (d.class === "infective") {
    diseases[d.id] = { class: "infective", system: d.system, rule: d.matching.rule, score: d.matching.score, assoc: engineAssoc(d.id) };
    if (d.reason) diseases[d.id].reason = d.reason;                 // declarative "why this" template
    if (d.reasonDerived) diseases[d.id].derived = d.reasonDerived;  // derived counters (_centor/_anthonisen)
  } else {
    diseases[d.id] = { class: "non_infective", system: d.system, find: d.matching.find };
  }
}

mkdirSync(join(ROOT, "kb", "dist"), { recursive: true });
const out = "/* GENERATED by kb/tools/build-kb-core.mjs — do not edit by hand. Runtime source of truth for reasoning. */\n" +
  "window.KB_CORE = " + JSON.stringify({ version: kbVersion, diseases }) + ";\n";
writeFileSync(join(ROOT, "kb", "dist", "kb.core.js"), out);
const inf = Object.values(diseases).filter((d) => d.class === "infective").length;
const ni = Object.values(diseases).filter((d) => d.class === "non_infective").length;
console.log(`kb.core.js written: ${Object.keys(diseases).length} diseases (${inf} infective, ${ni} non-infective), kbVersion=${kbVersion}`);
console.log(`size: ${(out.length / 1024).toFixed(1)} KB | VALID vocab: ${VALID.size}`);
console.log(`sample assoc MENINGITIS: ${JSON.stringify(diseases.MENINGITIS.assoc)}`);
