// swift-tools-version: 5.9
import PackageDescription

// StewardmdCapacitorWhisper — on-device Whisper STT plugin (whisper.cpp v1.9.1).
//
// The C/C++ inference engine is linked as a PREBUILT XCFramework release asset from
// whisper.cpp (Metal accelerated on-device, CPU fallback). Importable Swift module: `whisper`.
//
// ⚠️ MINIMUM DEPLOYMENT TARGET: the official prebuilt whisper.xcframework is built with
//    IOS_MIN_OS_VERSION=16.4, so the APP's build setting IPHONEOS_DEPLOYMENT_TARGET must be
//    >= 16.4 to link it (set to 16.4 in ios/App/App.xcodeproj). We declare this package at
//    .iOS(.v15) to MATCH the CLI-managed ios/App/CapApp-SPM/Package.swift (also .v15) — SPM
//    refuses a dependency whose platform floor exceeds the consumer's, and CapApp-SPM is
//    regenerated by `npx cap sync`. The real 16.4 floor is enforced by the app build setting +
//    the framework's own min-OS at link time. To support iOS < 16.4, build a custom XCFramework
//    with whisper.cpp's `build-xcframework.sh` (edit IOS_MIN_OS_VERSION), host it, and repoint
//    the `binaryTarget` url + checksum below. See README.md.
//
// The url + checksum are PINNED. checksum == `swift package compute-checksum <zip>` == the
// SHA-256 of the release zip (verified 2026-07 against
// github.com/ggml-org/whisper.cpp/releases/download/v1.9.1/whisper-v1.9.1-xcframework.zip).
let package = Package(
    name: "StewardmdCapacitorWhisper",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "StewardmdCapacitorWhisper",
            targets: ["WhisperPlugin"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", from: "8.0.0")
    ],
    targets: [
        .binaryTarget(
            name: "WhisperFramework",
            url: "https://github.com/ggml-org/whisper.cpp/releases/download/v1.9.1/whisper-v1.9.1-xcframework.zip",
            checksum: "8c3ecbe73f48b0cb9318fc3058264f951ab336fd530e82c4ccdd2298d1311a4c"
        ),
        .target(
            name: "WhisperPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm"),
                "WhisperFramework"
            ],
            path: "ios/Sources/WhisperPlugin")
    ]
)
