# Hand transcription of NFI 6th ed. draft 2019-20, Appendix 10d (renal) and 10b (lactation).
# Renal columns: drug, method, gfr>50, gfr10-50, gfr<10, CAPD, HD. Cross-checked against NFI 2011 Appendix 7d (identical table).
R = [
("Acetaminophen","I","q4h","q6h","q8h","Dose as GFR < 10","Dose as GFR < 10"),
("Acetazolamide","I","q6h","q12h","Avoid","No data","No data"),
("Acetylsalicyclic Acid","I","Q4h","Q4-6h","Avoid","As normal GFR","As normal GFR dose post HD"),
("Acyclovir","D, I","5 mg/kg q8h","5 mg/kg q12-24h","2.5 mg/kg q24h","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Allopurinol","D","75%","50%","33%","Dose as GFR < 10","Dose as GFR < 10"),
("Amikacin","D, I","60–90% q12h","30–70% q12–18h","20–30% q24–48h","15–20 mg/L/day","5 mg/kg post HD"),
("Amiloride","D","100%","50%","Avoid","NA","NA"),
("Aminophylline","D","100%","200–400 mg q12h","200–300 mg q12h","Dose as GFR < 10","Dose as GFR < 10"),
("Amphotericin B","I","q24h","q24h","q24-36h","Dose as GFR < 10","Dose as GFR < 10"),
("Ampicillin","I","q6h","q6–12h","q12-24h","Dose as GFR < 10","Dose as GFR < 10"),
("Cefazolin","I","q8h","q12h","q24–48h","0.5 g q12h","0.5–1.0 g post HD"),
("Cefixime","D","100%","75%","50%","200 mg q24h","200 mg q24h dose post HD"),
("Cefotaxime","I","100% q8h","100% q8h","50% q8–12h","1 g q24h","Dose as GFR < 10 dose post HD"),
("Chloroquine","D","100%","100%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Ciprofloxacin","D","100%","50-75%","50%","250 mg q8h","250 mg q12h"),
("Cisplatin","D","100%","75%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Cyclophosphamide","D","100%","75-100%","50-75%","Dose as GFR < 10","Dose as GFR < 10"),
("Dapsone","","100%","100%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Didanosine","I","100%","50%","25%","Dose as GFR < 10","Dose as GFR < 10"),
("Digoxin","D, I","100% q24h","25–75% q36h","10–25% q48h","Dose as GFR < 10","Dose as GFR < 10"),
("Enalapril","D","100%","75-100%","50-75%","Dose as GFR < 10","Dose as GFR < 10"),
("Erythromycin","D","100%","100%","50-75%","Dose as GFR < 10","Dose as GFR < 10"),
("Ethambutol","I","q24h","q24-36h","q48h","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Etoposide","D","100%","75%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Fentanyl","D","100%","75%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Fluconazole","D","100%","100%","50%","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Gentamicin","D, I","60–90% q8–12h","30–70% q12h","20–30% q24–72h","3–4 mg/L/day","Dose as GFR < 10 dose post HD"),
("Isoniazid","D","100%","100%","75%","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Lamivudine","D, I","100%","50–150 mg qd","25 mg qd","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Metformin","D","50%","Avoid","Avoid","Avoid","Avoid"),
("Metoclopramide","D","100%","75%","50%","Dose as GFR < 10","Dose as GFR < 10"),
("Penicillin G","D","100%","75%","20-50%","Dose as GFR < 10","Dose as GFR < 10"),
("Pyrazinamide","D","100%","As normal GFR","As normal GFR","As normal GFR","As normal GFR"),
("Quinine","I","q8h","q8-12h","q24h","Dose as GFR < 10","Dose as GFR < 10 dose post HD"),
("Streptomycin","I","q24h","q24–72h","q72h","20–40 mg/L/day","750 mg 2–3/week"),
("Triamterene","I","q12h","q12h","Avoid","Avoid","Avoid"),
("Tubocurarine","D","75%","50%","Avoid","Unknown","Unknown"),
("Vancomycin","D, I","500 mg q6-12h","500 mg q12-48h","500 mg q48-96h","Dose as GFR < 10","Dose as GFR < 10"),
("Zidovudine (AZT)","D, I","100% q8h","100% q8h","50% q12h","Dose as GFR < 10","Dose as GFR < 10"),
]
L = [
("Abacavir","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Acetylsalicylic Acid","Short course safe in usual dosage; monitor infant; regular use of high doses could impair platelet function and produce Hypoprothrombinemia in Infant if neonatal vitamin K stores low; possible risk of Reye’s syndrome"),
("Acyclovir","Significant amount in milk after systemic administration, but considered safe to use"),
("Alcohol","Large amounts may affect infant and reduce milk consumption"),
("Aminophylline","Present in milk-irritability in infant reported"),
("Amitriptyline","Detectable in breast milk; continue lactation; adverse effects possible; monitor infant for drowsiness"),
("Amoxycillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Amoxycillin + Clavulanic acid","Trace amounts in milk"),
("Ampicillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Artemether + Lumefantrine","Discontinue lactation during and for 1 week after stopping treatment; present in milk in animal studies"),
("Asparaginase","Lactation contraindicated"),
("Atenolol","Significant amount in milk; safe in usual dosage; monitor infant"),
("Atropine","Small amount present in milk; monitor infant"),
("Azathioprine","Lactation contraindicated"),
("Beclomethasone","Systemic effects in infant unlikely with maternal dose of less than equivalent of prednisolone 40 mg daily; monitor infant’s adrenal function with higher doses"),
("Benzathine benzylpenicillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Benzyl penicillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Betamethasone","Systemic effects in infant unlikely with maternal dose of less than equivalent of prednisolone 40 mg daily; monitor infant’s adrenal function with higher doses"),
("Bleomycin","Lactation contraindicated"),
("Carbamazepine","Continue lactation; adverse effects possible (severe skin reaction reported in 1 infant); monitor infant for drowsiness;"),
("Ceftazidime","Excreted in low concentrations; safe in usual dosage; monitor infant"),
("Ceftriaxone","Excreted in low concentrations; safe in usual dosage; monitor infant"),
("Chlorambucil","Lactation contraindicated"),
("Chloramphenicol","Continue lactation; use alternative drug if possible; may cause bone-marrow toxicity in infant; concentration in milk usually insufficient to cause ‘grey syndrome’"),
("Chlormethine","Lactation contraindicated"),
("Chloroquine","For malaria prophylaxis, amount probably too small to be harmful; inadequate for reliable protection against malaria, ; avoid lactation when used for rheumatic disease"),
("Chlorpheniramine","Safe in usual dosage; monitor infant for drowsiness"),
("Chlorpromazine","Continue lactation; adverse effects possible; monitor infant for drowsiness"),
("Ciprofloxacin","Continue lactation; use alternative drug if possible; high concentrations in breast milk"),
("Cisplatin","Lactation contraindicated"),
("Clindamycin","Amount probably too small to be harmful but bloody diarrhoea reported in 1 infant"),
("Clomifene","May inhibit lactation"),
("Clomipramine","Small amount present in milk; continue lactation; adverse effects possible; monitor infant for drowsiness"),
("Clonazepam","Continue lactation; adverse effects possible; monitor infant for drowsiness;"),
("Cloxacillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Colchicine","Present in milk but no adverse effects reported; caution because of risk of cytotoxicity"),
("Contraceptives, oral","Combined oral contraceptives may inhibit lactation-use alternative method of contraception until weaning or for 6 months after birth; progestogen-only contraceptives do not affect lactation (start 3 weeks after birth or later)"),
("Cyclophosphamide","Lactation contraindicated during and for 36 h after stopping treatment"),
("Cyclosporine","Present in milk-avoid"),
("Cytarabine","Lactation contraindicated"),
("Dacarbazine","Lactation contraindicated"),
("Dactinomycin","Lactation contraindicated"),
("Dapsone","Although significant amount in milk risk to infant very small; continue lactation; monitor infant for jaundice"),
("Daunorubicin","Lactation contraindicated"),
("Dexamethasone","Systemic effects in infant unlikely with maternal dose of less than equivalent of prednisolone 40 mg daily; monitor infant’s adrenal function with higher doses"),
("Diazepam","Continue lactation; adverse effects possible; monitor infant for drowsiness;"),
("Didanosine","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Diloxanide","Avoid"),
("Doxorubicin","Lactation contraindicated"),
("Doxycycline","Continue lactation; use alternative drug if possible (absorption and therefore discolouration of teeth in infant probably usually prevented by chelation with calcium in milk)"),
("Efavirenz","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Eflornithine","Avoid"),
("Ephedrine","Irritability and disturbed sleep reported"),
("Ergocalciferol","Caution with high doses; may cause hypercalcaemia in infant"),
("Ergotamine","Use alternative drug; ergotism may occur in infant; repeated doses may inhibit lactation"),
("Erythromycin","Only small amounts in milk; safe in usual dosage; monitor infant"),
("Ethinylestradiol","Use alternative method of contraception; may inhibit lactation; see also Contraceptives, Oral"),
("Etoposide","Lactation contraindicated"),
("Fluconazole","Present in milk; safe in usual dosage; monitor infant"),
("Flucytosine","Avoid"),
("5-Fluorouracil","Discontinue lactation"),
("Fluphenazine","Amount excreted in milk probably too small to be harmful; continue lactation; adverse effects possible; monitor infant for drowsiness"),
("Glibenclamide","Hypoglycaemia in infant"),
("Haloperidol","Amount excreted in milk probably too small to be harmful; continue lactation; adverse effects possible; monitor infant for drowsiness"),
("Halothane","Excreted in milk"),
("Hydralazine","Present in milk but not known to be harmful; monitor infant"),
("Hydrochlorothiazide","Use alternative drug; may inhibit lactation"),
("Hydrocortisone","Systemic effects in infant unlikely with maternal dose of less than equivalent of prednisolone 40 mg daily; monitor infant’s adrenal function with higher doses"),
("Ibuprofen","Amount too small to be harmful; short courses safe in usual doses"),
("Imipenem + Cilastatin","Present in milk-avoid"),
("Indinavir","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Iodine","Stop lactation; danger of neonatal hypothyroidism or goitre; appears to be concentrated in milk"),
("Isoniazid","Monitor infant for possible toxicity; theoretical risk of convulsions and neuropathy; prophylactic pyridoxine advisable in mother and infant"),
("Ivermectin","Avoid treating mother until infant is 1week old"),
("Lamivudine","Present in milk; lactation recommended during first 6 months if no safe alternative to breast milk"),
("Levamisole","Lactation contraindicated"),
("Levonorgestrel","Combined oral contraceptives may inhibit lactation-use alternative method of contraception until weaning or for 6 months after birth; progestogen-only contraceptives do not affect lactation (preferably start 6 weeks after birth or later)"),
("Lithium","Present in milk and risk of toxicity in infant; continue lactation; monitor infant carefully, particularly if risk of dehydration"),
("Lopinavir + Ritonavir","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Lumefantrine","See Artemether + Lumefantrine"),
("Medroxyprogesterone","Present in milk-no adverse effects reported (preferably start injectable contraceptive 6 weeks after birth or later)"),
("Mefloquine","Present in milk but risk to infant minimal"),
("6-Mercaptopurine","Lactation contraindicated"),
("Metformin","Present in milk but safe in usual doses; monitor infant"),
("Methotrexate","Lactation contraindicated"),
("Metoclopramide","Present in milk; adverse effects possible; monitor infant for adverse effects"),
("Metronidazole","Significant amount in milk; continue lactation; avoid large doses; use alternative drug if possible"),
("Morphine","Short courses safe in usual doses; monitor infant"),
("Nalidixic acid","Continue lactation; use alternative drug if possible; one case of haemolytic anaemia reported"),
("Nelfinavir","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Neostigmine","Amount probably too small to be harmful; monitor infant"),
("Nevirapine","Present in milk; lactation recommended during first 6 months if no safe alternative to breast milk"),
("Nifedipine","Small amount in milk; continue lactation; monitor infant"),
("Nitrofurantoin","Only small amounts in milk but could be enough to produce haemolysis in G-6-PD-deficient infants"),
("Norethisterone","Combined oral contraceptives may inhibit lactation-use alternative method of contraception until weaning or for 6 months after birth; progestogen-only contraceptives do not affect lactation (preferably start injectable contraceptive 6 weeks after birth or later)"),
("Ofloxacin","Continue lactation; use alternative drug if possible"),
("Paracetamol","Small amount present in milk: short courses safe in usual dosage; monitor infant"),
("Pentamidine","Avoid unless essential"),
("Pentavalent antimony compounds","Avoid"),
("Phenobarbital","Continue lactation; adverse effects possible; monitor infant for drowsiness;"),
("Phenoxy-Methyl penicillin","Trace amounts in milk; safe in usual dosage; monitor infant"),
("Phenytoin","Small amount present in milk; continue lactation; adverse effects possible; monitor infant for drowsiness;"),
("Potassium iodide","Stop lactation; danger of neonatal hypothyroidism or goitre; appears to be concentrated in milk"),
("Povidone–iodine","Avoid; iodine absorbed from vaginal preparations is concentrated in milk"),
("Praziquantel","Avoid lactation during and for 72 h after treatment; considered safe to continue lactation in treatment of schistosomiasis"),
("Prednisolone","Systemic effects in infant unlikely with maternal dose of less than prednisolone 40 mg daily; monitor infant’s adrenal function with higher doses"),
("Primaquine","Avoid; risk of haemolysis in G-6-PD-deficient infants"),
("Procainamide","Present in milk; continue lactation; monitor infant"),
("Procarbazine","Lactation contraindicated"),
("Promethazine","Safe in usual dosage; monitor infant for drowsiness"),
("Propranolol","Present in milk; safe in usual dosage; monitor infant"),
("Propylthiouracil","Monitor infant’s thyroid status but amounts in milk probably too small to affect infant; high doses might affect neonatal thyroid function"),
("Pyrimethamine","Significant amount-avoid administration of other folate antagonists to infant"),
("Quinidine","Significant amount but not known to be harmful"),
("Ranitidine","Significant amount present in milk, but not known to be harmful"),
("Ritonavir","See Lopinavir with Ritonavir"),
("Salbutamol","Safe in usual dosage; monitor infant"),
("Saquinavir","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Senna","Avoid; large doses may cause increased gastric motility and diarrhoea"),
("Silver sulfadiazine","Continue lactation; monitor infant for jaundice-small risk of kernicterus in jaundiced infants particularly with long- acting sulphonamides, and of haemolysis in G-6-PD-deficient infants"),
("Sodium valproate","see Valproic acid"),
("Stavudine","Lactation recommended during first 6 months if no safe alternative to breast milk"),
("Sulfadiazine","Continue lactation; monitor infant for jaundice-small risk of kernicterus in jaundiced infants particularly with long- acting sulphonamides, and of haemolysis in G-6-PD-deficient infants"),
("Sulfadoxine + Pyrimethamine","Continue lactation; monitor infant for jaundice-small risk of kernicterus in jaundiced infants and of haemolysis in G-6-PD-deficient infants (due to sulfadoxine)"),
("Sulfamethoxazole + Trimethoprim","Continue lactation; monitor infant for jaundice-small risk of kernicterus in jaundiced infants and of haemolysis in G-6-PD-deficient infants (due to sulfamethoxazole)"),
("Sulfasalazine","Continue lactation; monitor infant for jaundice-small amounts in milk (1 report of bloody diarrhoea and rashes); theoretical risk of neonatal haemolysis especially in G -6-PD-deficient infants"),
("Tamoxifen","Suppresses lactation; avoid unless potential benefit outweighs risk"),
("Testosterone","Avoid; may cause masculinization in the female infant or precocious development in the male infant; high doses suppress lactation"),
("Tetracycline","Continue lactation; use alternative drug if possible (absorption and therefore discolouration of teeth in infant probably usually prevented by chelation with calcium in milk)"),
("Theophylline","Present in milk-irritability in infant reported; modified-release preparations preferable"),
("Thiamine","Severely thiamine-deficient mothers should avoid lactation as toxic methyl - glyoxal excreted in milk"),
("Trimethoprim","Present in milk; safe in usual dosage; monitor infant"),
("Valproic acid","Small amount present in milk; continue lactation; adverse effects possible; monitor infant for drowsiness; (Sodium valproate)"),
("Vancomycin","Present in milk-significant absorption following oral administration unlikely"),
("Vinblastine","Lactation contraindicated"),
("Vincristine","Lactation contraindicated"),
("Warfarin","Risk of haemorrhage; increased by vitamin-K deficiency; warfarin appears safe"),
("Zidovudine","Lactation recommended during first 6 months if no safe alternative to breast milk"),
]
