-- StewardMD — Government Health Schemes: jurisdiction registry seed
-- 28 states + 8 union territories + 1 central row. Idempotent (INSERT OR IGNORE).
-- Apply: wrangler d1 execute stewardmd-govschemes --remote --file functions/db/govschemes_seed_jurisdictions.sql

INSERT OR IGNORE INTO jurisdictions (id, name, type, code) VALUES
('andhra-pradesh', 'Andhra Pradesh', 'state', 'AP'),
('arunachal-pradesh', 'Arunachal Pradesh', 'state', 'AR'),
('assam', 'Assam', 'state', 'AS'),
('bihar', 'Bihar', 'state', 'BR'),
('chhattisgarh', 'Chhattisgarh', 'state', 'CT'),
('goa', 'Goa', 'state', 'GA'),
('gujarat', 'Gujarat', 'state', 'GJ'),
('haryana', 'Haryana', 'state', 'HR'),
('himachal-pradesh', 'Himachal Pradesh', 'state', 'HP'),
('jharkhand', 'Jharkhand', 'state', 'JH'),
('karnataka', 'Karnataka', 'state', 'KA'),
('kerala', 'Kerala', 'state', 'KL'),
('madhya-pradesh', 'Madhya Pradesh', 'state', 'MP'),
('maharashtra', 'Maharashtra', 'state', 'MH'),
('manipur', 'Manipur', 'state', 'MN'),
('meghalaya', 'Meghalaya', 'state', 'ML'),
('mizoram', 'Mizoram', 'state', 'MZ'),
('nagaland', 'Nagaland', 'state', 'NL'),
('odisha', 'Odisha', 'state', 'OD'),
('punjab', 'Punjab', 'state', 'PB'),
('rajasthan', 'Rajasthan', 'state', 'RJ'),
('sikkim', 'Sikkim', 'state', 'SK'),
('tamil-nadu', 'Tamil Nadu', 'state', 'TN'),
('telangana', 'Telangana', 'state', 'TG'),
('tripura', 'Tripura', 'state', 'TR'),
('uttar-pradesh', 'Uttar Pradesh', 'state', 'UP'),
('uttarakhand', 'Uttarakhand', 'state', 'UT'),
('west-bengal', 'West Bengal', 'state', 'WB'),
('andaman-and-nicobar-islands', 'Andaman and Nicobar Islands', 'ut', 'AN'),
('chandigarh', 'Chandigarh', 'ut', 'CH'),
('dadra-and-nagar-haveli-and-daman-and-diu', 'Dadra and Nagar Haveli and Daman and Diu', 'ut', 'DH'),
('delhi', 'Delhi (NCT)', 'ut', 'DL'),
('jammu-and-kashmir', 'Jammu and Kashmir', 'ut', 'JK'),
('ladakh', 'Ladakh', 'ut', 'LA'),
('lakshadweep', 'Lakshadweep', 'ut', 'LD'),
('puducherry', 'Puducherry', 'ut', 'PY'),
('central', 'Central Government', 'central', '');
