-- StewardMD - Medical Updates: journal + openFDA sources for Clinical Bulletins (2026-09-28).
-- Hand-runnable copy of functions/_journal_sources.js (the pipeline seeds each batch once by itself).
-- Idempotent (INSERT OR IGNORE). From the repo root:
--   wrangler d1 execute stewardmd-updates --remote --command "$(sed 's/--.*$//' functions/db/seed_sources_journals.sql | tr '\n' ' ')"

INSERT OR IGNORE INTO sources (id, name, workspace, branch, type, homepage, guideline_page, rss_url, query, parser_type, priority, enabled, created_ts) VALUES
  ('openfda-approvals', 'FDA new drug and biologic approvals (openFDA)', 'internal_medicine', '', 'drug_approval', 'https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm', '', '', '', 'openfda', 15, 1, strftime('%s','now')*1000),
  ('pubmed-core', 'NEJM, Lancet, JAMA, BMJ: randomised and phase 3 trials', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("N Engl J Med"[ta] OR "Lancet"[ta] OR "JAMA"[ta] OR "BMJ"[ta]) AND ("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 60, 1, strftime('%s','now')*1000),
  ('pubmed-cardio', 'Circulation, Eur Heart J, JACC: randomised and phase 3 trials', 'internal_medicine', 'cardiology', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Circulation"[ta] OR "Eur Heart J"[ta] OR "J Am Coll Cardiol"[ta]) AND ("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 70, 1, strftime('%s','now')*1000),
  ('pubmed-onc', 'J Clin Oncol, Lancet Oncol, JAMA Oncol: phase 3 trials', 'internal_medicine', 'oncology', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("J Clin Oncol"[ta] OR "Lancet Oncol"[ta] OR "JAMA Oncol"[ta]) AND "Clinical Trial, Phase III"[pt] NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 70, 1, strftime('%s','now')*1000),
  ('pubmed-general', 'Ann Intern Med, JAMA Intern Med, Nature Medicine, NEJM Evidence: trials', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Ann Intern Med"[ta] OR "JAMA Intern Med"[ta] OR "Nat Med"[ta] OR "NEJM Evid"[ta]) AND ("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 65, 1, strftime('%s','now')*1000),
  ('pubmed-guidelines', 'Practice guidelines in major general and specialty journals', 'internal_medicine', '', 'guideline', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Practice Guideline"[pt] OR "Guideline"[pt]) AND ("N Engl J Med"[ta] OR "Lancet"[ta] OR "JAMA"[ta] OR "BMJ"[ta] OR "Ann Intern Med"[ta] OR "Circulation"[ta] OR "Eur Heart J"[ta] OR "J Am Coll Cardiol"[ta] OR "Diabetes Care"[ta] OR "Chest"[ta] OR "Clin Infect Dis"[ta] OR "Kidney Int"[ta] OR "Gastroenterology"[ta] OR "Hepatology"[ta] OR "Intensive Care Med"[ta] OR "J Clin Oncol"[ta]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 55, 1, strftime('%s','now')*1000),
  ('pubmed-lancet-specialty', 'Lancet specialty journals: randomised and phase 3 trials', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Lancet Infect Dis"[ta] OR "Lancet Respir Med"[ta] OR "Lancet Diabetes Endocrinol"[ta] OR "Lancet Gastroenterol Hepatol"[ta] OR "Lancet Neurol"[ta] OR "Lancet HIV"[ta] OR "Lancet Haematol"[ta] OR "Lancet Psychiatry"[ta] OR "Lancet Rheumatol"[ta]) AND ("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 75, 1, strftime('%s','now')*1000),
  ('pubmed-im-specialty', 'Internal medicine specialty journals: randomised and phase 3 trials', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Diabetes Care"[ta] OR "Kidney Int"[ta] OR "J Am Soc Nephrol"[ta] OR "Am J Respir Crit Care Med"[ta] OR "Chest"[ta] OR "Gastroenterology"[ta] OR "Hepatology"[ta] OR "Clin Infect Dis"[ta] OR "Intensive Care Med"[ta] OR "Crit Care Med"[ta] OR "Blood"[ta] OR "Ann Rheum Dis"[ta]) AND ("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 75, 1, strftime('%s','now')*1000),
  ('pubmed-india', 'Indian journals: trials, meta-analyses and guidelines', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("Indian J Med Res"[ta] OR "Natl Med J India"[ta] OR "J Assoc Physicians India"[ta] OR "Lancet Reg Health Southeast Asia"[ta] OR "Indian Pediatr"[ta]) AND (("Randomized Controlled Trial"[pt] OR "Clinical Trial, Phase III"[pt]) OR "Meta-Analysis"[pt] OR "Practice Guideline"[pt] OR "Guideline"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 65, 1, strftime('%s','now')*1000),
  ('pubmed-meta', 'NEJM, Lancet, JAMA, BMJ, Annals, JAMA IM: meta-analyses and systematic reviews', 'internal_medicine', '', 'trial', 'https://pubmed.ncbi.nlm.nih.gov', '', '', '("N Engl J Med"[ta] OR "Lancet"[ta] OR "JAMA"[ta] OR "BMJ"[ta] OR "Ann Intern Med"[ta] OR "JAMA Intern Med"[ta]) AND ("Meta-Analysis"[pt] OR "Systematic Review"[pt]) NOT ("Comment"[pt] OR "Letter"[pt] OR "Editorial"[pt])', 'pubmed', 80, 1, strftime('%s','now')*1000);
