package `in`.stewardmd.wear.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.tasks.await

/**
 * On-watch Google Sign-In (Path A). Uses Credential Manager to get a Google ID token for the account
 * paired to the watch, then signs into Firebase with it — so the watch authenticates as the same user
 * without any phone token bridge. [serverClientId] is the project's web OAuth client id (pass
 * R.string.default_web_client_id, generated by the google-services plugin).
 *
 * Requires: a Google account present on the watch + Play services. Fails cleanly (Result.failure) when
 * no account/credential is available (e.g. a bare emulator) so the UI can show a retry.
 */
class WatchSignIn(private val serverClientId: String) {
    suspend fun signIn(context: Context): Result<Unit> = try {
        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(serverClientId)
            .setFilterByAuthorizedAccounts(false)
            .build()
        val request = GetCredentialRequest.Builder().addCredentialOption(googleIdOption).build()
        val response = CredentialManager.create(context).getCredential(context, request)
        val idToken = GoogleIdTokenCredential.createFrom(response.credential.data).idToken
        FirebaseAuth.getInstance()
            .signInWithCredential(GoogleAuthProvider.getCredential(idToken, null))
            .await()
        Result.success(Unit)
    } catch (e: Throwable) {
        Result.failure(e)
    }
}
