#!/usr/bin/env python3
"""Generate the RadioAnatome licence and provenance documents.

WHY GENERATED: a hand-written LICENSE_MANIFEST.md drifts from sources.json the first
time someone adds a source in a hurry, and a stale licence document is worse than none
because it is trusted. sources.json is the single machine-enforced truth (check_sources
.require_clear refuses anything not CLEAR); these documents are rendered from it.

Writes into docs/radioanatome/:
    LICENSE_MANIFEST.md            every external asset, its licence and status
    LICENSE_REQUIRED.md            gated components, what they unlock, how to obtain
    DATA_PROVENANCE.md             datasets: source, version, date, licence, use
    MODEL_PROVENANCE.md            models/weights: code licence vs WEIGHTS licence
    FREE_MODEL_COVERAGE_MATRIX.md  structure -> model -> works on our data? -> free?
"""
import json
import os
import sys
from datetime import date

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(_HERE)
DOCS = os.path.join(_REPO, "docs", "radioanatome")

# Which register rows are DATASETS as opposed to models/weights/text.
DATASETS = {"visible-human", "totalsegmentator-dataset", "openneuro-cc0",
            "wikimedia-cc0", "tcia", "autopet-fdg-petct", "mindboggle-101",
            "spl-nac-brain-atlas", "jhu-icbm-dti-81", "healthy-total-body-cts"}
MODELS = {"totalsegmentator-total", "totalsegmentator-open-subtasks",
          "totalsegmentator-appendicular-bones", "totalsegmentator-brain-structures",
          "fastsurfer-segonly", "synthseg-v1", "nv-segment-ct", "nv-segment-ctmr",
          "fsl", "freesurfer"}

# The coverage matrix. Each row is a claim we can defend with a measurement or a
# licence URL, NOT an aspiration. "blocker" is the honest root cause.
COVERAGE = [
    # structure family, best free model, works on VHP cadaver?, free?, blocker, quality
    ("Skeleton (skull, spine, ribs, sternum, clavicle, pelvis, femur)",
     "TotalSegmentator total", "YES", "FREE (Apache-2.0)", "-", "SHIPPED, HU-verified"),
    ("Knee / tibia / fibula / patella",
     "TotalSegmentator appendicular_bones", "YES (bone survives freezing)",
     "GATED", "model licence", "deferred; classical fallback planned"),
    ("Hands / feet / small bones",
     "TotalSegmentator appendicular_bones", "YES", "GATED", "model licence",
     "deferred; classical fallback planned"),
    ("Liver, spleen, kidneys, pancreas, gallbladder, stomach, bowel",
     "expert masks shipped WITH the CC BY 4.0 dataset", "NO",
     "FREE (CC BY 4.0)", "VHP DATA: one 25-90 HU band, no contrast",
     "good on living CT"),
    ("Lungs and lung LOBES", "expert masks in the CC BY 4.0 dataset", "NO",
     "FREE (CC BY 4.0)", "VHP DATA: -540 HU vs -700/-850 living; no fissures",
     "good on living CT"),
    ("Heart, chambers, myocardium", "expert masks in the CC BY 4.0 dataset", "NO",
     "FREE (CC BY 4.0)", "VHP DATA: needs contrast", "good on living CT"),
    ("Aorta and major vessels", "expert masks in the CC BY 4.0 dataset", "NO",
     "FREE (CC BY 4.0)", "VHP DATA: no contrast in a cadaver",
     "good on living angiographic CT"),
    ("Skeletal muscle and fat", "expert masks in the CC BY 4.0 dataset", "NO",
     "FREE (CC BY 4.0)",
     "VHP DATA: pelvic muscle measured -13..-21 HU, 32-40% below -30 HU (fat)",
     "good on living CT"),
    ("Airway / trachea / larynx", "TotalSegmentator total", "NO", "FREE",
     "VHP DATA: air-in-body measured at 0 voxels; the airway is not air-filled",
     "good on living CT"),
    ("Brain: cerebrum, cerebellum, brainstem, ventricles, thalamus, basal ganglia",
     "FastSurfer --seg_only", "NO", "FREE (Apache-2.0 code)",
     "VHP DATA: 33-slice 4 mm cadaver T1 defeated SynthSeg",
     "good on a living 1 mm T1 (OpenNeuro CC0)"),
    ("Coronary arteries", "none free and verified", "NO", "NONE FOUND",
     "needs cardiac CTA plus a dedicated model", "NOT AVAILABLE"),
    ("PET / metabolic", "n/a - PET has no anatomy to segment", "n/a",
     "NO CLEAN DATA", "no commercially clean whole-body PET/CT exists",
     "NOT AVAILABLE, deferred by design"),
]


def _reg():
    return json.load(open(os.path.join(_HERE, "sources.json")))


def _rows(reg, keys):
    return [(k, v) for k, v in reg.items()
            if not k.startswith("_") and k in keys]


def _other(reg):
    known = DATASETS | MODELS
    return [(k, v) for k, v in reg.items()
            if not k.startswith("_") and k not in known]


def _fmt(v, key):
    return str(v.get(key, "-")).replace("|", "/").replace("\n", " ")


def manifest(reg):
    L = ["# RadioAnatome licence manifest", "",
         f"GENERATED by atlas-pipeline/provenance.py on {date.today()}. Do not hand-edit.",
         "Source of truth: `atlas-pipeline/sources.json`, which is enforced in code by",
         "`check_sources.require_clear()` — a verdict other than CLEAR makes the pipeline",
         "refuse to run, so a licence mistake fails loudly instead of shipping.", "",
         "`commercial` below is the LICENSOR's position, not ours.", "",
         "| id | licence | commercial | attribution | verdict |",
         "|---|---|---|---|---|"]
    for k, v in sorted((k, v) for k, v in reg.items() if not k.startswith("_")):
        L.append(f"| `{k}` | {_fmt(v,'licence')} | "
                 f"{'yes' if v.get('commercial') else 'NO'} | "
                 f"{_fmt(v,'attribution')} | **{_fmt(v,'verdict')}** |")
    cleared = [k for k, v in reg.items() if not k.startswith("_") and v.get("verdict") == "CLEAR"]
    L += ["", f"**{len(cleared)} CLEAR**, "
              f"{sum(1 for k,v in reg.items() if not k.startswith('_') and v.get('verdict')=='BLOCKED')} BLOCKED, "
              f"{sum(1 for k,v in reg.items() if not k.startswith('_') and v.get('verdict','').startswith('PENDING'))} pending.",
          "", "## Attribution actually owed", ""]
    for k, v in sorted((k, v) for k, v in reg.items() if not k.startswith("_")):
        if v.get("verdict") == "CLEAR" and v.get("attribution") not in (None, "none", "-"):
            L.append(f"- **{k}** — {_fmt(v,'attribution')}"
                     + (f" — credit line: *{v['credit']}*" if v.get("credit") else ""))
    return "\n".join(L) + "\n"


def required(reg):
    L = ["# Licence-gated components (DEFERRED, not used)", "",
         f"GENERATED on {date.today()}. Nothing in this file is used by the pipeline;",
         "`check_sources.require_clear()` refuses every one of them.", "",
         "Each entry states what anatomy it would unlock, whether buying it actually",
         "solves the problem, and the free alternative. Several are NOT worth buying",
         "because the limitation is our source data, not the model.", ""]
    for k, v in sorted((k, v) for k, v in reg.items() if not k.startswith("_")):
        if v.get("verdict") == "CLEAR":
            continue
        L += [f"## `{k}`", "",
              f"- **licence** — {_fmt(v,'licence')}",
              f"- **commercial use** — {'permitted' if v.get('commercial') else 'NOT permitted'}",
              f"- **status** — {_fmt(v,'verdict')}",
              f"- **why blocked** — {_fmt(v,'blocking_clause')}",
              f"- **verified from** — {_fmt(v,'verified_from')}"]
        if v.get("note"):
            L.append(f"- **note** — {_fmt(v,'note')}")
        L.append("")
    L += ["## Can these be added later without redesign?", "",
          "Yes. Every module is produced by `build.py` from (volume, mask, label-map),",
          "and the label map is a plain JSON file mapping model class names to canonical",
          "structure ids. Adding a licensed model later means running it, writing one",
          "label file and re-running build.py — the viewer, catalog, ontology and tests",
          "do not change. PET/CT is the same: a new modality value plus a label file.", ""]
    return "\n".join(L) + "\n"


def data_prov(reg):
    L = ["# Data provenance", "", f"GENERATED on {date.today()}.", "",
         "| dataset | licence | licence URL | redistribute? | derivatives? | used for |",
         "|---|---|---|---|---|---|"]
    use = {
        "visible-human": "whole-body + regional CT skeleton, all planes",
        "totalsegmentator-dataset": "living-patient CT soft tissue, organs, vessels",
        "openneuro-cc0": "living brain MRI (planned)",
        "wikimedia-cc0": "not currently used",
        "tcia": "not used",
        "autopet-fdg-petct": "NOT USED - deferred",
        "spl-nac-brain-atlas": "not currently used",
    }
    for k, v in sorted(_rows(reg, DATASETS)):
        redis = "yes" if v.get("verdict") == "CLEAR" else "NO"
        L.append(f"| `{k}` | {_fmt(v,'licence')} | {_fmt(v,'verified_from')} | "
                 f"{redis} | {redis} | {use.get(k,'-')} |")
    L += ["", "## Notes per dataset", ""]
    for k, v in sorted(_rows(reg, DATASETS)):
        L += [f"### `{k}`", f"- licence: {_fmt(v,'licence')}",
              f"- verdict: **{_fmt(v,'verdict')}**",
              f"- attribution: {_fmt(v,'attribution')}",
              f"- {_fmt(v, 'note') if v.get('note') else _fmt(v,'blocking_clause')}", ""]
    return "\n".join(L) + "\n"


def model_prov(reg):
    L = ["# Model and weights provenance", "",
         f"GENERATED on {date.today()}.", "",
         "**The distinction that matters:** an Apache-2.0 repository does NOT mean every",
         "checkpoint in it is Apache-2.0. TotalSegmentator is the worked example — its code",
         "and its `total` weights are Apache-2.0, but 18 subtask checkpoints are licence-",
         "gated. That was verified in code rather than inferred:",
         "`registry.requires_license(task)` is literally `task in commercial_models`.", "",
         "| model | code licence | WEIGHTS licence | commercial | verdict |",
         "|---|---|---|---|---|"]
    code = {
        "totalsegmentator-total": "Apache-2.0",
        "totalsegmentator-open-subtasks": "Apache-2.0",
        "totalsegmentator-appendicular-bones": "Apache-2.0 (code only)",
        "totalsegmentator-brain-structures": "Apache-2.0 (code only)",
        "fastsurfer-segonly": "Apache-2.0",
        "synthseg-v1": "Apache-2.0",
        "nv-segment-ct": "Apache-2.0",
        "nv-segment-ctmr": "Apache-2.0 (code only)",
        "fsl": "FSL Licence", "freesurfer": "FreeSurfer v1.0",
    }
    for k, v in sorted(_rows(reg, MODELS)):
        L.append(f"| `{k}` | {code.get(k,'-')} | {_fmt(v,'licence')} | "
                 f"{'yes' if v.get('commercial') else 'NO'} | **{_fmt(v,'verdict')}** |")
    L += ["", "## Unverified points, stated rather than hidden", "",
          "- `fastsurfer-segonly` — the WEIGHTS licence as distinct from the code licence",
          "  is not separately stated upstream, and its training labels are FreeSurfer-",
          "  derived. Recorded in sources.json as UNVERIFIED.",
          "- `synthseg-v1` — only the v1.0 in-repo weights are covered. The 2.0 / robust /",
          "  parc weights come from a separate link with no licence statement: unused.", ""]
    return "\n".join(L) + "\n"


def coverage_matrix():
    L = ["# Free model coverage matrix", "",
         f"GENERATED on {date.today()}.", "",
         "Read the **blocker** column before proposing a purchase. Where the blocker is",
         "VHP DATA, no model licence fixes it — the contrast is absent from the voxels,",
         "and the fix is living-patient source data, which is free under CC BY 4.0.", "",
         "| structure family | best model | works on VHP cadaver? | free? | blocker | expected quality |",
         "|---|---|---|---|---|---|"]
    for row in COVERAGE:
        L.append("| " + " | ".join(row) + " |")
    L += ["", "## The one purchase that is actually justified", "",
          "`appendicular_bones` — tibia, fibula, patella, and the hand and foot bones.",
          "It is the ONLY row where the limitation is the model rather than our data:",
          "bone contrast survives freezing, so the cadaver can support these labels.",
          "VISTA3D was checked against its own `label_dict.json` and has no tibia, fibula",
          "or patella either, so it is not a free substitute. A classical",
          "threshold-plus-position segmenter is the free fallback.", "",
          "## Purchases that would NOT help", "",
          "- `brain_structures` — SynthSeg ran clean on our cadaver T1 and still returned",
          "  ~2x L/R asymmetry with most of the brain unlabelled. Fix the data first.",
          "- `tissue_types`, `heartchambers_highres` — cannot recover contrast that was",
          "  never in the image.", ""]
    return "\n".join(L) + "\n"


def main():
    os.makedirs(DOCS, exist_ok=True)
    reg = _reg()
    for fn, body in (("LICENSE_MANIFEST.md", manifest(reg)),
                     ("LICENSE_REQUIRED.md", required(reg)),
                     ("DATA_PROVENANCE.md", data_prov(reg)),
                     ("MODEL_PROVENANCE.md", model_prov(reg)),
                     ("FREE_MODEL_COVERAGE_MATRIX.md", coverage_matrix())):
        p = os.path.join(DOCS, fn)
        open(p, "w", encoding="utf-8").write(body)
        print(f"wrote {os.path.relpath(p, _REPO)}  ({len(body)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
