/* functions/_wardsynq/hmis-items.js - the data items of the HMIS monthly format for an "Other Secondary Care Facility,
 * Pvt" (HMIS portal format, fileid=66), transcribed. Listed so WardSynQ can fill the items its record supports and mark
 * the rest as not available from WardSynQ data. */
const HMIS_FORMAT = Object.freeze({
  title: "Monthly Service Delivery Reporting format Other Secondary Care Facility Pvt FORMAT",
  facilityType: "Other Secondary Care Facility, Pvt"
});

const HMIS_SECTIONS = Object.freeze([
  { code: "M1", title: "Ante Natal Care (ANC) Services & High Risk Pregnancies" },
  { code: "M2", title: "Deliveries" },
  { code: "M3", title: "Number of Caesarean (C-Section) deliveries" },
  { code: "M4", title: "Pregnancy outcome & details of new-born/children" },
  { code: "M5", title: "Anaemia Mukt Bharat" },
  { code: "M6", title: "Post Natal Care (PNC)" },
  { code: "M7", title: "Sexually Transmitted Infections/Reproductive Tract Infections (STI/RTI) Cases" },
  { code: "M8", title: "Family Planning" },
  { code: "M9", title: "CHILD IMMUNISATION" },
  { code: "M10", title: "Number of cases of Childhood Diseases" },
  { code: "M11", title: "National Vector Borne Disease Control Programme (NVBDCP)" },
  { code: "M12", title: "Adolescent Health" },
  { code: "M13", title: "National TB Elimination Programme (NTEP)" },
  { code: "M14", title: "Patient Services" },
  { code: "M15", title: "Diagnostics" },
  { code: "M16", title: "Details of deaths reported:" },
  { code: "M17", title: "QA (Quality Assurance) & BEMMP (Biomedical Equipment Management & Maintenance Program)" }
]);

const HMIS_ITEMS = Object.freeze([
  // M1 - Ante Natal Care (ANC) Services & High Risk Pregnancies
  { code: "1.1.", section: "M1", label: "Total number of NEW Pregnant Women registered for ANC", parent: null, kind: "number" },
  { code: "1.1.a", section: "M1", label: "Out of total number of NEW pregnant women registered with age less than <15 years", parent: "1.1.", kind: "number" },
  { code: "1.1.b", section: "M1", label: "Out of total number of NEW pregnant women registered with age 15-19 years", parent: "1.1.", kind: "number" },
  { code: "1.1.c", section: "M1", label: "Out of total number of NEW pregnant women registered with age more than >19 to 49 years", parent: "1.1.", kind: "number" },
  { code: "1.1.d", section: "M1", label: "Out of total number of NEW pregnant women registered with age more than >49 years", parent: "1.1.", kind: "number" },
  { code: "1.1.1.", section: "M1", label: "Out of the total NEW ANC registered, number registered within 1st trimester (within 12 weeks)", parent: "1.1.", kind: "number" },
  { code: "1.1.2.", section: "M1", label: "Total ANC footfall/cases (Old cases + New Registration) attended", parent: null, kind: "number" },
  { code: "1.2.", section: "M1", label: "ANC services", parent: null, kind: "header" },
  { code: "1.2.1.", section: "M1", label: "Number of PW given Td1 (Tetanus Diptheria dose 1)", parent: "1.2.", kind: "number" },
  { code: "1.2.2.", section: "M1", label: "Number of PW given Td2 (Tetanus Diptheria dose 2)", parent: "1.2.", kind: "number" },
  { code: "1.2.3.", section: "M1", label: "Number of PW given Td Booster (Tetanus Diptheria dose booster)", parent: "1.2.", kind: "number" },
  { code: "1.2.4.", section: "M1", label: "Number of PW provided full course 180 Iron Folic Acid (IFA) tablets", parent: "1.2.", kind: "number" },
  { code: "1.2.5.", section: "M1", label: "Number of PW provided full course 360 Calcium tablets", parent: "1.2.", kind: "number" },
  { code: "1.2.6.", section: "M1", label: "Number of PW given one Albendazole tablet after 1st trimester", parent: "1.2.", kind: "number" },
  { code: "1.2.7.", section: "M1", label: "Number of PW received 4 or more ANC check ups", parent: "1.2.", kind: "number" },
  { code: "1.2.8.", section: "M1", label: "Number of PW given ANC Corticosteroids in Pre-Term Labour", parent: "1.2.", kind: "number" },
  { code: "1.3.", section: "M1", label: "Pregnant Women (PW) with Hypertension (BP>140/90)", parent: null, kind: "header" },
  { code: "1.3.1.", section: "M1", label: "New cases of PW with hypertension detected", parent: "1.3.", kind: "number" },
  { code: "1.3.2.", section: "M1", label: "Number of PW with hypertension managed at institution", parent: "1.3.", kind: "number" },
  { code: "1.3.3.", section: "M1", label: "Number of New Pre-Eclampsia/Eclampsia cases identified", parent: "1.3.", kind: "number" },
  { code: "1.3.4.", section: "M1", label: "Number of Pre-Eclampsia/Eclampsia cases managed during ANC", parent: "1.3.", kind: "number" },
  { code: "1.3.5.", section: "M1", label: "Number of Eclampsia cases managed during delivery", parent: "1.3.", kind: "number" },
  { code: "1.4.", section: "M1", label: "Pregnant Women (PW) with Anaemia", parent: null, kind: "header" },
  { code: "1.4.1.", section: "M1", label: "Number of PW tested for Haemoglobin (Hb) 4 or more than 4 times for respective ANCs", parent: "1.4.", kind: "number" },
  { code: "1.4.2.", section: "M1", label: "Number of PW tested for Haemoglobin (Hb)", parent: "1.4.", kind: "number" },
  { code: "1.4.3.", section: "M1", label: "Number of PW having Hb level<11(7.1 to 10.9 g/dl) (Out of total tested cases)", parent: "1.4.", kind: "number" },
  { code: "1.4.4.", section: "M1", label: "Number of PW having Hb level<=7 g/dl (Out of total tested cases)", parent: "1.4.", kind: "number" },
  { code: "1.4.5.", section: "M1", label: "Number of PW treated for severe anaemia (Hb<=7g/dl) (including referred-in cases)", parent: "1.4.", kind: "number" },
  { code: "1.5.", section: "M1", label: "Pregnant Women (PW) with Gestational Diabetes Mellitus (GDM)", parent: null, kind: "header" },
  { code: "1.5.1.", section: "M1", label: "Number of PW tested for Blood Sugar using OGTT(Oral Glucose Tolerance Test)", parent: "1.5.", kind: "number" },
  { code: "1.5.2.", section: "M1", label: "Number of PW tested positive for GDM out of total OGTT(Oral Glucose Tolerance Test) conducted", parent: "1.5.", kind: "number" },
  { code: "1.5.3.", section: "M1", label: "Number of GDM positive PW managed with Insulin/Metformin out of total tested positive for GDM", parent: "1.5.", kind: "number" },
  { code: "1.6.", section: "M1", label: "Pregnant Women (PW) with Syphilis", parent: null, kind: "header" },
  { code: "1.6.1.", section: "M1", label: "Syphilis test conducted for Pregnant Women", parent: "1.6.", kind: "number" },
  { code: "1.6.1.a", section: "M1", label: "Number of pregnant/Direct-In-Labor (DIL) women screened/tested (with VDRL/RPR/TPHA/RDT/PoC) for Syphilis", parent: "1.6.1.", kind: "number" },
  { code: "1.6.1.b", section: "M1", label: "Number of pregnant/DIL women found seropositive for Syphilis by VDRL/RPR/TPHA/RDT/PoC test", parent: "1.6.1.", kind: "number" },
  { code: "1.6.1.c", section: "M1", label: "Number of pregnant/DIL women found Syphilis-Seropositive and given treatment with injection Benzathine Penicillin (IM)", parent: "1.6.1.", kind: "number" },
  { code: "1.6.1.d", section: "M1", label: "Number of live births among Syphilis seropositive Pregnant Women", parent: "1.6.1.", kind: "number" },
  { code: "1.6.1.e", section: "M1", label: "Number of babies born to Syphilis-Seropositive Pregnant Women tested positive/ clinically diagnosed for congenital Syphilis", parent: "1.6.1.", kind: "number" },
  { code: "1.6.1.f", section: "M1", label: "Out of above, babies with congenital Syphilis received curative treatment", parent: "1.6.1.", kind: "number" },
  { code: "1.7.", section: "M1", label: "Thyroid test conducted for Pregnant Women", parent: null, kind: "number" },
  { code: "1.7.1.", section: "M1", label: "Number of Pregnant Women tested positive for Thyroid disorder", parent: "1.7.", kind: "number" },
  { code: "1.7.2.", section: "M1", label: "Number of Pregnant Women treated for thyroid disorder", parent: "1.7.", kind: "number" },
  { code: "1.8.", section: "M1", label: "Tuberculosis test conducted for Pregnant Women", parent: null, kind: "number" },
  { code: "1.8.1.", section: "M1", label: "Number of Pregnant Women screened for TB", parent: "1.8.", kind: "number" },
  { code: "1.8.2.", section: "M1", label: "Number of Pregnant Women identified with Presumptive TB symptoms", parent: "1.8.", kind: "number" },
  { code: "1.8.3.", section: "M1", label: "Number of Pregnant Women referred out of those identified with Presumptive TB symptoms", parent: "1.8.", kind: "number" },
  { code: "1.9.", section: "M1", label: "High Risk /Complicated Pregnancies", parent: null, kind: "header" },
  { code: "1.9.1.", section: "M1", label: "Total High Risk Pregnancy (HRP) Intrapartum including following:", parent: "1.9.", kind: "number" },
  { code: "1.9.1.a.", section: "M1", label: "Number of Pregnant Women only with Post-Partum Haemorrhage (Immediately after delivery) in the facility", parent: "1.9.1.", kind: "number" },
  { code: "1.9.1.b.", section: "M1", label: "Number of Pregnant Women only with Sepsis in the facility", parent: "1.9.1.", kind: "number" },
  { code: "1.9.1.c.", section: "M1", label: "Number of Pregnant Women identified only with Eclampsia in the facility", parent: "1.9.1.", kind: "number" },
  { code: "1.9.1.d.", section: "M1", label: "Number of Pregnant Women identified only with obstructed labour in the facility", parent: "1.9.1.", kind: "number" },
  { code: "1.9.1.e.", section: "M1", label: "Number of Pregnant Women identified with more than 1 complication listed above", parent: "1.9.1.", kind: "number" },
  { code: "1.9.2.", section: "M1", label: "Total High Risk Pregnancy (HRP) Antepartum (Only New Cases are to be reported)", parent: "1.9.", kind: "number" },
  { code: "1.9.3.", section: "M1", label: "Total no. of highrisk ANC cases referred to Higher/ any other facility (Referred out)", parent: "1.9.", kind: "number" },
  { code: "1.9.3.a.", section: "M1", label: "Total no. of Intrapartum/PNC High Risk Pregnancy cases referred to Higher/ any other facility (Referred out)", parent: "1.9.3.", kind: "number" },
  { code: "1.9.4.", section: "M1", label: "Total no. of highrisk ANC cases referred in to the facility (Referred in)", parent: "1.9.", kind: "number" },
  { code: "1.9.4.a.", section: "M1", label: "Total no. of Intrapartum/PNC High Risk Pregnancy cases attended or referred into the facility (Referred in)", parent: "1.9.4.", kind: "number" },

  // M2 - Deliveries
  { code: "2.1.", section: "M2", label: "Deliveries conducted at Home", parent: null, kind: "number" },
  { code: "2.1.1.", section: "M2", label: "Number of Home Deliveries attended by", parent: "2.1.", kind: "number" },
  { code: "2.2.", section: "M2", label: "Number of Institutional Deliveries conducted (Including C-Sections)", parent: null, kind: "number" },
  { code: "2.2.1.", section: "M2", label: "Out of total institutional deliveries(excluding C-section), number of women stayed for 48 hours or more after delivery", parent: "2.2.", kind: "number" },
  { code: "2.2.2", section: "M2", label: "Out of total Institutional deliveries, number of Institutional Deliveries (Excluding C-Sections) conducted at night (8 PM- 8 AM)", parent: "2.2.", kind: "number" },
  { code: "2.2.3.", section: "M2", label: "Out of total Institutional deliveries, number of institutional deliveries conducted at Midwifery Led Care Unit (MLCU)", parent: "2.2.", kind: "number" },
  { code: "2.3.", section: "M2", label: "Age wise total number of delivery (Home +Institutional) reported (2.3.1+2.3.2+2.3.3+2.3.4)", parent: null, kind: "number" },
  { code: "2.3.1.", section: "M2", label: "Out of total number of delivery, PW with age less than <15 years", parent: "2.3.", kind: "number" },
  { code: "2.3.2.", section: "M2", label: "Out of total number of delivery, PW with age 15-19 years", parent: "2.3.", kind: "number" },
  { code: "2.3.3.", section: "M2", label: "Out of total number of delivery, PW with age more than >19-49 years", parent: "2.3.", kind: "number" },
  { code: "2.3.4.", section: "M2", label: "Out of total number of delivery, PW with age more than > 49 years", parent: "2.3.", kind: "number" },

  // M3 - Number of Caesarean (C-Section) deliveries
  { code: "3.1.", section: "M3", label: "Total number of C -Section deliveries performed", parent: null, kind: "number" },
  { code: "3.1.1.", section: "M3", label: "Out of total C-sections, number performed at night (8 PM- 8 AM)", parent: "3.1.", kind: "number" },
  { code: "3.1.2.", section: "M3", label: "Out of total C-section, number of women stayed for 72 hours or more after delivery", parent: "3.1.", kind: "number" },

  // M4 - Pregnancy outcome & details of new-born/children
  { code: "4.1.", section: "M4", label: "Pregnancy Outcome (in number)", parent: null, kind: "header" },
  { code: "4.1.1.", section: "M4", label: "Live Birth", parent: "4.1.", kind: "number" },
  { code: "4.1.1.a", section: "M4", label: "Live Birth - Male", parent: "4.1.1.", kind: "number" },
  { code: "4.1.1.b", section: "M4", label: "Live Birth - Female", parent: "4.1.1.", kind: "number" },
  { code: "4.1.2.", section: "M4", label: "Number of Pre-term newborns ( < 37 weeks of pregnancy)", parent: "4.1.", kind: "number" },
  { code: "4.1.3.", section: "M4", label: "Still Birth", parent: "4.1.", kind: "number" },
  { code: "4.1.3.a", section: "M4", label: "Fresh Stillbirth - Intrapartum Stillbirth (28 weeks & above)", parent: "4.1.3.", kind: "number" },
  { code: "4.1.3.b", section: "M4", label: "Mascerated Stillbirth - Antepartum Stillbirth (28 weeks &above)", parent: "4.1.3.", kind: "number" },
  { code: "4.1.3.c", section: "M4", label: "Foetal Death (24-27 completed weeks)", parent: "4.1.3.", kind: "number" },
  { code: "4.2.", section: "M4", label: "Abortion (spontaneous)", parent: null, kind: "number" },
  { code: "4.3.", section: "M4", label: "Medical Termination of Pregnancy (MTP)", parent: null, kind: "header" },
  { code: "4.3.1.", section: "M4", label: "Number of MTPs conducted", parent: "4.3.", kind: "number" },
  { code: "4.3.1.a", section: "M4", label: "Surgical MTPs upto 12 weeks of pregnancy", parent: "4.3.1.", kind: "number" },
  { code: "4.3.1.b", section: "M4", label: "MTP more than 12 weeks of pregnancy", parent: "4.3.1.", kind: "number" },
  { code: "4.3.1.c", section: "M4", label: "MTPs completed through Medical methods of abortion (MMA)", parent: "4.3.1.", kind: "number" },
  { code: "4.3.2.", section: "M4", label: "Post-abortion/MTP Complications", parent: "4.3.", kind: "header" },
  { code: "4.3.2.a", section: "M4", label: "Total Post-abortion/MTP Complications Identified", parent: "4.3.2.", kind: "number" },
  { code: "4.3.2.b.", section: "M4", label: "Post-abortion/MTP complications identified (where abortions were carried out in facilities other than public and accredited private health facilities)", parent: "4.3.2.", kind: "number" },
  { code: "4.3.2.c.", section: "M4", label: "Post-abortion/MTP Complications treated", parent: "4.3.2.", kind: "number" },
  { code: "4.3.3.", section: "M4", label: "Number of women provided with Post-abortion/ MTP contraception", parent: "4.3.", kind: "number" },
  { code: "4.4.", section: "M4", label: "Details of Newborn children", parent: null, kind: "header" },
  { code: "4.4.1.", section: "M4", label: "Number of Newborns weighed at birth", parent: "4.4.", kind: "number" },
  { code: "4.4.2.", section: "M4", label: "Number of Newborns having weight less than 2500 gms", parent: "4.4.", kind: "number" },
  { code: "4.4.2.a", section: "M4", label: "Out of the above, number of Newborns having weight less than 1800 gms", parent: "4.4.2.", kind: "number" },
  { code: "4.4.3.", section: "M4", label: "Number of Newborns breast fed within 1 hour of birth", parent: "4.4.", kind: "number" },
  { code: "4.4.4.", section: "M4", label: "No. of Newborns discharged from the facility were exclusively breastfed till discharge", parent: "4.4.", kind: "number" },
  { code: "4.5.", section: "M4", label: "Rashtriya Bal Swasthya Karyakram (RBSK)", parent: null, kind: "header" },
  { code: "4.5.1.", section: "M4", label: "Number of Newborns screened for defects at birth (as per Comprehensive Newborn Screening, RBSK)", parent: "4.5.", kind: "number" },
  { code: "4.5.1.a", section: "M4", label: "Number of Newborns identified with visible birth defects (including Neural tube defect, Down's Syndrome, Cleft Lip & Palate, Club foot and Developmental dysplasia of the hip)", parent: "4.5.1.", kind: "number" },
  { code: "4.5.2.", section: "M4", label: "Number of SNCU discharged babies screened in DEIC", parent: "4.5.", kind: "number" },
  { code: "4.5.3.", section: "M4", label: "Number of children till age 18 years (affected with selected health conditions) managed for 4 Ds (Disease, Deficiency, Developmental Delay & Defect)", parent: "4.5.", kind: "number" },
  { code: "4.5.4.", section: "M4", label: "Number of children till age 18 years (affected with selected health conditions) managed by Intervention - Surgical", parent: "4.5.", kind: "number" },

  // M5 - Anaemia Mukt Bharat
  { code: "5.1.", section: "M5", label: "IFA Coverage", parent: null, kind: "header" },
  { code: "5.1.1.", section: "M5", label: "Number of women of reproductive age (WRA) 20-49 years (non-pregnant, non-lactating), provided 4 Red Iron and folic acid (IFA) tablets in a month", parent: "5.1.", kind: "number" },
  { code: "5.1.2.", section: "M5", label: "Number of children (6-59 months old) provided 8-10 doses (1ml) of IFA syrup (Bi weekly)", parent: "5.1.", kind: "number" },
  { code: "5.2.", section: "M5", label: "Anaemia- Identified & Treated", parent: null, kind: "header" },
  { code: "5.2.3.", section: "M5", label: "Beneficiaries diagnosed with mild and moderate Anaemia, put on treatment", parent: "5.2.", kind: "number" },
  { code: "5.2.3.a", section: "M5", label: "Number of anaemic in-school Children (5-9 years) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.3.b", section: "M5", label: "Number of anaemic in-school adolescent girls (10-19 years) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.3.c", section: "M5", label: "Number of anaemic out of school adolescent girls (10-19 years) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.3.d", section: "M5", label: "Number of anaemic in-school adolescent boys (10-19 years) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.3.e", section: "M5", label: "Number of anaemic lactating mothers (of 0-6 months old child) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.3.f", section: "M5", label: "Number of anaemic women of reproductive age (non-pregnant, non-lactating) (20-49 years) put on treatment", parent: "5.2.3.", kind: "number" },
  { code: "5.2.4.", section: "M5", label: "Beneficiaries diagnosed with Severe Anaemia, put on treatment", parent: "5.2.", kind: "number" },
  { code: "5.2.4.a", section: "M5", label: "Number of lactating mothers (of 0-6 months old child) diagnosed with severe anaemia and put on treatment", parent: "5.2.4.", kind: "number" },

  // M6 - Post Natal Care (PNC)
  { code: "6.1.", section: "M6", label: "In case of home delivery, number of women receiving 1st Postpartum checkups within 48 hours", parent: null, kind: "number" },
  { code: "6.2.", section: "M6", label: "Number of women receiving Postpartum checkup between 48 hours and 14 days after Institutional delivery", parent: null, kind: "number" },
  { code: "6.3.", section: "M6", label: "Number of mothers provided full course of 180 IFA tablets after delivery", parent: null, kind: "number" },
  { code: "6.4.", section: "M6", label: "Number of mothers provided full course 360 Calcium tablets after delivery", parent: null, kind: "number" },
  { code: "6.5.", section: "M6", label: "Total No of High Risk Mothers identified during Post Natal Period", parent: null, kind: "number" },
  { code: "6.6.", section: "M6", label: "Out of above identified number of High Risk Mothers managed (including referred in cases)", parent: null, kind: "number" },

  // M7 - STI/RTI Cases
  { code: "7.1.", section: "M7", label: "Number of new STI/RTI cases identified", parent: null, kind: "number" },
  { code: "7.1.1.", section: "M7", label: "Number of males assessed for STI/RTI", parent: "7.1.", kind: "number" },
  { code: "7.1.1.a", section: "M7", label: "Out of the above, number of males diagnosed with STI/RTI", parent: "7.1.1.", kind: "number" },
  { code: "7.1.1.b", section: "M7", label: "Out of the above, number of males treated for STI/RTI", parent: "7.1.1.", kind: "number" },
  { code: "7.1.2.", section: "M7", label: "Number of females (all females) assessed for STI/RTI", parent: "7.1.", kind: "number" },
  { code: "7.1.2.a", section: "M7", label: "Out of the above, number of females (all females) diagnosed with STI/RTI", parent: "7.1.2.", kind: "number" },
  { code: "7.1.2.b", section: "M7", label: "Out of the above, number of females (all females) treated for STI/RTI", parent: "7.1.2.", kind: "number" },
  { code: "7.1.3.", section: "M7", label: "Number of H/TG assessed for STI/RTI", parent: "7.1.", kind: "number" },
  { code: "7.1.3.a", section: "M7", label: "Out of the above, number of H/TG people diagnosed with STI/RTI", parent: "7.1.3.", kind: "number" },
  { code: "7.1.3.b", section: "M7", label: "Out of the above, number of H/TG people treated for STI/RTI", parent: "7.1.3.", kind: "number" },

  // M8 - Family Planning
  { code: "8.1.", section: "M8", label: "MALE STERILIZATION", parent: null, kind: "header" },
  { code: "8.1.1.", section: "M8", label: "Number of Non Scalpel Vasectomy (NSV) / Conventional Vasectomy conducted", parent: "8.1.", kind: "number" },
  { code: "8.2.", section: "M8", label: "FEMALE STERILIZATION", parent: null, kind: "header" },
  { code: "8.2.1.", section: "M8", label: "Number of Laparoscopic sterilizations (excluding post-abortion) conducted", parent: "8.2.", kind: "number" },
  { code: "8.2.2.", section: "M8", label: "Number of Interval sterilizations (Mini-lap/Conventional) (other than post-partum and post abortion) conducted", parent: "8.2.", kind: "number" },
  { code: "8.2.3.", section: "M8", label: "Number of Postpartum sterilizations (within 7 days of delivery by minilap or concurrent with caesarean section) conducted", parent: "8.2.", kind: "number" },
  { code: "8.2.4.", section: "M8", label: "Number of Post-abortion sterilizations (within 7 days of spontaneous or surgical abortion) conducted", parent: "8.2.", kind: "number" },
  { code: "8.3.", section: "M8", label: "Number of Interval IUCD Insertions (excluding PPIUCD and PAIUCD)", parent: null, kind: "number" },
  { code: "8.4.", section: "M8", label: "Number of Postpartum (within 48 hours of delivery) IUCD insertions", parent: null, kind: "number" },
  { code: "8.5.", section: "M8", label: "Number of Post-abortion (within 12 days of Spontaneous or surgical abortion) IUCD insertions", parent: null, kind: "number" },
  { code: "8.6.", section: "M8", label: "Number of IUCD Removals", parent: null, kind: "number" },
  { code: "8.7.", section: "M8", label: "Number of complications following IUCD Insertion", parent: null, kind: "number" },
  { code: "8.8.", section: "M8", label: "Injectable Contraceptive MPA- First Dose", parent: null, kind: "header" },
  { code: "8.8.1.", section: "M8", label: "Injectable Contraceptive MPA (Intra Muscular) - First Dose", parent: "8.8.", kind: "number" },
  { code: "8.8.2.", section: "M8", label: "Injectable Contraceptive MPA (Sub Cutaneous) - First Dose", parent: "8.8.", kind: "number" },
  { code: "8.9.", section: "M8", label: "Injectable Contraceptive MPA- Second Dose", parent: null, kind: "header" },
  { code: "8.9.1.", section: "M8", label: "Injectable Contraceptive MPA (Intra Muscular) - Second Dose", parent: "8.9.", kind: "number" },
  { code: "8.9.2.", section: "M8", label: "Injectable Contraceptive MPA (Sub Cutaneous)- Second Dose", parent: "8.9.", kind: "number" },
  { code: "8.10.", section: "M8", label: "Injectable Contraceptive MPA- Third Dose", parent: null, kind: "header" },
  { code: "8.10.1.", section: "M8", label: "Injectable Contraceptive MPA (Intra Muscular) - Third Dose", parent: "8.10.", kind: "number" },
  { code: "8.10.2.", section: "M8", label: "Injectable Contraceptive MPA (Sub Cutaneous)- Third Dose", parent: "8.10.", kind: "number" },
  { code: "8.11.", section: "M8", label: "Injectable Contraceptive MPA- Fourth and above Dose", parent: null, kind: "header" },
  { code: "8.11.1.", section: "M8", label: "Injectable Contraceptive MPA (Intra Muscular) - Fourth and above Dose", parent: "8.11.", kind: "number" },
  { code: "8.11.2.", section: "M8", label: "Injectable Contraceptive MPA (Sub Cutaneous)- Fourth and above Dose", parent: "8.11.", kind: "number" },
  { code: "8.12.", section: "M8", label: "Number of Combined Oral Pill cycles distributed to the beneficiary", parent: null, kind: "number" },
  { code: "8.13.", section: "M8", label: "Number of Condom pieces distributed to the beneficiary", parent: null, kind: "number" },
  { code: "8.14.", section: "M8", label: "Number of Centchroman (weekly) pill strips distributed to the beneficiary", parent: null, kind: "number" },
  { code: "8.15.", section: "M8", label: "Number of Emergency Contraceptive Pills (ECP) given to the beneficiary", parent: null, kind: "number" },
  { code: "8.16.", section: "M8", label: "Number of Pregnancy Test Kits (PTK) utilized", parent: null, kind: "number" },
  { code: "8.17.", section: "M8", label: "No. of Subdermal Contraceptive Implant", parent: null, kind: "header" },
  { code: "8.17.1.", section: "M8", label: "No. of Subdermal Contraceptive Implant inserted", parent: "8.17.", kind: "number" },
  { code: "8.17.2.", section: "M8", label: "No. of Subdermal Contraceptive Implant removed", parent: "8.17.", kind: "number" },
  { code: "8.18.", section: "M8", label: "Quality in sterilization services", parent: null, kind: "header" },
  { code: "8.18.1.", section: "M8", label: "Complications following male sterilization", parent: "8.18.", kind: "number" },
  { code: "8.18.2.", section: "M8", label: "Complications following female sterilization", parent: "8.18.", kind: "number" },
  { code: "8.18.3.", section: "M8", label: "Failures following male sterilization", parent: "8.18.", kind: "number" },
  { code: "8.18.4.", section: "M8", label: "Failures following female sterilization", parent: "8.18.", kind: "number" },
  { code: "8.18.5.", section: "M8", label: "Deaths following male sterilization", parent: "8.18.", kind: "number" },
  { code: "8.18.6.", section: "M8", label: "Deaths following female sterilization", parent: "8.18.", kind: "number" },
  { code: "8.19.", section: "M8", label: "Follow up in Sterilization", parent: null, kind: "header" },
  { code: "8.19.1.", section: "M8", label: "Number of cases of Female Sterilization followed up (after 1 month or on the resumption of her menstrual cycle whichever is earlier)", parent: "8.19.", kind: "number" },
  { code: "8.19.2.", section: "M8", label: "Number of cases of Male Sterilization followed up (after 3 months)", parent: "8.19.", kind: "number" },

  // M9 - CHILD IMMUNISATION
  { code: "9.1.", section: "M9", label: "Number of Infants 0 to 11 months old who received:", parent: null, kind: "header" },
  { code: "9.1.1.", section: "M9", label: "Child immunisation - Vitamin K (Birth Dose)", parent: "9.1.", kind: "number" },
  { code: "9.1.2.", section: "M9", label: "Child immunisation - BCG", parent: "9.1.", kind: "number" },
  { code: "9.1.3.", section: "M9", label: "Child immunisation - Pentavalent 1", parent: "9.1.", kind: "number" },
  { code: "9.1.4.", section: "M9", label: "Child immunisation - Pentavalent 2", parent: "9.1.", kind: "number" },
  { code: "9.1.5.", section: "M9", label: "Child immunisation - Pentavalent 3", parent: "9.1.", kind: "number" },
  { code: "9.1.6.", section: "M9", label: "Child immunisation - OPV 0 (Birth Dose)", parent: "9.1.", kind: "number" },
  { code: "9.1.7.", section: "M9", label: "Child immunisation - OPV1", parent: "9.1.", kind: "number" },
  { code: "9.1.8.", section: "M9", label: "Child immunisation - OPV2", parent: "9.1.", kind: "number" },
  { code: "9.1.9.", section: "M9", label: "Child immunisation - OPV3", parent: "9.1.", kind: "number" },
  { code: "9.1.10.", section: "M9", label: "Child immunisation - Hepatitis-B0 (Birth Dose)", parent: "9.1.", kind: "number" },
  { code: "9.1.11.", section: "M9", label: "Child immunisation - Inactivated Injectable Polio Vaccine 1 (IPV 1)", parent: "9.1.", kind: "number" },
  { code: "9.1.12.", section: "M9", label: "Child immunisation - Inactivated Injectable Polio Vaccine 2 (IPV 2)", parent: "9.1.", kind: "number" },
  { code: "9.1.13.", section: "M9", label: "Child immunisation - Rotavirus 1", parent: "9.1.", kind: "number" },
  { code: "9.1.14.", section: "M9", label: "Child immunisation - Rotavirus 2", parent: "9.1.", kind: "number" },
  { code: "9.1.15.", section: "M9", label: "Child immunisation - Rotavirus 3", parent: "9.1.", kind: "number" },
  { code: "9.1.16.", section: "M9", label: "Child immunisation - PCV1", parent: "9.1.", kind: "number" },
  { code: "9.1.17.", section: "M9", label: "Child immunisation - PCV2", parent: "9.1.", kind: "number" },
  { code: "9.2.", section: "M9", label: "Number of Children 9-11 months who received:", parent: null, kind: "header" },
  { code: "9.2.1.", section: "M9", label: "Child immunisation(9 - 11 months) - Inactivated Injectable Polio Vaccine 3 (IPV 3)", parent: "9.2.", kind: "number" },
  { code: "9.2.2.", section: "M9", label: "Child immunisation (9-11months) - Measles & Rubella (MR)/Measles containing vaccine(MCV) - 1st Dose", parent: "9.2.", kind: "number" },
  { code: "9.2.3.", section: "M9", label: "Child immunisation (9-11months) - JE 1st dose", parent: "9.2.", kind: "number" },
  { code: "9.2.4.", section: "M9", label: "Child immunisation - PCV Booster", parent: "9.2.", kind: "number" },
  { code: "9.2.5.", section: "M9", label: "Number of children aged between 9 and <12 months FULLY IMMUNIZED {BCG +OPV123+ Pentavalent123+ MR/ Measles Containing Vaccine (MCV)-1st Dose}", parent: "9.2.", kind: "number" },
  { code: "9.2.5.a", section: "M9", label: "FULLY IMMUNIZED children aged between 9 and <12 months- Male", parent: "9.2.5.", kind: "number" },
  { code: "9.2.5.b", section: "M9", label: "FULLY IMMUNIZED children aged between 9 and <12 months- Female", parent: "9.2.5.", kind: "number" },
  { code: "9.3.", section: "M9", label: "Children given following vaccination after 12 months (delayed vaccinations)", parent: null, kind: "header" },
  { code: "9.3.1.", section: "M9", label: "Child immunisation(after 12 months-delayed vaccination) - Measles & Rubella (MR)/Measles containing vaccine(MCV)- 1st Dose", parent: "9.3.", kind: "number" },
  { code: "9.3.2.", section: "M9", label: "Child immunisation (after 12 months-delayed vaccination) - JE 1st dose", parent: "9.3.", kind: "number" },
  { code: "9.3.3.", section: "M9", label: "Child immunisation - DPT 1 after 12 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.3.4.", section: "M9", label: "Child immunisation - DPT 2 after 12 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.3.5.", section: "M9", label: "Child immunisation - DPT 3 after 12 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.3.6.", section: "M9", label: "Child immunisation - DPT Booster after 24 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.3.7.", section: "M9", label: "Child immunisation - OPV Booster after 24 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.3.8.", section: "M9", label: "Child immunisation - JE Booster after 24 months of age (delayed vaccination)", parent: "9.3.", kind: "number" },
  { code: "9.4.", section: "M9", label: "Number of Children more than 12 months who received:", parent: null, kind: "header" },
  { code: "9.4.1.", section: "M9", label: "Child immunisation - Measles & Rubella (MR)/ Measles containing vaccine(MCV)- 2nd Dose (16-24 months)", parent: "9.4.", kind: "number" },
  { code: "9.4.2.", section: "M9", label: "Child immunisation - DPT 1st Booster", parent: "9.4.", kind: "number" },
  { code: "9.4.3.", section: "M9", label: "Child immunisation - OPV Booster", parent: "9.4.", kind: "number" },
  { code: "9.4.4.", section: "M9", label: "Number of children more than 16 months of age who received Japanese Encephalitis (JE) vaccine- 2nd dose (16-24 months)", parent: "9.4.", kind: "number" },
  { code: "9.5.", section: "M9", label: "Number of Children more than 23 months who received:", parent: null, kind: "header" },
  { code: "9.5.1.", section: "M9", label: "Child Immunization- Typhoid", parent: "9.5.", kind: "number" },
  { code: "9.5.2.", section: "M9", label: "Children more than 5 years received DPT5 (2nd Booster)", parent: "9.5.", kind: "number" },
  { code: "9.5.3.", section: "M9", label: "Children more than 10 years received Td10 (Tetanus Diptheria10)", parent: "9.5.", kind: "number" },
  { code: "9.5.4.", section: "M9", label: "Children more than 16 years received Td16 (Tetanus Diptheria16)", parent: "9.5.", kind: "number" },
  { code: "9.6.", section: "M9", label: "Adverse Event Following Immunisation (AEFI)", parent: null, kind: "header" },
  { code: "9.6.1.", section: "M9", label: "Number of cases of AEFI -Minor (eg.- fever, rash, pain etc)", parent: "9.6.", kind: "number" },
  { code: "9.6.2.", section: "M9", label: "Number of cases of AEFI - Severe (eg.- anaphylaxis, fever>102 degrees, not requiring hospitalization etc.)", parent: "9.6.", kind: "number" },
  { code: "9.6.3.", section: "M9", label: "Number of cases of AEFI - Serious (eg.- hospitalization, death, disability , cluster etc.)", parent: "9.6.", kind: "number" },
  { code: "9.6.3.a", section: "M9", label: "Out of Number of cases of AEFI - Serious , total number of AEFI deaths", parent: "9.6.3.", kind: "number" },
  { code: "9.8.", section: "M9", label: "Children received Vitamin A Doses between 9 months and 5 years", parent: null, kind: "header" },
  { code: "9.8.1.", section: "M9", label: "Child immunisation - Vitamin A Dose - 1", parent: "9.8.", kind: "number" },
  { code: "9.8.2.", section: "M9", label: "Child immunisation - Vitamin A Dose - 5", parent: "9.8.", kind: "number" },
  { code: "9.8.3.", section: "M9", label: "Child immunisation - Vitamin A Dose - 9", parent: "9.8.", kind: "number" },

  // M10 - Number of cases of Childhood Diseases
  { code: "10.1.", section: "M10", label: "New Cases of Childhood Diseases (0-5 years) & Leprosy (0-14 years) Include new cases of OPD/IPD/Emergency", parent: null, kind: "header" },
  { code: "10.1.1.", section: "M10", label: "Childhood Diseases - Pneumonia", parent: "10.1.", kind: "number" },
  { code: "10.1.2.", section: "M10", label: "Childhood Diseases - Asthma", parent: "10.1.", kind: "number" },
  { code: "10.1.3.", section: "M10", label: "Childhood Diseases - Sepsis", parent: "10.1.", kind: "number" },
  { code: "10.1.4.", section: "M10", label: "Childhood Diseases - Diphtheria", parent: "10.1.", kind: "number" },
  { code: "10.1.5.", section: "M10", label: "Childhood Diseases - Pertussis", parent: "10.1.", kind: "number" },
  { code: "10.1.6.", section: "M10", label: "Childhood Diseases - Tetanus Neonatorum", parent: "10.1.", kind: "number" },
  { code: "10.1.7.", section: "M10", label: "Childhood Diseases - Tuberculosis (TB)", parent: "10.1.", kind: "number" },
  { code: "10.1.8.", section: "M10", label: "Childhood Diseases - Acute Flaccid Paralysis(AFP)", parent: "10.1.", kind: "number" },
  { code: "10.1.9.", section: "M10", label: "Childhood Diseases - Measles", parent: "10.1.", kind: "number" },
  { code: "10.1.10.", section: "M10", label: "Childhood Diseases - Malaria", parent: "10.1.", kind: "number" },
  { code: "10.1.11.", section: "M10", label: "Childhood Diseases - Diarrhoea", parent: "10.1.", kind: "number" },
  { code: "10.1.12.", section: "M10", label: "Childhood Diseases - Diarrhoea treated with ORS", parent: "10.1.", kind: "number" },
  { code: "10.1.13.", section: "M10", label: "Childhood Diseases - Diarrhoea treated with Zinc for 14 days", parent: "10.1.", kind: "number" },
  { code: "10.1.14.", section: "M10", label: "Childhood Diseases -Leprosy Cases", parent: "10.1.", kind: "number" },
  { code: "10.1.15.", section: "M10", label: "Childhood Diseases- Leprosy with Grade II disability", parent: "10.1.", kind: "number" },
  { code: "10.2.", section: "M10", label: "Childhood IPD", parent: null, kind: "header" },
  { code: "10.2.1.", section: "M10", label: "Children admitted with Respiratory Infections", parent: "10.2.", kind: "number" },
  { code: "10.2.2.", section: "M10", label: "Children admitted with Pneumonia", parent: "10.2.", kind: "number" },
  { code: "10.2.3.", section: "M10", label: "Children admitted with Diarrhoea", parent: "10.2.", kind: "number" },

  // M11 - National Vector Borne Disease Control Programme (NVBDCP)
  { code: "11.1.", section: "M11", label: "Malaria", parent: null, kind: "header" },
  { code: "11.1.1.", section: "M11", label: "Microscopy Tests", parent: "11.1.", kind: "header" },
  { code: "11.1.1.a", section: "M11", label: "Total Blood Smears Examined for Malaria", parent: "11.1.1.", kind: "number" },
  { code: "11.1.1.b", section: "M11", label: "Malaria (Microscopy Tests ) - Plasmodium Vivax test positive", parent: "11.1.1.", kind: "number" },
  { code: "11.1.1.c", section: "M11", label: "Malaria (Microscopy Tests ) - Plasmodium Falciparum test positive", parent: "11.1.1.", kind: "number" },
  { code: "11.1.1.d", section: "M11", label: "Malaria (Microscopy Tests ) - Mixed test positive", parent: "11.1.1.", kind: "number" },
  { code: "11.1.2.", section: "M11", label: "Rapid Diagnostic Test (RDT )", parent: "11.1.", kind: "header" },
  { code: "11.1.2.a", section: "M11", label: "RDT conducted for Malaria", parent: "11.1.2.", kind: "number" },
  { code: "11.1.2.b", section: "M11", label: "Malaria (RDT) - Plasmodium Vivax test positive", parent: "11.1.2.", kind: "number" },
  { code: "11.1.2.c", section: "M11", label: "Malaria (RDT) - Plasmodium Falciparum test positive", parent: "11.1.2.", kind: "number" },
  { code: "11.1.2.d", section: "M11", label: "Malaria (RDT) - Mixed test positive", parent: "11.1.2.", kind: "number" },
  { code: "11.2.", section: "M11", label: "Kala Azar- Rapid Diagnostic Test (RDT)", parent: null, kind: "header" },
  { code: "11.2.1.", section: "M11", label: "Kala Azar (RDT) - Tests Conducted", parent: "11.2.", kind: "number" },
  { code: "11.2.2.", section: "M11", label: "Kala Azar Positive Cases", parent: "11.2.", kind: "number" },
  { code: "11.3.", section: "M11", label: "Dengue & Chikungunya", parent: null, kind: "header" },
  { code: "11.3.1.", section: "M11", label: "Dengue - Enzyme- Linked Immuno Sorbent Assay (ELISA) test conducted", parent: "11.3.", kind: "number" },
  { code: "11.3.2.", section: "M11", label: "Dengue - Enzyme- Linked Immuno Sorbent Assay (ELISA) test found positive", parent: "11.3.", kind: "number" },
  { code: "11.3.3.", section: "M11", label: "Chikungunya Enzyme- Linked Immuno Sorbent Assay (ELISA) test conducted", parent: "11.3.", kind: "number" },
  { code: "11.3.4.", section: "M11", label: "Chikungunya Enzyme- Linked Immuno Sorbent Assay (ELISA) test found positive", parent: "11.3.", kind: "number" },
  { code: "11.4.", section: "M11", label: "Acute Encephalitis Syndrome/ Japanese Encephalitis (AES/ JE)", parent: null, kind: "header" },
  { code: "11.4.1.", section: "M11", label: "No. of AES cases tested for JE(IgM ELISA)", parent: "11.4.", kind: "number" },
  { code: "11.4.2.", section: "M11", label: "No. of JE positive cases", parent: "11.4.", kind: "number" },
  { code: "11.5.", section: "M11", label: "Lymphatic Filariasis", parent: null, kind: "header" },
  { code: "11.5.1.", section: "M11", label: "Number of persons that consumed MDA(Mass Drug Administration) drugs during the MDA round", parent: "11.5.", kind: "number" },
  { code: "11.5.2.", section: "M11", label: "Number of Lymphatic Filarisis lymphoedema patients received MMDP (Morbidity Management And Disability Prevention) kits", parent: "11.5.", kind: "number" },
  { code: "11.5.3.", section: "M11", label: "Number of Hydrocele surgeries conducted in Lymphatic Filariasis (MMDP)", parent: "11.5.", kind: "number" },

  // M12 - Adolescent Health
  { code: "12.1.", section: "M12", label: "Adolescent Friendly Health Clinics (AFHCs)", parent: null, kind: "header" },
  { code: "12.1.1.", section: "M12", label: "Number of Adolescents (10-19 years) registered in Adolescent Friendly Health Clinic (AFHC)", parent: "12.1.", kind: "number" },
  { code: "12.1.1.a", section: "M12", label: "Girls registered in AFHC", parent: "12.1.1.", kind: "number" },
  { code: "12.1.1.b", section: "M12", label: "Boys registered in AFHC", parent: "12.1.1.", kind: "number" },
  { code: "12.1.2.", section: "M12", label: "Out of registered adolescents (10-19 years), number received clinical services", parent: "12.1.", kind: "number" },
  { code: "12.1.2.a", section: "M12", label: "Out of Girls registered, Girls received clinical services", parent: "12.1.2.", kind: "number" },
  { code: "12.1.2.b", section: "M12", label: "Out of Boys registered, Boys received clinical services", parent: "12.1.2.", kind: "number" },
  { code: "12.1.3.", section: "M12", label: "Out of registered adolescents (10-19 years), number received counselling", parent: "12.1.", kind: "number" },
  { code: "12.1.3.a", section: "M12", label: "Out of Girls registered, Girls received counselling", parent: "12.1.3.", kind: "number" },
  { code: "12.1.3.b", section: "M12", label: "Out of Boys registered, Boys received counselling", parent: "12.1.3.", kind: "number" },
  { code: "12.2.", section: "M12", label: "Coverage under MHS- Menstrual Hygiene Scheme (GOI supported)", parent: null, kind: "header" },
  { code: "12.2.2", section: "M12", label: "Number of sanitary napkin packs distributed free to ASHA (for her personal use)", parent: "12.2.", kind: "number" },
  { code: "12.2.4", section: "M12", label: "Number of adolescent girls provided sanitary napkin packs by State/UT supported Menstrual Hygiene Scheme (MHS)", parent: "12.2.", kind: "number" },
  { code: "12.3.", section: "M12", label: "Peer Educator Programme", parent: null, kind: "header" },
  { code: "12.3.1.", section: "M12", label: "Number of Adolescent Health & Wellness Days organized", parent: "12.3.", kind: "number" },

  // M13 - National TB Elimination Programme (NTEP)
  { code: "13.1.", section: "M13", label: "Number of beneficiaries who are registered at the ICTC centre.", parent: null, kind: "number" },
  { code: "13.2.", section: "M13", label: "Of the number registered at ICTC centre, the number of presumptive TB cases identified and referred for TB testing and diagnosis.", parent: null, kind: "number" },
  { code: "13.3.", section: "M13", label: "Number of beneficiaries who are registered at the NCD clinic.", parent: null, kind: "number" },
  { code: "13.4.", section: "M13", label: "The number registered at the NCD clinic includes the number of presumptive TB cases identified and referred for TB testing and diagnosis", parent: null, kind: "number" },

  // M14 - Patient Services
  { code: "14.1.", section: "M14", label: "Services provided", parent: null, kind: "header" },
  { code: "14.1.1.", section: "M14", label: "Geriatric/Elderly", parent: "14.1.", kind: "header" },
  { code: "14.1.1.a", section: "M14", label: "Total number of geriatric/elderly patients (age>=60 yrs) Registered", parent: "14.1.1.", kind: "number" },
  { code: "14.1.1.b", section: "M14", label: "Geriatric (age>=60 yrs) patients footfall", parent: "14.1.1.", kind: "number" },
  { code: "14.1.1.c", section: "M14", label: "Number of geriatric/elderly persons managed for any elderly conditions", parent: "14.1.1.", kind: "number" },
  { code: "14.1.1.d", section: "M14", label: "Number of geriatric/elderly persons followed-up for any elderly conditions", parent: "14.1.1.", kind: "number" },
  { code: "14.1.1.e", section: "M14", label: "Number of geriatric/elderly patients (age>=60 yrs) provided physiotherapy services", parent: "14.1.1.", kind: "number" },
  { code: "14.1.1.f", section: "M14", label: "Number of home bound (bed bound & restricted mobility) elderly and single elderly visited by ASHA & ANM/MPW-M during the month", parent: "14.1.1.", kind: "number" },
  { code: "14.1.2.", section: "M14", label: "Other Services", parent: "14.1.", kind: "header" },
  { code: "14.1.2.a", section: "M14", label: "Number of patients provided physiotherapy services", parent: "14.1.2.", kind: "number" },
  { code: "14.1.2.c", section: "M14", label: "Number of cases reported for Self Harm", parent: "14.1.2.", kind: "number" },
  { code: "14.2.", section: "M14", label: "Outpatient attendance (All) (excluding teleconsultation)", parent: null, kind: "header" },
  { code: "14.2.1.", section: "M14", label: "Allopathic- Outpatient attendance", parent: "14.2.", kind: "number" },
  { code: "14.2.1.a", section: "M14", label: "Out of above, number of specialist Allopathic OPD services provided", parent: "14.2.1.", kind: "number" },
  { code: "14.2.2.", section: "M14", label: "Ayush - Outpatient attendance", parent: "14.2.", kind: "number" },
  { code: "14.2.2.a", section: "M14", label: "Out of above, number of specialist AYUSH OPD services provided", parent: "14.2.2.", kind: "number" },
  { code: "14.3.", section: "M14", label: "Inpatient details", parent: null, kind: "header" },
  { code: "14.3.1.", section: "M14", label: "IPD Admission", parent: "14.3.", kind: "header" },
  { code: "14.3.1.a", section: "M14", label: "IPD Admission Male- Children<18yrs", parent: "14.3.1.", kind: "number" },
  { code: "14.3.1.b", section: "M14", label: "IPD Admission Male- Adults <60yrs", parent: "14.3.1.", kind: "number" },
  { code: "14.3.1.c", section: "M14", label: "IPD Admission Female- Children<18yrs", parent: "14.3.1.", kind: "number" },
  { code: "14.3.1.d", section: "M14", label: "IPD Admission Female- Adults<60yrs", parent: "14.3.1.", kind: "number" },
  { code: "14.3.1.e", section: "M14", label: "IPD Admission Geriatric->=60yrs", parent: "14.3.1.", kind: "number" },
  { code: "14.3.2.", section: "M14", label: "IPD Discharge", parent: "14.3.", kind: "header" },
  { code: "14.3.2.a", section: "M14", label: "IPD Discharge Male- Children<18yrs", parent: "14.3.2.", kind: "number" },
  { code: "14.3.2.b", section: "M14", label: "IPD Discharge Male- Adults<60yrs", parent: "14.3.2.", kind: "number" },
  { code: "14.3.2.c", section: "M14", label: "IPD Discharge Female- Children<18yrs", parent: "14.3.2.", kind: "number" },
  { code: "14.3.2.d", section: "M14", label: "IPD Discharge Female- Adults<60yrs", parent: "14.3.2.", kind: "number" },
  { code: "14.3.2.e", section: "M14", label: "IPD Discharge Geriatric->=60yrs", parent: "14.3.2.", kind: "number" },
  { code: "14.3.3.", section: "M14", label: "IPD Referred Out", parent: "14.3.", kind: "header" },
  { code: "14.3.3.a", section: "M14", label: "IPD Referred Male- Children<18yrs", parent: "14.3.3.", kind: "number" },
  { code: "14.3.3.b", section: "M14", label: "IPD Referred Male- Adults<60yrs", parent: "14.3.3.", kind: "number" },
  { code: "14.3.3.c", section: "M14", label: "IPD Referred Female- Children<18yrs", parent: "14.3.3.", kind: "number" },
  { code: "14.3.3.d", section: "M14", label: "IPD Referred Female- Adults<60yrs", parent: "14.3.3.", kind: "number" },
  { code: "14.3.3.e", section: "M14", label: "IPD Referred Geriatric->=60yrs", parent: "14.3.3.", kind: "number" },
  { code: "14.3.4.", section: "M14", label: "IPD Deaths (excluding deaths at Emergency department & Sick Newborn Care Unit (SNCU)", parent: "14.3.", kind: "header" },
  { code: "14.3.4.a", section: "M14", label: "IPD Deaths Male- Children<18yrs", parent: "14.3.4.", kind: "number" },
  { code: "14.3.4.b", section: "M14", label: "IPD Deaths Male- Adults<60yrs", parent: "14.3.4.", kind: "number" },
  { code: "14.3.4.c", section: "M14", label: "IPD Deaths Female- Children<18yrs", parent: "14.3.4.", kind: "number" },
  { code: "14.3.4.d", section: "M14", label: "IPD Deaths Female- Adults<60yrs", parent: "14.3.4.", kind: "number" },
  { code: "14.3.4.e", section: "M14", label: "IPD Deaths Geriatric->=60yrs", parent: "14.3.4.", kind: "number" },
  { code: "14.3.5.", section: "M14", label: "Total Number of cases Referred out (OPD+IPD+Emergency)", parent: "14.3.", kind: "number" },
  { code: "14.3.5.a", section: "M14", label: "Total cases Referred out (OPD+IPD+Emergency)-During Day", parent: "14.3.5.", kind: "number" },
  { code: "14.3.5.b", section: "M14", label: "Total cases Referred out (OPD+IPD+Emergency)-At Night (8 PM- 8 AM)", parent: "14.3.5.", kind: "number" },
  { code: "14.3.6.", section: "M14", label: "Day Care Admissions", parent: "14.3.", kind: "number" },
  { code: "14.3.7.", section: "M14", label: "Number of Left Against Medical Advice (LAMA) cases", parent: "14.3.", kind: "header" },
  { code: "14.3.7.a", section: "M14", label: "Number of Total Left Against Medical Advice (LAMA) cases reported at the facility", parent: "14.3.7.", kind: "number" },
  { code: "14.3.7.b", section: "M14", label: "Number of delivery LAMA cases reported at the facility", parent: "14.3.7.", kind: "number" },
  { code: "14.3.8.", section: "M14", label: "Total number of Medico Legal Cases reported at the facility", parent: "14.3.", kind: "number" },
  { code: "14.3.9.", section: "M14", label: "Total number of postmortem conducted at the facility", parent: "14.3.", kind: "number" },
  { code: "14.3.10.", section: "M14", label: "Total number of telemedicine consultation provided", parent: "14.3.", kind: "number" },
  { code: "14.4.", section: "M14", label: "Inpatient by disease/ health condition", parent: null, kind: "header" },
  { code: "14.4.1.", section: "M14", label: "Inpatient - Malaria", parent: "14.4.", kind: "number" },
  { code: "14.4.2.", section: "M14", label: "Inpatient - Dengue", parent: "14.4.", kind: "number" },
  { code: "14.4.3.", section: "M14", label: "Inpatient - Typhoid", parent: "14.4.", kind: "number" },
  { code: "14.4.4.", section: "M14", label: "Inpatient - Asthma, Chronic Obstructive Pulmonary Disease (COPD), Respiratory infections", parent: "14.4.", kind: "number" },
  { code: "14.4.5.", section: "M14", label: "Inpatient - Tuberculosis", parent: "14.4.", kind: "number" },
  { code: "14.4.6.", section: "M14", label: "Inpatient - Pyrexia of unknown origin (PUO)", parent: "14.4.", kind: "number" },
  { code: "14.4.7.", section: "M14", label: "Inpatient - Diarrhoea with dehydration", parent: "14.4.", kind: "number" },
  { code: "14.4.8.", section: "M14", label: "Inpatient - Leprosy (Reconstructive Surgery)", parent: "14.4.", kind: "number" },
  { code: "14.4.9.", section: "M14", label: "Inpatient - Operated for Cataract", parent: "14.4.", kind: "number" },
  { code: "14.4.10.", section: "M14", label: "Inpatient - Palliative Care", parent: "14.4.", kind: "number" },
  { code: "14.5.", section: "M14", label: "Emergency", parent: null, kind: "header" },
  { code: "14.5.1.", section: "M14", label: "Patients registered at Emergency Department", parent: "14.5.", kind: "number" },
  { code: "14.5.2.", section: "M14", label: "No. of Emergencies managed at night (8 PM- 8 AM)", parent: "14.5.", kind: "number" },
  { code: "14.5.3.", section: "M14", label: "Total Number of Emergency cases managed", parent: "14.5.", kind: "number" },
  { code: "14.5.4.", section: "M14", label: "Total Number of Emergency cases referred out", parent: "14.5.", kind: "number" },
  { code: "14.5.5.", section: "M14", label: "Total Number of CPR performed in the emergency", parent: "14.5.", kind: "number" },
  { code: "14.6.", section: "M14", label: "Emergency admissions/deaths due to", parent: null, kind: "header" },
  { code: "14.6.1.a", section: "M14", label: "Emergency - Trauma (accident, injury, poisoning etc) -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.1.b", section: "M14", label: "Emergency - Trauma (accident, injury, poisoning etc) -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.2.a", section: "M14", label: "Emergency - Burn -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.2.b", section: "M14", label: "Emergency - Burn -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.3.a", section: "M14", label: "Emergency - Obstetrics complications -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.3.b", section: "M14", label: "Emergency - Obstetrics complications -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.4.a", section: "M14", label: "Emergency - Snake Bite -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.4.b", section: "M14", label: "Emergency - Snake Bite -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.5.a", section: "M14", label: "Emergency - Acute Cardiac Emergencies -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.5.b", section: "M14", label: "Emergency - Acute Cardiac Emergencies -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.6.a", section: "M14", label: "Emergency - CVA (Cerebrovascular Disease)/Stroke -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.6.b", section: "M14", label: "Emergency - CVA (Cerebrovascular Disease)/Stroke -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.6.7.a", section: "M14", label: "Emergency - Dog Bite -Admission", parent: "14.6.", kind: "number" },
  { code: "14.6.7.b", section: "M14", label: "Emergency - Dog Bite -Deaths", parent: "14.6.", kind: "number" },
  { code: "14.7.", section: "M14", label: "Total number of deaths occurring at Emergency Department", parent: null, kind: "number" },
  { code: "14.8.", section: "M14", label: "Operations (excluding C-section)", parent: null, kind: "header" },
  { code: "14.8.1.a", section: "M14", label: "Total number of Major Operations conducted excluding C-Section (General and spinal anaesthesia)", parent: "14.8.", kind: "number" },
  { code: "14.8.1.b", section: "M14", label: "Out of Major Operation, Gynecology- Hysterectomy surgeries", parent: "14.8.", kind: "number" },
  { code: "14.8.1.c", section: "M14", label: "Major Surgeries excluding Obstetrics, Gynaecology and Opthalmology.", parent: "14.8.", kind: "number" },
  { code: "14.8.1.d", section: "M14", label: "No. of Major Surgeries done at night (8PM to 8 AM) (Excluding C section)", parent: "14.8.", kind: "number" },
  { code: "14.8.2.", section: "M14", label: "Minor Operations (No or local anaesthesia)", parent: "14.8.", kind: "number" },
  { code: "14.8.3.", section: "M14", label: "Number of post operative Surgical Site infection", parent: "14.8.", kind: "number" },
  { code: "14.9.", section: "M14", label: "In-Patient Head Count at midnight", parent: null, kind: "number" },
  { code: "14.10.", section: "M14", label: "Sick Newborns (up to 4 weeks) Admissions", parent: null, kind: "header" },
  { code: "14.10.1.", section: "M14", label: "Number of Admission in NBSU ( New Born Stabilisation Unit)", parent: "14.10.", kind: "number" },
  { code: "14.10.2.", section: "M14", label: "Number of total admissions in Special Newborn Care Unit (SNCU Admissions)", parent: "14.10.", kind: "number" },
  { code: "14.11.", section: "M14", label: "SNCU(Deaths & Discharge)", parent: null, kind: "header" },
  { code: "14.11.1.", section: "M14", label: "Number of deaths occurred at SNCU", parent: "14.11.", kind: "number" },
  { code: "14.11.2.", section: "M14", label: "Number of Newborns successfully discharged from SNCU", parent: "14.11.", kind: "number" },
  { code: "14.12.", section: "M14", label: "Janani Shishu Suraksha Karyakram (JSSK)", parent: null, kind: "header" },
  { code: "14.12.1", section: "M14", label: "Number of Pregnant Women(PW) and Post Natal Care (PNC) Beneficiaries", parent: "14.12.", kind: "header" },
  { code: "14.12.1.a", section: "M14", label: "Number of PW and PNC beneficiaries provided - Free Medicines under JSSK", parent: "14.12.1", kind: "number" },
  { code: "14.12.1.a.i", section: "M14", label: "Number of pregnant women provided free medicines during ANC period under JSSK", parent: "14.12.1.a", kind: "number" },
  { code: "14.12.1.a.ii", section: "M14", label: "Number of Pregnant women provided free medicines during delivery under JSSK", parent: "14.12.1.a", kind: "number" },
  { code: "14.12.1.a.iii", section: "M14", label: "Number of PNC mothers provided free medicines under JSSK", parent: "14.12.1.a", kind: "number" },
  { code: "14.12.1.b", section: "M14", label: "Number of women provided - Free Diet under JSSK", parent: "14.12.1", kind: "number" },
  { code: "14.12.1.c", section: "M14", label: "Number of PW and PNC beneficiaries provided - Free Diagnostics under JSSK", parent: "14.12.1", kind: "number" },
  { code: "14.12.1.c.i", section: "M14", label: "Number of pregnant women provided free diagnostics during ANC period under JSSK", parent: "14.12.1.c", kind: "number" },
  { code: "14.12.1.c.ii", section: "M14", label: "Number of Pregnant women provided free diagnostics during delivery under JSSK", parent: "14.12.1.c", kind: "number" },
  { code: "14.12.1.c.iii", section: "M14", label: "Number of PNC mothers provided free diagnostics under JSSK", parent: "14.12.1.c", kind: "number" },
  { code: "14.12.1.d", section: "M14", label: "Number of pregnant women provided - Free Home to facility transport for conducting delivery under JSSK", parent: "14.12.1", kind: "number" },
  { code: "14.12.1.e", section: "M14", label: "Number of pregnant women provided - Interfacility transfers when needed during delivery under JSSK(in case of referral)", parent: "14.12.1", kind: "number" },
  { code: "14.12.1.f", section: "M14", label: "Number of PNC mothers provided - Free Drop Back home after delivery under JSSK", parent: "14.12.1", kind: "number" },
  { code: "14.12.2.", section: "M14", label: "Number of sick infants provided", parent: "14.12.", kind: "header" },
  { code: "14.12.2.a", section: "M14", label: "Number of infants admitted at facility due to any sickness- JSSK Beneficiaries", parent: "14.12.2.", kind: "number" },
  { code: "14.12.2.b", section: "M14", label: "Number of sick infants provided - Free Medicines under JSSK", parent: "14.12.2.", kind: "number" },
  { code: "14.12.2.c", section: "M14", label: "Number of sick infants provided - Free Diagnostics under JSSK", parent: "14.12.2.", kind: "number" },
  { code: "14.12.2.d", section: "M14", label: "Number of sick infants provided - Free Home to facility transport under JSSK", parent: "14.12.2.", kind: "number" },
  { code: "14.12.2.e", section: "M14", label: "Number of infants received free referral transport under JSSK", parent: "14.12.2.", kind: "number" },
  { code: "14.13.", section: "M14", label: "Nutritional Rehabilitation Centre (NRC)", parent: null, kind: "header" },
  { code: "14.13.1.", section: "M14", label: "Number of sick SAM children admitted in standalone/ integrated NRC", parent: "14.13.", kind: "number" },
  { code: "14.13.2.", section: "M14", label: "Number of sick SAM children referred to standalone/ integrated NRC by Frontline Workers (AWW/ ASHA/ ANM)", parent: "14.13.", kind: "number" },
  { code: "14.13.3.", section: "M14", label: "Number of sick SAM children referred to standalone/ integrated NRC from IPD/OPD of other Health Facility (PHC/CHC/SDH/DH/other NRC)", parent: "14.13.", kind: "number" },
  { code: "14.13.4.", section: "M14", label: "Number of children Referred to standalone/ integrated NRC by RBSK Team", parent: "14.13.", kind: "number" },
  { code: "14.13.5.", section: "M14", label: "Number of SAM children discharged from standalone/ integrated NRC who met the discharge criteria", parent: "14.13.", kind: "number" },
  { code: "14.13.6.", section: "M14", label: "Number of admitted children left against medical advice (LAMA) / defaulter", parent: "14.13.", kind: "number" },
  { code: "14.13.7.", section: "M14", label: "Number of children died while admitted in standalone/ intergrated NRC", parent: "14.13.", kind: "number" },
  { code: "14.13.8.", section: "M14", label: "Number of children who completed all four post discharge follow-ups", parent: "14.13.", kind: "number" },
  { code: "14.13.9.", section: "M14", label: "Number of sick SAM children treated and admitted in the pediatric facility (other than standalone/ integrated NRC)", parent: "14.13.", kind: "number" },
  { code: "14.13.10.", section: "M14", label: "In-Patient Head Count at midnight for standalone/ integrated NRC", parent: "14.13.", kind: "number" },
  { code: "14.14.", section: "M14", label: "Number of Rogi Kalyan Samiti (RKS) meetings held", parent: null, kind: "number" },
  { code: "14.16.", section: "M14", label: "Total number of UHND/VHND sessions conducted in the reporting month", parent: null, kind: "number" },
  { code: "14.17.", section: "M14", label: "Total number of Outreach/Special Outreach camps conducted in the reporting month", parent: null, kind: "number" },
  { code: "14.17.1.", section: "M14", label: "Total number of outreach visits conducted by staff", parent: "14.17.", kind: "number" },
  { code: "14.17.2.", section: "M14", label: "Total number of outreach visits made by DMHP team", parent: "14.17.", kind: "number" },
  { code: "14.17.3.", section: "M14", label: "Total number of awareness campaigns/camps conducted for Mental Health", parent: "14.17.", kind: "number" },
  { code: "14.18.", section: "M14", label: "Patient Satisfaction Score of the facility in percentage (from Mera Aspatal)", parent: null, kind: "number" },
  { code: "14.19.", section: "M14", label: "National Viral Hepatitis Control Program (Diagnosis and Management of viral hepatitis)", parent: null, kind: "header" },
  { code: "14.19.1", section: "M14", label: "Total number of blood samples screened by ELISA/Rapid tests for viral hepatitis", parent: "14.19.", kind: "number" },
  { code: "14.19.1.a", section: "M14", label: "Total number of blood samples screened by ELISA/Rapid tests for viral hepatitis B i.e. HBsAg (excluding pregnant women)", parent: "14.19.1", kind: "number" },
  { code: "14.19.1.b", section: "M14", label: "Total number of blood samples screened by ELISA/Rapid tests for viral hepatitis C(Anti- HCV)", parent: "14.19.1", kind: "number" },
  { code: "14.19.2", section: "M14", label: "Total number of blood samples tested positive by ELISA/ Rapid tests for viral hepatitis & its management", parent: "14.19.", kind: "number" },
  { code: "14.19.2.a", section: "M14", label: "Total number of blood samples tested positive by ELISA/ Rapid tests for Hepatitis B (out of those tested for HBsAg excluding pregnant women)", parent: "14.19.2", kind: "number" },
  { code: "14.19.2.a.i", section: "M14", label: "Total number of positive blood samples for hepatitis B by ELISA/ Rapid tests tested for HBV DNA(out of those tested positive for HBsAg excluding pregnant women)", parent: "14.19.2.a", kind: "number" },
  { code: "14.19.2.a.ii", section: "M14", label: "Total number of patients found positive for HBsAg eligible for treatment for hepatitis B (excluding pregnant women)", parent: "14.19.2.a", kind: "number" },
  { code: "14.19.2.a.iii", section: "M14", label: "Total number of patients eligible for treatment for Hepatitis B put on treatment(out of those eligible for treatment excluding pregnant women)", parent: "14.19.2.a", kind: "number" },
  { code: "14.19.2.b", section: "M14", label: "Total number of blood samples tested positive by ELISA/ Rapid tests for Hepatitis C (out of those tested for Anti-HCV)", parent: "14.19.2", kind: "number" },
  { code: "14.19.2.b.i", section: "M14", label: "Total number of positive blood samples for Hepatitis C screened by test (ELISA/ Rapid tests) confirmed by HCV RNA testing (out of those positive for anti-HCV)", parent: "14.19.2.b", kind: "number" },
  { code: "14.19.2.b.ii", section: "M14", label: "Total number of patients put on treatment for Hepatitis C (out of those confirmed by HCV RNA i.e. HCV RNA detected)", parent: "14.19.2.b", kind: "number" },
  { code: "14.19.2.b.iii", section: "M14", label: "Total number of positive Hepatitis C patients who have completed treatment", parent: "14.19.2.b", kind: "number" },
  { code: "14.19.2.b.iv", section: "M14", label: "Total number of patients cleared for HCV RNA on sustained virological response at 12 weeks (SVR12)", parent: "14.19.2.b", kind: "number" },
  { code: "14.19.3.", section: "M14", label: "Hepatitis B in pregnancy", parent: "14.19.", kind: "header" },
  { code: "14.19.3.a", section: "M14", label: "Number of Pregnant Women tested for HBsAg", parent: "14.19.3.", kind: "number" },
  { code: "14.19.3.b", section: "M14", label: "Number of Pregnant Women who are HBsAg positive(out of those tested for Hepatitis B i.e. HBsAg)", parent: "14.19.3.", kind: "number" },
  { code: "14.19.3.c", section: "M14", label: "Number of Pregnant Women found positive for HBsAg referred out to higher centre for institutional delivery", parent: "14.19.3.", kind: "number" },
  { code: "14.19.3.d", section: "M14", label: "Number of Pregnant Women found positive for HBsAg delivered in an institution", parent: "14.19.3.", kind: "number" },
  { code: "14.19.3.e", section: "M14", label: "Number of newborn who received birth dose of Hepatitis B vaccine born to HBsAg positive pregnant women", parent: "14.19.3.", kind: "number" },
  { code: "14.19.3.f", section: "M14", label: "Number of New Borns to Pregnant Women (found positive for HBsAg) received Hepatitis B Immunoglobulin (HBIG) (within 24 hours of birth)", parent: "14.19.3.", kind: "number" },

  // M15 - Diagnostics
  { code: "15.1.", section: "M15", label: "Total Number of Lab Tests & Kit Tests", parent: null, kind: "header" },
  { code: "15.1.1.", section: "M15", label: "Total Number of Lab Tests done- Inhouse (including kits tests conducted in Laboratory)", parent: "15.1.", kind: "number" },
  { code: "15.1.2.", section: "M15", label: "Total Number of Lab Tests done- Outsourced (including kits tests conducted in Laboratory)", parent: "15.1.", kind: "number" },
  { code: "15.1.3.", section: "M15", label: "Total Number of Kit Tests conducted in Outreach areas/Camps/in-facility(outside lab)", parent: "15.1.", kind: "number" },
  { code: "15.2.", section: "M15", label: "Hb Tests Conducted", parent: null, kind: "header" },
  { code: "15.2.1.", section: "M15", label: "Number of Hb tests conducted including kit tests", parent: "15.2.", kind: "number" },
  { code: "15.2.2.", section: "M15", label: "Out of the total number of Hb tests done, Number having Hb < 7 mg", parent: "15.2.", kind: "number" },
  { code: "15.3.", section: "M15", label: "HIV tests", parent: null, kind: "header" },
  { code: "15.3.1.a", section: "M15", label: "Number of males screened for HIV by Whole Blood Finger Prick/RDT test/POC test", parent: "15.3.", kind: "number" },
  { code: "15.3.1.b", section: "M15", label: "Out of the above, No. of males found reactive for HIV", parent: "15.3.", kind: "number" },
  { code: "15.3.1.c", section: "M15", label: "No. of males subjected to HIV test at Confirmatory Centre/Stand Alone-ICTC", parent: "15.3.", kind: "number" },
  { code: "15.3.1.d", section: "M15", label: "Out of the above, No. of males confirmed as HIV Positive", parent: "15.3.", kind: "number" },
  { code: "15.3.2.a", section: "M15", label: "Number of females (non-ANC) screened for HIV by Whole Blood Finger Prick/RDT test/POC test", parent: "15.3.", kind: "number" },
  { code: "15.3.2.b", section: "M15", label: "Out of the above, No. of females (non-ANC) found reactive for HIV", parent: "15.3.", kind: "number" },
  { code: "15.3.2.c", section: "M15", label: "No. of females (non-ANC) subjected to HIV test at Confirmatory Centre/Stand Alone-ICTC", parent: "15.3.", kind: "number" },
  { code: "15.3.2.d", section: "M15", label: "Out of the above, No. of females (non-ANC) confirmed as HIV Positive", parent: "15.3.", kind: "number" },
  { code: "15.3.3.a", section: "M15", label: "Number of Pregnant Women (PW-ANC) screened for HIV by Whole Blood Finger Prick/RDT test/POC test", parent: "15.3.", kind: "number" },
  { code: "15.3.3.b", section: "M15", label: "Out of the above, No. of PW(ANC) found reactive for HIV", parent: "15.3.", kind: "number" },
  { code: "15.3.3.c", section: "M15", label: "No. of PW(ANC) subjected to HIV test at Confirmatory Centre/Stand Alone-ICTC", parent: "15.3.", kind: "number" },
  { code: "15.3.3.d", section: "M15", label: "Out of the above, No. of PW(ANC) confirmed as HIV Positive", parent: "15.3.", kind: "number" },
  { code: "15.3.3.e", section: "M15", label: "Number of DIL women screened for HIV by Whole Blood Finger Prick/RDT test/POC test", parent: "15.3.", kind: "number" },
  { code: "15.3.3.f", section: "M15", label: "Out of the above, No. of DIL women found reactive for HIV", parent: "15.3.", kind: "number" },
  { code: "15.3.3.g", section: "M15", label: "No. of DIL women subjected to HIV test at Confirmatory Centre/Stand Alone-ICTC", parent: "15.3.", kind: "number" },
  { code: "15.3.3.h", section: "M15", label: "Out of the above, No. of DIL women confirmed as HIV Positive", parent: "15.3.", kind: "number" },
  { code: "15.3.3.i", section: "M15", label: "Number of Pregnant Women (ANC&DIL) screened for HIV more than once(Repeated testing)", parent: "15.3.", kind: "number" },
  { code: "15.3.4.a", section: "M15", label: "Number of H/TG people screened for HIV by Whole Blood Finger Prick/RDT test/POC test", parent: "15.3.", kind: "number" },
  { code: "15.3.4.b", section: "M15", label: "Out of the above, No. of H/TG people found reactive for HIV", parent: "15.3.", kind: "number" },
  { code: "15.3.4.c", section: "M15", label: "No. of H/TG people subjected to HIV test at Confirmatory Centre /Stand Alone-ICTC", parent: "15.3.", kind: "number" },
  { code: "15.3.4.d", section: "M15", label: "Out of the above, No. of H/TG people confirmed as HIV Positive", parent: "15.3.", kind: "number" },
  { code: "15.4.", section: "M15", label: "STI/RTI attendees Tested for Syphilis", parent: null, kind: "header" },
  { code: "15.4.1.a", section: "M15", label: "Total number of males tested for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.1.b", section: "M15", label: "Out of the above, number of males tested reactive for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.1.c", section: "M15", label: "Out of the above, number of males treated for Syphilis", parent: "15.4.", kind: "number" },
  { code: "15.4.2.a", section: "M15", label: "Total number of female (non-ANC) tested for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.2.b", section: "M15", label: "Out of the above, number of females (non-ANC) tested reactive for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.2.c", section: "M15", label: "Out of the above, number of females (non-ANC) treated for Syphilis", parent: "15.4.", kind: "number" },
  { code: "15.4.3.a", section: "M15", label: "Total number of H/TG people tested for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.3.b", section: "M15", label: "Out of the above, number of H/TG people tested reactive for Syphilis (RPR/VDRL/PoC/ RDT/TPHA)", parent: "15.4.", kind: "number" },
  { code: "15.4.3.c", section: "M15", label: "Out of the above, number of H/TG people treated for Syphilis", parent: "15.4.", kind: "number" },
  { code: "15.5.", section: "M15", label: "Widal tests", parent: null, kind: "header" },
  { code: "15.5.1.", section: "M15", label: "Widal tests- Number Tested", parent: "15.5.", kind: "number" },
  { code: "15.5.2.", section: "M15", label: "Widal tests- Number Positive", parent: "15.5.", kind: "number" },
  { code: "15.6.", section: "M15", label: "Diagnostics Tests conducted", parent: null, kind: "header" },
  { code: "15.6.1.", section: "M15", label: "Radiology", parent: "15.6.", kind: "header" },
  { code: "15.6.1.a.i", section: "M15", label: "X-ray(Inhouse)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.a.i.1", section: "M15", label: "X-ray(Inhouse)-No. of chest X-rays done on patients with health risks- Diabetes, HIV, Smoking, Alcoholism, low BMI, geriatric population (>60),history of TB, contacts of TB", parent: "15.6.1.a.i", kind: "number" },
  { code: "15.6.1.a.ii", section: "M15", label: "X-ray(Outsource)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.b.i", section: "M15", label: "Ultrasonography (USG) (Inhouse)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.b.ii", section: "M15", label: "Ultrasonography (USG)(Outsource)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.c.i", section: "M15", label: "CT scan (Inhouse)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.c.ii", section: "M15", label: "CT scan (Outsource)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.d.i", section: "M15", label: "MRI (Inhouse)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.d.ii", section: "M15", label: "MRI (Outsource)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.e.i", section: "M15", label: "ECG (Inhouse)", parent: "15.6.1.", kind: "number" },
  { code: "15.6.1.e.ii", section: "M15", label: "ECG (Outsource)", parent: "15.6.1.", kind: "number" },

  // M16 - Details of deaths reported
  { code: "16.1.1.a", section: "M16", label: "New Born deaths within 24 hrs(1 to 23 Hrs 59 minutes) of birth at Facility/Facility to facility in transit", parent: null, kind: "number" },
  { code: "16.1.1.b", section: "M16", label: "New born deaths within 24 hrs(1 to 23 Hrs 59 minutes) of birth in Community (at home or home to facility transit)", parent: null, kind: "number" },
  { code: "16.1.2.a", section: "M16", label: "New Born deaths within 1 week (1 to 7 days) at Facility/Facility to facility in transit", parent: null, kind: "number" },
  { code: "16.1.2.b", section: "M16", label: "New born deaths within 1 week (1 to 7 days) At Community (at home or home to facility transit)", parent: null, kind: "number" },
  { code: "16.1.3.a", section: "M16", label: "New Born deaths within 8 to 28 days at Facility/Facility to facility in transit", parent: null, kind: "number" },
  { code: "16.1.3.b", section: "M16", label: "New born deaths within 8 to 28 days At Community (at home or home to facility transit)", parent: null, kind: "number" },
  { code: "16.1.4.a", section: "M16", label: "Infant Deaths (>28 days to below 12 months) at Facility/Facility to facility in transit", parent: null, kind: "number" },
  { code: "16.1.4.b", section: "M16", label: "Infant Deaths (>28 days to below 12 months) At Community (at home or home to facility transit)", parent: null, kind: "number" },
  { code: "16.2.", section: "M16", label: "Neonatal Deaths up to 4 weeks (0 to 28 days) due to", parent: null, kind: "header" },
  { code: "16.2.1.", section: "M16", label: "Neonatal Deaths up to 4 weeks (0 to 28 days) due to Sepsis", parent: "16.2.", kind: "number" },
  { code: "16.2.2.", section: "M16", label: "Neonatal Deaths up to 4 weeks (0 to 28 days) due to Asphyxia", parent: "16.2.", kind: "number" },
  { code: "16.2.3.", section: "M16", label: "Neonatal Deaths up to 4 weeks (0 to 28 days) due to complications of Prematurity", parent: "16.2.", kind: "number" },
  { code: "16.2.4.", section: "M16", label: "Neonatal Deaths up to 4 weeks (0 to 28 days) due to Other causes", parent: "16.2.", kind: "number" },
  { code: "16.3.", section: "M16", label: "Infant Deaths Between more than 28 days and below 12 months due to", parent: null, kind: "header" },
  { code: "16.3.1.", section: "M16", label: "Number of Infant Deaths (>28 days - below 12 months) due to Pneumonia", parent: "16.3.", kind: "number" },
  { code: "16.3.2.", section: "M16", label: "Number of Infant Deaths (>28 days -below 12 months) due to Diarrhoea", parent: "16.3.", kind: "number" },
  { code: "16.3.3.", section: "M16", label: "Number of Infant Deaths (>28 days -below 12 months) due to Fever related", parent: "16.3.", kind: "number" },
  { code: "16.3.4.", section: "M16", label: "Number of Infant Deaths (>28 days -below 12 months) due to Measles", parent: "16.3.", kind: "number" },
  { code: "16.3.5.", section: "M16", label: "Number of Infant Deaths (>28 days -below 12 months) due to Others", parent: "16.3.", kind: "number" },
  { code: "16.4.", section: "M16", label: "Child Deaths between 1 - below 5 years due to", parent: null, kind: "header" },
  { code: "16.4.1.", section: "M16", label: "Number of Child Deaths (1 -below 5 years) due to Pneumonia", parent: "16.4.", kind: "number" },
  { code: "16.4.2.", section: "M16", label: "Number of Child Deaths (1 -below 5 years) due to Diarrhoea", parent: "16.4.", kind: "number" },
  { code: "16.4.3.", section: "M16", label: "Number of Child Deaths (1 -below 5 years) due to Fever related", parent: "16.4.", kind: "number" },
  { code: "16.4.4.", section: "M16", label: "Number of Child Deaths (1 -below 5 years) due to Measles", parent: "16.4.", kind: "number" },
  { code: "16.4.5.", section: "M16", label: "Number of Child Deaths (1 -below 5 years) due to Others", parent: "16.4.", kind: "number" },
  { code: "16.5.", section: "M16", label: "Maternal Deaths at facility due to", parent: null, kind: "header" },
  { code: "16.5.1.", section: "M16", label: "Number of Maternal Deaths at facility due to APH (Antepartum Haemmorhage)", parent: "16.5.", kind: "number" },
  { code: "16.5.2.", section: "M16", label: "Number of Maternal Deaths at facility due to PPH (Post-Partum Haemmorhage)", parent: "16.5.", kind: "number" },
  { code: "16.5.3.", section: "M16", label: "Number of Maternal Deaths at facility due to Pregnancy related infection and sepsis, Fever", parent: "16.5.", kind: "number" },
  { code: "16.5.4.", section: "M16", label: "Number of Maternal Deaths at facility due to Abortion and/ or its complication", parent: "16.5.", kind: "number" },
  { code: "16.5.5.", section: "M16", label: "Number of Maternal Deaths at facility due to Obstructed/prolonged labour", parent: "16.5.", kind: "number" },
  { code: "16.5.6.", section: "M16", label: "Number of Maternal Deaths at facility due to Severe hypertension/fits/Pre Eclampsia/Eclampsia in pregnancy, during delivery and puerperium", parent: "16.5.", kind: "number" },
  { code: "16.5.7.", section: "M16", label: "Number of Maternal Deaths at facility due to Other/Unknown Causes", parent: "16.5.", kind: "number" },
  { code: "16.5.8.", section: "M16", label: "Age wise total Maternal Deaths, occurred at Facility", parent: "16.5.", kind: "number" },
  { code: "16.5.8.a", section: "M16", label: "Out of total number of maternal deaths at facility, deaths with age less than <15 years", parent: "16.5.8.", kind: "number" },
  { code: "16.5.8.b", section: "M16", label: "Out of total number of maternal deaths at facility, deaths with age 15-19 years", parent: "16.5.8.", kind: "number" },
  { code: "16.5.8.c", section: "M16", label: "Out of total number maternal deaths at facility, deaths with age more than >19-49 years", parent: "16.5.8.", kind: "number" },
  { code: "16.5.8.d", section: "M16", label: "Out of total number maternal deaths at facility, deaths with age more than >49 years", parent: "16.5.8.", kind: "number" },
  { code: "16.6.", section: "M16", label: "Total Facility Based Maternal Death Reviews (FBMDR) done", parent: null, kind: "number" },
  { code: "16.7.", section: "M16", label: "Other Deaths (except Infant, Child & Maternal Deaths) 5 years and above due to", parent: null, kind: "header" },
  { code: "16.7.1.", section: "M16", label: "Number of deaths due to Diarrhoeal diseases", parent: "16.7.", kind: "number" },
  { code: "16.7.2.", section: "M16", label: "Number of deaths due to Tuberculosis", parent: "16.7.", kind: "number" },
  { code: "16.7.3.", section: "M16", label: "Number of deaths due to Respiratory diseases including infections (other than TB)", parent: "16.7.", kind: "number" },
  { code: "16.7.4.", section: "M16", label: "Number of deaths due to Other Fever Related", parent: "16.7.", kind: "number" },
  { code: "16.7.5.", section: "M16", label: "Number of deaths due to Heart disease/Hypertension related", parent: "16.7.", kind: "number" },
  { code: "16.7.6.", section: "M16", label: "Number of deaths due to Cancer", parent: "16.7.", kind: "number" },
  { code: "16.7.7.", section: "M16", label: "Number of deaths due to Neurological disease including strokes", parent: "16.7.", kind: "number" },
  { code: "16.7.8.", section: "M16", label: "Number of deaths due to Accidents/Burn cases", parent: "16.7.", kind: "number" },
  { code: "16.7.9.", section: "M16", label: "Number of deaths due to Animal bites and stings", parent: "16.7.", kind: "number" },
  { code: "16.7.10.", section: "M16", label: "Number of deaths due to Known Acute Disease", parent: "16.7.", kind: "number" },
  { code: "16.7.11.", section: "M16", label: "Number of deaths due to Known Chronic Disease", parent: "16.7.", kind: "number" },
  { code: "16.7.12.", section: "M16", label: "Number of deaths due to Other Causes", parent: "16.7.", kind: "number" },
  { code: "16.8.", section: "M16", label: "Deaths due to Vector Borne Diseases ( all age groups)", parent: null, kind: "header" },
  { code: "16.8.1.", section: "M16", label: "Number of Deaths due to Malaria- Plasmodium Vivax", parent: "16.8.", kind: "number" },
  { code: "16.8.2.", section: "M16", label: "Number of Deaths due to Malaria- Plasmodium Falciparum", parent: "16.8.", kind: "number" },
  { code: "16.8.3.", section: "M16", label: "Number of Deaths due to Kala Azar", parent: "16.8.", kind: "number" },
  { code: "16.8.4.", section: "M16", label: "Number of Deaths due to Dengue", parent: "16.8.", kind: "number" },
  { code: "16.8.5.", section: "M16", label: "Number of Deaths due to Acute Encephelitis Syndrome (AES)", parent: "16.8.", kind: "number" },
  { code: "16.8.6.", section: "M16", label: "Number of Deaths due to Japanese Encephalitis (JE)", parent: "16.8.", kind: "number" },
  { code: "16.9.", section: "M16", label: "Total Deaths (5 years and above of age): Excluding in-transit & maternal deaths", parent: null, kind: "header" },
  { code: "16.9.1", section: "M16", label: "5 years and above to below 10 years", parent: "16.9.", kind: "number" },
  { code: "16.9.2", section: "M16", label: "10 year and above to below 19 years", parent: "16.9.", kind: "number" },
  { code: "16.9.3", section: "M16", label: "Adult 19 years and above", parent: "16.9.", kind: "number" },
  { code: "16.10.", section: "M16", label: "Total In-transit Deaths :Excluding infant & maternal deaths", parent: null, kind: "header" },
  { code: "16.10.1", section: "M16", label: "In-transit Deaths: 1 year and below 5 years", parent: "16.10.", kind: "number" },
  { code: "16.10.2", section: "M16", label: "In-transit Deaths: 5 years and above to below 10 years", parent: "16.10.", kind: "number" },
  { code: "16.10.3", section: "M16", label: "In-transit Deaths: 10 year and above to below 19 years", parent: "16.10.", kind: "number" },
  { code: "16.10.4", section: "M16", label: "In-transit Deaths: Adult 19 years and above", parent: "16.10.", kind: "number" },

  // M17 - QA (Quality Assurance) & BEMMP
  { code: "17.1.", section: "M17", label: "EQAS Compliance", parent: null, kind: "header" },
  { code: "17.1.1.", section: "M17", label: "Total number of Haematology tests registered under External Quality Assurance Scheme (EQAS)", parent: "17.1.", kind: "number" },
  { code: "17.1.2.", section: "M17", label: "No. of registered Haematology tests reported EQAS Compliant", parent: "17.1.", kind: "number" },
  { code: "17.1.3.", section: "M17", label: "Total number of Biochemistry tests registered under External Quality Assurance Scheme (EQAS)", parent: "17.1.", kind: "number" },
  { code: "17.1.4.", section: "M17", label: "No. of registered Bio chemistry tests report EQAS Compliant", parent: "17.1.", kind: "number" },
  { code: "17.1.5.", section: "M17", label: "Total Quantity of Bio medical waste generated in Kg for the month - (All Yellow, Red, white & Blue)", parent: "17.1.", kind: "number" },
  { code: "17.1.6.", section: "M17", label: "Total Quantity of General waste generated in Kg for the month", parent: "17.1.", kind: "number" },
  { code: "17.2.", section: "M17", label: "Biomedical Equipment Management & Maintenance Program", parent: null, kind: "header" },
  { code: "17.2.1.", section: "M17", label: "Total number of breakdown calls reported for the month", parent: "17.2.", kind: "number" },
  { code: "17.2.2.", section: "M17", label: "Total number of breakdown attended for the month", parent: "17.2.", kind: "number" },
  { code: "17.2.3.", section: "M17", label: "Number of visit made by the service engineer/ BME for the month", parent: "17.2.", kind: "number" }
]);

export { HMIS_FORMAT, HMIS_SECTIONS, HMIS_ITEMS };
